### PR TITLE
Upstream merge 2020-07-30 (egress firewall & IP)

### PR DESCRIPTION
**Pull request by dcbw**
@JacobTanenbaum @alexanderConstantinescu @danwinship @trozet @openshift/networking

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
let's see if it passes...

**Comment by dcbw** [comment]
We need https://github.com/openshift/cluster-network-operator/pull/737 to merge before this is going to work.

**Comment by dcbw** [comment]
/hold
not going to work until https://github.com/openshift/cluster-network-operator/pull/737 lands

**Comment by danwinship** [comment]
/test e2e-gcp-ovn
failures are mostly monitoring-related

**Comment by trozet** [comment]
Prometheus failures again. That has nothing to do with this PR. Failures are happening on all gco ovn jobs. Safe to override I think.

**Pull request merged**
