### PR TITLE
Bug 2058762: Fixes libovsdb errors + hang

### PR DESCRIPTION
**Pull request by trozet**
Updates the schema so updates for SBDB will not result in error. Corrects cache update error handling.

### CODE REVIEW

**Comment by bparees** [comment]
overriding valid-bz label given that QE has verified the 4.11 PR already.

**Comment by abhat** [comment]
/override ci/prow/e2e-aws-ovn-windows

This job has been perma-failing on a windows e2e test that doesn't look related to the changes made here.

**Pull request merged**
