### PR TITLE
Add a CNO kind job to CI

### PR DESCRIPTION
**Pull request by nerdalert**
- Runs the CNO kind deployment against the ovn-kubernetes PR on push/merge

Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>

### CODE REVIEW

**Comment by danwinship** [comment]
Why? We already run tests against a full OCP cluster...

**Comment by nerdalert** [comment]
@danwinship this PR was based off conversations with @trozet and @dave-tucker. Sounded like some bugs had slipped through with lack of CNO testing.

**Comment by danwinship** [comment]
Maybe they meant we should add this *upstream*?

**Comment by nerdalert** [comment]
@danwinship upstream was discussed, I think we thought it might be kind of weird having OCP specific testing in the upstream OSS. Maybe we can flesh it out on tomorrow's standup. Ty for taking a look.

**Comment by dave-tucker** [comment]
Yeah we don't need this as I think `prow` takes care of running integration against OCP.
What we need is automation to keep this repo up-to-date with upstream so that integration is being done often enough to catch issues, and not only when we decide to manually sync the two.

**Comment by trozet** [comment]
Yeah this patch needs to be upstream in ovn-org.

@danwinship the point of this is because patches get merged upstream and then we find out later CNO needed missing changes and now things are broken downstream. Then the person trying to merge downstream has to go back and search numerous commits and try to figure out what happened.

Since CNO works with KIND, we can have a simple job here to run CNO+KIND deployment and catch those errors and label the PR with "needs-CNO-change" or something so that the author or committer needs to go downstream and link a corresponding PR for the required change.

**Pull request closed without merging**
