### PR TITLE
Dockerfile: Bump OVN to ovn-23.09.0-109.el9fdp

### PR DESCRIPTION
**Pull request by dceara**
Includes the following relevant changes:
- actions: Use random port selection for SNAT with external_port_range.
  [https://issues.redhat.com/browse/FDP-301]
  [https://issues.redhat.com/browse/RFE-4980]
- northd: Make sure that affinity flows match on VIP.
  [https://issues.redhat.com/browse/FDP-290]
- ovn: Add tunnel PMTUD support.
  [https://bugzilla.redhat.com/show_bug.cgi?id=2241711]
- northd: Use proper field for lookup_nd
  [https://issues.redhat.com/browse/FDP-283]
  [https://issues.redhat.com/browse/OCPBUGS-27093]

### CODE REVIEW

**Comment by dceara** [comment]
CC: @trozet @tssurya @jcaamano

Corresponding PR to bump to -109 in ovn-org/ovn-kubernetes:
https://github.com/ovn-org/ovn-kubernetes/pull/4114

**Comment by tssurya** [comment]
are the rpms tagged correctly? not 106 but 109?

**Comment by dceara** [comment]
> are the rpms tagged correctly? not 106 but 109?

We moved to -109 to be in sync with upstream fedora (-106 didn't build on rawhide).  Yes, they're tagged but maybe not yet synced:
```
$ brew list-tagged rhaos-4.16-rhel-9-candidate | grep ovn23.09
ovn23.09-23.09.0-100.el9fdp               rhaos-4.16-rhel-9-candidate  dceara
ovn23.09-23.09.0-109.el9fdp               rhaos-4.16-rhel-9-candidate  nusiddiq
```

**Comment by dceara** [comment]
Closing in favor of https://github.com/openshift/ovn-kubernetes/pull/2066

**Pull request closed without merging**
