### PR TITLE
[wip] Dockerfile: bump to ovn2.13-20.06.2-1.el7fdp and openvswitch2.13-2.13.0-46.el7fdp

### PR DESCRIPTION
**Pull request by dcbw**

### CODE REVIEW

**Comment by dcbw** [comment]
```
+ GOOS=windows
+ GOARCH=amd64
+ go build -v -mod vendor -gcflags '' -ldflags '-B 0x7679323f825dfb755c41c7ea2ac541d4e6f2b6f0' -o /go/src/github.com/openshift/ovn-kubernetes/go-controller/_output/go/bin/windows/hybrid-overlay-node.exe ./hybrid-overlay/cmd/hybrid-overlay-node
github.com/ovn-org/ovn-kubernetes/go-controller/hybrid-overlay/cmd/hybrid-overlay-node
error: build error: no such image
```
/retest

**Comment by dcbw** [comment]
```
error: some steps failed:
  * could not run steps: step [release:latest] failed: release "release-latest" failed: pod didn't start running within 30 minutes: 
* Container artifacts is not ready with reason Completed and message 
* Container release is not ready with reason ImagePullBackOff and message Back-off pulling image "docker-registry.default.svc:5000/ci-op-sf25stn5/stable@sha256:84542de08144b8ad41ab260560088c177ee232a081e0eea345107dfc457b90d7"
2020/08/25 02:33:48 could not load result reporting options: failed to read file "": open : no such file or directory
```
/retest

**Comment by aojea** [comment]
/test all
soak ... soak ... :)

**Comment by aojea** [comment]
/retest
installation problem

**Comment by alexanderConstantinescu** [comment]
@dcbw : what's the diff with https://github.com/openshift/ovn-kubernetes/pull/240 . The title is the same and the content seems to be the same too

**Comment by alexanderConstantinescu** [comment]
Also, why is this patch specifying using RHEL 7 packages (I assume that's what el7 stands for)?

**Pull request closed without merging**
