### PR TITLE
Bug 2006325: Bump OVN to ovn21.09-21.09.0-19.el8fdp

### PR DESCRIPTION
**Pull request by dceara**
Includes fix for:
https://bugzilla.redhat.com/show_bug.cgi?id=2006306

### CODE REVIEW

**Comment by dceara** [comment]
@trozet FYI

**Comment by trozet** [comment]
/retitle Bug 2006325: Bump OVN to ovn21.09-21.09.0-19.el8fdp

**Comment by trozet** [comment]
/override ci/prow/4.10-upgrade-from-stable-4.8-e2e-aws-ovn-upgrade

**Comment by dceara** [comment]
/retest-required

okd-images failing due to `Error: Unable to find a match: ovn21.09 = 21.09.0-19.el8fd...-host = 21.09.0-19.el8fdp ovn21.09-vtep = 21.09.0-19.el8fdp`
I just tagged 21.09.0-19.el8fdp in 4.9, retrying.

**Comment by trozet** [comment]
@vrutkovs something wrong with OKD image building on 4.10?

**Comment by vrutkovs** [comment]
>@vrutkovs something wrong with OKD image building on 4.10?

Yes, sorry, we didn't build OKD 4.10 nightlies, please ignore test results for master branch for now

**Pull request merged**
