### PR TITLE
OCPBUGS-36608: [release-4.16] ovspinning: Set affinity of each thread

### PR DESCRIPTION
**Pull request by zeeke**
OVS CPU pinning ensures the CPU consumed by the processes `ovsdb-server` and `ovs-vswitchd` are the same as the OVNkube container. `ovs-vswitchd` process has threads and calling `SchedSetaffinity()` on the main PID only is does not guarantee that the already spawned threads inherit that affinity. The following is an example of such a situation:

```
sh-4.4# taskset -apc $(pgrep ovs-vswitchd)
pid 4059's current affinity list: 0-2,6,9,15-66,69,70,73,79-127
pid 4335's current affinity list: 0-2,32,33,64-66,96,97
pid 2715051's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
pid 2715052's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
pid 2715053's current affinity list: 0-2,5,6,15-66,69,70,73,79-127
...
```

This changes makes the CPU align routine loop over all the threads of the given PID and invoke `SchedSetaffinity` on all of them.

To test these changes, a simple `sleep 10` process is not enough, as it doesn't spawn any thread. A go version of the sleep is therefore provided for testing purpose, in the form of a simple `main`.

#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

backport of: 
- https://github.com/ovn-org/ovn-kubernetes/pull/4470

cc @MarSik

### CODE REVIEW

**Comment by zeeke** [comment]
@MarSik , @ricky-rav Please take a look at this 4.16 backport

**Comment by ricky-rav** [comment]
@zeeke I see you did a manual cherry pick. Were there any conflicts in the code?

**Comment by zeeke** [comment]
No conflicts. I did a manual cherry pick instead of using the cherry-pick robot because this is the first backport from master branch.
Is there any smarter way to get this?

**Comment by ricky-rav** [comment]
no, you did the right thing in the end, I got confused as well :D I just needed to know whether there were any conflicts :)

**Review by ricky-rav — APPROVED** [review]

**Comment by cgoncalves** [comment]
@tssurya @jcaamano please review this backport. Thank you.

**Comment by zeeke** [comment]
/jira backport release-4.15,release-4.14

@tssurya, @trozet can you take a look at this backport?

**Review by tssurya — APPROVED** [review]
/approve
/label backport-risk-assessed

**Pull request merged**
