### PR TITLE
OCPBUGS-18378: LGW: Fix the precedence of rules in FORWARD chain

### PR DESCRIPTION
**Pull request by tssurya**
This PR ensures that the IPTable rules for LGW
are of the correct priority. The ACCEPT forwarding rules should be inserted and therefore be of higher priority always compared to the default DROP rules specially when forwarding is disabled by default
on clusters. If not traffic breaks. Without this fix we end up in:

[98325:268968232] -A FORWARD -d 169.254.169.1/32 -j ACCEPT [89489:13888546] -A FORWARD -s 169.254.169.1/32 -j ACCEPT [18:1080] -A FORWARD -d 172.30.0.0/16 -j ACCEPT
[0:0] -A FORWARD -s 172.30.0.0/16 -j ACCEPT
[0:0] -A FORWARD -p tcp -m tcp --dport 22624 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with icmp-port-unreachable [0:0] -A FORWARD -p tcp -m tcp --dport 22623 --tcp-flags FIN,SYN,RST,ACK SYN -j REJECT --reject-with icmp-port-unreachable [1262:75720] -A FORWARD -i br-ex -j DROP
[295724:17429107] -A FORWARD -o br-ex -j DROP
[0:0] -A FORWARD -o ovn-k8s-mp0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT [0:0] -A FORWARD -i ovn-k8s-mp0 -j ACCEPT

we need the mp0 rules above the DROP rules always

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit 5738c58c095920540f3435f1cc72e564bcae125d)

### CODE REVIEW

**Comment by tssurya** [comment]
only stable lgw upgrades will pass, master->master+pr will fail, we will need to do a one time override to get this fix in.

**Comment by zeeke** [comment]
/label acknowledge-critical-fixes-only

This fixes "Local Gateway Mode" installation of OVNk, which is widely used in telco installations.

**Comment by zeeke** [comment]
Job `ci/prow/e2e-aws-ovn-upgrade-local-gateway` fails to setup the initial cluster:

[Job logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1851/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade-local-gateway/1698953430501953536#1:build-log.txt%3A11)
```
INFO[2023-09-05T08:08:30Z] Step e2e-aws-ovn-upgrade-local-gateway-ipi-install-install-stableinitial failed after 1h0m28s. 
```

[e2e-aws-ovn-upgrade-local-gateway/ipi-install-install-stableinitial/artifacts/.openshift_install-1693901309.log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1851/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade-local-gateway/1698953430501953536/artifacts/e2e-aws-ovn-upgrade-local-gateway/ipi-install-install-stableinitial/artifacts/.openshift_install-1693901309.log)

```
time="2023-09-05T08:08:29Z" level=error msg="failed to initialize the cluster: Cluster operators authentication, console are not available"
```

[openshift-authentication-operator_authentication-operator-75c9f484-9pgbx_authentication-operator.log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1851/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade-local-gateway/1698953430501953536/artifacts/e2e-aws-ovn-upgrade-local-gateway/gather-extra/artifacts/pods/openshift-authentication-operator_authentication-operator-75c9f484-9pgbx_authentication-operator.log)

```
...
E0905 08:14:14.721328       1 base_controller.go:268] OAuthServerRouteEndpointAccessibleController reconciliation failed: Get "https://oauth-openshift.apps.ci-op-4kn394gc-94c59.origin-ci-int-aws.dev.rhcloud.com/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0905 08:14:20.145913       1 base_controller.go:268] OAuthServerRouteEndpointAccessibleController reconciliation failed: Get "https://oauth-openshift.apps.ci-op-4kn394gc-94c59.origin-ci-int-aws.dev.rhcloud.com/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0905 08:14:25.157325       1 base_controller.go:268] OAuthServerRouteEndpointAccessibleController reconciliation failed: Get "https://oauth-openshift.apps.ci-op-4kn394gc-94c59.origin-ci-int-aws.dev.rhcloud.com/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
E0905 08:14:30.160958       1 base_controller.go:268] OAuthServerRouteEndpointAccessibleController reconciliation failed: Get "https://oauth-openshift.apps.ci-op-4kn394gc-94c59.origin-ci-int-aws.dev.rhcloud.com/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
...
```

We'll get that prow job fixed when this PR is merged and built in a ci image. 
It looks safe to override to me.

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
