### PR TITLE
OCPBUGS-44784: Bump ovs to 3.1.0-137

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by anuragthehatter** [comment]
Looks good to QE
```
sh-5.1# rpm -qa | grep -i openv
openvswitch-selinux-extra-policy-1.0-36.el9fdp.noarch
openvswitch3.1-3.1.0-137.el9fdp.x86_64
python3-openvswitch3.1-3.1.0-137.el9fdp.x86_64
openvswitch3.1-ipsec-3.1.0-137.el9fdp.x86_64
openvswitch3.1-devel-3.1.0-137.el9fdp.x86_64
sh-5.1# exit
```
error: 8 fail, 56 pass, 3 skip (1h23m532s)
fail/skip ones are not compatible with 4.14 so we are good

**Comment by zshi-redhat** [comment]
@jcaamano @tssurya  can you help review this ovs version bump for next 4.14.z (Nov 27 cutoff) ?
This ovs change is to introduce an improvement for ipsec timeout/connection issue. We will do 4.14.z/4.15.z bump first with ovs-3.1 and then 4.16.z/4.17.z with ovs-3.3/ovs-3.4, slack discussion for why we do it in this order can be found here: https://redhat-internal.slack.com/archives/C07S54F9URX/p1732106083861699?thread_ts=1732105570.262839&cid=C07S54F9URX

4.15.z has merged: https://github.com/openshift/ovn-kubernetes/pull/2359
4.14.z qe pre-merge test passed.

**Comment by sdodson** [comment]
/override ci/prow/4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade ci/prow/4.14-upgrade-from-stable-4.13-local-gateway-e2e-aws-ovn-upgrade
these have all passed on previous runs

**Pull request merged**
