### PR TITLE
[release-4.13] OCPBUGS-13175:Check the status of a pod before trying to get its ip

### PR DESCRIPTION
**Pull request by bpickard22**
No conflicts in cherry-picks 
Backporting to 4.13 to resolve https://issues.redhat.com//browse/OCPBUGS-11567 and https://issues.redhat.com/browse/OCPBUGS-13863

### CODE REVIEW

**Comment by bpickard22** [comment]
@trozet @tssurya PTAL

**Comment by dan1el-k** [comment]
Can confirm this issue with OKD version:

- 4.13.0-0.okd-2023-07-09-062029 
- 4.13.0-0.okd-2023-06-24-145750
- 4.13.0-0.okd-2023-06-04-080300

It especially happens after shutdown and restart of the cluster

**Pull request merged**
