### PR TITLE
OCPBUGS-32985,SDN-4436: Dockerfile.base: Bump OVN to ovn24.03-24.03.1-36.el9fdp

### PR DESCRIPTION
**Pull request by dceara**
Relevant OVN features/performance improvements:
- ovn-northd logical flow incremental processing
- improved RBAC for Southbound BFD, IGMP_Group tables
- QoS packet marking:
  https://issues.redhat.com/browse/FDP-42
- BFD support for ECMP policy routes
  https://issues.redhat.com/browse/FDP-234
- Support new LSP enable_router_port_acl option to enable conntrack for router ports

OCP relevant fixes:
- a349ec5c14 northd: sync lb applied to logical routers in sb db lb table
  https://bugzilla.redhat.com/show_bug.cgi?id=2193323
  - allows using OVN's LB conntrack flushing feature on backend removal
- 6eff687d5f acl-log: Properly log the "pass" verdict.
  https://issues.redhat.com/browse/FDP-442

Other relevant fixes:
- 69e90f664a northd: fix infinite loop in ovn_allocate_tnlid()
- 72390c4fea pinctrl: Fixed 100% cpu on ovs connection loss.
- 6b1618a96f ofctrl: Wait at S_WAIT_BEFORE_CLEAR only once.
- b213cb641a ovn-controller: Fix busy loop when ofctrl is disconnected.
- 17b6a12fa2 ovn-controller: Support VIF-based local encap IPs selection.
- 41eefcb280 encaps: Create separate tunnels for multiple local encap IPs.
- 325c7b203d controller: split mg action in table 39 and 40 to fit kernel netlink buffer size
  https://bugzilla.redhat.com/show_bug.cgi?id=2232152
- c16e5da803 controller: disable OpenFlow inactivity probing
  https://mail.openvswitch.org/pipermail/ovs-dev/2023-May/404625.html
- ab7a8fe4c0 northd: introduce ls_datapath_group column in lb sb db table

### CODE REVIEW

**Comment by dceara** [comment]
CC: @tssurya

**Comment by trozet** [comment]
/hold

due to https://issues.redhat.com/browse/FDP-570

**Comment by dceara** [comment]
> /hold
> 
> due to https://issues.redhat.com/browse/FDP-570

With https://github.com/ovn-org/ovn-kubernetes/pull/4288 merged upstream should we go ahead and remove the hold on this one?

**Comment by tssurya** [comment]
@asood-rh : Could you also leave a comment here on the PR (what you mentioned in the email thread such that its visible?); thanks in advance, tl;dr QE has pre-verified this.

**Comment by tssurya** [comment]
/retitle SDN-4436: Dockerfile.base: Bump OVN to ovn24.03-24.03.1-36.el9fdp

**Comment by tssurya** [comment]
/hold
ugh why does it approve when i lgtm, tim can remove hold

**Comment by anuragthehatter** [comment]
`build 4.16,openshift/ovn-kubernetes#2142,openshift/os#1495,openshift/ovn-kubernetes#2126` on cluster-bot
causing merge conflicts @numansiddique

**Comment by numansiddique** [comment]
Maybe its better to test them separately ?

Otherwise https://github.com/openshift/ovn-kubernetes/pull/2142  should be on top of this one PR or vice versa.

**Comment by tssurya** [comment]
@igsilya @numansiddique : this one picks up the OVN CVE for https://bugzilla.redhat.com/show_bug.cgi?id=2267840 right?

**Comment by tssurya** [comment]
/retitle OCPBUGS-32985,SDN-4436: Dockerfile.base: Bump OVN to ovn24.03-24.03.1-36.el9fdp

**Comment by tssurya** [comment]
> > @igsilya @numansiddique : this one picks up the OVN CVE for https://bugzilla.redhat.com/show_bug.cgi?id=2267840 right?
> 
> Yes. The earliest build with the fix is `24.03.1-4.el9` , so `24.03.1-36.el9` from this PR has it as well.
> 
> FWIW, AFAIK, OpenShift doesn't use the functionality affected by the CVE.

we use bfd for icni feature

**Comment by igsilya** [comment]
> > > @igsilya @numansiddique : this one picks up the OVN CVE for https://bugzilla.redhat.com/show_bug.cgi?id=2267840 right?
> > 
> > 
> > Yes. The earliest build with the fix is `24.03.1-4.el9` , so `24.03.1-36.el9` from this PR has it as well.
> > FWIW, AFAIK, OpenShift doesn't use the functionality affected by the CVE.
> 
> we use bfd for icni feature

The issue only affects DBF enabled on geneve tunnels, so in order to have it ovn-kubernetes needs to set more than one gateway chassis per LRP or have `HA_Chassis_Group`s configured.   I don't see ovn-kubernetes setting either, but maybe I'm missing something.

The original advisory with the issue description is available here: https://www.openwall.com/lists/oss-security/2024/03/12/5

**Pull request merged**
