### PR TITLE
OCPBUGS-33328,OCPBUGS-30224,SDN-4388: [DownstreamMerge] 10 may 2024

### PR DESCRIPTION
**Pull request by npinaeva**
no conflicts

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retitle OCPBUGS-33328,OCPBUGS-30224,SDN-4388: [DownstreamMerge] 10 may 2024

**Comment by martinkennelly** [comment]
/test 4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade

Unrelated

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade 

Unrelated

**Comment by martinkennelly** [comment]
/test e2e-openstack-ovn 

5 LB tests failed - not sure why. Retesting.
Tests:
```
[sig-installer][Suite:openshift/openstack][lb][Serial] The Openstack platform should create a UDP Amphora LoadBalancer when a UDP svc with type:LoadBalancer is created on Openshift 
[sig-installer][Suite:openshift/openstack][lb][Serial] The Openstack platform should create a TCP Amphora LoadBalancer when LoadBalancerService ingressController is created on Openshift 
[sig-installer][Suite:openshift/openstack][lb][Serial] The Openstack platform should limit service access on an UDP Amphora LoadBalancer when an UDP LoadBalancer svc setting the loadBalancerSourceRanges spec is created on Openshift 
[sig-installer][Suite:openshift/openstack][lb][Serial] The Openstack platform should apply lb-method on UDP Amphora LoadBalancer when a UDP svc with monitors and ETP:Local is created on Openshift
[sig-installer][Suite:openshift/openstack][lb][Serial] The Openstack platform should create a TCP Amphora LoadBalancer when a TCP svc with type:LoadBalancer is created on Openshift 
```

**Comment by martinkennelly** [comment]
/test okd-e2e-gcp-ovn 
API server didnt come up:
```
dial tcp 34.135.229.205:6443: connect: connection refused
```

**Comment by jcaamano** [comment]
/retitle OCPBUGS-33328,OCPBUGS-30224,SDN-4388,OCPBUGS-32161: [DownstreamMerge] 10 may 2024

**Pull request merged**
