### PR TITLE
Bug 1942702: backport lr-nat-del/add fixes

### PR DESCRIPTION
**Pull request by trozet**
Backporting lr-nat-del/add fixes to 4.7 due to OVN bump which contains regression:
https://bugzilla.redhat.com/show_bug.cgi?id=1942707

### CODE REVIEW

**Comment by trozet** [comment]
@knobunc @dcbw FYI

**Review by knobunc — APPROVED** [review]
/lgtm

**Review by asood-rh — APPROVED** [review]
/lgtm

**Comment by markmc** [comment]
(patch manager) approving urgent upgrade blocker

**Pull request merged**
