### PR TITLE
[WIP] DNM Upstream and shared gw host ct use label

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
aws passed, going to push a fix for GCP

**Comment by trozet** [comment]
Saw this over the weekend a couple times where:
Operator progressing (NodeInstaller): NodeInstallerProgressing: 2 nodes are at revision 5; 1 nodes are at revision 6

Operator unavailable (WellKnown_NotReady): WellKnownAvailable: The well-known endpoint is not yet available: got '404 Not Found' status while trying to GET the OAuth well-known https://10.0.0.4:6443/.well-known/oauth-authorization-server endpoint data

Sometimes install just fails with this, not sure why yet. There's a panic in openshift-kube-scheduler-operator_openshift-kube-scheduler-operator about doing a watch on kapi, but maybe that's because kapi isnt up yet.

**Comment by dcbw** [comment]
OpenStack is failing to bring up the 3rd master node, which prevents anything else from coming up:

```
[[0;32m  OK  [0m] Mounted /var.
         Starting OSTree Remount OS/ Bind Mounts...
[   18.330265] ostree-remount[1017]: ostree-remount: failed to remount(ro) /sysroot: Device or resource busy
         Mounting Mount etcd as a ramdisk...
[[0;1;31mFAILED[0m] Failed to start OSTree Remount OS/ Bind Mounts.
See 'systemctl status ostree-remount.service' for details.
[[0;32m  OK  [0m] Mounted Mount etcd as a ramdisk.
[[0;32m  OK  [0m] Reached target Timers.
[[0;32m  OK  [0m] Reached target Login Prompts.
```

**Comment by dcbw** [comment]
https://github.com/openshift/ovn-kubernetes/pull/269

**Pull request closed without merging**
