### PR TITLE
Bug 1958972: Fixes adding nodes to use new Services controller

### PR DESCRIPTION
**Pull request by trozet**
Accidentally the old services/endpoints watcher code was being used to handle service sync for when a node is added/updated. During scale deployments we would notice this would create deadlock. This PR migrates the code to only use the new services controller and removes the legacy code.

### CODE REVIEW

**Comment by trozet** [comment]
dualstack currently broken:
https://bugzilla.redhat.com/show_bug.cgi?id=1966602

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Comment by dcbw** [comment]
dualstack currently broken:
https://bugzilla.redhat.com/show_bug.cgi?id=1966602

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
