### PR TITLE
OCBUGS-4502: Dockerfile: bump OVN to 22.09.0-25

### PR DESCRIPTION
**Pull request by dcbw**
* Tue Dec 06 2022 Dumitru Ceara <dceara@redhat.com> - 22.09.0-24
- northd: Include VIP port in LB affinity learn flow matches. (#2150533)
[Upstream: cc037c7538d635e7d014e98935a83bc15140674f]

@tssurya

### CODE REVIEW

**Comment by tssurya** [comment]
/retitle OCBUGS-4502: Dockerfile: bump OVN to 22.09.0-25

**Comment by dcbw** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade
/override ci/prow/4.12-upgrade-from-stable-4.11-images
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-images

These jobs are not applicable to 4.13 (since 4.13 should use 4.12->4.13 jobs not 4.11 ones) and are only there because another PR with the same content was mistakenly opened for 4.12 and GitHub notices that the same commits are present and conflates the two PRs.

**Comment by tssurya** [comment]
/retitle OCPBUGS-4502: Dockerfile: bump OVN to 22.09.0-25

**Pull request merged**
