### PR TITLE
OCPBUGS-32985,OCPBUGS-32925: Dockerfile: Bump OVS to 3.3.0-2

### PR DESCRIPTION
**Pull request by igsilya**
**- What this PR does and why is it needed**

OVS 3.3 is going to be a new LTS release.  It also includes significant database performance improvements especially in the area of initial database file read and the database conversion on updates.

OVS 3.3 also includes extended support for NXT_CT_FLUSH allowing to flush CT entries by marks and labels.  This will be used in future versions on OVN.  (Though this is not relevant for the ovn-kubernetes container image.)

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by igsilya** [comment]
FWIW, the perfscale test failures seem irrelevant to the PR.

**Comment by anuragthehatter** [comment]
/label qe-approved

(OCP QE results looks good as communicated via email)

**Comment by igsilya** [comment]
@anuragthehatter Thanks for the testing!  Could you confirm that the tests were performed with or without openshift/os#1495 ?

**Comment by tssurya** [comment]
/retitle OCPBUGS-32985,OCPBUGS-32925: Dockerfile: Bump OVS to 3.3.0-2

**Pull request merged**
