### PR TITLE
OCPBUGS-31419,OCPBUGS-32461,SDN-4243: Downstream Merge 22nd April 2024

### PR DESCRIPTION
**Pull request by tssurya**
@JacobTanenbaum @trozet @maiqueb 

Conflicts:
go-controller/go.sum
go-controller/vendor/modules.txt

because we don't have https://github.com/openshift/ovn-kubernetes/commit/2afe7b877d7c1d774af1156f717cf49f4030e139
in upstream

### CODE REVIEW

**Comment by tssurya** [comment]
/hold

something is wrong here:
```
Deployment "/openshift-ovn-kubernetes/ovnkube-control-plane" rollout is not making progress - pod ovnkube-control-plane-6d9d9846c8-vvwf7 is in CrashLoopBackOff State
Deployment "/openshift-ovn-kubernetes/ovnkube-control-plane" rollout is not making progress - pod ovnkube-control-plane-6d9d9846c8-zgqvz is in CrashLoopBackOff State
```

**Comment by tssurya** [comment]
ipamclaims.k8s.cni.cncf.io is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-control-plane" cannot list resource "ipamclaims" in API group "k8s.cni.cncf.io" at the cluster scope
2024-04-22T14:00:52.518827439Z E0422 14:00:52.518818       1 reflector.go:147] github.com/k8snetworkplumbingwg/ipamclaims/pkg/crd/ipamclaims/v1alpha1/apis/informers/externalversions/factory.go:132: Failed to watch *v1alpha1.IPAMClaim: failed to list *v1alpha1.IPAMClaim: ipamclaims.k8s.cni.cncf.io is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-control-plane" cannot list resource "ipamclaims" in API group "k8s.cni.cncf.io" at the cluster scope
2024-04-22T14:00:54.011229870Z I0422 14:00:54.011193       1 ovnkube.go:577] Stopping ovnkube...

**Comment by maiqueb** [comment]
@tssurya / @jcaamano https://github.com/ovn-org/ovn-kubernetes/pull/4300

**Comment by trozet** [comment]
/retitle OCPBUGS-31419,OCPBUGS-32461,SDN-4243: Downstream Merge 22nd April 2024

**Comment by tssurya** [comment]
hmm I want to say there is something fishy with azure run:
```
namespace/e2e-deployment-5982 node/ci-op-5ikn2swg-e6384-6kpdz-worker-centralus2-m9d6n pod/webserver-556cc9d77-dncsl hmsg/6396f71e2b - 5.07 seconds after deletion - firstTimestamp/2024-04-24T16:07:30Z interesting/true lastTimestamp/2024-04-24T16:07:30Z reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_webserver-556cc9d77-dncsl_e2e-deployment-5982_48ead612-f725-4389-b91a-d9014e83ae9e_0(af7eb9002992a051df94029c0c2613a1e83f799b342eebb503bab6442f401349): error adding pod e2e-deployment-5982_webserver-556cc9d77-dncsl to CNI network "multus-cni-network": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: 'ContainerID:"af7eb9002992a051df94029c0c2613a1e83f799b342eebb503bab6442f401349" Netns:"/var/run/netns/16d416cf-e6dc-46ec-ae81-da712ffb0d3c" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=e2e-deployment-5982;K8S_POD_NAME=webserver-556cc9d77-dncsl;K8S_POD_INFRA_CONTAINER_ID=af7eb9002992a051df94029c0c2613a1e83f799b342eebb503bab6442f401349;K8S_POD_UID=48ead612-f725-4389-b91a-d9014e83ae9e" Path:"" ERRORED: error configuring pod [e2e-deployment-5982/webserver-556cc9d77-dncsl] networking: [e2e-deployment-5982/webserver-556cc9d77-dncsl/48ead612-f725-4389-b91a-d9014e83ae9e:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-deployment-5982/webserver-556cc9d77-dncsl af7eb9002992a051df94029c0c2613a1e83f799b342eebb503bab6442f401349 network default NAD default] [e2e-deployment-5982/webserver-556cc9d77-dncsl af7eb9002992a051df94029c0c2613a1e83f799b342eebb503bab6442f401349 network default NAD default] failed to get pod annotation: timed out waiting for pod after 1s: pods "webserver-556cc9d77-dncsl" not found
```
but it seems like the pods just got deleted somehow and we are trying to do weird things for a deleted pod and then not ignoring the "pod-not-found" errors?

**Pull request merged**
