### PR TITLE
OCPBUGS-33758,OCPBUGS-35347,SDN-4919,OCPBUGS-35367,OCPBUGS-33758,SDN-5011: Downstream Merge: July 2nd

### PR DESCRIPTION
**Pull request by tssurya**
@npinaeva @jcaamano @jluhrsen @tssurya @trozet @kyrtapz @JacobTanenbaum @zeeke @dceara

### CODE REVIEW

**Comment by zeeke** [comment]
/retitle OCPBUGS-35347,SDN-4919,OCPBUGS-35367: Downstream Merge: July 2nd

cc @MarSik

**Comment by jcaamano** [comment]
/retitle OCPBUGS-33758,OCPBUGS-35347,SDN-4919,OCPBUGS-35367,OCPBUGS-33758,SDN-5011: Downstream Merge: July 2nd

**Comment by tssurya** [comment]
@jcaamano : wanna lgtm this one?

**Pull request merged**
