### PR TITLE
Modifications for klog v2.

### PR DESCRIPTION
**Pull request by tfherbert**
Fixes bug #1886062 Logging is broken because of upstream change to klog v2.

### CODE REVIEW

**Comment by tfherbert** [comment]
I am triggering a retest but it is unlikely that these two test failures are logging related from looking at logs.
/retest

**Comment by alexanderConstantinescu** [comment]
@tfherbert : this PR should go upstream. Could you please /close it and re-open a new PR in ovn-org/ovn-kubernetes?

**Comment by tfherbert** [comment]
Closing this PR in preference for continuing the work in upstream ovn-k.

**Pull request closed without merging**
