### PR TITLE
Bug 1857522: 7-21-2020 merge

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by abhat** [comment]
/lgtm

Can you create a bz to revert https://github.com/openshift/ovn-kubernetes/pull/204/commits/e79b5bca8e976224151d37c6271ff2878313d8e7?

**Comment by dcbw** [comment]
e2e-aws failure looks like a bootstrap node etcd failure; lots of connection refused, and around that time on the bootstrap node:

```
Jul 22 01:34:19 ip-10-0-24-70 bootkube.sh[10535]: Skipped "secret-service-network-serving-signer.yaml" secrets.v1./service-network-serving-signer -n openshift-kube-apiserver-operator as it already exists
Jul 22 01:34:36 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:36.452069       1 reflector.go:251] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to watch *v1.Pod: Get https://localhost:6443/api/v1/pods?watch=true: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:37 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:37.459253       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:38 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:38.459889       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:39 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:39.460460       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:40 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:40.461022       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:41 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:41.461619       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
Jul 22 01:34:42 ip-10-0-24-70 bootkube.sh[10535]: E0722 01:34:42.462277       1 reflector.go:134] github.com/openshift/cluster-bootstrap/pkg/start/status.go:66: Failed to list *v1.Pod: Get https://localhost:6443/api/v1/pods: dial tcp [::1]:6443: connect: connection refused
```

**Comment by dcbw** [comment]
AWS seems all borked on the bootstrap control plane, and then everything gets torn down. I dont' think this is ovnkube.

Jul 22 01:14:40 ip-10-0-24-70 bootkube.sh[2129]: Updated status for "99_openshift-cluster-api_worker-machineset-1.yaml" machinesets.v1beta1.machine.openshift.io/ci-op-cr68wdsh-834bf-4pt2c-worker-us-west-1b -n openshift-machine-api
Jul 22 01:33:26 ip-10-0-24-70 bootkube.sh[2129]: Error: error while checking pod status: timed out waiting for the condition
Jul 22 01:33:26 ip-10-0-24-70 bootkube.sh[2129]: Tearing down temporary bootstrap control plane...

**Comment by trozet** [comment]
> /lgtm
> 
> Can you create a bz to revert [e79b5bc](https://github.com/openshift/ovn-kubernetes/commit/e79b5bca8e976224151d37c6271ff2878313d8e7)?

I don't think we need a bz, since it will only be in master.

**Comment by trozet** [comment]
/hold
something is broken with ovn-k8s, we are getting empty macs in northd commands for lsp set:
2020-07-22T14:36:46Z|00223|ovn_northd|INFO|invalid syntax '10.128.4.4' in logical switch port addresses. No MAC address found
2020-07-22T14:36:46Z|00224|ovn_northd|INFO|Dropped 1961 log messages in last 60 seconds (most recently, 0 seconds ago) due to excessive rate
2020-07-22T14:36:46Z|00225|ovn_northd|INFO|invalid syntax '10.128.4.4' in port security. No MAC address found

**Comment by stbenjam** [comment]
This was merged with e2e-metal-ipi tests still running, which failed due to the changes here. It'd be great if you'd check out the results on e2e-metal-ipi when merging changes, since none of the other OVN tests cover IPv6, right?

I filed https://bugzilla.redhat.com/show_bug.cgi?id=1860710


https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/204/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi/1286403200164827137


```
level=error msg="Cluster operator network Degraded is True with RolloutHung: DaemonSet \"openshift-ovn-kubernetes/ovnkube-master\" rollout is not making progress - pod ovnkube-master-slt8c is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-master\" rollout is not making progress - pod ovnkube-master-llrx7 is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-master\" rollout is not making progress - pod ovnkube-master-sgdhj is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-kwmln is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-jc78x is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-nm944 is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - last change 2020-07-23T21:31:57Z"
```

I filed

**Comment by trozet** [comment]
@stbenjam the merge happens automatically. You could propose making it required to pass for merge to happen. I didn't know metal-ipi used ipv6 (maybe we could add that to the job name?), but it would be nice to have that as a required job as long as it is stable.

**Comment by stbenjam** [comment]
Well it’s a bit of a catch 22, how can we be stable when we’re constantly broken by changes? I don’t know how to break that cycle. 

I think the only thing we can ask is that you look at optional jobs before approving/lgtm to make sure if it’s failing it wasn’t due to the changes here.

**Comment by trozet** [comment]
I'll check when I can. Some good news is upstream we are about to add ipv6
jobs, which should help us to avoid breaking you downstream in the future.

**Comment by stbenjam** [comment]
Do you think we could take https://github.com/openshift/ovn-kubernetes/pull/215 downstream before that happens?

**Comment by trozet** [comment]
No the fix needs to be upstream first and it's already part of:

https://github.com/ovn-org/ovn-kubernetes/pull/1343

I expect that to be merged today or tomorrow and then we will do another
upstream -> downstream merge.

**Comment by stbenjam** [comment]
Right, that PR was open since May so I didn't know when it would land. If it's in the next day that's fine but this is the last week before feature freeze.  https://github.com/ovn-org/ovn-kubernetes/pull/1539 was the upstream version of the OpenShift PR if 1343 is going to be delayed.

**Pull request merged**
