### PR TITLE
OCPBUGS-2663, Bug 2091780, OCPBUGS-6739: Downstream merge 2023-02-20

### PR DESCRIPTION
**Pull request by zeeke**
Further changes in addition to the merge commit:

- Move OCPHack test code to its own test file.
- Apply changes due to [ovn-kubernetes/pull/3387](https://github.com/ovn-org/ovn-kubernetes/pull/3387) to downstream-only code 
- Fix `hybrid_test.go` applying changes from [ovn-kubernetes/pull/3405](https://github.com/ovn-org/ovn-kubernetes/pull/3405)
  - d/s version of the file seems different than u/s

### CODE REVIEW

**Comment by zeeke** [comment]
/hold

Waiting for 
- https://github.com/openshift/ovn-kubernetes/pull/1531

**Comment by tssurya** [comment]
/retitle OCPBUGS-2663, Bug 2091780: Downstream merge 2023-02-15

**Comment by flavio-fernandes** [comment]
/retitle OCPBUGS-2663, Bug 2091780, OCPBUGS-6739: Downstream merge 2023-02-15

**Comment by flavio-fernandes** [comment]
Reviewed changes related to OCPBUGS-6739 : all lgtm. TY @zeeke !

- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/97c91c2e6485ddf9157f1fa5f7dd3d973925d5c0
- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/2000f2e057267414d5c639326e31f5472cb39f06
- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/36991fb2cac69c8d91e1a63d262badc73fd9a310
- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/b64d072270a1ce4f865b363f926fa60a54294d7c
- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/f63796ec18450c9a241336f4be01238c5eed9621
- https://github.com/openshift/ovn-kubernetes/pull/1533/commits/c7fd02c133233cf940fc7537e481a95700e060a3

**Comment by maiqueb** [comment]
@zeeke should we rename the PR's title ? It now features upstream merged PRs up to Feb 20th.

**Review by maiqueb — COMMENTED** [review]
lgtm on the optional subnet for multi-homing stuff.

Let me know if you need the lgtm tag - not adding it yet since I think we should require LGTMs from other parties.

**Comment by dcbw** [comment]
DIff against 146279a0650e50e8a9516425e189d21ab7511340 upstream looks good.

/approve
/lgtm

**Pull request merged**
