### PR TITLE
Bug 1958375: Bump OVN to 20.12.0-140.el8fdp

### PR DESCRIPTION
**Pull request by trozet**
Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
/assign @alexanderConstantinescu 

@dcbw FYI

**Comment by alexanderConstantinescu** [comment]
The build is correctly tagged and I see builds passing (the ones that aren't are the ones usually perma-failing), so

/lgtm

**Comment by trozet** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

dualstack are known failures covered by a bz

/override ci/prow/e2e-aws-ovn-windows

windows issue is known and doesn't have anything to do with ovn bump

**Pull request merged**
