### PR TITLE
[release-4.12] OCPBUGS-2896: Refactor retry into its own pkg

### PR DESCRIPTION
**Pull request by ricky-rav**
cherry-pick of commits from https://github.com/ovn-org/ovn-kubernetes/pull/3171

Fixes #OCPBUGS-2896

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
lgtm

**Comment by ricky-rav** [comment]
@trozet this PR should be good to go, if you can approve it. Thanks!

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
