### PR TITLE
OCPBUGS-10251: fix duplicated metric registration

### PR DESCRIPTION
**Pull request by zshi-redhat**
MetricResourceRetryFailuresCount metric is registered in NetworkControllerManager and Node modes. When both are specified, the second registration fails with the following error:

panic: duplicate metrics collector registration attempted goroutine 234 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x1e1a662?, {0xc000e35620?, 0x1, 0x15?})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/github.com/prometheus/client_golang/prometheus/registry.go:178
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/metrics.RegisterMasterFunctional()
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/metrics/master.go:385 +0x6b8
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*networkControllerManager).configureMetrics(0xc0003f61e0, 0x48fe77?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_controller_manager.go:359 +0x36
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*networkControllerManager).Init(0xc0003f61e0)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_controller_manager.go:298 +0x25
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*networkControllerManager).Start.func1({0x214bc88, 0xc000e5c1c0})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_controller_manager.go:220 +0x14f
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b

Signed-off-by: Zenghui Shi <zshi@redhat.com>
(cherry picked from commit bdeb82fc22ee186846413a29b59b7ba27248e9c5)

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/4.13-upgrade-from-stable-4.12-local-gateway-e2e-aws-ovn-upgrade

```
ns/openshift-kube-controller-manager pod/kube-controller-manager-ip-10-0-136-82.us-west-2.compute.internal node/ip-10-0-136-82.us-west-2.compute.internal - 2805.46 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandbox with name "k8s_kube-controller-manager-ip-10-0-136-82.us-west-2.compute.internal_openshift-kube-controller-manager_dcff34f70921c684995a1c1e9bd791ec_0": parsing image configuration: Get "https://d11wsypyfft1aa.cloudfront.net/docker/registry/v2/blobs/sha256/b2/b27c6a37e2c16156949212bc70f60ee317bb6f5628cb336fe2e668344a873316/data?Expires=1679643768&Signature=cOHVhSYM6FZrT8rtIVyvOYXVE-Ts5StGhrq3hMU-XVEZ7Sc44-0XzwK9RSsbq2YgO3RtmyMKJfjpZs3I~gmO6OH5PubuUDO9kbwoOTt95hNUz5lUflT9EoAEzxqO3vhizyxg6B~MJf7sUODNHaVwr-qNcMI-qguVSjsDzdZOLu2zAmL8XI0ipy87ydN7TM6dRCoJzoG1~G-XoVHUbH~BT-DKRx5-Z1JhNhAW-jIW~oQq6DC6x1q91YwFZUNi9l3yi639GuM4sorxRTwo1LXtSDidlDm8syvm59N8bJ0E7g0UFz-0duDAMt59rLL487ZgUnIew5i3B8xf4rBRBLCT0g__&Key-Pair-Id=K35IN2XBI3W7KZ": read tcp 10.0.136.82:51424->18.161.3.97:443: read: connection reset by peer
ns/openshift-kube-apiserver pod/revision-pruner-9-ip-10-0-136-82.us-west-2.compute.internal node/ip-10-0-136-82.us-west-2.compute.internal - 334.72 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandbox with name "k8s_revision-pruner-9-ip-10-0-136-82.us-west-2.compute.internal_openshift-kube-apiserver_1d4073c3-debe-405d-a8c8-5faeff3b12e4_0": parsing image configuration: Get "https://d11wsypyfft1aa.cloudfront.net/docker/registry/v2/blobs/sha256/b2/b27c6a37e2c16156949212bc70f60ee317bb6f5628cb336fe2e668344a873316/data?Expires=1679643769&Signature=OTAHfuXjkKr9LTzjWEzI-d902MhVPbuLroHog~QQkjncpRnD97qAidUYn1XF7bs4PveIqMAMGakKq-1lugGqmowvLIamnV34ryY11aqslb51w9F8ndKXOIr1lmBK2vHs1rrq40ShqNNxtclx00ftzld-EjjGkv0ZreQB8RTbpWmgQGotrTYtES4sFSUkyYe-9Pcd6TNky-oInNjq0ldtVs2h70fQfcgEG3SfPknpHBCimaPcWabHsEk1O2WWteAW5WkGH~11rtXsFmVbezO7blmoBklI4t9adGmVngERbGPEhO5CO7rKKEaewlCViUCiDHdkCn4L3twBW3tbNMt4hg__&Key-Pair-Id=K35IN2XBI3W7KZ": read tcp 10.0.136.82:40078->18.161.3.184:443: read: connection reset by peer
ns/openshift-ovn-kubernetes pod/ovnkube-master-cjsrz node/ip-10-0-136-82.us-west-2.compute.internal - never deleted - network rollout - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandbox with name "k8s_ovnkube-master-cjsrz_openshift-ovn-kubernetes_55516fa4-179e-4164-870b-4a73d35c2a02_0": parsing image configuration: Get "https://d11wsypyfft1aa.cloudfront.net/docker/registry/v2/blobs/sha256/b2/b27c6a37e2c16156949212bc70f60ee317bb6f5628cb336fe2e668344a873316/data?Expires=1679643769&Signature=OTAHfuXjkKr9LTzjWEzI-d902MhVPbuLroHog~QQkjncpRnD97qAidUYn1XF7bs4PveIqMAMGakKq-1lugGqmowvLIamnV34ryY11aqslb51w9F8ndKXOIr1lmBK2vHs1rrq40ShqNNxtclx00ftzld-EjjGkv0ZreQB8RTbpWmgQGotrTYtES4sFSUkyYe-9Pcd6TNky-
```

Is not a network problem.

**Pull request merged**
