### PR TITLE
OCPBUGS-31814:  ipv6+all protocols conntrack flush

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of https://github.com/openshift/ovn-kubernetes/pull/2066 and https://github.com/ovn-org/ovn-kubernetes/pull/4154 (ds merge https://github.com/openshift/ovn-kubernetes/pull/2110)
Added extra commit fixing ipv6 tests https://github.com/openshift/ovn-kubernetes/commit/39f2cebedd7311a36a0a2b1b7532e2db61fb1a1c to be able to test the change at least locally
skipped ovn bump, as a newer version was merged here https://github.com/openshift/ovn-kubernetes/pull/2121

### CODE REVIEW

**Comment by npinaeva** [comment]
TODO: rebase on top of https://github.com/openshift/ovn-kubernetes/pull/2121/files

**Comment by knobunc** [comment]
/label jira/valid-bug

This can't be verified on 4.16 at the moment.

**Pull request merged**
