### PR TITLE
Bug 1845702: build: require openvswitch2.13 >= 2.13.0-29 or later

### PR DESCRIPTION
**Pull request by dcbw**
Includes fixes for:
https://bugzilla.redhat.com/show_bug.cgi?id=1834838
https://bugzilla.redhat.com/show_bug.cgi?id=1822290

@abhat @jtaleric

### CODE REVIEW

**Comment by squeed** [comment]
contacted the dptp help desk to figure out why the ovn rpms are missing.

**Comment by dcbw** [comment]
/retest
RPM repo errors.

**Pull request merged**
