### PR TITLE
Bug 2057723: Multiple fixes around Network Policies

### PR DESCRIPTION
**Pull request by trozet**
Changes-Include:

- Fixes error messages for getting ips from pods on pod add in netpol handlers
- Fixes sorting/duplicate IPs in address sets
- Adds retry mechanism for network policy

### CODE REVIEW

**Comment by trozet** [comment]
/hold
found one more fix we need:
https://github.com/ovn-org/ovn-kubernetes/pull/2847

**Comment by anuragthehatter** [comment]
Looks good. NP regression passed on this PR

/label qe-approved
/label cherry-pick-approved

**Pull request merged**
