### PR TITLE
OCPBUGS-2176: add endpointSlice informer in master process

### PR DESCRIPTION
**Pull request by zshi-redhat**
In MicroShift, ovnkube-master and ovnkube-node run in a single process/container
which acts as both master and node roles. The NewMasterWatchFactory needs to
initialize a new watch factory for both, otherwise it results in panic watching
endpointSlice which only existed in node watch factory.

This PR creates endpointSlices in master watch factory even it is not used when
master and node are deployed separately, this will be fixed by upstream PR:
https://github.com/ovn-org/ovn-kubernetes/pull/3193.

Signed-off-by: Zenghui Shi <zshi@redhat.com>
(cherry picked from commit b6c1b081fb670423a53febc1e62ea9db89abdb63)

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@jcaamano @trozet PTAL.

**Comment by jcaamano** [comment]
@zshi-redhat can you explain a bit why we need this in the commit message or PR message or the bug? There is no info anywhere. Might be obvious for some but not all.

**Comment by zshi-redhat** [comment]
> @zshi-redhat can you explain a bit why we need this in the commit message or PR message or the bug? There is no info anywhere. Might be obvious for some but not all.

@jcaamano sure, I updated the PR message.

**Pull request merged**
