### PR TITLE
Bug 2073411: Fix ETP=local for host->svc traffic

### PR DESCRIPTION
**Pull request by tssurya**
Fix ETP=local for host->svc traffic
    
    OVN-K implemented host->svc case for ETP=local incorrectly.
    We considered traffic originating from host->sameNP or
    host->LB or host->EIP as external while in reality its
    neither internal or external per sig-network. So it should
    default to special case i.e "cluster" even if "local" is set.
    
    We had added custom e2e's for ETP=local for host->svc which
    are not needed anymore.
    
    Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
    (cherry picked from commit 107f6639ac8a8c321fe36d647fba4ed319a5303b)
    
    Conflicts:
            test/e2e/e2e.go
    because we are missing https://github.com/openshift/ovn-kubernetes/commit/4d834f31e667dea26a808b4154eb2085e9600ded

### CODE REVIEW

**Review by andreaskaris — COMMENTED** [review]
/lgtm

**Comment by anuragthehatter** [comment]
Its currently being tested by QE

**Pull request merged**
