### PR TITLE
SDN-4930,OCPBUGS-39009: Downstream Merge Sept 18th

### PR DESCRIPTION
**Pull request by pliurh**
#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by tssurya** [comment]
thanks @pliurh for opening a downstream merge (please notify sdn-team on slack so that another person doesn't start one)
since this is bringing in UDN pieces please run payloads. thanks in advance!

**Comment by tssurya** [comment]
udn tests are failing:

1. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2302/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-single-node-techpreview/1836393483011624960
2. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2302/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn-techpreview/1836393506524893184

none of the tech-previews have passed, this needs investigation.

**Comment by martinkennelly** [comment]
/payload-job-with-prs e2e-gcp-ovn-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-techpreview openshift/origin#29041
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview openshift/origin#29041
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview openshift/origin#29041

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-serial

Unrelated

**Comment by martinkennelly** [comment]
/test 4.18-upgrade-from-stable-4.17-e2e-aws-ovn-upgrade 

Unrelated.

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-serial

Init failure - unrelated

**Comment by martinkennelly** [comment]
/test e2e-gcp-ovn-techpreview 

UDN tests failed because test pods didnt become running within a period of time.

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-techpreview

bootstrap issue - unrelated

**Comment by martinkennelly** [comment]
/test 4.18-upgrade-from-stable-4.17-e2e-aws-ovn-upgrade 

No obvious failures just a pod watcher got disconnected.

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-serial 

Test exceeded 4 hours and got killed.

**Comment by martinkennelly** [comment]
/test e2e-vsphere-ovn-techpreview

Failed to build an image

**Comment by martinkennelly** [comment]
/test e2e-metal-ipi-ovn-techpreview 

Tests exceeded 4 hours

**Comment by martinkennelly** [comment]
# e2e-metal-ipi-ovn-ipv6-techpreview

We can ignore the UDN test failures because those tests require dualstack. I have asked jamos advice regarding how to fix this in release.

**Comment by martinkennelly** [comment]
Looking good but failed for other reasons:
* e2e-metal-ipi-ovn-dualstack-techpreview
* e2e-metal-ipi-ovn-dualstack-local-gateway-techpreview

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-serial

Timed out again..
I checked ovnkube logs and didnt see anything obvious that stood out.

**Comment by martinkennelly** [comment]
/test 4.18-upgrade-from-stable-4.17-e2e-aws-ovn-upgrade

Looks ok

**Comment by martinkennelly** [comment]
/payload 4.18 ci blocking
/payload 4.18 nightly blocking

Last run looked good but some disruption on serial. Rerunning.

**Comment by martinkennelly** [comment]
/payload 4.18 ci blocking

Previous run looks good just 2 tests didnt bootstrap

**Comment by martinkennelly** [comment]
/payload 4.18 ci blocking

Waiting on origin PR to merge to clear CI.

**Comment by tssurya** [comment]
https://pr-payload-tests.ci.openshift.org/runs/ci/62f0d120-823d-11ef-9da2-cd2c809eb83d-0 and https://pr-payload-tests.ci.openshift.org/runs/ci/488cde90-80cc-11ef-8411-c5413a452c0b-1 are looking good

**Pull request merged**
