### PR TITLE
[WIP] DNM Test shared gw again

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@dcbw green check marks!

**Comment by zshi-redhat** [comment]
Trying to test this PR on 4.8.0-0.nightly-2021-03-08-184701 IPv4 environment:
1) built ovn-k8s image from this PR
2) built CNO image by applying PR https://github.com/openshift/cluster-network-operator/pull/897 on top of latest CNO master
3) substitute both ovn-k8s and CNO images 

Hit the error in ovnkube-master on master nodes:
```
E0310 08:06:26.023907       1 master.go:274] Failed to upgrade OVN topology to version 3: unable to get DGP MAC binding, err: OVN command '/usr/bin/ovn-sbctl --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --bootstrap-ca-cert=/ovn-ca/ca-bundle.crt --db=ssl:10.0.1.10:9642,ssl:10.0.1.11:9642,ssl:10.0.1.12:9642 --timeout=15 --columns=_uuid --no-headings find mac_binding ip=fd99::1' failed: exit status 1, stderr: ovn-sbctl: fd99::1: unexpected ":" parsing string
panic: unable to get DGP MAC binding, err: OVN command '/usr/bin/ovn-sbctl --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --bootstrap-ca-cert=/ovn-ca/ca-bundle.crt --db=ssl:10.0.1.10:9642,ssl:10.0.1.11:9642,ssl:10.0.1.12:9642 --timeout=15 --columns=_uuid --no-headings find mac_binding ip=fd99::1' failed: exit status 1, stderr: ovn-sbctl: fd99::1: unexpected ":" parsing string
```

Shall it assume one of `V6NodeLocalNATSubnetNextHop` and `V4NodeLocalNATSubnetNextHop` doesn't exist in case of single-stack deployment?

**Comment by zshi-redhat** [comment]
Another failure after skipping the `DGP mac binding` error:
```
E0310 11:40:58.631393       1 master.go:274] Failed to upgrade OVN topology to version 3: unable to remove node local switch, err: OVN command '/usr/bin/ovn-nbctl --timeout=15 ls-del node_local_switch' failed: exit status 1, stderr: ovn-nbctl: node_local_switch: switch name not found
panic: unable to remove node local switch, err: OVN command '/usr/bin/ovn-nbctl --timeout=15 ls-del node_local_switch' failed: exit status 1, stderr: ovn-nbctl: node_local_switch: switch name not found
```

Maybe only log the warning instead of error out in cleanupDGP ?

**Comment by zshi-redhat** [comment]
After skipping the above two failures,  master failed to allow subnets:
```
I0310 12:06:47.430342       1 master.go:278] Allocating subnets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6128c6]

goroutine 340 [running]:
net.networkNumberAndMask(0x0, 0x0, 0xc002923600, 0x40d8d0, 0xc002834180, 0x20, 0x20)
	/usr/lib/golang/src/net/ip.go:476 +0x26
net.(*IPNet).Contains(0x0, 0xc0021da0a0, 0x10, 0x10, 0x0)
	/usr/lib/golang/src/net/ip.go:500 +0x2f
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ipallocator.(*Range).contains(0xc00235bdd0, 0xc0021da0a0, 0x10, 0x10, 0xc0021da0a0, 0xa)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/ipallocator/allocator.go:193 +0x50
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ipallocator.(*Range).Allocate(0xc00235bdd0, 0xc0021da0a0, 0x10, 0x10, 0x4, 0x4)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/ipallocator/allocator.go:131 +0x4d
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).StartClusterMaster(0xc00237e900, 0x7fff7db71a84, 0xe, 0x0, 0x0)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/master.go:305 +0x12a9
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).Start.func1(0x1e30640, 0xc001670180)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/master.go:90 +0x167
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:207 +0x113
```

**Comment by trozet** [comment]
> Trying to test this PR on 4.8.0-0.nightly-2021-03-08-184701 IPv4 environment:
> 
> 1. built ovn-k8s image from this PR
> 2. built CNO image by applying PR [openshift/cluster-network-operator#897](https://github.com/openshift/cluster-network-operator/pull/897) on top of latest CNO master
> 3. substitute both ovn-k8s and CNO images
> 
> Hit the error in ovnkube-master on master nodes:
> 
> ```
> E0310 08:06:26.023907       1 master.go:274] Failed to upgrade OVN topology to version 3: unable to get DGP MAC binding, err: OVN command '/usr/bin/ovn-sbctl --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --bootstrap-ca-cert=/ovn-ca/ca-bundle.crt --db=ssl:10.0.1.10:9642,ssl:10.0.1.11:9642,ssl:10.0.1.12:9642 --timeout=15 --columns=_uuid --no-headings find mac_binding ip=fd99::1' failed: exit status 1, stderr: ovn-sbctl: fd99::1: unexpected ":" parsing string
> panic: unable to get DGP MAC binding, err: OVN command '/usr/bin/ovn-sbctl --private-key=/ovn-cert/tls.key --certificate=/ovn-cert/tls.crt --bootstrap-ca-cert=/ovn-ca/ca-bundle.crt --db=ssl:10.0.1.10:9642,ssl:10.0.1.11:9642,ssl:10.0.1.12:9642 --timeout=15 --columns=_uuid --no-headings find mac_binding ip=fd99::1' failed: exit status 1, stderr: ovn-sbctl: fd99::1: unexpected ":" parsing string
> ```
> 
> Shall it assume one of `V6NodeLocalNATSubnetNextHop` and `V4NodeLocalNATSubnetNextHop` doesn't exist in case of single-stack deployment?

Thanks @zshi-redhat we now always assume the DGP is dual stack. I just need to add missing quotes around the address for ipv6. Can you send me the steps for how you are testing this please?

**Comment by trozet** [comment]
> Another failure after skipping the `DGP mac binding` error:
> 
> ```
> E0310 11:40:58.631393       1 master.go:274] Failed to upgrade OVN topology to version 3: unable to remove node local switch, err: OVN command '/usr/bin/ovn-nbctl --timeout=15 ls-del node_local_switch' failed: exit status 1, stderr: ovn-nbctl: node_local_switch: switch name not found
> panic: unable to remove node local switch, err: OVN command '/usr/bin/ovn-nbctl --timeout=15 ls-del node_local_switch' failed: exit status 1, stderr: ovn-nbctl: node_local_switch: switch name not found
> ```
> 
> Maybe only log the warning instead of error out in cleanupDGP ?

we need to add --if-exists here

**Comment by zshi-redhat** [comment]
With latest commits, these errors were fixed:
1) br-local is removed on all nodes
2) no errors for cleanup dgp
3) no allocation for dgp subnet

**Comment by trozet** [comment]
ci all broken

/retest

**Pull request closed without merging**
