### PR TITLE
[release-4.11] OCPBUGS-7319: Bump OVN to 22.09, enable session affinity timeout

### PR DESCRIPTION
**Pull request by tssurya**
See individual commits for more details.
/cc @dcbw @trozet : for help with risk analysis.

### CODE REVIEW

**Comment by tssurya** [comment]
NOTE: I haven't tagged the RPM yet. I'll do that after ensuring we are risk free.

**Comment by dcbw** [comment]
/lgtm
/approve
RPMs are tagged now, just have to wait for the sync

**Comment by zhaozhanqi** [comment]
using cluster-bot with this PR and setup one dual stack cluster.  and the following features

```
passed: (41.9s) 2023-02-13T10:58:17 "[sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (52.2s) 2023-02-13T10:58:28 "[sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (1m1s) 2023-02-13T10:58:36 "[sig-network] Services should have session affinity work for NodePort service [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (1m5s) 2023-02-13T10:58:41 "[sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (1m28s) 2023-02-13T10:59:03 "[sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance] [Skipped:Network/OVNKuberenetes] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (1m36s) 2023-02-13T10:59:11 "[sig-network] Networking Granular Checks: Services should function for client IP based session affinity: http [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]"

passed: (1m39s) 2023-02-13T10:59:14 "[sig-network] [Feature:IPv6DualStack] Granular Checks: Services Secondary IP Family [LinuxOnly] should function for client IP based session affinity: http [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]"

passed: (1m41s) 2023-02-13T10:59:16 "[sig-network] Networking Granular Checks: Services should function for client IP based session affinity: udp [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]"

passed: (1m43s) 2023-02-13T10:59:18 "[sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] [Skipped:Network/OVNKuberenetes] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]"

passed: (1m43s) 2023-02-13T10:59:19 "[sig-network] [Feature:IPv6DualStack] Granular Checks: Services Secondary IP Family [LinuxOnly] should function for client IP based session affinity: udp [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]"

Collection of node logs and analysis took: 3.339923969s
10 pass, 0 skip (1m46s)
```
/label qe-approved

**Pull request merged**
