### PR TITLE
[wip]: Make pod event handling parallel

### PR DESCRIPTION
**Pull request by abhat**
Let pod event handling be parallel to use multiple informer queues for scalability.

### CODE REVIEW

**Comment by danwinship** [comment]
@abhat is this PR still useful or did you just forget to close it?

**Comment by abhat** [comment]
> @abhat is this PR still useful or did you just forget to close it?

No, I have been making changes to it for my testing of go-ovn bindings. No need to review it. I haven't been pushing it. I guess I will close it for now.

**Pull request closed without merging**
