### PR TITLE
iptables package is missing in microshift image

### PR DESCRIPTION
**Pull request by zshi-redhat**
Signed-off-by: Zenghui Shi <zshi@redhat.com>

### CODE REVIEW

**Comment by dcbw** [comment]
@zshi-redhat do we need the same change in the rhel8 Dockerfile.base ?

**Comment by zshi-redhat** [comment]
> @zshi-redhat do we need the same change in the rhel8 Dockerfile.base ?

Yes, let me update the PR.

**Comment by zshi-redhat** [comment]
> > @zshi-redhat do we need the same change in the rhel8 Dockerfile.base ?
> 
> Yes, let me update the PR.

Done.

**Pull request merged**
