### PR TITLE
[release-4.10] Bug 2105276: Fix panics in DestroyNetworkPolicy if policy is nil

### PR DESCRIPTION
**Pull request by tssurya**
Not clean cherry-pick. I included some fixes from Cathy's PR's that will be useful in 4.10.
All conflicts are outlined in each of the commits if any.

### CODE REVIEW

**Comment by anuragthehatter** [comment]
This needs a backport-risk-assessed label before QE can approve this. QE regression on NP cases lookg good though. Thanks

**Review by trozet — APPROVED** [review]
/approve
/label backport-risk-assessed

**Review by flavio-fernandes — COMMENTED** [review]
**NOTE**: I notice that the backport commit  https://github.com/openshift/ovn-kubernetes/pull/1182/commits/0c5fe55849e2c7cf2401e0fc074923f9b4164dc2 ,
does not include the bulkop flag to `true` as what was done in https://github.com/openshift/ovn-kubernetes/commit/bcac90774b76a33088036fedc2504928a95dc89e#r78239672 .
I'm assuming that was intentional.

**Pull request merged**
