### PR TITLE
SDN-4157: DownstreamMerge 25th march 2024

### PR DESCRIPTION
**Pull request by tssurya**
@kyrtapz @maiqueb @jluhrsen @pperiyasamy @qinqon

### CODE REVIEW

**Comment by maiqueb** [comment]
+1 / lgtm on my 2 doc commits.

**Comment by pperiyasamy** [comment]
/lgtm 
for my EgressQoS commits.

**Comment by tssurya** [comment]
```
�[91m�[1m[Fail] �[0m�[90mOVN master EgressIP Operations �[0m�[0mOn node DELETE �[0m�[90m[secondary host network] should perform proper OVN transactions when namespace and pod is created after node egress label switch �[0m�[91m�[1m[It] interconnect enabled; node1 in global and node2 in remote zones �[0m
�[37m/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/egressip_test.go:3105�[0m
```
I am unsure why this UT is failing here: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2100/pull-ci-openshift-ovn-kubernetes-master-unit/1775085344073453568

```
2024/04/02 09:20:23 server: "caller"={"file"="server.go" "line"=211} "msg"="Skipping transaction DB commit due to error" "error"="failed to process operation" "operations"=[{"op"="wait" "table"="Logical_Router_Policy" "rows"=[{"priority"=501 "match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"}] "columns"=["priority" "match"] "timeout"=0 "where"=["where column priority == 501" "where column match == inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"] "until"="!="} {"op"="insert" "table"="Logical_Router_Policy" "row"={"priority"=501 "action"="reroute" "match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "nexthops"="100.64.0.4"} "uuid"="b5ce8686-2d6d-4702-9f8c-83720dead160"} {"op"="mutate" "table"="Logical_Router" "mutations"=[{"Column"="policies" "Mutator"="insert" "Value"={"uuid"="b5ce8686-2d6d-4702-9f8c-83720dead160"}}] "where"=["where column _uuid == {23b0d751-6abd-44db-873c-124393a71a53}"]}] "results"=[{"error"="timed out" "uuid"={"uuid"=""}} null null] "operation error"="timed out"
2024/04/02 09:20:23 server: "caller"={"file"="server.go" "line"=211} "msg"="Skipping transaction DB commit due to error" "error"="failed to process operation" "operations"=[{"op"="wait" "table"="Logical_Router_Policy" "rows"=[{"match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "priority"=501}] "columns"=["priority" "match"] "timeout"=0 "where"=["where column priority == 501" "where column match == inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"] "until"="!="} {"op"="insert" "table"="Logical_Router_Policy" "row"={"nexthops"="100.64.0.4" "priority"=501 "action"="reroute" "match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"} "uuid"="477121d8-9ec2-4158-8073-eb36453f5eca"} {"op"="mutate" "table"="Logical_Router" "mutations"=[{"Column"="policies" "Mutator"="insert" "Value"={"uuid"="477121d8-9ec2-4158-8073-eb36453f5eca"}}] "where"=["where column _uuid == {23b0d751-6abd-44db-873c-124393a71a53}"]}] "results"=[{"error"="timed out" "uuid"={"uuid"=""}} null null] "operation error"="timed out"
2024/04/02 09:20:23 server: "caller"={"file"="server.go" "line"=211} "msg"="Skipping transaction DB commit due to error" "error"="failed to process operation" "operations"=[{"op"="wait" "table"="Logical_Router_Policy" "rows"=[{"match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "priority"=501}] "columns"=["priority" "match"] "timeout"=0 "where"=["where column priority == 501" "where column match == inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"] "until"="!="} {"op"="insert" "table"="Logical_Router_Policy" "row"={"action"="reroute" "match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "nexthops"="100.64.0.4" "priority"=501} "uuid"="96a99ea6-15ce-4e44-93b1-e5ff47184d96"} {"op"="mutate" "table"="Logical_Router" "mutations"=[{"Column"="policies" "Mutator"="insert" "Value"={"uuid"="96a99ea6-15ce-4e44-93b1-e5ff47184d96"}}] "where"=["where column _uuid == {23b0d751-6abd-44db-873c-124393a71a53}"]}] "results"=[{"error"="timed out" "uuid"={"uuid"=""}} null null] "operation error"="timed out"
2024/04/02 09:20:23 server: "caller"={"file"="server.go" "line"=211} "msg"="Skipping transaction DB commit due to error" "error"="failed to process operation" "operations"=[{"op"="wait" "table"="Logical_Router_Policy" "rows"=[{"match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "priority"=501}] "columns"=["priority" "match"] "timeout"=0 "where"=["where column priority == 501" "where column match == inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14"] "until"="!="} {"op"="insert" "table"="Logical_Router_Policy" "row"={"action"="reroute" "match"="inport == \"rtos-node1\" && ip4.src == $a11971853777183785484 && ip4.dst != 10.128.0.0/14" "nexthops"="100.64.0.4" "priority"=501} "uuid"="34273389-836c-415e-91af-3f5fa981eab7"} {"op"="mutate" "table"="Logical_Router" "mutations"=[{"Column"="policies" "Mutator"="insert" "Value"={"uuid"="34273389-836c-415e-91af-3f5fa981eab7"}}] "where"=["where column _uuid == {23b0d751-6abd-44db-873c-124393a71a53}"]}] "results"=[{"error"="timed out" "uuid"={"uuid"=""}} null null] "operation error"="timed out"
```
heh; saving link to open a flake, retesting

**Pull request merged**
