### PR TITLE
[DownstreamMerge] 8-16-23

### PR DESCRIPTION
**Pull request by trozet**
Includes hybrid overlay fix and egress IP.

@martinkennelly @jcaamano FYI

### CODE REVIEW

**Comment by zshi-redhat** [comment]
known issue https://issues.redhat.com/browse/OCPBUGS-16629

needs override for:
e2e-aws-ovn-local-to-shared-gateway-mode-migration
e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration

**Comment by zshi-redhat** [comment]
probably need to override the following windows jobs as well
e2e-aws-ovn-windows
e2e-vsphere-ovn-windows

known WMCO issue as mentioned by @jcaamano in another [PR](https://github.com/openshift/ovn-kubernetes/pull/1817#issuecomment-1680165070)
https://redhat-internal.slack.com/archives/CM4ERHBJS/p1692035137053939

**Comment by zshi-redhat** [comment]
e2e-aws-ovn-hypershift failed with `Error: required inputs are missing: infrastructure ID is required`

/test e2e-aws-ovn-hypershift

**Comment by zshi-redhat** [comment]
e2e-aws-ovn-hypershift failed multiple times, looks like it is related to the egressip change:
```
W0817 01:36:34.405511       1 egressip_event_handler.go:89] Egress node initialization error: unable to use node ip-10-0-135-4.ec2.internal for egress assignment, err: k8s.ovn.org/node-primary-ifaddr annotation not found for node "ip-10-0-135-4.ec2.internal"
```

**Comment by zshi-redhat** [comment]
> e2e-aws-ovn-hypershift failed to create hosted cluster multiple times, looks like it is related to the egressip change:
> 
> ```
> W0817 01:36:34.405511       1 egressip_event_handler.go:89] Egress node initialization error: unable to use node ip-10-0-135-4.ec2.internal for egress assignment, err: k8s.ovn.org/node-primary-ifaddr annotation not found for node "ip-10-0-135-4.ec2.internal"
> ```

maybe this is just a transient failure.

**Comment by jcaamano** [comment]
known WMCO issue: https://redhat-internal.slack.com/archives/CM4ERHBJS/p1692035137053939

/override ci/prow/e2e-vsphere-ovn-windows
/override ci/prow/e2e-aws-ovn-windows

**Pull request merged**
