### PR TITLE
[release-4.12] OCPBUGS-16336: Backport support AllocateLoadBalancerNodePortsFalse 

### PR DESCRIPTION
**Pull request by andreaskaris**
Fixes https://issues.redhat.com/browse/OCPBUGS-16336
~~~
  git cherry-pick -x 40199eed08d999e760deba3d09a1125a09c8624b
  git cherry-pick -x 0111e1faec20d16505a110449966273b430b7ad1
~~~

a)  Conflicts in pkg/node/gateway_shared_intf.go require  40199eed08d999e760deba3d09a1125a09c8624b, therefore I cherry-picked that one as well

b) /development/ovn-kubernetes/go-controller/pkg/node/gateway_iptables.go

Minor conflict on comment only at:
~~~
  491 //        if !svcHasLocalHostNetEndPnt and svcTypeIsITPLocal, rule that marks clusterIP traffic to steer it to ovn-k8s-mp0 is added.
  492 //                                                                                                                      
>>493 <<<<<<< HEAD                                                                                                            
  494 func getGatewayIPTRules(service *kapi.Service, svcHasLocalHostNetEndPnt bool) []iptRule {                               
  495 =======                                                                                                                 
  496 //  if !svcHasLocalHostNetEndPnt and svcTypeIsITPLocal, rule that marks clusterIP traffic to steer it to ovn-k8s-mp0 is added.
  497 func getGatewayIPTRules(service *kapi.Service, localEndpoints []string, svcHasLocalHostNetEndPnt bool) []iptRule {      
  498 >>>>>>> 0111e1fae (Support AllocateLoadBalancerNodePortsFalse) 
~~~

c) Conflicts in pkg/node/gateway_shared_intf.go due to out of order cherry-pick where aceef010daf0697fe81dba91a39ed0fdb6563dea merged first

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by trozet** [comment]
note: original PR upstream with e2e test: https://github.com/ovn-org/ovn-kubernetes/pull/3151/commits

**Review by tssurya — APPROVED** [review]
the changes lgtm. thanks @andreaskaris: since risk is minimal we decided we could just backport this, let's make sure the doc bug reflects that then - the fact that we will support this starting from 4.12.z stream or whatever..
I am bringing up a cluster to test this out. - once I verify this will add the label.
TYSM @andreaskaris !

**Comment by tssurya** [comment]
```
$ oc get svc -n surya
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
hello-world-2   LoadBalancer   172.30.99.126   35.224.169.37   80:30261/TCP   89s
```
```
$ oc get po -n surya -owide
NAME                             READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
hello-world-2-6454869ff6-fvz59   1/1     Running   0          34m   10.128.2.13   ci-ln-htbqhxb-72292-wzknb-worker-b-f9z9s   <none>           <none>
hello-world-2-6454869ff6-pbq2m   1/1     Running   0          34m   10.128.2.14   ci-ln-htbqhxb-72292-wzknb-worker-b-f9z9s   <none>           <none>
hello-world-2-6454869ff6-ptvn8   1/1     Running   0          34m   10.131.0.13   ci-ln-htbqhxb-72292-wzknb-worker-a-2cmjt   <none>           <none>
hello-world-2-6454869ff6-wj2vd   1/1     Running   0          34m   10.129.2.17   ci-ln-htbqhxb-72292-wzknb-worker-c-g98tc   <none>           <none>
```
With nodeports:
```
[0:0] -A OVN-KUBE-ETP -d 35.224.169.37/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 169.254.169.3:30261
[0:0] -A OVN-KUBE-ETP -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 30261 -j DNAT --to-destination 169.254.169.3:30261
```
w/o NPs:
```
workera
[0:0] -A OVN-KUBE-ETP -d 35.224.169.37/32 -p tcp -m tcp --dport 80 -m statistic --mode random --probability 1.00000000000 -j DNAT --to-destination 10.131.0.13:8080
workerb
[0:0] -A OVN-KUBE-ETP -d 35.224.169.37/32 -p tcp -m tcp --dport 80 -m statistic --mode random --probability 0.50000000000 -j DNAT --to-destination 10.128.2.13:8080
[0:0] -A OVN-KUBE-ETP -d 35.224.169.37/32 -p tcp -m tcp --dport 80 -m statistic --mode random --probability 1.00000000000 -j DNAT --to-destination 10.128.2.14:8080
workerc
[1:60] -A OVN-KUBE-ETP -d 35.224.169.37/32 -p tcp -m tcp --dport 80 -m statistic --mode random --probability 1.00000000000 -j DNAT --to-destination 10.129.2.17:8080
```
```
[surya@hidden-temple yaml_debugging]$ curl 35.224.169.37:80
Hello Kubernetes!
```

**Comment by asood-rh** [comment]
@andreaskaris How far back are the plans to put in this change?

**Comment by andreaskaris** [comment]
@asood-rh only 4.12

**Pull request merged**
