### PR TITLE
[DownstreamMerge] Fix previous downstream merge

### PR DESCRIPTION
**Pull request by trozet**
Un-reverts https://github.com/openshift/ovn-kubernetes/pull/809

Pulls in latest upstream changes which include a fix for port addresses syntax and libovsdb fixes.

### CODE REVIEW

**Comment by trozet** [comment]
/hold
until we can get a green light on promotion tests

@dead2k @stbenjam can we get the promotion tests to run on this image and see if the issues with upgrade are fixed? Can wait until the PR CI is done and shows good results if you want.

**Comment by trozet** [comment]
Pulled in a couple more fixes from upstream:
https://github.com/ovn-org/ovn-kubernetes/pull/2581
https://github.com/ovn-org/ovn-kubernetes/pull/2572

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-ipv6
```
+(./04_setup_ironic.sh:141): main(): sudo podman ps --all
+(./04_setup_ironic.sh:141): main(): grep -w 'ipa-downloader$'
+(./04_setup_ironic.sh:145): main(): sudo podman pod exists ironic-pod
+(./04_setup_ironic.sh:150): main(): sudo podman pod create -n ironic-pod
time="2021-11-02T13:57:32Z" level=error msg="Error freeing pod lock after failed creation: no such file or directory"
Error: error adding Infra Container: error pulling infra-container image: Error initializing source docker://registry.access.redhat.com/ubi8/pause:latest: error pinging docker registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": dial tcp: lookup registry.access.redhat.com on 127.0.0.1:53: read udp 127.0.0.1:40382->127.0.0.1:53: i/o timeout
+(./04_setup_ironic.sh:1): main(): removetmp
+(utils.sh:588): removetmp(): '[' -n ' /tmp/release-update--eeANlP2Fij /tmp/mirror-installer--UDJUAS7W3S' ']'
+(utils.sh:588): removetmp(): rm -rf /tmp/release-update--eeANlP2Fij /tmp/mirror-installer--UDJUAS7W3S
make: *** [Makefile:21: ironic] Error 125
Fetching kubeconfig, other credentials...
scp: /root/dev-scripts/ocp/ostest/auth/kubeconfig: No such file or directory
scp: /root/dev-scripts/ocp/ostest/auth/kubeadmin-password: No such file or directory
Adding proxy-url in kubeconfig
sed: can't read /tmp/secret/kubeconfig: No such file or directory
dev-scripts setup completed, fetching logs
tar: Removing leading `/' from member names
Removing REDACTED info from log...
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-11-02T13:57:35Z"}
error: failed to execute wrapped command: exit status 2 
```

**Comment by dcbw** [comment]
The AWS tests are all failing:
`[sig-builds][Feature:Builds] clone repository using git:// protocol should clone using git:// if no proxy is configured`

Slack thread: https://coreos.slack.com/archives/CFUGK0K9R/p1635864176016300

**Comment by dcbw** [comment]
openstack job failures are due to something sucking up so much CPU that NBDB cannot process any requests from ovnkube-master. Or perhaps that our instance types in PSI are too small.

**Comment by jluhrsen** [comment]
the last run of jobs had quite a few of initial cluster setup issues it seemed. Some of the jobs that made it past that
and failed didn't seem to have the symptom I was digging in to yesterday where pods were not coming up. I'll keep an eye on these jobs. I also ran our real upgrade 4.8->4.10 which seemed to show the pod creation issue more frequently I think. we can run that a few times in a row.

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-ipv6
```
+(./04_setup_ironic.sh:118): main(): echo 'export MIRRORED_RELEASE_IMAGE=registry.build01.ci.openshift.org/ci-op-8hcfdw7j/release@sha256:365680b8208b50608e790701821db517821329879cb95135a6de189e8b0fa1c4'
+(./04_setup_ironic.sh:122): main(): '[' -z '' ']'
+(./04_setup_ironic.sh:123): main(): oc adm release extract --registry-config /opt/dev-scripts/pull_secret.json --command=openshift-baremetal-install --to /tmp/mirror-installer--K8ushCBYBH virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:365680b8208b50608e790701821db517821329879cb95135a6de189e8b0fa1c4
error: unable to parse image registry.build01.ci.openshift.org/ci-op-8hcfdw7j/stable@sha256:cfb53848b9836a09ccf56a0b3b4d0b2fbaa8089e492b5a7027d2e948c21d94c4: cannot retrieve image configuration for manifest sha256:cfb53848b9836a09ccf56a0b3b4d0b2fbaa8089e492b5a7027d2e948c21d94c4: received unexpected HTTP status: 500 Internal Server Error
+(./04_setup_ironic.sh:1): main(): removetmp
+(utils.sh:588): removetmp(): '[' -n ' /tmp/release-update--mwvOtHVvo9 /tmp/mirror-installer--K8ushCBYBH' ']'
+(utils.sh:588): removetmp(): rm -rf /tmp/release-update--mwvOtHVvo9 /tmp/mirror-installer--K8ushCBYBH
make: *** [Makefile:21: ironic] Error 1
```

**Pull request merged**
