### PR TITLE
OCPBUGS-18402: Make ovnkube-trace to work for ovnkube-controller

### PR DESCRIPTION
**Pull request by pperiyasamy**
Clean cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3889.
/assign @kyrtapz @trozet

### CODE REVIEW

**Comment by tssurya** [comment]
wait these are not critical bugs why are we cherry-picking them? the more we cherry-pick the more chance of conflicts, why don't we wait for d/s merge?

**Comment by pperiyasamy** [comment]
closing it in favor of https://github.com/openshift/ovn-kubernetes/pull/1868.

**Pull request closed without merging**
