### PR TITLE
[wip] ovn2.13-20.06.1-12-fdn soak test for rhbz#1860053

### PR DESCRIPTION
**Pull request by numansiddique**
Signed-off-by: Numan Siddique <nusiddiq@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by numansiddique** [comment]
@dcbw

**Comment by aojea** [comment]
do you need to test this or is superseded by the other PR with 20.06.1-6?

**Comment by numansiddique** [comment]
Probably I would need both as this fixes an issue and the other improves the conntrack usage in OVN. But this build is buggy.

I'll update the PR with the new rpms. Till then pelase don't trigger a run.

Also I'll be testing these rpms first in the ovn-k8s CI.

**Comment by numansiddique** [comment]
> I assume you're just creating a specific image for ovn for that BZ?

That's right and see if there  are any regressions in the openshift tests because of changes in OVN.

**Pull request closed without merging**
