### PR TITLE
[release-4.18] OCPBUGS-46527: Network policies in UDN do not work

### PR DESCRIPTION
**Pull request by pperiyasamy**
clean cherry-pick from 4.19, no conflicts.

/assign @qinqon @dceara @tssurya @trozet

### CODE REVIEW

**Comment by tssurya** [comment]
/hold

@jluhrsen is doing syncs why are we cherrypicking commits ?

**Comment by pperiyasamy** [comment]
> @jluhrsen is doing syncs why are we cherrypicking commits ?

yes @tssurya , i missed that somehow, closing this PR in favor of https://github.com/openshift/ovn-kubernetes/pull/2403.

**Pull request closed without merging**
