### PR TITLE
SDN-3931,OCPBUGS-29952,OCPBUGS-25889: Downstream merge 12 04 24

### PR DESCRIPTION
**Pull request by martinkennelly**
@npinaeva @bpickard22

### CODE REVIEW

**Comment by martinkennelly** [comment]
/hold 

OVN isnt bumped in base.

**Comment by martinkennelly** [comment]
/retest

Unrelated to this PR

**Comment by npinaeva** [comment]
/retitle SDN-3931,OCPBUGS-29952,OCPBUGS-25889: Downstream merge 12 04 24

**Comment by tssurya** [comment]
/approve
/lgtm
the dualstack failures are well known: https://issues.redhat.com/browse/OCPBUGS-23957

**Pull request merged**
