### PR TITLE
Bug 1976215: Fix: sync egress IP for missed events on start-up

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Cherry-picked without problems from: https://github.com/ovn-org/ovn-kubernetes/pull/2300

/assign @abhat @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
/approve
/lgtm
Failures are largely flakes; the "pod OVN annotations changed" ones indicate that the pod was deleted and re-created underneath the CNI plugin, so the CNI plugin running for the first pod's sandbox must exit and let the second sandbox run instead.

**Comment by abhat** [comment]
The ovn dualstack job has been perma-failing on the external connectivity test.
Overriding that job.
/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Comment by Reamer** [comment]
I hope this will be backported to 4.7 and 4.8.

**Comment by alexanderConstantinescu** [comment]
> I hope this will be backported to 4.7 and 4.8.

4.8 back-port: https://github.com/openshift/ovn-kubernetes/pull/665

**Pull request merged**
