### PR TITLE
[release-4.12] Bug OCPBUGS-4379: apply retry logic to ovnk-node controllers

### PR DESCRIPTION
**Pull request by ricky-rav**
apply retry logic to ovnk node controllers.

Clean cherry pick, but it required to include also these dependent changes:

- dependent commit from @bpickard22: https://github.com/openshift/ovn-kubernetes/commit/fc2c3b9ebb3ab47392cb5083a2361ed64e25521f
- CI fix from @dcbw https://github.com/ovn-org/ovn-kubernetes/pull/3275/commits/27aa9982590a927a6e54150d826ac315d4d654f5, without which we get a bunch of "operation not permitted" errors upon performing (real) conntrack operations on downstream CI:
```
• Failure [0.125 seconds]
Node Operations
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_localnet_linux_test.go:161
  on add and delete
  /go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_localnet_linux_test.go:1378
    manages iptables rules and openflows for NodePort backed by ovn-k pods where ETP=local, SGW [It]
    /go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_localnet_linux_test.go:1861

    Unexpected error:
        <*errors.errorString | 0xc00078f460>: {
            s: "DeleteService failed for nodePortWatcher: failed to delete conntrack entry for service namespace1/service1: failed to delete conntrack entry for service namespace1/service1 with nodeIP 10.128.174.235, nodePort 8080, protocol TCP: operation not permitted",
        }
        DeleteService failed for nodePortWatcher: failed to delete conntrack entry for service namespace1/service1: failed to delete conntrack entry for service namespace1/service1 with nodeIP 10.128.174.235, nodePort 8080, protocol TCP: operation not permitted
    occurred

    /go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_localnet_linux_test.go:1958
```

Original upstream PR: https://github.com/ovn-org/ovn-kubernetes/pull/3176

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by ricky-rav** [comment]
`tide` is totally going nuts...

/retest-required

**Pull request merged**
