### PR TITLE
OCPBUGS-37196: [release-4.15] ovspinning: Set affinity of each thread

### PR DESCRIPTION
**Pull request by cgoncalves**
Backport of https://github.com/openshift/ovn-kubernetes/pull/2220

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by jcaamano** [comment]
/overide ci/prow/e2e-metal-ipi-ovn-ipv6 

Unrelated, a bug has been created to track this
https://issues.redhat.com/browse/OCPBUGS-37717

**Pull request merged**
