### PR TITLE
OCPBUGS-26023: Dockerfile: Bump OVN to ovn-23.09.0-100.el9fdp

### PR DESCRIPTION
**Pull request by dceara**
Includes the following relevant change:
- Make sure affinity learnt flows are auto deleted.
  [https://issues.redhat.com/browse/OCPBUGS-26023]
  [https://issues.redhat.com/browse/FDP-257]

### CODE REVIEW

**Comment by dceara** [comment]
/hold

Waiting for green light from upstream https://github.com/ovn-org/ovn-kubernetes/pull/4088.

@trozet @npinaeva

**Comment by dceara** [comment]
/retest

`ci/prow/okd-e2e-gcp-ovn` fails in similar ways with other PRs, likely unrelated.

`ci/prow/e2e-aws-ovn-windows` - `Contained sensitive information -- content removed.` I'm not sure what to make of this; I think the cluster bringup failed.

`ci/prow/e2e-vsphere-ovn`:
```

tar: ./6650517f9707ca92ba6404efae69667c25bae8ff87efe7e1aa96968f542ad84c/audit_logs/kube-apiserver/ci-op-6yxxsw22-fb62e-4x96m-master-0-audit-2024-01-16T23-08-18.475.log.gz: file changed as we read it
tar: ./6650517f9707ca92ba6404efae69667c25bae8ff87efe7e1aa96968f542ad84c/audit_logs/kube-apiserver: file changed as we read it
tar: ./6650517f9707ca92ba6404efae69667c25bae8ff87efe7e1aa96968f542ad84c/audit_logs: file changed as we read it
tar: ./6650517f9707ca92ba6404efae69667c25bae8ff87efe7e1aa96968f542ad84c: file changed as we read it
tar: .: file changed as we read it
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-01-16T23:33:52Z"}
error: failed to execute wrapped command: exit status 1
}
```
happens at must gather time, probably a flake

`ci/prow/4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade`:
```
response Body: {"ProwJobName":"pull-ci-openshift-ovn-kubernetes-master-4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade","ProwJobRunID":1747360164849127424,"Release":"Presubmits","CompareRelease":"4.16","Tests":[{"Name":"[sig-node][invariant] alert/TargetDown should not be at or above info in ns/kube-system","Risk":{"Level":{"Name":"High","Level":100},"Reasons":["This test has passed 99.68% of 928 runs on jobs ['periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade'] in the last 14 days."]},"OpenBugs":[]}],"OverallRisk":{"Level":{"Name":"High","Level":100},"Reasons":["Maximum failed test risk: High"]},"OpenBugs":[]}
```
Looks unrelated.

`ci/prow/e2e-aws-ovn-kubevirt`:
```
error: failed to create/update secret: failed to update secret: Timeout: request did not complete within requested timeout - context deadline exceeded 
```
Unrelated.

**Comment by npinaeva** [comment]
Included to https://github.com/openshift/ovn-kubernetes/pull/2018

**Comment by dceara** [comment]
Closing in favor of #2018

**Pull request closed without merging**
