### PR TITLE
[WIP] DNM Downstream hybrid gw mode

### PR DESCRIPTION
**Pull request by trozet**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by trozet** [comment]
aws and gcp are having image build problems:

1/6 Tests Failed. | expand_less
-- | --
: Clone the correct source code into an image and tag it as src expand_more | : Clone the correct source code into an image and tag it as src expand_more
: Clone the correct source code into an image and tag it as src expand_more

**Comment by dcbw** [comment]
https://github.com/openshift/ovn-kubernetes/pull/269

**Pull request closed without merging**
