### PR TITLE
Bug 1880591: 9-30-2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Fixes:
- Upgrade by ensuring reject ACLs get removed.
- logical route policy deletion when nodes are deleted.

### CODE REVIEW

**Comment by trozet** [comment]
@dcbw @danwinship

**Comment by trozet** [comment]
more external load balancer problems on GCP:
 Get "https://api.ci-op-r9726gmv-99b10.origin-ci-int-gce.dev.openshift.com:6443/api/v1/nodes?fieldSelector=spec.unschedulable%3Dfalse&resourceVersion=0": dial tcp 34.73.222.91:6443: i/o timeout

**Comment by dcbw** [comment]
azure is still failing due to capacity issues

**Pull request merged**
