### PR TITLE
Bug 1959352: scale fixes 1

### PR DESCRIPTION
**Pull request by trozet**
Includes a bunch of scale fixes to make ovnkube-master more efficient at pod handling.

### CODE REVIEW

**Comment by dcbw** [comment]
gcp-ovn failure happened before any ovnkube components even started; kubelet didn't have serviceaccount tokens for GCP or something during bootstrap so ti couldn't run any containers.
/retest

**Comment by dcbw** [comment]
/test e2e-ovn-hybrid-step-registry
e2e tests completed successfully with no failures, except that must-gather could not run:
```
[36mINFO[0m[2021-08-19T04:21:55Z] Logs for container test in pod e2e-ovn-hybrid-step-registry-gather-extra: 
[36mINFO[0m[2021-08-19T04:21:55Z] {"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 600ns timeout","severity":"error","time":"2021-08-19T04:21:49Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:252","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15s grace period","severity":"error","time":"2021-08-19T04:21:49Z"}
{"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-08-19T04:21:49Z"}
error: failed to execute wrapped command: exit status 127 
[36mINFO[0m[2021-08-19T04:21:55Z] Step e2e-ovn-hybrid-step-registry-gather-extra failed after 10s. 
```

**Comment by dcbw** [comment]
Many of the CI failures are fixed by https://github.com/openshift/release/pull/21215

**Comment by trozet** [comment]
/hold

going to pull in subsequent fixes

**Comment by trozet** [comment]
/hold

there is a segfault that can happen:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/667/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1428456311216934912

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
The failing tests were supposed to be skipped (one is bogus, two are not yet supported) but got unskipped the other day with the 1.22 rebase.

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
The cluster just doesn't have network connectivity to pull the installer:
```
+(utils.sh:12): retry_with_timeout(): timeout 60 bash -c 'curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | sudo tar -U -C /usr/local/bin -xzf -'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0+(utils.sh:12): retry_with_timeout(): exit_code=124
+(utils.sh:13): retry_with_timeout(): ((  exit_code == 0  ))
+(utils.sh:18): retry_with_timeout(): return 124
+(./01_install_requirements.sh:1): main(): removetmp
```

**Pull request merged**
