### PR TITLE
Enable CNCC in OVNK

### PR DESCRIPTION
**Pull request by andreaskaris**
Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dulek** [comment]
/retest

Let's see the OpenStack job passing.

**Comment by andreaskaris** [comment]
Ah yeah this is not how this works, anyway. We already merged this upstream so we have to wait for the downstream merge: https://github.com/ovn-org/ovn-kubernetes/commit/eeef0175d948852fd67ff42a1ad6ed2956b92267

This one here was just for the clusterbot tests. Sorry about that!

**Pull request closed without merging**
