### PR TITLE
OCPBUGS-28848: Ignore hybrid-overlay nodes from EgressIP controller

### PR DESCRIPTION
**Pull request by kyrtapz**
Clean cherry pick from 63641aa8b5faa50be2e7f33b49a6d95c1eacf36e

### CODE REVIEW

**Comment by kyrtapz** [comment]
//jira cherry-pick OCPBUGS-23430

**Comment by kyrtapz** [comment]
@tssurya ptal as you approved the initial change

**Review by tssurya — APPROVED** [review]
/lgtm
/label backport-risk-assessed
ditto same as https://github.com/openshift/ovn-kubernetes/commit/63641aa8b5faa50be2e7f33b49a6d95c1eacf36e

**Comment by tssurya** [comment]
@kyrtapz : do you have a cu waiting for this fix? why are we backporting this to 4.14? we do not backport by default.

**Pull request merged**
