### PR TITLE
Revert "cluster.go: Disable Southbound DB conditional monitoring."

### PR DESCRIPTION
**Pull request by pecameron**
This reverts commit 799df52e72d24d77d5531e0961609ae9e43ca8b6.

### CODE REVIEW

**Comment by pecameron** [comment]
@dcbw @danwinship PTAL

**Comment by danwinship** [comment]
@dcbw knows the details of what we're doing here so I'll defer to him.

If the upstream code fails with some versions of OVN though should we revert/fix it upstream?

**Comment by dcbw** [comment]
@pecameron can you backport for 4.5 as well please?

**Pull request merged**
