### PR TITLE
Revert "[DownstreamMerge] 8-8-2022"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/ovn-kubernetes#1237

Some concerns https://github.com/openshift/ovn-kubernetes/pull/1248 may not be enough, opening another test revert to increase odds we get something we can merge to get payloads going again.

### CODE REVIEW

**Comment by trozet** [comment]
@dgoodwin from your aggregator runs: 
```

: [sig-apps] Deployment should not disrupt a cloud load-balancer's connectivity during rollout [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less | 0s
-- | --
{Failed: Passed 5 times, failed 4 times.  The historical pass rate is 100%.  The required number of passes is 8.  name: '[sig-apps] Deployment should not disrupt a cloud load-balancer''s connectivity   during rollout [Suite:openshift/conformance/parallel] [Suite:k8s]' testsuitename: openshift-tests summary: 'Failed: Passed 5 times, failed 4 times.  The historical pass rate is 100%.  The   required number of passes is 8.' passes:
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade/1559976211025760256

**Comment by stbenjam** [comment]
Took https://github.com/openshift/ovn-kubernetes/pull/1248 instead.  Note, this is a one-off since our process is TRT should revert the entire breaking PR.

/close

**Pull request closed without merging**
