### PR TITLE
OCPBUGS-5841: ovnkube-node: Existing management port check

### PR DESCRIPTION
**Pull request by wizhaoredhat**
When ovnkube-node configures management port interface it may fail if host already have it configured but it is different interface. To handle that do the following:
- verify that port exists on the integrational bridge and it represents provided management port netdevice or OVS internal port, if no netdevice were provided;
- verify that no interface exists with the name of the management port;

If any of the checks had failed then need to remove port from the bridge, unless it is OVS internal port and we expect it; flush IP addresses, routes, tables from management netdevice interface. Both representor and netdevice interfaces renamed to original names, if latter stored in OVS database, or to generic names: {net|rep} + ddmmyyHHMMSS

Because ovnkube doesn't have unload sequence, port check done during new management port creation.

Signed-off-by: Dmytro Linkin <dlinkin@nvidia.com>
(cherry picked from upstream commit 9da055f26906d2dcf40af2584df9196878116503)

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@trozet

**Comment by wizhaoredhat** [comment]
@huiran0826 Could you please provide the cherry-pick-approved label?

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

failed is unrelated to this error.

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
failure unrelated to this PR

**Pull request merged**
