### PR TITLE
OCPBUGS-17773: Perf increases to pod deletion

### PR DESCRIPTION
**Pull request by trozet**
Includes critical performance fixes for 4.14.

### CODE REVIEW

**Comment by jcaamano** [comment]
@trozet this might increase the probability for the duplicated IPs race condition to happen. The pod is updated with status IP later than the annotation, increasing the time window we might not notice another pod has been allocated with that IP.

**Comment by trozet** [comment]
local gateway jobs are broken for a different reason. Overriding..

/override ci/prow/e2e-aws-ovn-local-gateway
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

**Pull request merged**
