### PR TITLE
[release-4.13] OCPBUGS-14492: Backport OVN component templates for NodePort services.

### PR DESCRIPTION
**Pull request by dceara**
**- What this PR does and why is it needed**
This is a backport to 4.13 of the LB Templates implementation of NodePort services.  It includes the commits from the following upstream PRs:
- [Use OVN component templates for NodePort services.](https://github.com/ovn-org/ovn-kubernetes/pull/3430)
- [services: Don't try to list/cleanup templates when OVN doesn't support that.](https://github.com/ovn-org/ovn-kubernetes/pull/3523)

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dceara** [comment]
CC: @abhat @dcbw @trozet @tssurya @jcaamano

**Comment by dceara** [comment]
`ci/prow/e2e-vsphere-windows` failure after the test stage while:
```
 INFO[2023-06-15T16:51:14Z] Running step e2e-vsphere-windows-gather-extra. 
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2023-06-15T16:52:16Z"}
INFO[2023-06-15T16:52:16Z] Received signal.                              signal=interrupt 
```

**Comment by dceara** [comment]
`ci/prow/e2e-vsphere-ovn` failure seems to happen with other PRs too:
```
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (default fs)] provisioning should mount multiple PV pointing to the same storage on the same node [Suite:openshift/conformance/parallel] [Suite:k8s] 
```

**Comment by dceara** [comment]
`ci/prow/e2e-openstack-ovn` failure seems unrelated:
```
[sig-arch][Late] operators should not create watch channels very often [apigroup:apiserver.openshift.io] [Suite:openshift/conformance/parallel]
```

**Comment by dceara** [comment]
`ci/prow/e2e-aws-ovn-windows` failed to install cluster:
```
level=error msg=StaticPodsDegraded: pod/kube-controller-manager-ip-10-0-237-217.ec2.internal container "kube-controller-manager-recovery-controller" is terminated: Completed: 
level=info msg=Cluster operator kube-controller-manager Progressing is True with NodeInstaller: NodeInstallerProgressing: 1 nodes are at revision 5; 2 nodes are at revision 6
level=info msg=Cluster operator network ManagementStateDegraded is False with : 
level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
level=error msg=The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
level=error msg=https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
level=error msg=The 'wait-for install-complete' subcommand can then be used to continue the installation
level=error msg=failed to initialize the cluster: Cluster operator kube-controller-manager is degraded
Installer exit with code 6
```

**Comment by dceara** [comment]
Depends on https://github.com/openshift/ovn-kubernetes/pull/1708

**Comment by dceara** [comment]
The failure seems unrelated:
```
[sig-metal] should get working host from infra provider
{  ofcir: Failed to create ci resource: ipi-ci-op-s6zn5fx9-472d2-1676214644789743616}
```

**Comment by jcaamano** [comment]
Missed the originating commit for cherrypick `[release-4.13] OCPBUGS-14492: Backport OVN component templates for NodePort services.`

**Pull request merged**
