### PR TITLE
OCPBUGS-24219,OCPBUGS-22221,OCPBUGS-25670: Downstream Merge 31st Jan 2024

### PR DESCRIPTION
**Pull request by tssurya**
@npinaeva @JacobTanenbaum @pperiyasamy

### CODE REVIEW

**Comment by npinaeva** [comment]
/retitle OCPBUGS-24219,OCPBUGS-22221,OCPBUGS-25670: Downstream Merge 31st Jan 2024

**Comment by pperiyasamy** [comment]
https://github.com/openshift/ovn-kubernetes/pull/2038/commits/bc05711c9e32b9e322bb68dda32419cac21877ae is LGTM

**Pull request merged**
