### PR TITLE
OCPBUGS-4825: [DownstreamMerge] 12-14-22

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
upstream fix here: https://github.com/ovn-org/ovn-kubernetes/pull/3323

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn
https://bugzilla.redhat.com/show_bug.cgi?id=2150905

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
https://coreos.slack.com/archives/CFP6ST0A3/p1670860628776879

**Comment by dcbw** [comment]
/test  ci/prow/4.13-upgrade-from-stable-4.12-local-gateway-e2e-aws-ovn-upgrade

level=error msg=Error: error waiting for EC2 NAT Gateway (nat-08cddeeedf636e621) create: unexpected state 'failed', wanted target 'available'. last error: InvalidSubnetID.NotFound: The specified subnet subnet-07a56430336ce75fc does not exist

**Comment by dcbw** [comment]
/test 4.13-upgrade-from-stable-4.12-local-gateway-e2e-aws-ovn-upgrade

level=error msg=Error: error waiting for EC2 NAT Gateway (nat-08cddeeedf636e621) create: unexpected state 'failed', wanted target 'available'. last error: InvalidSubnetID.NotFound: The specified subnet subnet-07a56430336ce75fc does not exist

**Comment by dcbw** [comment]
/override ci/prow/4.13-upgrade-from-stable-4.12-local-gateway-e2e-aws-ovn-upgrade

```
info: Loading sha256:4a7e9ed868fd3addc69ef3ec20a69445479c9198f2fafbaeb95adbb5af90cd24 ovirt-installer
info: Loading sha256:8133299e00cd0986dcf1acf696c03765e76b333303c7057920c731c9391ea885 service-ca-operator
info: Loading sha256:18944680363311e637efc71e2378fbf093fe772ae61aab6d3aa7a22f4fef73a6 vsphere-cluster-api-controllers
info: Loading sha256:3e28b7b06d7795ee740d0f40efb74914595f12b99b5d585536e4f7a269c9abcc vsphere-problem-detector
error: unable to access the source layer sha256:04c07d90d5492d7b0ca1eaf4e4197104204f091b9fdd5ffc4000b0657eaa6df0: received unexpected HTTP status: 500 Internal Server Error
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-12-15T03:22:09Z"} 
[36mINFO[0m[2022-12-15T03:22:13Z] Ran for 17m24s                               
[31mERRO[0m[2022-12-15T03:22:13Z] Some steps failed:                           
[31mERRO[0m[2022-12-15T03:22:13Z] 
  * could not run steps: step [release:latest] failed: release "release-latest" failed: the pod ci-op-30xymw0m/release-latest failed after 16s (failed containers: release): ContainerFailed one or more containers exited
```

**Pull request merged**
