### PR TITLE
WIP: test OVS 72.fdp8

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
/cc

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
/test e2e-aws-ovn

`Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.`

**Comment by dcbw** [comment]
See also https://github.com/openshift/ovn-kubernetes/pull/361 for this same OVS version in 4.6, to isolate any instability in 4.7 CI from the OVS change.

**Comment by alexanderConstantinescu** [comment]
Most jobs seem to be passing, both `e2e-aws-ovn` / `e2e-azure-ovn` failed because of 

```
[sig-api-machinery][Feature:APIServer][Late] kubelet terminates kube-apiserver gracefully [Suite:openshift/conformance/parallel]
[sig-network] pods should successfully create sandboxes by other
[sig-network] pods should successfully create sandboxes by getting pod
[sig-network] pods should successfully create sandboxes by reading container
```

which if I remember correctly is a endemic problem with recent jobs.

**Pull request closed without merging**
