### PR TITLE
ovn: bump to ovn21.12-21.12.0-24.el8fdp

### PR DESCRIPTION
**Pull request by dcbw**
Pick up support for LoadBalancer Groups:

http://patchwork.ozlabs.org/project/ovn/list/?series=265023&archive=both&state=*

which can greatly improve performance/scale with large numbers of Kube Services, once ovnkube picks up the support.

### CODE REVIEW

**Comment by dceara** [comment]
@dcbw Shall we use the new (still building) ovn21.12-21.12.0-22 instead?  Some of the relevant differences between -21 and -21:

```
13be1f19d binding: Log iface-id-ver mismatch.
5c4010dd7 northd: Generate ARP responder flows only for reachable VIPs.
b609aeeb0 lflow: Consistent conjunction id generation.
773ecb283 test-utils: Add test_read_uint_hex_value helper.
274f84a35 lflow-cache: Remove conjunction id cache.
c24aed5dd lflow-cache.h: Fix comment about lflow-cache.
f4864726c controller: add memory accounting for local_datapath
fcac403e5 controller: keep mcast_query_list list in sync with sb configuration
b44f6373b northd: Do not calculate database sequence numbers incrementally
1fa6612ff northd: Add lflow node
7de82dcc5 northd: Call build_mcast_groups() from build_lflows()
5a9778510 northd: Introduce struct northd_data
ccb3a13e9 northd: Add n_nat_entries field to 'struct ovn_datapath'
4597317f1 northd: Introduce incremental processing for northd
e6bcb889a ovn-nbctl: Fix lrp-set-gateway-chassis.
45d9840ea northd: Don't add ARP responder flows for unreachable VIPs.
bb715113f northd: Treat reachable and unreachable VIPs differently.
5c6f8bd7b ovs: Bump submodule to include ovsdb/IDL optimizations.
```

**Comment by dceara** [comment]
> @dcbw Shall we use the new (still building) ovn21.12-21.12.0-22 instead? Some of the relevant differences between -21 and -21:
> 
> ```
> 13be1f19d binding: Log iface-id-ver mismatch.
> 5c4010dd7 northd: Generate ARP responder flows only for reachable VIPs.
> b609aeeb0 lflow: Consistent conjunction id generation.
> 773ecb283 test-utils: Add test_read_uint_hex_value helper.
> 274f84a35 lflow-cache: Remove conjunction id cache.
> c24aed5dd lflow-cache.h: Fix comment about lflow-cache.
> f4864726c controller: add memory accounting for local_datapath
> fcac403e5 controller: keep mcast_query_list list in sync with sb configuration
> b44f6373b northd: Do not calculate database sequence numbers incrementally
> 1fa6612ff northd: Add lflow node
> 7de82dcc5 northd: Call build_mcast_groups() from build_lflows()
> 5a9778510 northd: Introduce struct northd_data
> ccb3a13e9 northd: Add n_nat_entries field to 'struct ovn_datapath'
> 4597317f1 northd: Introduce incremental processing for northd
> e6bcb889a ovn-nbctl: Fix lrp-set-gateway-chassis.
> 45d9840ea northd: Don't add ARP responder flows for unreachable VIPs.
> bb715113f northd: Treat reachable and unreachable VIPs differently.
> 5c6f8bd7b ovs: Bump submodule to include ovsdb/IDL optimizations.
> ```

We should actually use ovn21.12-21.12.0-23.el8fdp instead, which picks up the BFD regression fix:
```
993d7113a (upstream/main) northd: I-P: fix BFD dependency.
```

**Comment by dceara** [comment]
ovn21.12-21.12.0-24.el8fdp is built and tagged downstream, we should change this PR to use it instead.  It picks up:
```
  904c55329 ovs: Bump submodule to include OVS library perf fixes.
  12ddb1c9d lflow-cache: Automatically trim cache when it becomes inactive.
  bcd9a8fb1 ovn-controller: Avoid infinite replying for TCP/ICMP connection reset messages
  58ed501ea controller: Add IDL memory reports.
  044b4a4ce northd: remove leftover references to l3redirect_port
  9e8d24eb7 inc-proc-eng: Add inc-engine/recompute command.
  953832eb1 ovn-northd: Don't trigger recompute for transactions that are in progress.
  0df68408a inc-proc-northd: Don't reset I-P engine force recompute.
  b6a750112 manpages.mk: fix dependencies path
  69c50054d tests: Really fix requested-chassis localport test
  7dc58fe4e northd: allow having VXLAN encaps in ovn-ic enabled setup
  acffcc0dd nb: Add support for gateway_mtu_bypass.
  48d8b0704 tests: fix flaky VXLAN check port/datapath key space limits test
  602896502 controller I-P: Add missing FDB flows when a datapath is added locally.
  709909563 ovn-nb: Document LRP gateway_mtu option
  993d7113a northd: I-P: fix BFD dependency.
  a035cbf0b redhat: Properly package ovn-detrace.
```

**Comment by trozet** [comment]
needs rebase

**Comment by dcbw** [comment]
aws down due to outage
/retest

**Pull request merged**
