### PR TITLE
Bug 1930248: 4-7-21 merge

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
/assign @dcbw @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
gcp and okd are lease failures
dual-stack is `{"level":"info","msg":"level=error msg=StaticPodsDegraded: pod/etcd-master-2.ostest.test.metalkube.org container \"etcd\" is waiting: CrashLoopBackOff: back-off 5m0s restarting failed container=etcd pod=etcd-master-2.ostest.test.metalkube.org_openshift-etcd(69b529b1-67b6-488f-a312-75cf0b90528a)","time":"2021-04-07T16:54:23Z"}`

/retest

**Comment by trozet** [comment]
Gcp ovn passed which is good. But the sync mgmt commit might have a bug in it.

/hold

**Comment by abhat** [comment]
The dual stack metal job has been failing because of dual VIP issues. Need the baremetal team to fix that failing job.

**Comment by trozet** [comment]
deprecated in favor of https://github.com/openshift/ovn-kubernetes/pull/496

**Pull request closed without merging**
