### PR TITLE
[release-4.15] OCPBUGS-28725: Update netpol namespace address sets usage to the old ways

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of the first commit from https://github.com/ovn-org/ovn-kubernetes/pull/4086 (4 last ones are UT refactoring)
d/s merge https://github.com/openshift/ovn-kubernetes/pull/2038/commits
no conflicts

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/approve
/label backport-risk-assessed

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by dgoodwin** [comment]
We had a payload pol on some NetPol tests over the weekend, just noticed this PR and was wondering if you think this could have caused these failures on this job? https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade/1756168704820776960

The test is acting weird, it seems to only record a result very rarely, perhaps only when it fails. We'll dig into that but I'm curious about the fact this PR went in, and then these three tests failed on that job:

[sig-network] Netpol NetworkPolicy between server and client should allow ingress access from namespace on one named port [Feature:NetworkPolicy] [Skipped:Network/OVNKubernetes] [Skipped:Network/OpenShiftSDN/Multitenant] [Skipped:Network/OpenShiftSDN] [Suite:openshift/conformance/parallel] [Suite:k8s]

[sig-network] Netpol NetworkPolicy between server and client should allow egress access on one named port [Feature:NetworkPolicy] [Skipped:Network/OVNKubernetes] [Skipped:Network/OpenShiftSDN/Multitenant] [Skipped:Network/OpenShiftSDN] [Suite:openshift/conformance/parallel] [Suite:k8s]

[sig-network] Netpol NetworkPolicy between server and client should allow ingress access on one named port [Feature:NetworkPolicy] [Skipped:Network/OVNKubernetes] [Skipped:Network/OpenShiftSDN/Multitenant] [Skipped:Network/OpenShiftSDN] [Suite:openshift/conformance/parallel] [Suite:k8s]

**Comment by npinaeva** [comment]
These tests should be skipped for ovn-kubernetes based in `[Skipped:Network/OVNKubernetes]`, so I don't know why they were included at all.

**Pull request merged**
