### PR TITLE
OCPBUGS-35876: [release-4.12] ipv6+all protocols conntrack flush

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of https://github.com/openshift/ovn-kubernetes/pull/2200
OVN fix for 23.06 is here https://issues.redhat.com/browse/FDP-293, was bumped by https://github.com/openshift/ovn-kubernetes/commit/e3862d7782bda93f48511d43a117e1098b1f54bd 
e2es were run manually.

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/label backport-risk-assessed
/lgtm

**Comment by trozet** [comment]
/hold

looks like something is broken with the imports:

vendor/golang.org/x/sys/unix/syscall_unix.go:150:9: undefined: mapper
vendor/golang.org/x/sys/unix/syscall_unix.go:154:9: undefined: mapper
# github.com/google/go-cmp/cmp
vendor/github.com/google/go-cmp/cmp/path.go:349:15: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/path.go:3[51](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2214/pull-ci-openshift-ovn-kubernetes-release-4.12-unit/1806706495199383552#1:build-log.txt%3A51):15: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:22:28: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:34:35: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:36:98: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:[55](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2214/pull-ci-openshift-ovn-kubernetes-release-4.12-unit/1806706495199383552#1:build-log.txt%3A55):61: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:72:42: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:76:37: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:80:36: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:82:38: undefined: value.Pointer
vendor/github.com/google/go-cmp/cmp/report_references.go:82:38: too many errors

**Comment by npinaeva** [comment]
> /hold
> 
> looks like something is broken with the imports:

Somehow I managed to bump the library to the wrong version, fixed now (ndp v1.0.0)
/hold cancel

**Pull request merged**
