### PR TITLE
OCPBUGS-165:  [DownstreamMerge] 8-29-2022 merge

### PR DESCRIPTION
**Pull request by trozet**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jcaamano** [comment]
/lgtm

I don't know what's going on with the ovn upgrade job, different type of failures that I would not think are related with the changes on this PR.

**Comment by trozet** [comment]
the upgrade failure is due to an alert firing about openshift-config-operator being down:
```
  fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Sep  2 16:49:56.593: Unexpected alerts fired or pending after the test run:

alert TargetDown fired for 2615 seconds with labels: {job="metrics", namespace="openshift-config-operator", service="metrics", severity="warning"}
```

I can see in OVN at that time the correct service and pod are created. I doubt the commits in this PR have anything to do with this failure.

**Pull request merged**
