### PR TITLE
OCPBUGS-31853,OCPBUGS-31854: EIP multi NIC IPv6 support and default route with next hop

### PR DESCRIPTION
**Pull request by martinkennelly**
Conflict within `go.sum` when applying commit 0ff1336d44e6d92ac7047a6d4b24bd4f81eecbce

Also, conflict within e2e `egressip.go` file when applying 5b54d96896bac4e5a219896333a149c6270d8225

Minor conflicts.

### CODE REVIEW

**Comment by huiran0826** [comment]
@martinkennelly Let me know once it's ready for pre-merge testing.

**Comment by martinkennelly** [comment]
> @martinkennelly Let me know once it's ready for pre-merge testing.

Hi @huiran0826, you may begin.

**Comment by martinkennelly** [comment]
/test 4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade
Unrelated

**Comment by martinkennelly** [comment]
/test 4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade
Unrelated

**Comment by huiran0826** [comment]
The attached bugs were verified and regression was done, looks good
/label qe-approved

**Review by trozet — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by martinkennelly** [comment]
/lgtm

Missing by tim

**Pull request merged**
