### PR TITLE
[release-4.9] Bug 2105277: Fix panics in DestroyNetworkPolicy if policy is nil

### PR DESCRIPTION
**Pull request by tssurya**
NOTE to reviewers: Code changed considerably in these parts between 4.12 and all the way here. I have outlined conflicts in each commit but mainly, **this PR needs careful review** because I couldn't really port any unit tests since I ran into issues with the goovn test framework build.

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by tssurya** [comment]
we seem to be hitting https://bugzilla.redhat.com/show_bug.cgi?id=2106163 in the CI

**Pull request merged**
