### PR TITLE
Revert #796 and #807

### PR DESCRIPTION
**Pull request by stbenjam**
Since the sync with upstream has landed, ovn upgrades are failing and CI release payloads are being blocked. See https://bugzilla.redhat.com/show_bug.cgi?id=2018966

If there's no immediate fix, payload-impacting changes should be reverted and then any fix is built on "unreverting the revert".

See also: https://github.com/openshift/release/pull/23157 adds an upgrade presubmit to this repo.

### CODE REVIEW

**Comment by trozet** [comment]
/hold

the upstream -> downstream (merge) resync took a long time to do an was very complicated. Le'ts try to see if we can just fix whatever functionality is broken, rather than revert

**Comment by deads2k** [comment]
manually triggered jobs from @petr-muller 

1. https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/ovn809-e2e-aws-ovn-upgrade/1455165953120669696

**Comment by deads2k** [comment]
> /hold
> 
> the upstream -> downstream (merge) resync took a long time to do and was very complicated. Le'ts try to see if we can just fix whatever functionality is broken, rather than revert

This PR isn't attempting to make a fix any harder.  Since it's a clean revert, it is possible to build a fix based on this PR #809, an unrevert, and a fix.  Structuring the fix PR in this way makes it possible for the rest of the org and the downstream dependencies to deliver bugs and features while the problem is investigated, a fix reviews, and a fix delivered.

**Comment by dgoodwin** [comment]
/hold cancel

Looks like we've got some test failures to investigate or deal with though.

**Comment by deads2k** [comment]
vsphere-ovn appears to be failing on an environment set up concern that is systemic, but not related to this PR: https://coreos.slack.com/archives/C015H2WDJRY/p1635780126032400

one of the gcp ovns got unlucky with a build-01 upgrade and had a data collection pod get killed.  Also not related to this PR and this PR passed all the tests for it: https://coreos.slack.com/archives/CBN38N3MW/p1635778525237500

The first aws-ovn (https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/809/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1455174115877982208) failed to install due to some cloud credential creation failure.  But @dgoodwin told me not to worry.

**Comment by dgoodwin** [comment]
The 1 of 6 credentials request failures looks like a legit problem originating from https://github.com/openshift/external-dns-operator/pull/45, more details tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2019001

**Comment by dgoodwin** [comment]
/retest

https://github.com/openshift/external-dns-operator/pull/49 has reverted the cred request failing to sync change.

**Comment by dgoodwin** [comment]
Despite the revert, the last test run picked up an external-dns-operator commit that was still too old (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/809/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1455192228531015680/artifacts/release/artifacts/release-payload-latest/image-references), we are not sure how this is possible, Petr confirmed that ci job payloads should be using the latest bleeding edge code.

**Comment by dgoodwin** [comment]
Petr confirms there is some caching.

/retest

**Comment by dgoodwin** [comment]
/skip

@Miciah informs me this should allow us to get past the failures on optional jobs. vsphere and openstack are both optional: true in release repo.

Hopefully if we can clear the cred requests problem we can get this merged. Cred request issue still blocked by the fact that for some reason, the retests keep picking up a few commits prior to the latest in external-dns repo. Another pr has merged to take external-dns out of the release repo entirely as it wasn't supposed to be there. If either can get picked up we should be close.

**Comment by deads2k** [comment]
seeing if we can get a new base in https://github.com/openshift/ovn-kubernetes/pull/810

**Pull request merged**
