### PR TITLE
Bug 2041830: Fix panic in Hybrid Overlay

### PR DESCRIPTION
**Pull request by tssurya**
https://github.com/ovn-org/ovn-kubernetes/commit/1b94cbb795af5817c7258109642d185bb3c3f07d

Managed to break Hybrid overlay specifically with the creation of the
MAC binding for the HO logical Port since we never actually passed
a valid sbClient to the ho Controller.

Also the unit tests were broken in the sense that we didn't have a test
that ensured we actually created all the needed OVN objects from
scratch, these objects are

The HO Logical Switch Port
The HO Logiacal Router Policy
The HO Mac binding

this commit fixes the above problems and more related to HO
found while fixing the tests

Signed-off-by: astoycos <astoycos@redhat.com>
(cherry picked from commit 51f3d5f669595a8a9efd2e2292faefe359e84543)

Conflict in `MasterController struct` since we are missing
https://github.com/ovn-org/ovn-kubernetes/commit/b77e0e3027d905089daa50bcd2731e9b4498079e#diff-9811e6f2e1ecf87a3a4c6c1b6b8e9c0df5d921c8591985a1c09e93e95e9dae52
downstream

Conflicts:
	go-controller/hybrid-overlay/pkg/controller/master.go

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
Fixes the `e2e-aws-windows` job. It panics badly rn:
```
2022-01-15T19:05:10.887274695Z E0115 19:05:10.887239       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2022-01-15T19:05:10.887274695Z goroutine 856 [running]:
2022-01-15T19:05:10.887274695Z k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bd5fc0, 0x2e22800)
2022-01-15T19:05:10.887274695Z 	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
2022-01-15T19:05:10.887274695Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2022-01-15T19:05:10.887274695Z 	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
2022-01-15T19:05:10.887274695Z panic(0x1bd5fc0, 0x2e22800)
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
this job is not currently expected to work due to version skew between kube-apiserver and the e2e tests
https://bugzilla.redhat.com/show_bug.cgi?id=2040671

**Pull request merged**
