### PR TITLE
[DownstreamMerge] Revert revert

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@jluhrsen @dcbw FYI

**Comment by trozet** [comment]
may have to wait for mirrors to update with tagged version of OVN

**Comment by deads2k** [comment]
An aggregated view of the jobs launched this morning can be found: https://drive.google.com/drive/folders/1-m0VMNw3sB102LjGrq79S3YTIhwtgPU0

The aggregated azure job appears to have 57 failures that are significantly more common in this PR than they are in our historical data.

The aggregated gcp job appears to have 4 failures that more common in this PR than they are in our historical data.

**Comment by anuragthehatter** [comment]
@trozet Hit same annotation issue on this build http://pastebin.test.redhat.com/1009530

**Comment by trozet** [comment]
> @trozet Hit same annotation issue on this build http://pastebin.test.redhat.com/1009530

@anuragthehatter this PR doesn't include https://github.com/ovn-org/ovn-kubernetes/commit/ad53d2464ae67312c47871d3b4e86019138e8087 yet

**Comment by trozet** [comment]
/hold cancel

I'm removing the hold as the latest upgrade jobs do not show any sign of deadlock or other malfunction. Most of the tests seem to pass OK in the latest round of results. I'll defer to @deads2k to see if he wants to run another round of promotion CI before we merge and aggregate the results to ensure we dont regress on merging this.

/assign @deads2k

**Comment by deads2k** [comment]
/hold

It's hard to pick out manually, but there are still azure failures.  See https://drive.google.com/drive/folders/1U_-Un71aSbzIZ0ZHPeH2lpTR-3qatrUB

Failed: suite=[openshift-tests], [sig-network][Feature:Whereabouts] should use whereabouts net-attach-def to limit IP ranges for newly created pods [Suite:openshift/conformance/parallel]
Failed: Passed 3 times, failed 2 times. The historical pass rate is 100%. The required number of passes is 4.
1.  Failure - periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade/1461661180421476352
2.  Failure - periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade/1461661220779069440

The other azure failures are not related to this PR and were reverted early this morning.

**Comment by trozet** [comment]
> /hold
> 
> It's hard to pick out manually, but there are still azure failures. See https://drive.google.com/drive/folders/1U_-Un71aSbzIZ0ZHPeH2lpTR-3qatrUB
> 
> Failed: suite=[openshift-tests], [sig-network][Feature:Whereabouts] should use whereabouts net-attach-def to limit IP ranges for newly created pods [Suite:openshift/conformance/parallel] Failed: Passed 3 times, failed 2 times. The historical pass rate is 100%. The required number of passes is 4.
> 
> 1. Failure - periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade/1461661180421476352 - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/ovn-kubernetes-834-ci-4.10-e2e-azure-ovn-upgrade/1461661180421476352
> 2. Failure - periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade/1461661220779069440 - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/ovn-kubernetes-834-ci-4.10-e2e-azure-ovn-upgrade/1461661220779069440
> 
> The other azure failures are not related to this PR and were reverted early this morning.
> 
> The gcp run looks clean for ovn, only failed on another issue that I'm reverting tonight (in queue: [openshift/cluster-kube-controller-manager-operator#574](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/574)).
> 
> I suggest re-running azure on Monday when dptp is back awake for a larger sample-size and if it's good we can remove hold.

Those 2 azure runs were without the deadlock fix. Let's see how a fresh round performs on Monday.

**Comment by deads2k** [comment]
1. GCP is clean.
2. Azure is clean.
3. AWS is clean

/hold cancel

**Comment by deads2k** [comment]
also, that's the greenest CI we've seen in a bit on this! :)

**Pull request merged**
