### PR TITLE
Bug 1998423: kube master don't fail trying to cache same GW LRP IPs as already exist

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
/cc

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
All CI runs show no sign of the symptoms caused by https://bugzilla.redhat.com/show_bug.cgi?id=1998423. Every job seems to be failing because of specific test flakes or prevalent problems with that job  (e2e-metal-ipi-ovn-dualstack)

I will continue to 

/retest 

this, but I think we have a good CI signal indicating a successful fix for the problem.

**Comment by alexanderConstantinescu** [comment]
This doesn't seem to work, I still need more time to investigate this:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/705/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1432996500048187392/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-8ckg9_ovnkube-master.log

**Comment by alexanderConstantinescu** [comment]
/retitle Bug 1998423: kube master don't fail trying to cache same GW LRP IPs as already exist 
/auto-cc
/assign @dcbw @abhat

**Comment by alexanderConstantinescu** [comment]
`e2e-metal-ipi-ovn-dualstack` is perma-failing. Can be overriden
`e2e-gcp-ovn` flaked
`e2e-metal-ipi-ovn-ipv6` is 80 % red, it didn't fail because of this though

**Comment by abhat** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
job perma-fails because of: https://bugzilla.redhat.com/show_bug.cgi?id=2000086

**Comment by alexanderConstantinescu** [comment]
I think we can override `e2e-gcp-ovn` it's constantly failing on `crictl should be able to run crictl on the node ` which will be fixed by https://bugzilla.redhat.com/show_bug.cgi?id=2000589

**Comment by abhat** [comment]
/override ci/prow/e2e-gcp-ovn
Fails because of: https://bugzilla.redhat.com/show_bug.cgi?id=2000589

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn 
`crictl should be able to run crictl on the node` failing in many jobs/PRs... fix is in https://github.com/openshift/origin/pull/26444

**Comment by abhat** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
job perma-fails because of: https://bugzilla.redhat.com/show_bug.cgi?id=2000086

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn
```
[sig-auth][Feature:SCC][Early] should not have pod creation failures during install
fail [github.com/openshift/origin/test/extended/authorization/scc.go:73]: 4 pods failed before test on SCC errors
Error creating: pods "console-operator-bcff8569b-" is forbidden: unable to validate against any security context constraint: [provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount] for ReplicaSet.apps/v1/console-operator-bcff8569b -n openshift-console-operator happened 15 times
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn
```
: [sig-cli] oc builds new-build
Sep  4 10:41:05.014: INFO: Running 'oc --namespace=e2e-test-oc-builds-t8xw6 --kubeconfig=/tmp/kubeconfig-3445657011 get bc/stdintest --template {{with .spec.output.to}}{{.kind}} {{.name}}{{end}}'
Sep  4 10:41:05.404: INFO: Running 'oc --namespace=e2e-test-oc-builds-t8xw6 --kubeconfig=/tmp/kubeconfig-3445657011 delete all --all'
Sep  4 10:41:06.374: INFO: Error running /usr/bin/oc --namespace=e2e-test-oc-builds-t8xw6 --kubeconfig=/tmp/kubeconfig-3445657011 delete all --all:
StdOut>
error: the server doesn't have a resource type "noxus"
StdErr>
error: the server doesn't have a resource type "noxus"

error: the server doesn't have a resource type "noxus"
```

```
 CustomResourceDefinition Watch [Privileged:ClusterAdmin] CustomResourceDefinition Watch watch on custom resource definition objects
STEP: Destroying namespace "e2e-crd-watch-9640" for this suite.
fail [k8s.io/kubernetes@v1.22.0-rc.0/test/e2e/apimachinery/crd_watch.go:106]: failed to patch custom resource: name1
Unexpected error:
    <*errors.StatusError | 0xc000554640>: {
        ErrStatus: {
            TypeMeta: {Kind: "Status", APIVersion: "v1"},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "noxus.mygroup.example.com \"name1\" not found",
            Reason: "NotFound",
            Details: {
                Name: "name1",
                Group: "mygroup.example.com",
                Kind: "noxus",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    noxus.mygroup.example.com "name1" not found
```

**Pull request merged**
