### PR TITLE
Downstream Merge 2023-08-03

### PR DESCRIPTION
**Pull request by jcaamano**
PTAL @MarSik @ricky-rav @oshoval  @kyrtapz @trozet

### CODE REVIEW

**Comment by trozet** [comment]
@jluhrsen looks like this script is timing out

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1798/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-local-to-shared-gateway-mode-migration/1687283364953853952/artifacts/e2e-aws-ovn-local-to-shared-gateway-mode-migration/ovn-local-to-shared-gateway-mode-migration/build-log.txt

maybe we need to increase the timeout there?

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration

rollout timed out but master pods did become ready. Timeout needs bump I think.

```
+ timeout 360s oc rollout status ds/ovnkube-master -n openshift-ovn-kubernetes
Waiting for daemon set "ovnkube-master" rollout to finish: 1 out of 3 new pods have been updated...
Waiting for daemon set "ovnkube-master" rollout to finish: 1 out of 3 new pods have been updated...
Waiting for daemon set "ovnkube-master" rollout to finish: 1 out of 3 new pods have been updated...
Waiting for daemon set "ovnkube-master" rollout to finish: 1 out of 3 new pods have been updated...
Waiting for daemon set "ovnkube-master" rollout to finish: 2 out of 3 new pods have been updated...
Waiting for daemon set "ovnkube-master" rollout to finish: 2 out of 3 new pods have been updated...
{"component":"entrypoint","error":"wrapped process failed: exit status 124","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-08-07T08:10:26Z"}
error: failed to execute wrapped command: exit status 124
```

**Pull request merged**
