### PR TITLE
Dockerfile: bump to ovn22.09-22.09.0-5.el8fdp

### PR DESCRIPTION
**Pull request by dcbw**
Includes significant performance fixes for load-balancers, northd, and data plane latency. The following links to the specific patches document their performance gains:

https://mail.openvswitch.org/pipermail/ovs-dev/2022-September/397541.html
http://patchwork.ozlabs.org/project/ovn/patch/20220908154620.681323-1-i.maximets@ovn.org/
http://patchwork.ozlabs.org/project/ovn/patch/20220913113329.7576-1-i.maximets@ovn.org/
http://patchwork.ozlabs.org/project/ovn/patch/20220824064051.2525214-1-hzhou@ovn.org/

### CODE REVIEW

**Comment by dcbw** [comment]
(Have to give the poor mirrors time to sync the new build...)

**Comment by dcbw** [comment]
RPMs now available and image builds.

/retest

**Comment by dcbw** [comment]
Windows jobs failing because of kube-1.25 merge without kubelet 1.25 (should be fixed by https://coreos.slack.com/archives/CM4ERHBJS/p1664551950438109)

OKD jobs failing because new RPMs only get promoted to OKD when there's an accepted build, which there hasn't yet been. See https://coreos.slack.com/archives/CLKF3H5RS/p1664553586427369?thread_ts=1664550360.604629&cid=CLKF3H5RS

**Comment by abhat** [comment]
/hold
@dcbw are there scale results we can point to?

**Comment by dcbw** [comment]
> are there scale results we can point to?

Updated the PR description with the scale results done in ovn-heater; but we don't have internal results at this time.

**Comment by trozet** [comment]
looks like e2e-hypershift was renamed to e2e-aws-ovn-hypershift and tide is just confused:
https://github.com/openshift/release/pull/32730/files

e2e-aws-ovn-hypershift looks like it passed, just the job timed out while trying executing a step that dumps info:

```
INFO[2022-10-05T21:52:52Z] Step e2e-aws-ovn-hypershift-conformance-tests succeeded after 54m50s. 
INFO[2022-10-05T21:52:52Z] Step phase test succeeded after 54m50s.      
INFO[2022-10-05T21:52:52Z] Running multi-stage phase post               
INFO[2022-10-05T21:52:52Z] Running step e2e-aws-ovn-hypershift-dump.    
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2022-10-05T21:53:13Z"}
INFO[2022-10-05T21:53:13Z] Received signal.                              signal=interrupt
INFO[2022-10-05T21:53:16Z] error: Process interrupted with signal interrupt, cancelling execution..
```
@jluhrsen fyi 

I'm good with overriding this to merge.

**Comment by trozet** [comment]
Looks like the build src operation is what took so long:
```
[36mINFO[0m[2022-10-05T17:53:23Z] Tagging ocp/4.12:hypershift-operator into pipeline:ocp-4.12-hypershift-operator. 
[36mINFO[0m[2022-10-05T17:53:24Z] Building src                                 
[36mINFO[0m[2022-10-05T20:14:57Z] Build src succeeded after 2h21m34s    
```

**Comment by dcbw** [comment]
Also, everything CI is broken right now... https://coreos.slack.com/archives/CEKNRGF25/p1665026049145599

**Comment by vrutkovs** [comment]
CI should be back now
/retest

**Comment by dcbw** [comment]
Still fallout from the Akamai outage; clusters can't even bootstrap.
/retest

**Comment by dcbw** [comment]
All CI is currently broken by https://github.com/openshift/cluster-version-operator/pull/844

**Comment by dcbw** [comment]
https://github.com/openshift/cluster-version-operator/pull/844 reverted; bootstrap should be good now

**Comment by dcbw** [comment]
/retest
Still having the image pull issues from Akamai for jobs that started a couple hours ago.

**Comment by dcbw** [comment]
/retest

AWS infra issues: `msg=Error: error reading Main Route Table Association (rtbassoc-0a14fd2b1739aa6f9): empty result`

**Comment by dcbw** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade

```
journal:Oct 09 07:00:48.998231 ip-10-0-209-142 kubenswrapper[2518]: E1009 07:00:48.998128    2518 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-runtimeclass-e2e-runtimeclass-5136-preconfigured-hand697b6.171c547ae2ffe8f2", GenerateName:"", Namespace:"e2e-runtimeclass-5136", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"e2e-runtimeclass-5136", Name:"test-runtimeclass-e2e-runtimeclass-5136-preconfigured-hand697b6", UID:"244cef6c-e525-46d3-8b49-55a10d9dc404", APIVersion:"v1", ResourceVersion:"87348", FieldPath:""}, Reason:"FailedCreatePodSandBox", Message:"Failed to create pod sandbox: runtimeclass.node.k8s.io \"e2e-runtimeclass-5136-preconfigured-handler\" not found", Source:v1.EventSource{Component:"kubelet", Host:"ip-10-0-209-142.us-east-2.compute.internal"}, FirstTimestamp:time.Date(2022, time.October, 9, 7, 0, 48, 991406322, time.Local), LastTimestamp:time.Date(2022, time.October, 9, 7, 0, 48, 991406322, time.Local), Count:1, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "test-runtimeclass-e2e-runtimeclass-5136-preconfigured-hand697b6.171c547ae2ffe8f2" is forbidden: unable to create new content in namespace e2e-runtimeclass-5136 because it is being terminated' (will not retry!)
```

is not a network error.

**Pull request merged**
