### PR TITLE
[release-4.12] OCPBUGS-26243: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

### PR DESCRIPTION
**Pull request by flavio-fernandes**
This is a clean cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2011

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/retitle [release-4.12] OCPBUGS-26243: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
