### PR TITLE
Bug 1934643: Downstream merge 3-10-21

### PR DESCRIPTION
**Pull request by trozet**
Includes fixes for BFD on external gateways

### CODE REVIEW

**Comment by trozet** [comment]
@fedepaol FYI

**Comment by dcbw** [comment]
All the recent failures are "waiting for image pull secrets"... FWIW. not OVN related AFAICT.

**Comment by trozet** [comment]
@vrutkovs @abhat pointed out it looks like okd-gcp-ovn is not working because of some selinux issues while trying to create OVS dirs

**Comment by abhat** [comment]
@vrutkovs this is the issue we are seeing:
```Mar 12 16:40:25.979575 localhost ovs-ctl[735]: Creating empty database /etc/openvswitch/conf.db.
Mar 12 16:40:25.986000 localhost audit[784]: AVC avc:  denied  { fsetid } for  pid=784 comm="install" capability=4  scontext=system_u:system_r:openvswitch_t:s0 tcontext=system_u:system_r:openvswitch_t:s0 tclass=capability permissive=0
Mar 12 16:40:25.996000 localhost audit[786]: AVC avc:  denied  { fsetid } for  pid=786 comm="install" capability=4  scontext=system_u:system_r:openvswitch_t:s0 tcontext=system_u:system_r:openvswitch_t:s0 tclass=capability permissive=0
Mar 12 16:40:25.996000 localhost audit[786]: AVC avc:  denied  { fsetid } for  pid=786 comm="install" capability=4  scontext=system_u:system_r:openvswitch_t:s0 tcontext=system_u:system_r:openvswitch_t:s0 tclass=capability permissive=0
Mar 12 16:40:26.021000 localhost audit[788]: AVC avc:  denied  { write } for  pid=788 comm="ovsdb-server" name="/" dev="tmpfs" ino=1 scontext=system_u:system_r:openvswitch_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
Mar 12 16:40:26.021000 localhost audit[788]: AVC avc:  denied  { write } for  pid=788 comm="ovsdb-server" name="/" dev="tmpfs" ino=1 scontext=system_u:system_r:openvswitch_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=dir permissive=0
Mar 12 16:40:26.022879 localhost ovs-ctl[788]: ovsdb-server: failed to create temporary file (Permission denied)
Mar 12 16:40:26.023727 localhost ovs-ctl[735]: Starting ovsdb-server ... failed!
Mar 12 16:40:26.024442 localhost systemd[1]: ovsdb-server.service: Control process exited, code=exited, status=1/FAILURE
Mar 12 16:40:26.024581 localhost systemd[1]: ovsdb-server.service: Failed with result 'exit-code'.
Mar 12 16:40:26.025430 localhost systemd[1]: Failed to start Open vSwitch Database Unit.
Mar 12 16:40:26.042461 localhost systemd[1]: Dependency failed for Open vSwitch.
Mar 12 16:40:26.044498 localhost systemd-logind[783]: Watching system buttons on /dev/input/event0 (Power Button)
Mar 12 16:40:26.044636 localhost systemd-logind[783]: Watching system buttons on /dev/input/event1 (Sleep Button)
Mar 12 16:40:26.044780 localhost systemd-logind[783]: Watching system buttons on /dev/input/event2 (AT Translated Set 2 keyboard)
Mar 12 16:40:26.045567 localhost systemd-logind[783]: New seat seat0.
Mar 12 16:40:26.051354 localhost systemd[1]: Dependency failed for Configures OVS with proper host networking configuration.
Mar 12 16:40:26.063312 localhost systemd[1]: ovs-configuration.service: Job ovs-configuration.service/start failed with result 'dependency'.
Mar 12 16:40:26.063342 localhost systemd[1]: openvswitch.service: Job openvswitch.service/start failed with result 'dependency'.
Mar 12 16:40:26.063357 localhost systemd[1]: Dependency failed for Open vSwitch Forwarding Unit.
Mar 12 16:40:26.073325 localhost systemd[1]: ovs-vswitchd.service: Job ovs-vswitchd.service/start failed with result 'dependency'.
Mar 12 16:40:26.072000 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=ovsdb-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mar 12 16:40:26.075554 localhost systemd[1]: Started User Login Management.
Mar 12 16:40:26.083000 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-logind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 12 16:40:26.086412 localhost systemd[1]: Starting Network Manager...
Mar 12 16:40:26.093492 localhost systemd[1]: ovs-delete-transient-ports.service: Starting requested but asserts failed.
Mar 12 16:40:26.093514 localhost systemd[1]: Assertion failed for Open vSwitch Delete Transient Ports.
```
 I am not convinced that this is a problem the PR introduces. I am going to lgtm this particular PR.

**Pull request merged**
