### PR TITLE
OCPBUGS-14549: Forward ICMP Fragmentation needed packets in Shared GW mode

### PR DESCRIPTION
**Pull request by pperiyasamy**
Clean cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/3762.
/assign @trozet @tssurya

### CODE REVIEW

**Comment by tssurya** [comment]
/hold
in favour of https://github.com/openshift/ovn-kubernetes/pull/1854
that is high prio escalation

**Comment by tssurya** [comment]
wait these are not critical bugs why are we cherry-picking them? the more we cherry-pick the more chance of conflicts, why don't we wait for d/s merge?

**Comment by pperiyasamy** [comment]
closing it in favor of https://github.com/openshift/ovn-kubernetes/pull/1868.

**Pull request closed without merging**
