### PR TITLE
OCPBUGS-36382: Handle IP fragments in SGW mode

### PR DESCRIPTION
**Pull request by jcaamano**
Backport of 9051f15
Also cherry-picked related (but non feature) commits for reduced conflict resolution:  8bb2db423 0ae0b0ea9

Conflicts (trivial):
* go-controller/pkg/node/gateway_shared_intf.go
* go-controller/pkg/util/kube.go
* test/e2e/util.go

### CODE REVIEW

**Review by tssurya — APPROVED** [review]
/lgtm
/label backport-risk-assessed

thanks for the awesome commit messages and also outlining conflicts, they aligned. change lgtm (can't think of any backport risks here)

curiosity question: in ocp what's the default value of `net.ipv4.ip_no_pmtu_disc` ?

**Comment by jcaamano** [comment]
> curiosity question: in ocp what's the default value of `net.ipv4.ip_no_pmtu_disc` ?

0, so PMTUD enabled

**Pull request merged**
