### PR TITLE
[wip] ovn2.13-20.06.1-4 soak test for rhbz1860053

### PR DESCRIPTION
**Pull request by dcbw**
https://bugzilla.redhat.com/show_bug.cgi?id=1860053

FDP ovn2.13-20.06.1-4 plus http://patchwork.ozlabs.org/project/openvswitch/patch/20200724193845.1956595-1-numans@ovn.org/

@numansiddique @trozet

### CODE REVIEW

**Comment by dcbw** [comment]
aws seems like a flake: `deploymentconfigs with test deployments should run a deployment to completion and then scale to zero`

/retest

**Comment by dcbw** [comment]
Hmm, metal-ipi fails with ovnkube-master saying:
`F0724 22:40:20.204764       1 ovnkube.go:130] error when trying to initialize go-ovn NB client: couldn't initialize NBDB client: error creating SSL OVNDBClient for database OVN_Northbound at address ssl:[fd2e:6f44:5dd8:c956::14]:9641,ssl:[fd2e:6f44:5dd8:c956::15]:9641,ssl:[fd2e:6f44:5dd8:c956::16]:9641: failed to connect: dial tcp: address [fd2e:6f44: missing ']' in address`

**Comment by numansiddique** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1860053
> 
> FDP ovn2.13-20.06.1-4 plus http://patchwork.ozlabs.org/project/openvswitch/patch/20200724193845.1956595-1-numans@ovn.org/
> 
> @numansiddique @trozet

Unfortunately the patch - http://patchwork.ozlabs.org/project/openvswitch/patch/20200724193845.1956595-1-numans@ovn.org/ is buggy. I submitted the patch without checking in some code.

The v2 of the patch is here - http://patchwork.ozlabs.org/project/openvswitch/patch/20200724210252.1976634-1-numans@ovn.org/

**Comment by numansiddique** [comment]
> > https://bugzilla.redhat.com/show_bug.cgi?id=1860053
> > FDP ovn2.13-20.06.1-4 plus http://patchwork.ozlabs.org/project/openvswitch/patch/20200724193845.1956595-1-numans@ovn.org/
> > @numansiddique @trozet
> 
> Unfortunately the patch - http://patchwork.ozlabs.org/project/openvswitch/patch/20200724193845.1956595-1-numans@ovn.org/ is buggy. I submitted the patch without checking in some code.
> 
> The v2 of the patch is here - http://patchwork.ozlabs.org/project/openvswitch/patch/20200724210252.1976634-1-numans@ovn.org/

Submitted the PR with the proper OVN builds here - https://github.com/openshift/ovn-kubernetes/pull/213

**Pull request closed without merging**
