### PR TITLE
OCPBUGS-11511: [release-4.13] static pod creation

### PR DESCRIPTION
**Pull request by bpickard22**
Clean backport of https://github.com/ovn-org/ovn-kubernetes/pull/3347

### CODE REVIEW

**Comment by jcaamano** [comment]
@bpickard22 was the last commit required? Would it make lint fail? How was that not already happening? Out of curiosity.

**Comment by bpickard22** [comment]
> @bpickard22 was the last commit required? Would it make lint fail? How was that not already happening? Out of curiosity.

yes the last commit is required to satisfy the lint. I think there was some mixup with the timing of merges and this commit went in after the 1.26 bump https://github.com/openshift/ovn-kubernetes/blob/8513b38e5a74c0c5f303dca30a27e6cc24bdf89c/go-controller/pkg/ovn/policy.go

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
