### PR TITLE
Bug 1978797: Sync exgw routes on startup

### PR DESCRIPTION
**Pull request by trozet**
Includes a fix for the previous clean up, which was accidentally always
removing ECMP routes at start up, and not removing legacy routes (that
did not specify output port).

Signed-off-by: Tim Rozet <trozet@redhat.com>
Co-authored-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>

### CODE REVIEW

**Comment by tssurya** [comment]
LGTM. I'll wait for the tests (gcp-ovn and aws-ovn) to pass to approve.

**Comment by trozet** [comment]
e2e failures in gcp ovn have nothing to do with this patch. This patch only affects start up of ovnkube-master:

```


[sig-arch] events should not repeat pathologically expand_less | 0s
-- | --
2 events happened too frequently  event happened 25 times, something is wrong: ns/e2e-test-cli-deployment-cr7h9 pod/hook-1-hook-pre node/ci-op-1zl66x6h-99b10-2z5qq-worker-b-6rttf - reason/BackOff Back-off restarting failed container event happened 23 times, something is wrong: ns/e2e-statefulset-3240 pod/test-pod node/ci-op-1zl66x6h-99b10-2z5qq-worker-c-wrb46 - reason/BackOff Back-off restarting failed container


```

**Pull request merged**
