### PR TITLE
[release-4.11] OCPBUGS-2745: Fixes SNAT-ing Logic for EgressIPs

### PR DESCRIPTION
**Pull request by tssurya**
Backport of https://github.com/openshift/ovn-kubernetes/pull/1331 and https://github.com/openshift/ovn-kubernetes/pull/1333
Conflicts for each commit outlined in commit message.

Note that I brought in some of miguel's test refactor commits because its going to make backporting life easier for everyone specially since we have started running unit tests downstream

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by tssurya** [comment]
https://github.com/openshift/ovn-kubernetes/pull/1325 merged... so we are going to have to retest everything..

**Comment by trozet** [comment]
https://github.com/openshift/ovn-kubernetes/pull/1325/files was a 1 line change, there is no point in waiting for all retests to be done and all the jobs passed previously

/override ci/prow/e2e-aws-ovn
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration
/override ci/prow/4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration 
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway
/override ci/prow/e2e-gcp-ovn 
/override ci/prow/e2e-metal-ipi-ovn-dualstack
/override ci/prow/e2e-metal-ipi-ovn-ipv6

**Comment by trozet** [comment]
help

**Pull request merged**
