### PR TITLE
SDN-4930: Bump OVN to ovn24.09-24.09.0-beta.31.el9fdp

### PR DESCRIPTION
**Pull request by trozet**
Upstream bump and test: https://github.com/ovn-org/ovn-kubernetes/pull/4712

### CODE REVIEW

**Comment by trozet** [comment]
/override ci/prow/4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade
/override ci/prow/4.16-upgrade-from-stable-4.15-local-gateway-images

**Comment by tssurya** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-azure-ovn-upgrade

**Comment by trozet** [comment]
/override ci/prow/4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade

**Comment by trozet** [comment]
/override ci/prow/4.16-upgrade-from-stable-4.15-local-gateway-images

**Comment by asood-rh** [comment]
/label qe-approved

The pre merge test results look good, no failures.

**Pull request merged**
