### PR TITLE
[release-4.15] OCPBUGS-25486: Fix Egress IP Deletion Handler to Prevent OVN Policy Leaks

### PR DESCRIPTION
**Pull request by flavio-fernandes**
Clean cherry pick from commit db4aaf417af4df9ffa587482d5b2e4b86e53418b (via https://github.com/openshift/ovn-kubernetes/pull/1990)

Resolved an issue where the Egress IP deletion handler misidentified affected pods, leading to unintended leaks of OVN logical router policies and SNATs. This occurred in scenarios with matchExpressions that only excluded keys and values.

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/label backport-risk-assessed
/approve

**Review by tssurya — APPROVED** [review]
/lgtm

**Pull request merged**
