### PR TITLE
wip: test ovn2.13-20.12.0-5.el8fdn

### PR DESCRIPTION
**Pull request by dcbw**
Soak test

### CODE REVIEW

**Comment by aojea** [comment]
@dcbw is this going to be available for 4.7?

**Comment by dcbw** [comment]
> @dcbw is this going to be available for 4.7?

I'd like it to be, as long as it passes tests. It's got a number of the perf/scale fixes that we want, plus the BFD implementation.

**Comment by dcbw** [comment]
dualstack-ipi:
` fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: Packet setup failed."} `

**Comment by dcbw** [comment]
vsphere:
```
 level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: Post "https://vcenter.sddc-44-236-21-251.vmwarevmc.com/rest/com/vmware/cis/session": dial tcp 44.236.21.251:443: connect: connection timed out
level=error
level=error msg=  on ../tmp/openshift-install-078560108/main.tf line 5, in provider "vsphere":
level=error msg=   5: provider "vsphere" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
error: failed to execute wrapped command: exit status 1 
```

**Comment by aojea** [comment]
> > @dcbw is this going to be available for 4.7?
> 
> I'd like it to be, as long as it passes tests. It's got a number of the perf/scale fixes that we want, plus the BFD implementation.

and we don't have to use ACLs for the loadbalancers without endpoints ;)
https://github.com/openshift/ovn-kubernetes/pull/392#issuecomment-761596725

**Comment by dcbw** [comment]
vsphere and hybrid-step-registry appear to be flakes
openstack is `Error from server (NotFound): imagestreamtags.image.openshift.io "local-busybox:latest" not found`

/retest

**Comment by dcbw** [comment]
aws failure with only flakes...

```
Flaky invariants:

[sig-arch] Monitor cluster while tests execute
[sig-network] pods should successfully create sandboxes by reading container

Flaky tests:

[sig-builds][Feature:Builds] build can reference a cluster service  with a build being created from new-build should be able to run a build that references a cluster service [Suite:openshift/conformance/parallel]
```

/test all

**Comment by dcbw** [comment]
gcp ignition/setup issues
/retest

**Pull request closed without merging**
