### PR TITLE
Bug 2047299, OCPBUGS-2337: [DownstreamMerge] 13 Jan 2023

### PR DESCRIPTION
**Pull request by kyrtapz**
Revert the previous merge https://github.com/openshift/ovn-kubernetes/commit/c76929fe8d9f59aa4456a97703b802ef1a5c5bf3 since it was done wrong :disappointed: 

Merge current upstream:

Conflicts:
go-controller/pkg/ovn/base_network_controller_pods.go
go-controller/pkg/ovn/pods.go

Moved addLogicalPortToNetwork back to BaseNetworkController since BaseSecondaryNetworkController uses it.
HACK: Downstream addLogicalPortToNetwork needs to call addPodToNamespace(DefaultNetworkController), to fix that provide a DefaultNetworkController pointer as an argument.

### CODE REVIEW

**Comment by trozet** [comment]
Need to investigate egress firewall failures and npe in the test

**Comment by npinaeva** [comment]
/retitle Bug 2047299, OCPBUGS-2337: [DownstreamMerge] 13 Jan 2023

**Comment by npinaeva** [comment]
looks like egress firewall is permafailing for some time now https://issues.redhat.com/browse/OCPBUGS-4425

**Comment by trozet** [comment]
egress firewall failure is not due to this PR and being tracked at: https://issues.redhat.com/browse/OCPBUGS-4425

DNS null pointer exception is due to a regression with: https://github.com/openshift/origin/pull/27650

**Comment by lmilleri** [comment]
I think https://github.com/openshift/ovn-kubernetes/pull/1474/commits/88e61e97e11d80714c9f690f94cf68fb12db729b is introducing a regression. I am no longer able to create pods because of the following error:
```
Warning  FailedCreatePodSandBox  0s  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_debug-network-4_vdpa_a22a5fde-d890-4520-b4ad-05420b0b3e82_0(df7762cbe5e46e99beacf99e1e470671f9b9b488619af2ab2b187d313829ea16): error adding pod vdpa_debug-network-4 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): [vdpa/debug-network-4/a22a5fde-d890-4520-b4ad-05420b0b3e82:ovn-kubernetes-a]: error adding container to network "ovn-kubernetes-a": CNI request failed with status 400: '[vdpa/debug-network-4 df7762cbe5e46e99beacf99e1e470671f9b9b488619af2ab2b187d313829ea16] [vdpa/debug-network-4 df7762cbe5e46e99beacf99e1e470671f9b9b488619af2ab2b187d313829ea16] failed to configure pod interface: failure in plugging pod interface: failed to run 'ovs-vsctl --timeout=30 add-port br-int df7762cbe5e46e9 other_config:transient=true -- set interface df7762cbe5e46e9 external_ids:attached_mac=0a:58:0a:87:00:2a external_ids:iface-id=vdpa_debug-network-4 external_ids:iface-id-ver=a22a5fde-d890-4520-b4ad-05420b0b3e82 external_ids:ip_addresses=10.135.0.42/23 external_ids:sandbox=df7762cbe5e46e99beacf99e1e470671f9b9b488619af2ab2b187d313829ea16 -- --if-exists remove interface df7762cbe5e46e9 external_ids k8s.ovn.org/network -- --if-exists remove interface df7762cbe5e46e9 external_ids k8s.ovn.org/nad external_ids:vf-netdev-name=ens1f0v1': exit status 1
  "ovs-vsctl: external_ids:vf-netdev-name=ens1f0v1: unexpected \":\" parsing set of 1 or more strings\n"

```
@zshi-redhat is suggesting:
"move https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/cni/helper_linux.go#L399-L401 to line 390"
I tested and it works for me

**Pull request merged**
