### PR TITLE
Downstream merge 2022-03-22

### PR DESCRIPTION
**Pull request by squeed**
Pick up https://github.com/ovn-org/ovn-kubernetes/pull/2837

### CODE REVIEW

**Comment by tssurya** [comment]
```
I0322 19:21:57.209870       1 topology_version.go:118] No version string found. The OVN topology is before versioning is introduced. Upgrade needed
I0322 19:21:57.210111       1 transact.go:41] Configuring OVN: [{Op:update Table:Logical_Router Row:map[external_ids:{GoMap:map[k8s-cluster-router:yes k8s-ovn-topo-version:5]}] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column _uuid == {4a2aed25-1fcb-481e-8713-aaba6e40fa08}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
I0322 19:21:57.212879       1 topology_version.go:49] Updated Logical_Router ovn_cluster_router topology version to 5
E0322 19:21:57.215348       1 ovn.go:419] Failed to report topology version: configmaps "control-plane-status" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot patch resource "configmaps" in API group "" in the namespace "openshift-ovn-kubernetes"
panic: configmaps "control-plane-status" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-controller" cannot patch resource "configmaps" in API group "" in the namespace "openshift-ovn-kubernetes"

goroutine 118 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).Start.func1({0x1eb34b0, 0xc001aa7480})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/master.go:100 +0x154
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x154

```
masters are crashing on a scale run,

**Comment by tssurya** [comment]
/hold
```
W0322 19:29:09.494261   24026 node_upgrade.go:66] Error retrieving ConfigMap openshift-ovn-kubernetes/control-plane-status: configmaps "control-plane-status" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot get resource "configmaps" in API group "" in the namespace "openshift-ovn-kubernetes"
F0322 19:29:09.494278   24026 ovnkube.go:133] failed to get initial topology version: configmaps "control-plane-status" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot get resource "configmaps" in API group "" in the namespace "openshift-ovn-kubernetes"

```

**Comment by squeed** [comment]
argh, we added that. Debugging.

**Comment by squeed** [comment]
@tssurya we added those RBAC bits today in CNO - have you picked that up?

**Comment by tssurya** [comment]
> @tssurya we added those RBAC bits today in CNO - have you picked that up?

ah probably not yet :( we just did a run on the latest image of openshift probably the CNO bits hadn't merged? my bad.
if the CNO PR is already merged then we are good.

**Comment by tssurya** [comment]
/hold cancel
https://github.com/openshift/cluster-network-operator/pull/1329 is merged

**Comment by tssurya** [comment]
actually let's confirm that first because we took the image from the CI run on https://github.com/openshift/ovn-kubernetes/pull/1008 which was opened after the CNO PR was merged...

**Comment by squeed** [comment]
I checked all the CI runs - the upgrade was sucessful, it failed on deprovision. The topology code worked as expected.

/override ci/prow/e2e-metal-ipi-ovn-ipv6
/override ci/prow/4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade

**Comment by squeed** [comment]
Loki query to see this: https://grafana-loki.ci.openshift.org/explore?orgId=1&left=%5B%221647978590638%22,%221648064990639%22,%22Grafana%20Cloud%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Binvoker%3D%5C%22openshift-internal-ci%2Fpull-ci-openshift-ovn-kubernetes-master-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade%2F1506388925743108096%5C%22%7D%20%7C%20unpack%20%7C%20namespace%3D%5C%22openshift-ovn-kubernetes%5C%22%20%7C~%20%5C%22opology%5C%22%22%7D%5D

**Pull request merged**
