### PR TITLE
[WIP] [DNM] Downstream merge 2 23 21 endpoints

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by aojea** [comment]
/retest
```

3/2816 Tests Failed. | expand_less
-- | --
: [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should be able to connect to a service that is idled because a GET on the route will unidle it [Suite:openshift/conformance/parallel/minimal] expand_more | : [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should be able to connect to a service that is idled because a GET on the route will unidle it [Suite:openshift/conformance/parallel/minimal] expand_more
: [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should be able to connect to a service that is idled because a GET on the route will unidle it [Suite:openshift/conformance/parallel/minimal] expand_more
: [sig-api-machinery][Feature:APIServer][Late] kubelet terminates kube-apiserver gracefully [Suite:openshift/conformance/parallel] expand_more | : [sig-api-machinery][Feature:APIServer][Late] kubelet terminates kube-apiserver gracefully [Suite:openshift/conformance/parallel] expand_more
: [sig-api-machinery][Feature:APIServer][Late] kubelet terminates kube-apiserver gracefully [Suite:openshift/conformance/parallel] expand_more
: Run multi-stage test e2e-aws-ovn - e2e-aws-ovn-openshift-e2e-test container test expand_more | : Run multi-stage test e2e-aws-ovn - e2e-aws-ovn-openshift-e2e-test container test expand_more
: Run multi-stage test e2e-aws-ovn - e2e-aws-ovn-openshift-e2e-test container test expand_more


```

**Comment by trozet** [comment]
we can compare with #440

**Pull request closed without merging**
