### PR TITLE
OCPBUGS-7010: [release-4.11] Fix Egress FW ACL rules in dualstack mode

### PR DESCRIPTION
**Pull request by martinkennelly**
Clean cherry-pick.

Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest
Unrelated issues and attempting to see if unit test failure is a flake. Unable to detect this unit test failure locally.

**Comment by martinkennelly** [comment]
/test e2e-hypershift
Hypershift job should be fixed now. Unrelated to this PR.

**Comment by martinkennelly** [comment]
@zhaozhanqi Can you add cherry-pick approved?

**Comment by dcbw** [comment]
Adding cherry-pick-approved since it was already qe-approved

**Comment by flavio-fernandes** [comment]
woot!!! 🥳

**Pull request merged**
