### PR TITLE
OCPBUGS-38653,OCPBUGS-38267,OCPBUGS-38693: Downstream Merge 14th August 2024

### PR DESCRIPTION
**Pull request by tssurya**
depends on https://github.com/openshift/ovn-kubernetes/pull/2259

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]

**Comment by tssurya** [comment]
We have https://pr-payload-tests.ci.openshift.org/runs/ci/4219ce90-5eaf-11ef-884f-6a25e6f62e3b-0 and https://pr-payload-tests.ci.openshift.org/runs/ci/4219ce90-5eaf-11ef-884f-6a25e6f62e3b-1 results from payload

they look good except for the stable upgrades:

1. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade/1825756468448595968
2. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-azure-ovn-upgrade/1825756494457475072
3. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-gcp-ovn-rt-upgrade/1825756601001185280

all 3 are showing errors that say:
```
Could not fetch backend disruption data for 1825756470193426432
Could not fetch backend disruption data for 1825756477676064768
Could not fetch backend disruption data for 1825756484391145472
Could not fetch backend disruption data for 1825756491940892672
Could not fetch backend disruption data for 1825756481874563072
Could not fetch backend disruption data for 1825756489432698880
Could not fetch backend disruption data for 1825756486903533568
Could not fetch backend disruption data for 1825756475172065280
Could not fetch backend disruption data for 1825756472693231616
```
I am not sure what that means

**Pull request merged**
