### PR TITLE
OCPBUGS-28819: Support Permanent Session Affinity

### PR DESCRIPTION
**Pull request by tssurya**
CLEAN Cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/2045

### CODE REVIEW

**Comment by tssurya** [comment]
sample failure: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2046/pull-ci-openshift-ovn-kubernetes-release-4.14-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade/1753027061854769152
```

: [sig-network-edge] ns/openshift-console route/console disruption/ingress-to-console connection/new should be available throughout the test expand_less	0s
{  backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console was unreachable during disruption:  for at least 3s (maxAllowed=2s):

Feb 01 14:07:58.149 - 1s    E backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console reason/DisruptionBegan request-audit-id/aefd37be-f145-4b21-aefe-f163ca656402 backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console stopped responding to GET requests over new connections: Get "https://console-openshift-console.apps.ci-op-08lhviwy-8964d.origin-ci-int-aws.dev.rhcloud.com/healthz": EOF
Feb 01 14:19:11.150 - 1s    E backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console reason/DisruptionBegan request-audit-id/38eb7bea-df47-41b9-b333-f420234d03be backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console stopped responding to GET requests over new connections: Get "https://console-openshift-console.apps.ci-op-08lhviwy-8964d.origin-ci-int-aws.dev.rhcloud.com/healthz": EOF
Feb 01 14:27:19.150 - 999ms E backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console reason/DisruptionBegan request-audit-id/861668c0-a04b-4d72-b894-3258d04aa601 backend-disruption-name/ingress-to-console-new-connections connection/new disruption/openshift-tests namespace/openshift-console route/console stopped responding to GET requests over new connections: Get "https://console-openshift-console.apps.ci-op-08lhviwy-8964d.origin-ci-int-aws.dev.rhcloud.com/healthz": EOF}
```
retesting this for now, but will double check versus next run

**Comment by asood-rh** [comment]
@tssurya The PR needs backport assessed label.
The PR has been pre merge tested. Details in the bug.

/label cherry-pick-approved
/label qe-approved

**Pull request merged**
