### PR TITLE
OCPBUGS-6953, OCPBUGS-6955: [Downstream Merge 6th Feb 2023]

### PR DESCRIPTION
**Pull request by tssurya**
Brings in the fixes for https://issues.redhat.com/browse/OCPBUGS-6953 and https://issues.redhat.com/browse/OCPBUGS-6955

tagging commit owners @pperiyasamy @dcbw

### CODE REVIEW

**Comment by pperiyasamy** [comment]
@tssurya Thanks you! Can you also provide reference to [OCPBUGS-5934](https://issues.redhat.com/browse/OCPBUGS-5934) in the PR title because this [commit](https://github.com/openshift/ovn-kubernetes/pull/1509/commits/87fb483e211cc0e3cd409af5a5d5916e87200539) aims to fix the bug.

**Comment by tssurya** [comment]
@pperiyasamy : Hey Peri! We tested that last week and it doesn't work when there is more than one bug, better to manually link the PR to your bug and then move it to MODIFIED when this PR merges.

**Comment by pperiyasamy** [comment]
> @pperiyasamy : Hey Peri! We tested that last week and it doesn't work when there is more than one bug, better to manually link the PR to your bug and then move it to MODIFIED when this PR merges.

OK @tssurya , Thanks for the info!

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows

https://redhat-internal.slack.com/archives/CBN38N3MW/p1675695577499609

**Pull request merged**
