### PR TITLE
Merge upstream - 20200807

### PR DESCRIPTION
**Pull request by abhat**
Periodic merge of upstream changes into openshift/ovn-k

### CODE REVIEW

**Comment by aojea** [comment]
@abhat can you pull in the latest commits from upstream?
 they have several fixes that may help to stabilize this, I've checked several jobs and still have failures in the order of 20s test

**Comment by danwinship** [comment]
just merged the shared gateway IPv6 support too

**Comment by abhat** [comment]
@danwinship pulled in shared gateway mode support for IPv6.

**Comment by abhat** [comment]
Closing in favor of #234.

**Pull request closed without merging**
