### PR TITLE
Bug 2085089: Add support for enabling UDP packet aggregation on veth interfaces

### PR DESCRIPTION
**Pull request by danwinship**
Cherry-picked from https://github.com/ovn-org/ovn-kubernetes/pull/3033

/cc
/hold

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
metal jobs failed to do bad metal commit; should be fixed by https://github.com/openshift/release/pull/29736
/test e2e-metal-ipi-ovn-dualstack
/test e2e-metal-ipi-ovn-ipv6

**Pull request merged**
