### PR TITLE
OCPBUGS-27215,OCPBUGS-26979,OCPBUGS-24271,OCPBUGS-22923,OCPBUGS-20220,OCPBUGS-20209: Downstream Merge 2nd Feb 2024

### PR DESCRIPTION
**Pull request by martinkennelly**
/hold

~I know theres another DS merge - pretesting~ (merged into this)

/cc

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest

Image registry issues

**Comment by qinqon** [comment]
/retitle OCPBUGS-27215,OCPBUGS-26979,OCPBUGS-24271,OCPBUGS-22923,OCPBUGS-20220,OCPBUGS-20209: Downstream Merge 2nd Feb 2024

**Comment by martinkennelly** [comment]
/unhold

@trozet

**Pull request merged**
