### PR TITLE
Upstream rebase 2020-01-17

### PR DESCRIPTION
**Pull request by dcbw**
@knobunc @danwinship @pecameron @JacobTanenbaum @rcarrillocruz @alexanderConstantinescu @juanluisvaladas

### CODE REVIEW

**Comment by dcbw** [comment]
AWS took too long; terraform issues.

/retest

**Comment by dcbw** [comment]
/hold 
got some pod setup issues I'm trying to look into

**Comment by dcbw** [comment]
```
Error downloading packages:
audit-libs-python-2.8.5-4.el7.x86_64: [Errno 256] No more mirrors to try.
```
/retest

**Comment by dcbw** [comment]
/retest

```
2020/01/15 19:51:36 Build ovn-kubernetes previously failed from an infrastructure error (DockerBuildFailed), retrying...
2020/01/15 19:51:37 Build ovn-kubernetes failed, printing logs:
```

**Comment by dcbw** [comment]
```
level=error msg="Error: Error deleting IAM Role ci-op-27w1rhck-834bf-tczpg-bootstrap-role: NoSuchEntity: The role with name ci-op-27w1rhck-834bf-tczpg-bootstrap-role cannot be found."
level=error msg="\tstatus code: 404, request id: d9b5548e-fdb4-4b5d-b9b7-4ee28218cd0b"
level=error
level=error
level=fatal msg="Terraform destroy: failed to destroy using Terraform"
```
/retest

**Comment by dcbw** [comment]
```
E0121 00:07:24.046508       1 operator.go:272] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Grafana failed: reconciling Grafana Deployment failed: updating deployment object failed: waiting for DeploymentRollout of grafana: deployment grafana is not ready. status: (replicas: 2, updated: 1, ready: 0, unavailable: 2)
```

And there are two Grafana pods (eg https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/77/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/182/artifacts/e2e-aws-ovn/pods/openshift-monitoring_grafana-598d7864c5-5z5wx_grafana.log ) and they look like they're fine...

**Comment by dcbw** [comment]
A CI success.
/retest

**Comment by smarterclayton** [comment]
The most recent failure was interesting, it appeared to be related to an inability to configure ingress due to a failure to create CRDs.  Did you look at why?

**Comment by dcbw** [comment]
@smarterclayton I don't think it's the CRD thing? It seems like the router pods fail for some reason, but the logs don't say why:

```
                        "lastState": {
                            "terminated": {
                                "containerID": "cri-o://ec82bbbbc48e732aa197889cf1329adeedfb091e6c5fff4985013fd5cdc54982",
                                "exitCode": 2,
                                "finishedAt": "2020-01-21T12:49:34Z",
                                "message": "I0121 12:48:54.767777       1 template.go:297] router \"level\"=0 \"msg\"=\"starting router\"  \"version\"=\"majorFromGit: \\nminorFromGit: \\ncommitFromGit: 43661b2\\nversionFromGit: v0.0.0-unknown\\ngitTreeState: clean\\nbuildDate: 2020-01-17T11:44:13Z\\n\"\nI0121 12:48:54.770467       1 metrics.go:153] metrics \"level\"=0 \"msg\"=\"router health and metrics port listening on HTTP and HTTPS\"  \"address\"=\"0.0.0.0:1936\"\nI0121 12:48:54.776222       1 router.go:294] template \"level\"=0 \"msg\"=\"watching for changes\"  \"path\"=\"/etc/pki/tls/private\"\nE0121 12:48:54.778184       1 haproxy.go:395] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory\nI0121 12:48:54.801621       1 router.go:548] template \"level\"=0 \"msg\"=\"router reloaded\"  \"output\"=\" - Proxy protocol on, checking http://localhost:80 ...\\n - Health check ok : 0 retry attempt(s).\\n\"\nI0121 12:48:54.801653       1 router.go:257] router \"level\"=0 \"msg\"=\"router is including routes in all namespaces\"  \nI0121 12:48:55.036891       1 router.go:548] template \"level\"=0 \"msg\"=\"router reloaded\"  \"output\"=\" - Proxy protocol on, checking http://localhost:80 ...\\n - Health check ok : 0 retry attempt(s).\\n\"\n",
                                "reason": "Error",
                                "startedAt": "2020-01-21T12:48:54Z"
                            }
                        },
                        "name": "router",
```

**Comment by dcbw** [comment]
> The most recent failure was interesting, it appeared to be related to an inability to configure ingress due to a failure to create CRDs. Did you look at why?

@smarterclayton maybe this?
```
E0121 12:30:31.891376       1 customresource_handler.go:655] error building openapi models for servicemonitors.monitoring.coreos.com: ERROR $root.definitions.com.coreos.monitoring.v1.ServiceMonitor.properties.spec.properties.endpoints.items.<array>.properties.targetPort has invalid property: anyOf
```
but then things seem to recover, or it's a red herring:

```
2020-01-21T12:23:54.214Z	INFO	operator.ingress_controller	ingress/monitoring.go:36	created servicemonitor	{"namespace": "openshift-ingress", "name": "router-default"}
```

**Comment by smarterclayton** [comment]
@ironcladlou what I linked in slack

**Comment by dcbw** [comment]
A CI success.
/test e2e-aws-ovn

**Comment by dcbw** [comment]
Another CI success.
/test e2e-aws-ovn

**Comment by dcbw** [comment]
One perhaps legit failure.
/test e2e-aws-ovn

**Comment by dcbw** [comment]
Another CI success.
/test e2e-aws-ovn

**Comment by dcbw** [comment]
`error: could not run steps: step [release-inputs] failed: could not copy stable imagestreamtag: Timeout: request did not complete within allowed duration`
/retest

**Comment by dcbw** [comment]
`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"`
/retest

**Comment by dcbw** [comment]
`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"`
/test e2e-aws-ovn

**Pull request merged**
