### PR TITLE
Bug 2092567: [Downstream Merge] 16/11/2022

### PR DESCRIPTION
**Pull request by tssurya**
Tagging commit authors
@ricky-rav  for lgtm since you have lots of small fixes coming in
@andreaskaris : PTAL your commits
@JacobTanenbaum @dcbw : Please note that we are not cherry-picking individual commits any more for bug fixes since 4.13 branch has already opened (in context of https://github.com/openshift/ovn-kubernetes/pull/1377 ), we are back to bulk merges.
@pperiyasamy: Please check your commit.

CLEAN MERGE, NO CONFLICTS. cc @trozet @dcbw for merge.

### CODE REVIEW

**Comment by tssurya** [comment]
/hold
waiting for https://github.com/ovn-org/ovn-kubernetes/pull/3275

**Comment by ricky-rav** [comment]
/LGTM
Thank you, Surya!

**Pull request merged**
