### PR TITLE
[DownstreamMerge] Merge 21-12-7

### PR DESCRIPTION
**Pull request by trozet**
@jcaamano @tssurya @dceara @dcbw @astoycos

### CODE REVIEW

**Comment by dceara** [comment]
@trozet We need to first merge https://github.com/openshift/ovn-kubernetes/pull/818 to have an OVN version that supports Load_Balancer_Group.

**Comment by tssurya** [comment]
> @trozet We need to first merge #818 to have an OVN version that supports Load_Balancer_Group.

This has merged, this might need a rebase for CI to pass?

**Comment by trozet** [comment]
windows failure:

```
--- FAIL: TestWMCO/network/Pod_DNS_Resolution (23.62s)
            --- FAIL: TestWMCO/network/Pod_DNS_Resolution/Valid_URL (10.87s)
```

dont know if its a flake or not

**Pull request merged**
