### PR TITLE
OCPBUGS-25394,SDN-4194,OCPBUGS-24055: [DownstreamMerge] 14 Dec 2023

### PR DESCRIPTION
**Pull request by npinaeva**
no conflicts

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/retitle OCPBUGS-25394,SDN-4194,OCPBUGS-24055: [DownstreamMerge] 14 Dec 2023

**Comment by flavio-fernandes** [comment]
Compared PR.

/lgtm

```
❯ git co -b ds_pr1990
Switched to a new branch 'ds_pr1990'

❯ git rev-parse HEAD
bce9f15ad23e221c00b02b8349643cd10e9a1e66

❯ git co downstream/master
❯ git co -b compare_ds_pr1990
❯ git merge ups/master
Merge made by the 'ort' strategy.
 contrib/kind.sh                                            |   2 +-
 dist/images/ovnkube.sh                                     |   7 +++++++
 go-controller/pkg/libovsdb/ops/portgroup.go                |  14 ++++++++++++++
 go-controller/pkg/metrics/ovs.go                           |  68 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 go-controller/pkg/ovn/base_network_controller_namespace.go |  25 +++++++++++++------------
 go-controller/pkg/ovn/base_network_controller_pods.go      |  22 ----------------------
 go-controller/pkg/ovn/egressip.go                          |   9 +++++----
 go-controller/pkg/ovn/egressip_test.go                     |  56 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 go-controller/pkg/ovn/namespace_test.go                    | 111 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 go-controller/pkg/ovn/pods_test.go                         |  24 ++++++++++++++++++++++--
 10 files changed, 294 insertions(+), 44 deletions(-)

❯ git diff bce9f15ad23e221c00b02b8349643cd10e9a1e66 | wc -l
0
```

**Review by trozet — APPROVED** [review]
/approve

**Pull request merged**
