### PR TITLE
[release-4.16] OCPBUGS-41551: Add subnet overlap check for transit switch subnet

### PR DESCRIPTION
**Pull request by arghosh93**
This PR is to emit error and terminate ovnkube startup if transit switch subnet is being used as either join switch or masquerade subnet.

Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com>
(cherry picked from commit 46d35e6ce0f5c4a36906f050d11e99b72e390077)

#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/approve
/label backport-risk-assessed

**Review by tssurya — APPROVED** [review]
/lgtm

cleanbackport hence lgtm I will talk with @arghosh93 to understand the full picture of this + CNO

**Pull request merged**
