### PR TITLE
Bug 1873311: 8 27 2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Includes fixes for Network policy and egress IP.
Note the revert for allow-related will lower performance for pod<->pod traffic without network policy.

### CODE REVIEW

**Comment by trozet** [comment]
@dcbw @danwinship @vpickard @tssurya

**Comment by dcbw** [comment]
rhel8 RPM mirrors are broken and cannot download necessary RPMs:

```
Errors during downloading metadata for repository 'rhel-8-server-ose':
  - Status code: 404 for http://base-4-6-rhel8.ocp.svc/rhel-8-server-ose/repodata/b8df5faabb92041ca5365f3e48729158d42777d26e6af0a50a8040a8197a4f9a-filelists.xml.gz (IP: 172.30.186.152)
  - Status code: 404 for http://base-4-6-rhel8.ocp.svc/rhel-8-server-ose/repodata/dcab78e42cb4e94713200f9b8901b9059b1b09bac1e14f7c04963ada4281cf3b-primary.xml.gz (IP: 172.30.186.152)
Error: Failed to download metadata for repo 'rhel-8-server-ose': Yum repo downloading error: Downloading error(s): repodata/b8df5faabb92041ca5365f3e48729158d42777d26e6af0a50a8040a8197a4f9a-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/dcab78e42cb4e94713200f9b8901b9059b1b09bac1e14f7c04963ada4281cf3b-primary.xml.gz - Cannot download, all mirrors were already tried without success
error: build error: running 'yum install -y  	selinux-policy && 	yum clean all' failed with exit code 1
```

**Pull request merged**
