### PR TITLE
Bug 1973286: Merge 2021-07-06

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
/assign @dcbw @trozet @astoycos 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by astoycos** [comment]
@dcbw Netpol seems like the first thing to flake, we need to keep an eye on this though because some of these commits are for blocker bugs **cough cough  https://bugzilla.redhat.com/show_bug.cgi?id=1978797

**Comment by trozet** [comment]
gcp-ovn is perma failing even in a PR that doesn't change anything:
https://github.com/openshift/ovn-kubernetes/pull/607

Failures look to mostly be centered around network policy.

/override ci/prow/e2e-gcp-ovn

**Pull request merged**
