### PR TITLE
[release-4.10] OCPBUGS-1454: Fix NP upgrade bug: unexpectedly found multiple equivalent ACLs (arp v/s arp||nd)

### PR DESCRIPTION
**Pull request by tssurya**
Cherry-picked from https://github.com/openshift/ovn-kubernetes/pull/1259.
Conflicts are outlined in commit message for each commit.

### CODE REVIEW

**Comment by tssurya** [comment]
https://github.com/openshift/origin/pull/27429 needs to pass first

**Comment by tssurya** [comment]
/hold
till we fix https://issues.redhat.com/browse/OCPBUGS-1705

**Comment by tssurya** [comment]
@anuragthehatter For the 4.10 we will need to do all the tests :D

- We need to do the actual bug test where the (arp) && (arp || nd) was introduced, an upgrade from a 4.9.31 to any version on 4.10 without this fix should introduce the bug, then we test if this version with fix fixes that...
- Repeat same to ensure the default ACL names are changed from <ns>_<np-name> to <ns>-<standard-suffix>
- All the 3 trimACL corner cases we had for > 45 characters

**Comment by tssurya** [comment]
hmm the stable upgrade fails and everytime its a new alert problem!

1. last run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1269/pull-ci-openshift-ovn-kubernetes-release-4.10-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1580064435186176000 `CsvAbnormalFailedOver2Min`
2. before that: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1269/pull-ci-openshift-ovn-kubernetes-release-4.10-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1579895858344759296  
```{  1 events happened too frequently

event happened 25 times, something is wrong: ns/openshift-config-operator pod/openshift-config-operator-7bc5884657-7gtj9 node/ip-10-0-155-62.us-west-2.compute.internal - reason/ProbeError Readiness probe error: Get "https://10.128.0.21:8443/healthz": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
body: 
}
```
3. Before before that: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1269/pull-ci-openshift-ovn-kubernetes-release-4.10-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1579811067561775104 :
```
event happened 35 times, something is wrong: ns/openshift-config-operator pod/openshift-config-operator-7587c4f5f7-djgh8 node/ip-10-0-155-44.ec2.internal - reason/ProbeError Liveness probe error: Get "https://10.129.0.13:8443/healthz": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
body: 

event happened 25 times, something is wrong: ns/openshift-config-operator pod/openshift-config-operator-7587c4f5f7-djgh8 node/ip-10-0-155-44.ec2.internal - reason/ProbeError Readiness probe error: Get "https://10.129.0.13:8443/healthz": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
body: 
}
```

**Comment by anuragthehatter** [comment]
QE testing looks good on all  3 trim ACL cases and ```outport == @a12181866158835321247_ingressDefaultDeny && (arp || nd)``` also looks good. Thanks

**Comment by tssurya** [comment]
thanks Anurag! are we also good on the arp versus arp || nd duplicate ACLs bug?
/assign @jcaamano for the labels

**Pull request merged**
