### PR TITLE
OCPBUGS-298: Dockerfile: bump OVN to 22.09.0-54

### PR DESCRIPTION
**Pull request by kyrtapz**
Follow up to https://github.com/openshift/ovn-kubernetes/pull/1488.
In 4.12 OVN has to be updated both in `Dockerfile.base` and in `Dockerfile`

### CODE REVIEW

**Comment by kyrtapz** [comment]
`e2e-vsphere-ovn` failure doesn't seem to be related to this change: https://issues.redhat.com/browse/OCPBUGS-6976

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
https://github.com/openshift/ovn-kubernetes/pull/1500 fixes this

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows
https://redhat-internal.slack.com/archives/CBN38N3MW/p1675695577499609

**Comment by dcbw** [comment]
Will be obsoleted by https://github.com/openshift/ovn-kubernetes/pull/1504

**Pull request closed without merging**
