### PR TITLE
Upstream merge 2020-02-26

### PR DESCRIPTION
**Pull request by dcbw**
@openshift/networking

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
aws-ovn had one failing test which seemed suspicious:

` Managed cluster should have no crashlooping pods in core namespaces over two minutes `

I looked in deeper and found this:

```
Feb 27 03:32:02.699 - 120s  W node/ip-10-0-129-233.us-west-1.compute.internal node is not ready
Feb 27 03:32:02.699 - 120s  W ns/openshift-image-registry pod/node-ca-lchp9 node/ip-10-0-129-233.us-west-1.compute.internal pod has been pending longer than a minute
Feb 27 03:32:09.402 I persistentvolume/pvc-54e64c4c-fb59-4931-907b-163c4cd111dd error deleting EBS volume "vol-057ddc09617af1d37" since volume is currently attached to "i-0be746f3d03124e98"
Feb 27 03:32:15.136 I persistentvolume/pvc-54e64c4c-fb59-4931-907b-163c4cd111dd error deleting EBS volume "vol-057ddc09617af1d37" since volume is currently attached to "i-0be746f3d03124e98" (2 times)
Feb 27 03:32:17.483 I persistentvolume/pvc-569a80a2-cd62-4f7e-bdf4-5f3896aeacf9 error deleting EBS volume "vol-044345580df6c058a" since volume is currently attached to "i-0be746f3d03124e98"
Feb 27 03:32:30.147 I persistentvolume/pvc-569a80a2-cd62-4f7e-bdf4-5f3896aeacf9 error deleting EBS volume "vol-044345580df6c058a" since volume is currently attached to "i-0be746f3d03124e98" (2 times)
Feb 27 03:32:55.011 I ns/openshift-marketplace deployment/samename Scaled up replica set samename-6bbcc96879 to 1
Feb 27 03:32:55.054 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j node/ created
Feb 27 03:32:55.065 I ns/openshift-marketplace replicaset/samename-6bbcc96879 Created pod: samename-6bbcc96879-4dj2j
Feb 27 03:32:55.084 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j Successfully assigned openshift-marketplace/samename-6bbcc96879-4dj2j to ip-10-0-136-72.us-west-1.compute.internal
Feb 27 03:33:04.612 W ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j node/ip-10-0-136-72.us-west-1.compute.internal graceful deletion within 30s
Feb 27 03:33:05.042 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j Container image "registry.svc.ci.openshift.org/ci-op-9g8kq5f1/stable@sha256:3de7f623e9db1e99b6be662cb9224bf1ec5bbb1a35704d1bda94f3bc888a485e" already present on machine
Feb 27 03:33:05.055 E ns/openshift-ovn-kubernetes pod/ovnkube-node-5fq8t node/ip-10-0-129-233.us-west-1.compute.internal container=ovn-controller container exited with code 137 (Error): 2020-02-27T03:16:42Z|00001|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connecting...\n2020-02-27T03:16:42Z|00002|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connection attempt failed (No such file or directory)\n2020-02-27T03:16:43Z|00003|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connecting...\n2020-02-27T03:16:43Z|00004|reconnect|INFO|unix:/var/run/openvswitch/db.sock: connected\n2020-02-27T03:16:43Z|00005|main|INFO|OVS IDL reconnected, force recompute.\n2020-02-27T03:16:43Z|00006|main|INFO|OVNSB IDL reconnected, force recompute.\n2020-02-27T03:16:43Z|00007|reconnect|INFO|ssl:10.0.131.185:9642: connecting...\n2020-02-27T03:16:43Z|00008|reconnect|INFO|ssl:10.0.131.185:9642: connected\n2020-02-27T03:16:43Z|00009|ofctrl|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting to switch\n2020-02-27T03:16:43Z|00010|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...\n2020-02-27T03:16:43Z|00011|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (No such file or directory)\n2020-02-27T03:16:43Z|00012|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: waiting 1 seconds before reconnect\n2020-02-27T03:16:44Z|00013|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...\n2020-02-27T03:16:44Z|00014|rconn|INFO|unix:/var/run/openvswitch/br-int.mgmt: connected\n2020-02-27T03:16:44Z|00001|pinctrl(ovn_pinctrl1)|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting to switch\n2020-02-27T03:16:44Z|00002|rconn(ovn_pinctrl1)|INFO|unix:/var/run/openvswitch/br-int.mgmt: connecting...\n2020-02-27T03:16:44Z|00003|rconn(ovn_pinctrl1)|INFO|unix:/var/run/openvswitch/br-int.mgmt: connected\n
Feb 27 03:33:05.819 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j Created container samename
Feb 27 03:33:06.085 W ns/openshift-ovn-kubernetes pod/ovnkube-node-5fq8t node/ip-10-0-129-233.us-west-1.compute.internal container=ovn-controller container restarted
Feb 27 03:33:06.254 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j Started container samename
Feb 27 03:33:12.122 E ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j node/ip-10-0-136-72.us-west-1.compute.internal container=samename container exited with code 2 (Error): 
Feb 27 03:33:12.824 I ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j Stopping container samename
Feb 27 03:33:21.540 W ns/openshift-marketplace pod/samename-6bbcc96879-4dj2j node/ip-10-0-136-72.us-west-1.compute.internal deleted

failed: (2m5s) 2020-02-27T03:34:05 "[Feature:Platform] Managed cluster should [Top Level] [Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]"
```

It seems the ovn-controller had problems at that same moment. I looked at the logs and found this, 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/106/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/403/artifacts/e2e-aws-ovn/pods/openshift-ovn-kubernetes_ovnkube-node-5fq8t_ovn-controller.log

I will talk to Numan about this and open a BZ for it. It should however be independent of this PR, so...

/test e2e-aws-ovn
/test e2e-gcp-ovn

**Comment by dcbw** [comment]
AWS failure was API throttling.
GCP failure is `[Conformance][Area:Networking][Feature:Router] The HAProxy router [Top Level] [Conformance][Area:Networking][Feature:Router] The HAProxy router should set Forwarded headers appropriately [Suite:openshift/conformance/parallel/minimal]` which is often flaky.

/retest

**Comment by danwinship** [comment]
If you're waiting for e2e-gcp-ovn to pass, don't hold your breath. https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn

**Comment by dcbw** [comment]
/retest

`validate AWS credentials: checking install permissions: error simulating policy: Throttling: Rate exceeded`

**Pull request merged**
