### PR TITLE
OCPBUGS-17666: Downstream Merge august 15th 2023

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/lgtm

```
❯ git fetch downstream
❯ git checkout master && git merge downstream/master
❯ git co -b mock-downstream-merge-august-15th-2023
❯ git fetch ups
❯ git merge ups/master
Auto-merging go-controller/cmd/ovnkube/ovnkube.go
Merge made by the 'ort' strategy.
 go-controller/cmd/ovnkube/ovnkube.go                           |  1 +
 go-controller/pkg/clustermanager/clustermanager.go             |  3 ---
 go-controller/pkg/libovsdb/libovsdb.go                         |  2 +-
 go-controller/pkg/metrics/cluster_manager.go                   | 12 ------------
 go-controller/pkg/node/default_node_network_controller.go      | 53 ++++++++++++++++++++++++++++++++---------------------
 go-controller/pkg/node/default_node_network_controller_test.go | 36 +-----------------------------------
 6 files changed, 35 insertions(+), 72 deletions(-)

❯ git diff downstream/pr/1817 | wc -l
0
```

**Comment by flavio-fernandes** [comment]
**Note:** The `so local-> shared && shared-> local` jobs are failing due to this:
https://issues.redhat.com/browse/OCPBUGS-16629  and we should be okay overriding for this PR.
`e2e-aws-ovn-kubevirt` is not getting scheduled to run  (or is behind a long queue?).

**Comment by jcaamano** [comment]
known WMCO issue: https://redhat-internal.slack.com/archives/CM4ERHBJS/p1692035137053939

/override ci/prow/e2e-vsphere-ovn-windows

**Comment by jcaamano** [comment]
same here
/override ci/prow/e2e-aws-ovn-windows

**Comment by jcaamano** [comment]
https://issues.redhat.com/browse/OCPBUGS-16629

/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration 
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration

**Pull request merged**
