### PR TITLE
Kube 1.25 bump

### PR DESCRIPTION
**Pull request by bpickard22**
Pulls in https://github.com/ovn-org/ovn-kubernetes/pull/3210 to update kube version to 1.25

### CODE REVIEW

**Comment by ricky-rav** [comment]
/lgtm
Thanks, Ben!

**Comment by tssurya** [comment]
unit test failing because of https://github.com/ovn-org/ovn-kubernetes/pull/3250

**Comment by bpickard22** [comment]
closing in favor of larger downstream merge

**Pull request closed without merging**
