### PR TITLE
Bug 1887456: 11-20-2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Includes fixes for:

1. shared gw mode flows for ingress to pods
2. local gateway moving to normal flows from flood
3. fixes icmpv6 flooding in shared bridge flows
4. fix network policy when the namespace label changes
5. fixes for CNI with ADD failures related to using a namespace that starts with a number

### CODE REVIEW

**Comment by trozet** [comment]
@dcbw @danwinship PTAL

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

The job failure is being tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1895909

**Comment by dcbw** [comment]
openstack failed because bootstrap didn't bring up one of the nodes; didn't even get far enough to start networking.

vsphere failed in bootstrap before networking started too.

**Pull request merged**
