### PR TITLE
[DNM] [WIP] Testing only

### PR DESCRIPTION
**Pull request by stbenjam**
Revert "OCPBUGS-27215,OCPBUGS-26979,OCPBUGS-24271,OCPBUGS-22923,OCPBUGS-20220,OCPBUGS-20209: Downstream Merge 2nd Feb 2024"

Reverts openshift/ovn-kubernetes#2048

### CODE REVIEW

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-agent-compact-ipv4-conformance

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-agent-compact-ipv4-conformance

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-agent-compact-ipv4-conformance

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-agent-compact-ipv4-conformance

**Comment by andfasano** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-agent-compact-ipv4-conformance

**Comment by andfasano** [comment]
I think this PR could be safely closed, a tentative fix is available on https://github.com/openshift/ovn-kubernetes/pull/2077

**Pull request closed without merging**
