### PR TITLE
rebase to upstream 2020-07-11

### PR DESCRIPTION
**Pull request by danwinship**
Specifically to get all pending dual-stack work

Note in particular the three new local commits:
- [iptables-scripts: sync to upstream](https://github.com/openshift/ovn-kubernetes/commit/9d53b73fc902e44aa1fb00023d7cb2dcc08ef3dd), which just removes some unnecessary divergence
- [Revert IPv4-in-single-stack-IPv6 hack](https://github.com/openshift/ovn-kubernetes/pull/201/commits/dfb20b2be464a9205b51c392fcc901c6753f06a7), which reverts the single-stack Azure/AWS hacks, which never fully worked, and are no longer relevant; in the future, if clouds only support dual-stack, not single-stack IPv6, then we will only support dual-stack OCP on them, not single-stack IPv6.
- [Mark OCP-specific hacks more clearly](https://github.com/openshift/ovn-kubernetes/commit/3f708d6c24680d3475ca9e40fa854dd78a7cba57) which renames the existing OCP-local go files to `OCP_HACKS.go`, moves some more code into them, and adds `// OCP HACK` comments around the pieces of code in other files that refer to them. Keeping the code in other files helps to prevent merge conflicts, and adding the `// OCP HACK` comments help to make it clearer, when rebasing, that a merge conflict is being caused by an intentional divergence.

The previous rebase had some divergence from upstream around the delete conntrack stuff. I assume that this was either accidental or due to the fact that that code was still in flux. This merge puts us fully back in sync with upstream on that.

The MCS and Azure/GCP LoadBalancer hacks in `go-controller/pkg/node/OCP_HACKS.go` have now been updated for dual-stack.

### CODE REVIEW

**Comment by dcbw** [comment]
@danwinship you need to bump our Dockerfile for Go 1.13 since upstream now requires it:

```
-FROM openshift/origin-release:golang-1.12 AS builder
+FROM openshift/origin-release:golang-1.13 AS builder
```

**Comment by danwinship** [comment]
ovn-kube master logs are full of weird northd errors:

```
E0713 22:04:14.990087       1 master.go:204] Failed to get ovn-northd status stderr() :(failed to run the command since failed to get ovn-northd's pid: open /var/run/ovn/ovn-northd.pid: no such file or directory)
E0713 22:04:14.996474       1 master.go:188] Failed to get northd_probe_interval value stderr(ovn-nbctl: no key "northd_probe_interval" in NB_Global record "." column options
) :(OVN command '/usr/bin/ovn-nbctl --timeout=5 get NB_Global . options:northd_probe_interval' failed: exit status 1)
E0713 22:04:21.242763       1 metrics.go:124] failed to get coverage/show output for ovn-northd stderr(): (failed to run the command since failed to get ovn-northd's pid: open /var/run/ovn/ovn-northd.pid: no such file or directory)
```

This seems to be new with this PR (eg, [this nightly from a few days ago](https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-ovn-4.6/1282363760928886784/artifacts/e2e-aws/pods/openshift-ovn-kubernetes_ovnkube-master-5rdln_ovnkube-master.log) doesn't show the same problem). I'm not sure why though since nothing should be changing anything about master/northd communication in this PR...

**Comment by danwinship** [comment]
oh, probably those metrics are new...

**Comment by danwinship** [comment]
last e2e-aws run failed because one of the nodes appears to have stopped receiving new events. [Logs](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/201/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1282781610898362368/artifacts/e2e-aws-ovn/pods/openshift-ovn-kubernetes_ovnkube-node-8zm42_ovnkube-node.log) show the last pod event at 21:49:33, but, eg [the master logs](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/201/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1282781610898362368/artifacts/e2e-aws-ovn/pods/openshift-ovn-kubernetes_ovnkube-master-86n54_ovnkube-master.log) show it allocating pod `e2e-net-services1-4502/execpod-sourceip-ip-10-0-157-84.us-west-2.compute.internalrwx4d` to that node at 21:51:12

**Comment by danwinship** [comment]
> ovn-kube master logs are full of weird northd errors:

filed https://github.com/openshift/cluster-network-operator/pull/710. But that doesn't block this; it just screws up the new metrics, nothing else

**Comment by danwinship** [comment]
routes are failing on gcp and Azure; probably mis-merged the gcp/azure loadbalancer hack

**Pull request closed without merging**
