### PR TITLE
DS-Merge: Part1: No UDN Bits

### PR DESCRIPTION
**Pull request by tssurya**
1. DNS Resolver
2. Masquerade Day2
3. EIP Multinic escalation fix

### CODE REVIEW

**Comment by kyrtapz** [comment]
This error looks suspect:
```
: [sig-network] pods should successfully create sandboxes by other expand_less 	0s
{  2 failures to create the sandbox

namespace/openshift-multus node/ci-op-bzqyhsk0-22ebe-d2vvl-master-1 pod/network-metrics-daemon-xhpbr hmsg/b1deceee10 - never deleted - firstTimestamp/2024-08-14T09:49:18Z interesting/true lastTimestamp/2024-08-14T09:49:18Z reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-xhpbr_openshift-multus_01f5ef94-15a8-4f59-b97f-daa8082ab552_0(1cc3d985efb0750dc5ae122a08e3408d83024e3575b48278e02f5bcf1a876679): no CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?
namespace/openshift-multus node/ci-op-bzqyhsk0-22ebe-d2vvl-master-1 pod/network-metrics-daemon-xhpbr hmsg/075df857a4 - never deleted - firstTimestamp/2024-08-14T09:49:18Z interesting/true lastTimestamp/2024-08-14T09:49:18Z reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-metrics-daemon-xhpbr_openshift-multus_01f5ef94-15a8-4f59-b97f-daa8082ab552_0(a8030c605712c3271bd9d664a558d01989f7e4b93a5c2b0c07ae6c2fe497bbff): no CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?}
```
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2254/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn-upgrade/1823609719420358656

/test e2e-azure-ovn-upgrade

**Comment by martinkennelly** [comment]
Looked at the logs and i think its just a flake during upgrade of a control plane node

**Comment by martinkennelly** [comment]
It occurred during update it seems from the log stamps. I think its probably a flake due to a race as CNO deploys this metrics component alongside ovn-k right?

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade
Disruption seen:
11s (maxAllowed=6s)

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade

Unrelated infra bootstrap issue

**Comment by martinkennelly** [comment]
@tssurya we're good here - we merge?

**Pull request closed without merging**
