### PR TITLE
Bug 1860710: 7-27-2020 merge

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@stbenjam FYI

**Comment by danwinship** [comment]
e2e-aws-ovn and e2e-gcp-ovn are both failing with (among others)
```
[sig-instrumentation]  Prometheus when installed on the cluster should provide named network metrics [Suite:openshift/conformance/parallel]
fail [github.com/openshift/origin@/test/extended/util/prometheus/helpers.go:174]: Expected
     <map[string]error \| len:1>: {
         "pod_network_name_info{pod=\"execpodhw655\",namespace=\"e2e-test-prometheus-ppwwf\",network_name=\"secondary\"} == 0": {
             s: "promQL query: pod_network_name_info{pod=\"execpodhw655\",namespace=\"e2e-test-prometheus-ppwwf\",network_name=\"secondary\"} == 0 had reported incorrect results:\n[]",
         },
     }
 to be empty
```

This does not appear to be flaking in plain e2e-aws

**Comment by trozet** [comment]
> e2e-aws-ovn and e2e-gcp-ovn are both failing with (among others)
> 
> ```
> [sig-instrumentation]  Prometheus when installed on the cluster should provide named network metrics [Suite:openshift/conformance/parallel]
> fail [github.com/openshift/origin@/test/extended/util/prometheus/helpers.go:174]: Expected
>      <map[string]error \| len:1>: {
>          "pod_network_name_info{pod=\"execpodhw655\",namespace=\"e2e-test-prometheus-ppwwf\",network_name=\"secondary\"} == 0": {
>              s: "promQL query: pod_network_name_info{pod=\"execpodhw655\",namespace=\"e2e-test-prometheus-ppwwf\",network_name=\"secondary\"} == 0 had reported incorrect results:\n[]",
>          },
>      }
>  to be empty
> ```
> 
> This does not appear to be flaking in plain e2e-aws

I see a bunch of prometheus failures in regular AWS:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1860/pull-ci-openshift-machine-config-operator-master-e2e-aws/1287891822491734016

**Comment by trozet** [comment]
PDB tests are failing a lot as well, like:
[sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it [Suite:openshift/conformance/parallel] [Suite:k8s]

**Comment by danwinship** [comment]
> I see a bunch of prometheus failures in regular AWS:

But there were none of _that specific test_, which failed on both AWS and GCP in this PR, suggesting a possible regression in this rebase. But it looks like it passed now so I guess it was just a flake.

**Comment by stbenjam** [comment]
e2e-metal-ipi passed! 

The previous failures are [also showing up on IPv4 with OpenShiftSDN](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ocp-4.6-e2e-metal-ipi-ipv4/1287538431110418432). So it seems unrelated, there's some flakiness with the api server.

That uses OpenShiftSDN, so not a product of any ovn changes AFAICT.

**Comment by dcbw** [comment]
aws fail is a flake on PDB
/test e2e-aws-ovn

**Comment by trozet** [comment]
Not sure why CI robot is not restarting gcp-ovn

/test e2e-gcp-ovn

**Pull request merged**
