### PR TITLE
Bug 2078222, OCPBUGS-4119, OCPBUGS-5930, OCPBUGS-4425: [DownstreamMerge] 1-31-23

### PR DESCRIPTION
**Pull request by tssurya**
Clean Merge, + one OCPHACKS commit on top. See last commit message for details.

Following-up from https://github.com/openshift/ovn-kubernetes/pull/1493 since @trozet 's on PTO 

tagging commit owners: @JacobTanenbaum @dcbw @zshi-redhat @trozet @maiqueb @martinkennelly @npinaeva

### CODE REVIEW

**Comment by npinaeva** [comment]
/retitle Bug 2078222, OCPBUGS-4119, OCPBUGS-5930: [DownstreamMerge] 1-31-23

**Comment by martinkennelly** [comment]
/retitle Bug 2078222, OCPBUGS-4119, OCPBUGS-5930, OCPBUGS-4425: [DownstreamMerge] 1-31-23

**Pull request merged**
