### PR TITLE
[release-4.8] Bug 1976241: Update existing policy ACLs on start

### PR DESCRIPTION
**Pull request by jcaamano**
This is a cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/600/commits/98306249a6d844a60e6c58e431a3b03e37738d2d && https://github.com/openshift/ovn-kubernetes/pull/600/commits/8a635a8198a20a54cba749fb57404c739fdd388e

### CODE REVIEW

**Comment by aravindhp** [comment]
Patch manager comment: Dependent [bug 1962387](https://bugzilla.redhat.com/show_bug.cgi?id=1962387) has been transitioned from MODIFIED to RELEASE_PENDING by the PR author. Not picking for the release due to that reason.

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.50

picked

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.50

picked

**Pull request merged**
