### PR TITLE
OCPBUGS-34405: [release-4.14] dns: fix deadlock in case of error

### PR DESCRIPTION
**Pull request by npinaeva**
backport of https://github.com/openshift/ovn-kubernetes/pull/2182

### CODE REVIEW

**Comment by jcaamano** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade

**Comment by jcaamano** [comment]
/hold
/override ci/prow/4.14-upgrade-from-stable-4.13-local-gateway-e2e-aws-ovn-upgrade

**Comment by npinaeva** [comment]
/hold cancel
since we couldn't figure out a way to run upgrade in local gateway mode

**Pull request merged**
