### PR TITLE
OCPBUGS-3075: [release-4.12]  Fix netpol races

### PR DESCRIPTION
**Pull request by npinaeva**
cherry-pick for https://github.com/openshift/ovn-kubernetes/pull/1323

### CODE REVIEW

**Comment by dcbw** [comment]
/approve
/retest

something odd going on with CI:
```
[36mINFO[0m[2022-11-02T09:02:39Z] Building src                                 
[36mINFO[0m[2022-11-02T09:03:46Z] Build src succeeded after 1m7s               
[36mINFO[0m[2022-11-02T09:03:46Z] Building ovn-kubernetes                      
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2022-11-02T09:03:51Z"}
[36mINFO[0m[2022-11-02T09:03:51Z] Received signal.                              [36msignal[0m=interrupt
```

**Comment by trozet** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade

**Comment by trozet** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade

**Comment by trozet** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-images

**Comment by npinaeva** [comment]
ovn-conf step failed with `Could not resolve host: github.com`. retesting again

**Pull request merged**
