### PR TITLE
Bug 1903408: Merge externalTrafficPolicy and smartnic v2 support 

### PR DESCRIPTION
**Pull request by astoycos**
This PR pulls int the code needed to land the externalTrafficPolicy feature to work.  It needs to merge downstream along with the smartnicv2 code because it is closely intertwined.  

cc @Billy99

### CODE REVIEW

**Comment by astoycos** [comment]
Weird in `e2e-aws-ovn` seeing 
```
Aug 10 18:03:32.349: INFO: Creating new exec pod
Aug 10 18:03:41.515: INFO: Running '/usr/bin/kubectl --server=https://api.ci-op-dkzzsipn-834bf.origin-ci-int-aws.dev.rhcloud.com:6443 --kubeconfig=/tmp/kubeconfig-495760389 --namespace=e2e-services-709 exec execpodz2kh7 -- /bin/sh -x -c echo hostName | nc -v -t -w 2 nodeport-test 80'
Aug 10 18:03:41.962: INFO: stderr: "+ echo hostName\n+ nc -v -t -w 2 nodeport-test 80\nConnection to nodeport-test 80 port [tcp/http] succeeded!\n"
Aug 10 18:03:41.962: INFO: stdout: "nodeport-test-rgmqc"
```

Which looks like things are succeeding but in stderr not stdout will need to investigate

**Comment by squeed** [comment]
@astoycos the CI failures are very concerning. Especially "[sig-network] Services should be able to create a functioning NodePort service"

**Comment by squeed** [comment]
/retest-required
to get some more data

**Comment by astoycos** [comment]
It passes on upstream 
```
[BeforeEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
STEP: Creating a kubernetes client
Aug 11 13:10:28.191: INFO: >>> kubeConfig: /home/astoycos/admin.conf
STEP: Building a namespace api object, basename services
Aug 11 13:10:28.255: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:745
[It] should be able to create a functioning NodePort service [Conformance]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:640
STEP: creating service nodeport-test with type=NodePort in namespace services-4279
STEP: creating replication controller nodeport-test in namespace services-4279
I0811 13:10:28.271891 2565991 runners.go:190] Created replication controller with name: nodeport-test, namespace: services-4279, replica count: 2
I0811 13:10:31.324763 2565991 runners.go:190] nodeport-test Pods: 2 out of 2 created, 0 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0811 13:10:34.325362 2565991 runners.go:190] nodeport-test Pods: 2 out of 2 created, 0 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
I0811 13:10:37.326381 2565991 runners.go:190] nodeport-test Pods: 2 out of 2 created, 2 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
Aug 11 13:10:37.326: INFO: Creating new exec pod
Aug 11 13:10:42.341: INFO: Running '/home/astoycos/bin/kubectl --server=https://10.8.125.13:11337 --kubeconfig=/home/astoycos/admin.conf --namespace=services-4279 exec execpodjst56 -- /bin/sh -x -c nc -zv -t -w 2 nodeport-test 80'
Aug 11 13:10:42.664: INFO: stderr: "+ nc -zv -t -w 2 nodeport-test 80\nConnection to nodeport-test 80 port [tcp/http] succeeded!\n"
Aug 11 13:10:42.664: INFO: stdout: ""
Aug 11 13:10:42.664: INFO: Running '/home/astoycos/bin/kubectl --server=https://10.8.125.13:11337 --kubeconfig=/home/astoycos/admin.conf --namespace=services-4279 exec execpodjst56 -- /bin/sh -x -c nc -zv -t -w 2 10.96.31.240 80'
Aug 11 13:10:42.865: INFO: stderr: "+ nc -zv -t -w 2 10.96.31.240 80\nConnection to 10.96.31.240 80 port [tcp/http] succeeded!\n"
Aug 11 13:10:42.865: INFO: stdout: ""
Aug 11 13:10:42.866: INFO: Running '/home/astoycos/bin/kubectl --server=https://10.8.125.13:11337 --kubeconfig=/home/astoycos/admin.conf --namespace=services-4279 exec execpodjst56 -- /bin/sh -x -c nc -zv -t -w 2 172.18.0.2 31531'
Aug 11 13:10:43.066: INFO: stderr: "+ nc -zv -t -w 2 172.18.0.2 31531\nConnection to 172.18.0.2 31531 port [tcp/31531] succeeded!\n"
Aug 11 13:10:43.066: INFO: stdout: ""
Aug 11 13:10:43.066: INFO: Running '/home/astoycos/bin/kubectl --server=https://10.8.125.13:11337 --kubeconfig=/home/astoycos/admin.conf --namespace=services-4279 exec execpodjst56 -- /bin/sh -x -c nc -zv -t -w 2 172.18.0.3 31531'
Aug 11 13:10:43.284: INFO: stderr: "+ nc -zv -t -w 2 172.18.0.3 31531\nConnection to 172.18.0.3 31531 port [tcp/31531] succeeded!\n"
Aug 11 13:10:43.284: INFO: stdout: ""
[AfterEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
Aug 11 13:10:43.284: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "services-4279" for this suite.
[AfterEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:749


• [SLOW TEST:15.101 seconds]
[sig-network] Services
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:23
  should be able to create a functioning NodePort service [Conformance]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:640
------------------------------
{"msg":"PASSED [sig-network] Services should be able to create a functioning NodePort service [Conformance]","total":-1,"completed":1,"skipped":74,"failed":0}
Aug 11 13:10:43.292: INFO: Running AfterSuite actions on all nodes


Aug 11 13:10:28.503: INFO: Running AfterSuite actions on all nodes
Aug 11 13:10:43.306: INFO: Running AfterSuite actions on node 1


Ran 1 of 5668 Specs in 15.521 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Flaked | 0 Pending | 5667 Skipped
```

**Pull request closed without merging**
