### PR TITLE
OCPBUGS-28742, OCPBUGS-17207: Downstream Merge 22nd Feb 2024

### PR DESCRIPTION
**Pull request by martinkennelly**
cc @jcaamano @kyrtapz @maiqueb @oribon @tssurya

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
lgtm for my added e2e tests.

**Comment by kyrtapz** [comment]
lgtm for 23c8e0cd55bd04b4f4711c789f1e556d55031c47

**Comment by tssurya** [comment]
/retest-required
will approve after CI is fully green

**Comment by tssurya** [comment]
@kyrtapz didn't you have a bug for the certs fix? Should we tag that here?

**Comment by kyrtapz** [comment]
/retitle OCPBUGS-28742, OCPBUGS-17207: Downstream Merge 22nd Feb 2024

**Pull request merged**
