### PR TITLE
Bug 2084249: [Downstream merge] 12-05-2022

### PR DESCRIPTION
**Pull request by tssurya**
tagging @oribon @stbenjam @abhat as commit owners
@trozet @dcbw for reviews

### CODE REVIEW

**Comment by dcbw** [comment]
Metal jobs failing iwth:
```
level=error
level=error msg=Error: could not contact Ironic API: timeout reached
level=error
level=error msg=  with ironic_node_v1.openshift-master-host[0],
level=error msg=  on main.tf line 13, in resource "ironic_node_v1" "openshift-master-host":
level=error msg=  13: resource "ironic_node_v1" "openshift-master-host" {
level=error
level=error
```

/retest

**Comment by trozet** [comment]
closing in favor of #1090 so we can get egress ip retry in for FF

/close

**Pull request closed without merging**
