### PR TITLE
OCPBUGS-29350,SDN-4542,OCPBUGS-29389: Downstream Merge 29th Feb 2024

### PR DESCRIPTION
**Pull request by kyrtapz**
No conflicts.
@tssurya @jcaamano @qinqon @martinkennelly

### CODE REVIEW

**Comment by kyrtapz** [comment]
unit tests failed: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2089/pull-ci-openshift-ovn-kubernetes-master-unit/1762768840850149376
/test unit

**Comment by kyrtapz** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2089/pull-ci-openshift-ovn-kubernetes-master-unit/1762830334031826944
/test unit

**Comment by kyrtapz** [comment]
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2089/pull-ci-openshift-ovn-kubernetes-master-unit/1762834261318045696 another new one...
/test unit

**Comment by tssurya** [comment]
/retitle SDN-4542, OCPBUGS-29389: Downstream Merge 29th Feb 2024

**Comment by tssurya** [comment]
/retitle SDN-4542,OCPBUGS-29389: Downstream Merge 29th Feb 2024

**Comment by martinkennelly** [comment]
/retitle OCPBUGS-29350,SDN-4542,OCPBUGS-29389: Downstream Merge 29th Feb 2024

**Comment by andfasano** [comment]
Running also an agent compact job, since the patch includes a fix (https://github.com/ovn-org/ovn-kubernetes/pull/4168) for https://issues.redhat.com/browse/OCPBUGS-29350 

/test e2e-agent-compact-ipv4

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn

` [FAILED] unable to decode release payload with error: invalid character 'w' looking for beginning of value`
Doesnt look related to this PR

**Comment by martinkennelly** [comment]
Same error in hypershift job and it seems its widespread issue: https://search.dptools.openshift.org/?search=Managed+cluster+should+ensure+pods+use+downstream+images+from+our+release+image+with+proper+ImagePullPolicy+&maxAge=12h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by martinkennelly** [comment]
/test e2e-metal-ipi-ovn-ipv6 

Cluster init failure

**Comment by martinkennelly** [comment]
This PR should fix that `unable to decode release payload...` issue: https://github.com/openshift/origin/pull/28631

**Comment by martinkennelly** [comment]
/retest

Fix is merged.

**Comment by martinkennelly** [comment]
/retest

Platform setup failure and `Job execution failed: Pod got deleted unexpectedly`

**Comment by tssurya** [comment]
ipv6 errors due to unrelated reasons: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2089/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6/1763583731601248256
retested

**Comment by kyrtapz** [comment]
the metal job failure looks related to https://redhat-internal.slack.com/archives/C02CZNQHGN8/p1709541815810969

**Pull request merged**
