### PR TITLE
[release-4.6] OCPBUGS-16210: Dockerfile: build both RHEL7 and RHEL8 shims

### PR DESCRIPTION
**Pull request by jcaamano**
Since the shim (ovn-k8s-cni-overlay) gets copied to the host OS and executed in the host mount namespace by CRIO/Multus it needs to be runtime compatible with the host OS. Running a RHEL8-built shim on a RHEL7 system doesn't work due to different shared library dependencies between the two OS versions.

This wasn't a problem before because CGO_ENABLED=0 which essentially statically linked everything into the binary. But since we actually need CGO_ENABLED=1 (which ART forces on "official" builds anyway) to ensure we use OpenSSL's crypto for FIPS compliance, we run into the OS version problem with our binaries since they are really always built with CGO_ENABLED=1 anyway.

So... build two separate versions of ovn-kubernetes in different layers, and copy the RHEL7 shim into a special location where our container startup scripts can find it.

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
(cherry picked from commit 932ef31ed728426b7bb8c52b52ed52cb38d84a1d) (cherry picked from commit 20f8d238c00fdfbb9c93689ed0c7f1d8b360a255) (cherry picked from commit 37a5ded3eec9faed3d187b9418303aa93dc7da64)

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jcaamano** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

Gather extra failed which I don't think has anything to do with this PR, but all tests passed.

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

error: unable to connect to image repository virthost.ostest.test.metalkube.org:5000/localimages/local-release-image@sha256:40175d5690e2d4691fc95e1cc1881892627d39ef29330d3b778f80aa981d5abe: Get "https://virthost.ostest.test.metalkube.org:5000/v2/": Internal Server Error

**Pull request merged**
