### PR TITLE
OCPBUGS-27093: Dockerfile: Bump OVN to ovn-23.09.0-112.el9fdp

### PR DESCRIPTION
**Pull request by dceara**
Includes the following relevant changes:
- actions: Use random port selection for SNAT with external_port_range.
  [https://issues.redhat.com/browse/FDP-301]
  [https://issues.redhat.com/browse/RFE-4980]
- northd: Make sure that affinity flows match on VIP.
  [https://issues.redhat.com/browse/FDP-290]
- ovn: Add tunnel PMTUD support.
  [https://bugzilla.redhat.com/show_bug.cgi?id=2241711]
- northd: Use proper field for lookup_nd
  [https://issues.redhat.com/browse/FDP-283]
  [https://issues.redhat.com/browse/OCPBUGS-27093]
- northd: Remove the protocol match from ECMP symmetric reply flows.
  [https://issues.redhat.com/browse/FDP-358]
- northd: Explicitly handle SNAT for ICMP need frag.
  [https://issues.redhat.com/browse/FDP-159]

### CODE REVIEW

**Comment by dceara** [comment]
CC: @trozet @tssurya @jcaamano

Corresponding PR to bump to -112 in ovn-org/ovn-kubernetes:
https://github.com/ovn-org/ovn-kubernetes/pull/4114

**Comment by dceara** [comment]
/hold
until mirrors are synced and upstream PR is merged

**Review by trozet — APPROVED** [review]
/approve

**Comment by trozet** [comment]
/retitle OCPBUGS-27093: Dockerfile: Bump OVN to ovn-23.09.0-112.el9fdp

**Pull request merged**
