### PR TITLE
SDN-4930,OCPBUGS-38949: Downstream Merge 28th August

### PR DESCRIPTION
**Pull request by martinkennelly**
cc @tssurya

### CODE REVIEW

**Comment by tssurya** [comment]
/hold

1. please add 4930 epic to the title; 
2. ensure the previous merge has come in a nightly green payload before removing this hold
3. run payloads nightly and ci and ensure they are green
4. ensure all tech preview jobs are green and if any red's then ensure its not us

**Comment by martinkennelly** [comment]
/test 4.16-upgrade-from-stable-4.15-local-gateway-e2e-aws-ovn-upgrade

No networking issue. "Connection refused"

**Comment by martinkennelly** [comment]
None of the failures look related to this PR

**Comment by martinkennelly** [comment]
@tssurya what did you mean by this:
`please add 4930 epic to the title;`

Dont know of any issue with 4930

**Comment by martinkennelly** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-azure-ovn-upgrade

**Comment by tssurya** [comment]
/retitle SDN-4930,OCPBUGS-38949: Downstream Merge 28th August

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade

unrelated test failures.

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-techpreview

unrelated infra init issue

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn

infra init issue

**Comment by tssurya** [comment]
/override ci/prow/e2e-azure-ovn because its infra related failures and its happening everywhere and also this job had already passed in previous run: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2276/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn/1828767909845929984

**Pull request merged**
