### PR TITLE
4-9-21 merge

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by abhat** [comment]
The PR is rebased with upstream that has the commit to set the default host network namespace to empty string. Cancelling the hold.

/hold cancel

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-windows

aws-ovn-windows isnt going to pass due to known issue with:
[36mINFO[0m[2021-04-10T00:27:19Z] === RUN   TestWMCO/create/Node_Metadata/ip-10-0-249-249.us-east-2.compute.internal_Validation_Tests/Kubelet_Version 
[36mINFO[0m[2021-04-10T00:27:19Z]     validation_test.go:38:                   
[36mINFO[0m[2021-04-10T00:27:19Z]         	Error Trace:	validation_test.go:38  
[36mINFO[0m[2021-04-10T00:27:19Z]         	Error:      	Should be true         
[36mINFO[0m[2021-04-10T00:27:19Z]         	Test:       	TestWMCO/create/Node_Metadata/ip-10-0-249-249.us-east-2.compute.internal_Validation_Tests/Kubelet_Version 
[36mINFO[0m[2021-04-10T00:27:19Z]         	Messages:   	expected kubelet version was not present on ip-10-0-249-249.us-east-2.compute.internal

**Comment by trozet** [comment]
@dcbw in the azure failure ovnkube-master is in crash loop backoff. It looks like nbdb is not coming up on one of the nodes:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/496/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn/1380683315459133440

INFO[2021-04-10T02:08:05Z] level=error msg=Cluster operator network Degraded is True with RolloutHung: DaemonSet "openshift-ovn-kubernetes/ovnkube-master" rollout is not making progress - pod ovnkube-master-t4c2q is in CrashLoopBackOff State INFO[2021-04-10T02:08:05Z] level=error msg=DaemonSet "openshift-ovn-kubernetes/ovnkube-master" rollout is not making progress - last change 2021-04-10T01:19:10Z

**Comment by abhat** [comment]
Overriding the e2e-aws-ovn-windows job: Known issue with 1.21 and dual-stack kube-proxy on Windows

**Pull request merged**
