### PR TITLE
[release-4.17] SDN-4919,OCPBUGS-39200: 4.18 merge - 5th Sept

### PR DESCRIPTION
**Pull request by martinkennelly**
/cc 
/hold 

TBD

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest

no issue that seem related to this PR

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade

Test passed but exceeded 4 hours and got killed. 
```
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:169","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2024-09-06T10:46:20Z"}
INFO[2024-09-06T10:46:20Z] Received signal.                              signal=interrupt
INFO[2024-09-06T10:46:20Z] error: Process interrupted with signal interrupt, cancelling execution... 

```

**Comment by martinkennelly** [comment]
/test 4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade

ditto

**Comment by martinkennelly** [comment]
/test e2e-metal-ipi-ovn-techpreview

nothing indicating this PR is causing failure.

**Comment by martinkennelly** [comment]
payload jobs are good

**Comment by martinkennelly** [comment]
Metal tech preview continues to fail in the same mannor - nothing obvious sticking out.

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade 

`INFO[2024-09-06T15:21:31Z] Running step e2e-azure-ovn-upgrade-ipi-deprovision-deprovision. 
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:169","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2024-09-06T15:23:16Z"}`

No tests failed.

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade 

`{  ["e2e-azure-ovn-upgrade" pod "e2e-azure-ovn-upgrade-openshift-e2e-test" failed: could not watch pod: context canceled
Link to step on registry info site: https://steps.ci.openshift.org/reference/openshift-e2e-test
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=ovn-kubernetes&branch=release-4.17&test=e2e-azure-ovn-upgrade, cancelled]}`

**Comment by tssurya** [comment]
/hold
don't merge this till we get the bug in services fixed (contact Ricky for details, martin)

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade 

Test reach timelimit of 4 hours. No failures reported but unsure if its just unreported.
Looked at ovn-k and no issues seen in mg logs.

**Comment by martinkennelly** [comment]
Waiting for https://github.com/ovn-org/ovn-kubernetes/pull/4734

**Comment by jluhrsen** [comment]
the hypershift-conformance-techpreview job is new and we hope that it can pass, but I think it has some permafailing
tests that we may need to dig in to. I started a slack thread [here](https://redhat-external.slack.com/archives/C01C8502FMM/p1730746026912429).

**Comment by jluhrsen** [comment]
/test e2e-azure-ovn-upgrade 

looks like the [last run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2291/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-azure-ovn-upgrade/1852418404267331584) was good with e2e, but some gather step had trouble. let's see what the next run looks like.

**Comment by tssurya** [comment]
@jluhrsen hmm why are we trying to get this merge in? We should just straight get your opened 4.17 merge in...this introduces the bug which we don't want to introduce...

**Comment by jluhrsen** [comment]
> @jluhrsen hmm why are we trying to get this merge in? We should just straight get your opened 4.17 merge in...this introduces the bug which we don't want to introduce...

@tssurya, that's fine. we can close this and move on with mine. I figured this one was very close to being good with the team though (passing CI, etc) and would effectively make my other PR built on top of this much smaller.

I also did not know about "the bug" this would introduce.

let's close this and I'll focus my attention on https://github.com/openshift/ovn-kubernetes/pull/2335

BTW, I don't have permission to close this.

**Pull request closed without merging**
