### PR TITLE
OCPBUGS-10929:[release-4.13]4.13 1.26 bump

### PR DESCRIPTION
**Pull request by bpickard22**
Backport of 1.26 bump -> https://github.com/ovn-org/ovn-kubernetes/pull/3401
Includes kube dep bumps to 1.26 and error checking for event handlers and informers

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-windows
https://redhat-internal.slack.com/archives/CM4ERHBJS/p1680098938285029

**Pull request merged**
