### PR TITLE
[release-4.11] OCPBUGS-4408: Validate node subnet annotations against cluster networks

### PR DESCRIPTION
**Pull request by pperiyasamy**
This is manual cherry-pick of 4.12 commits https://github.com/openshift/ovn-kubernetes/commit/9b7784b3acdbe13d174b1fdc8f904f35685eb378 https://github.com/openshift/ovn-kubernetes/commit/302b3080fcca4ca149ed64e1ed49c432e2d596bf https://github.com/openshift/ovn-kubernetes/commit/2d7a0f7b524fed908917f1b705432fbee9eb29b7 https://github.com/openshift/ovn-kubernetes/commit/e60a0ce037a73e1490c794af4d0195cd4a573847 https://github.com/openshift/ovn-kubernetes/commit/e524e3a0dc7c887cb4b8124aff1b7cad4d53d1e1.

Signed-off-by: Periyasamy Palanisamy [pepalani@redhat.com](mailto:pepalani@redhat.com)

### CODE REVIEW

**Comment by anuragthehatter** [comment]
Looks good in QE testing on bot build

/label qe-approved

**Comment by dcbw** [comment]
/retest

RPM mirrors were down for a while Friday and no images could be built.

**Comment by dcbw** [comment]
@pperiyasamy any idea if the unit test hang means we need a bit more fixup on 4.11 to account for things that may have changed since then?

**Pull request merged**
