### PR TITLE
[DownstreamMerge] 8-1-23

### PR DESCRIPTION
**Pull request by trozet**
Includes the fix for azure pdb-new disruption.

### CODE REVIEW

**Comment by trozet** [comment]
/remove-do-not-merge/work-in-progress

**Comment by trozet** [comment]
@dcbw you may need to force merge this. The stupid bot won't remove the do not merge.

**Comment by tssurya** [comment]
there is some install issues happening, let's retest and make sure the CI is green

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
/override ci/prow/e2e-metal-ipi-ovn-dualstack

```
{  3-08-02 15:18:26.884712559 +0000 UTC m=+3103.253017445
disruption/kube-api connection/new setting the intervals as done at time 2023-08-02 15:18:26.884744989 +0000 UTC m=+3103.253049876
ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new consumer sampler context is done at 2
ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new setting the intervals as done at time 2023-08-02 15:18:26.8847862 +0000 UTC m=+3103.253091087
disruption/cache-openshift-api connection/new setting the intervals as done at time 2023-08-02 15:18:26.88475798 +0000 UTC m=+3103.253062877
disruption/cache-openshift-api connection/reused setting the intervals as done at time 2023-08-02 15:18:26.88477965 +0000 UTC m=+3103.253084537
disruption/ci-cluster-network-liveness connection/reused consumer sampler context is done at 2
disruption/ci-cluster-network-liveness connection/reused setting the intervals as done at time 2023-08-02 15:18:26.884808221 +0000 UTC m=+3103.253113108
Collecting data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x649b253]

goroutine 566163 [running]:
github.com/openshift/origin/pkg/invariantlibrary/disruptionlibrary.(*Availability).CollectData.func2()
	github.com/openshift/origin/pkg/invariantlibrary/disruptionlibrary/disruption_invariant_adapter.go:67 +0x53
created by github.com/openshift/origin/pkg/invariantlibrary/disruptionlibrary.(*Availability).CollectData
	github.com/openshift/origin/pkg/invariantlibrary/disruptionlibrary/disruption_invariant_adapter.go:65 +0xe5
++ date +%s
+ echo 1690989536
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-08-02T15:18:56Z"}
error: failed to execute wrapped command: exit status 2
```

/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration
Just needs more time to roll things out

**Pull request merged**
