### PR TITLE
Bug 1942603: [release-4.7] Allow from router network policy support 

### PR DESCRIPTION
**Pull request by abhat**
This PR back-ports the allow-from-router feature for release-4.7.

### CODE REVIEW

**Comment by abhat** [comment]
This PR along with openshift/cluster-network-operator/pull/1087 needs to be cherry-picked together. CNO changes are necessary to enable the functionality.

**Comment by asood-rh** [comment]
/lgtm

Used the PR to build image registry.build01.ci.openshift.org/ci-ln-108qgx2/release:latest to create a OVNKubernetes cluster in vSphere to test allow from router traffic policy with both labels.

**Comment by sdodson** [comment]
Removed cheery-pick-approved for now as this appears to be a feature backport. Is this truly a new capability and if so who's approved the feature backport?

**Pull request merged**
