### PR TITLE
[DownstreamMerge] 04-13-22

### PR DESCRIPTION
**Pull request by squeed**
Merge in the latest changes from upstream as of 04-12

### CODE REVIEW

**Comment by squeed** [comment]
hmm, something weird with packages
```
 Package iproute-5.15.0-3.el8.x86_64 is already installed.
Error: 
 Problem: package iproute-tc-5.12.0-4.el8.x86_64 requires iproute(x86-64) = 5.12.0-4.el8, but none of the providers can be installed
  - cannot install both iproute-5.12.0-4.el8.x86_64 and iproute-5.15.0-3.el8.x86_64
  - cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) 
```

/test images
just to make sure it's not transient

**Comment by squeed** [comment]
There, allowing the downgrading of a few packages fixed the build.

**Comment by squeed** [comment]
At this point, I'm starting to be convinced that upstream has broken windows.
@dcbw / @JacobTanenbaum could you help me debug?

**Comment by squeed** [comment]
Most likely is https://github.com/ovn-org/ovn-kubernetes/pull/2877 being the culprit.

**Comment by squeed** [comment]
Looks like the windows e2e test was still trying just to spin up a server.
/retest-required
hmm.

**Comment by zshi-redhat** [comment]
@squeed we'd also need to backport this PR for hypershift: https://github.com/ovn-org/ovn-kubernetes/pull/2872

**Comment by zshi-redhat** [comment]
> @squeed we'd also need to backport this PR for hypershift: [ovn-org/ovn-kubernetes#2872](https://github.com/ovn-org/ovn-kubernetes/pull/2872)

Ignore this, it is always in downstream.

**Comment by trozet** [comment]
dualstack looks permafail

**Comment by trozet** [comment]
aws ovn upgrade failure is:


3/3420 Tests Failed. | expand_less
-- | --
: [sig-scheduling][Early] The openshift-etcd pods should be scheduled on different nodes [Suite:openshift/conformance/parallel] expand_more | : [sig-scheduling][Early] The openshift-etcd pods should be scheduled on different nodes [Suite:openshift/conformance/parallel] expand_more
: [sig-scheduling][Early] The openshift-etcd pods should be scheduled on different nodes [Suite:openshift/conformance/parallel] expand_more

not our problem

**Comment by trozet** [comment]
major upgrade failed because of:
: [sig-scheduling][Early] The HAProxy router pods should be scheduled on different nodes [Suite:openshift/conformance/parallel] 

also not our problem

**Pull request closed without merging**
