### PR TITLE
[WIP] Test completed pod fixes

### PR DESCRIPTION
**Pull request by trozet**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by deads2k** [comment]
/test all

(intentionally kicking everything to see if we get lucky/unlucky and hit a failure)

**Comment by deads2k** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1520017424294875136

appears to be the spot to look for 4.10 to 4.11 aws ovn upgrades with this fix.  If the fix works, we should see every run pass `[bz-networking] pod IPs should not be used by two pods at the same time`

**Comment by deads2k** [comment]
First round tested clean, can we prioritize a review to merge here?

**Comment by deads2k** [comment]
`[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the h2spec conformance tests [Suite:openshift/conformance/parallel/minimal] ` is also failing in master (we're testing a kube-apiserver-operator revert)

/override ci/prow/e2e-gcp-ovn

**Comment by trozet** [comment]
closing as this looks good and is now merged in upstream. Downstream merge here: https://github.com/openshift/ovn-kubernetes/pull/1064

**Pull request closed without merging**
