### PR TITLE
OCPBUGS-20238,OCPBUGS-20178: Downstream merge 2023-10-09

### PR DESCRIPTION
**Pull request by jcaamano**
@dcbw @tssurya @martinkennelly @jluhrsen @trozet @numansiddique @jordigilh @ricky-rav

### CODE REVIEW

**Comment by jcaamano** [comment]
/retitle OCPBUGS-20238, OCPBUGS-20178: Downstream merge 2023-10-09

**Comment by jcaamano** [comment]
/retitle OCPBUGS-20238,OCPBUGS-20178: Downstream merge 2023-10-09

**Comment by martinkennelly** [comment]
LGTM for my commits

**Comment by tssurya** [comment]
https://github.com/openshift/ovn-kubernetes/pull/1923 is present already where payloads are successful
this will need rebase once that merges.

**Comment by tssurya** [comment]
@jcaamano : perhaps you can approve 1923 because that is ready to go and then you can repush and reun all these red jobs here.

**Comment by ricky-rav** [comment]
Can we override e2e-metal-ipi-ovn-ipv6? It has been failing since September 29th and we overrode it yesterday:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6?buildId=1710124736123506688
https://github.com/openshift/ovn-kubernetes/pull/1923#issuecomment-1753153908

**Comment by flavio-fernandes** [comment]
> Can we override e2e-metal-ipi-ovn-ipv6? It has been failing since September 29th and we overrode it yesterday: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6?buildId=1710124736123506688 [#1923 (comment)](https://github.com/openshift/ovn-kubernetes/pull/1923#issuecomment-1753153908)

I think so!

@trozet @dcbw could you please:

/override ci/prow/e2e-metal-ipi-ovn-ipv6
metal v6 not coming up https://issues.redhat.com/browse/TRT-1284

**Pull request merged**
