### PR TITLE
use false in OnAdd in WithUpdateHandlingForObjReplace

### PR DESCRIPTION
**Pull request by jluhrsen**
this was caught in review for the PR to rebase to k8s 1.27 [0] but the PR was approved and merged before it could be updated.

[0] https://github.com/ovn-org/ovn-kubernetes/pull/3593/files/2c4701d8e2ac5326affe0fc39f97f8fefb71e437..3ce2d31065684edc4607be3b51b1754867c71ebf#top

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jcaamano** [comment]
/approve cancel

@jluhrsen Should we do this upstream first?

**Comment by jluhrsen** [comment]
> /approve cancel
> 
> @jluhrsen Should we do this upstream first?

Yes, my bad. I'll do that, and we'll get it here on a d/s merge

**Comment by jluhrsen** [comment]
> > /approve cancel
> > @jluhrsen Should we do this upstream first?
> 
> Yes, my bad. I'll do that, and we'll get it here on a d/s merge

https://github.com/ovn-org/ovn-kubernetes/pull/3776

**Pull request closed without merging**
