### PR TITLE
OCPBUGS-17867: CARRY: Removes restriction for ip scope universe on node ips

### PR DESCRIPTION
**Pull request by trozet**
We suspect this is what is causing hypershift to fail.

### CODE REVIEW

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn

I tried to look at the output artifacts of this test run but no must gathers gathered. The failure signature in build log is:
```
Running step e2e-aws-ovn-ipi-install-monitoringpvc. 
INFO[2023-08-17T11:58:34Z] pod pending for more than 30m0s: containers have not started in 39m20.120373735s: ci-scheduling-dns-wait, cp-entrypoint-wrapper, place-entrypoint, sidecar, test: 
* Container sidecar is not ready with reason PodInitializing
* Container test is not ready with reason PodInitializing
Found 2 events for Pod e2e-aws-ovn-ipi-install-monitoringpvc:
* 0001-01-01T00:00:00Z 0x : Successfully assigned ci-op-20tg98pl/e2e-aws-ovn-ipi-install-monitoringpvc to ip-10-29-193-134.ec2.internal
* 2023-08-17T11:56:57Z 9x kubelet: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded 
INFO[2023-08-17T11:58:34Z] Step e2e-aws-ovn-ipi-install-monitoringpvc failed after 0s. 
INFO[2023-08-17T11:58:34Z] Step phase pre failed after 26s.          
```

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Comment by jcaamano** [comment]
/title OCPBUGS-17867: CARRY: Removes restriction for ip scope universe on node ips

**Comment by jcaamano** [comment]
/retitle OCPBUGS-17867: CARRY: Removes restriction for ip scope universe on node ips

**Pull request merged**
