### PR TITLE
Bug 2011525: [DownstreamMerge] Downstream merge 08-02-2022

### PR DESCRIPTION
**Pull request by tssurya**
cc @trozet @dcbw 

We need to bump the Dockerfile golang version to 1.17 since we have vendored in new packages. Else image build fails with error:
```
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```

See https://go.dev/doc/go1.17#reflect . Hence there is one extra commit on top of the merge commit.

NOTE@approvers: Do not merge the PR that the bot will open to try and override my dockerfile change to sync with release repo until release folks update the images to 1.17.

### CODE REVIEW

**Comment by tssurya** [comment]
tagging @martinkennelly and @kyrtapz who have commits on this one per [instructions](https://docs.google.com/document/d/11Ax17QT0FB_OMV9_ifwWX3ppoLlc3OujjAikZP3J1v4/edit#) in case they want to move attached bz-es to relevant state.

**Comment by tssurya** [comment]
/hold
nicely red...

**Comment by tssurya** [comment]
maybe the images job failed because of https://github.com/ovn-org/ovn-kubernetes/pull/2810 ? Hard to figure out which go version the images job uses.

**Comment by dcbw** [comment]
gcp failed because of https://github.com/openshift/cluster-network-operator/pull/1302 which literally just merged...

/retest

**Pull request merged**
