### PR TITLE
[DownstreamMerge] 4 -28-22 completed pods

### PR DESCRIPTION
**Pull request by trozet**
based on @zshi-redhat merge with only the completed pod fixes

### CODE REVIEW

**Comment by tssurya** [comment]
It's happening in this merge request:
```
2022-04-30T17:11:44.674Z|00803|binding|INFO|Mismatch iface-id-ver for lport e2e-statefulset-9558_ss-0, expected 67ec61d5-1f1b-4c9e-98bd-b5d9e9803435, found 9874984a-ffd7-4ecf-bbf2-873062cddbb7

```

**Comment by zshi-redhat** [comment]
this one can be closed in favor of https://github.com/openshift/ovn-kubernetes/pull/1064 ?

**Pull request closed without merging**
