### PR TITLE
Bug 1880974: 9-21-2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Fixes for:

- ipv6
- host networking
- exgws
- egress firewall

### CODE REVIEW

**Comment by trozet** [comment]
/assign @danwinship 

@JacobTanenbaum FYI

**Comment by trozet** [comment]
kube api server failed in gcp with:
pods/openshift-kube-apiserver_kube-apiserver-ci-op-fthrih8d-99b10-ffhvz-master-2_kube-apiserver.log.gz:E0922 02:43:31.459388      18 runtime.go:76] Observed a panic: close of nil channel

**Comment by aojea** [comment]
/retest
last gcp error is related to iam policies
```
level=error msg="Error: Request \"Create IAM Members roles/compute.instanceAdmin serviceAccount:ci-op-fthrih8d-99b10-9gs8l-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \\\"project \\\\\\\"openshift-gce-devel-ci\\\\\\\"\\\"\" returned error: Error applying IAM policy for project \"openshift-gce-devel-ci\": Error setting IAM policy for project \"openshift-gce-devel-ci\": googleapi: Error 400: Deleted member 'ci-op-jiln9z-openshift-m-5gfp9@openshift-gce-devel-ci.iam.gserviceaccount.com?uid=115889882616816327004' is not deleted., badRequest"
```

**Comment by aojea** [comment]
The azure job looks really wrong though, 47 test failed, and a quick look show connections timeout as the reason

**Comment by aojea** [comment]
> kube api server failed in gcp with:
> pods/openshift-kube-apiserver_kube-apiserver-ci-op-fthrih8d-99b10-ffhvz-master-2_kube-apiserver.log.gz:E0922 02:43:31.459388 18 runtime.go:76] Observed a panic: close of nil channel

it has a bzilla open already https://bugzilla.redhat.com/show_bug.cgi?id=1881225

**Comment by trozet** [comment]
kubeapi  server panic again, we need to wait for:
https://github.com/openshift/kubernetes/pull/368

**Comment by trozet** [comment]
@danwinship  @dcbw verified on GCP cluster with this PR I can access host network service endpoints from another host in a different subnet:

```
[trozet@trozet Downloads]$ kubectl get svc
NAME         TYPE           CLUSTER-IP   EXTERNAL-IP                            PORT(S)   AGE
kubernetes   ClusterIP      172.30.0.1   <none>                                 443/TCP   126m
openshift    ExternalName   <none>       kubernetes.default.svc.cluster.local   <none>    118m

[trozet@trozet Downloads]$ kubectl get ep
NAME         ENDPOINTS                                   AGE
kubernetes   10.0.0.2:6443,10.0.0.4:6443,10.0.0.5:6443   132m

[trozet@trozet Downloads]$ kubectl get node -o wide
NAME                                       STATUS   ROLES    AGE    VERSION           INTERNAL-IP
ci-ln-gig3582-f76d1-7vh7k-master-0         Ready    master   127m   v1.19.0+7e8389f   10.0.0.5
ci-ln-gig3582-f76d1-7vh7k-master-1         Ready    master   127m   v1.19.0+7e8389f   10.0.0.2
ci-ln-gig3582-f76d1-7vh7k-master-2         Ready    master   127m   v1.19.0+7e8389f   10.0.0.4
ci-ln-gig3582-f76d1-7vh7k-worker-b-z4dwn   Ready    worker   114m   v1.19.0+7e8389f   10.0.32.2 

[trozet@trozet Downloads]$ oc debug node/ci-ln-gig3582-f76d1-7vh7k-worker-b-z4dwn 
Starting pod/ci-ln-gig3582-f76d1-7vh7k-worker-b-z4dwn-debug ...
To use host binaries, run `chroot /host`
Pod IP: 10.0.32.2
If you don't see a command prompt, try pressing enter.
sh-4.4# chroot /host
sh-4.4# curl -k https://172.30.0.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403

```

**Comment by dcbw** [comment]
vsphere has been replaced by vsphere-ovn and we don't care about its failure
/override ci/prow/vsphere

**Comment by dcbw** [comment]
Last test runs have failed 1-2 volume tests only with i/o timeouts to the gcp apiserver public IP.
/override ci/prow/e2e-gcp-ovn
/skip

**Pull request merged**
