### PR TITLE
OCPBUGS-31500,OCPBUGS-31501: EIP multi NIC IPv6 support and default route with next hop

### PR DESCRIPTION
**Pull request by martinkennelly**
/hold
/cc

### CODE REVIEW

**Comment by huiran0826** [comment]
[OCPBUGS-31500](https://issues.redhat.com//browse/OCPBUGS-31500) and [ OCPBUGS-31501](https://issues.redhat.com//browse/OCPBUGS-31501) were tested and looks good, still need to do some regression.

**Comment by martinkennelly** [comment]
@huiran0826 let me know when regression complete.

**Comment by martinkennelly** [comment]
Because theres a lot of changes here, i think id like regression suite tested before attempting to merge it.

**Comment by huiran0826** [comment]
@martinkennelly  Yeah, regression was done, and looks good.

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
