### PR TITLE
OCPBUGS-4503: [release-4.12] Dockerfile: bump OVN to 22.09.0-25

### PR DESCRIPTION
**Pull request by dcbw**
* Tue Dec 06 2022 Dumitru Ceara <dceara@redhat.com> - 22.09.0-24
- northd: Include VIP port in LB affinity learn flow matches. (#2150533)
[Upstream: cc037c7538d635e7d014e98935a83bc15140674f]

### CODE REVIEW

**Comment by tssurya** [comment]
/retitle OCPBUGS-4503: [release-4.12] Dockerfile: bump OVN to 22.09.0-25

**Comment by dcbw** [comment]
/test e2e-vsphere-windows

```
[36mINFO[0m[2022-12-07T13:11:32Z] Running step e2e-vsphere-windows-ipi-conf-vsphere-check. 
[36mINFO[0m[2022-12-07T13:11:42Z] Logs for container test in pod e2e-vsphere-windows-ipi-conf-vsphere-check: 
[36mINFO[0m[2022-12-07T13:11:42Z] 2022-12-07 13:11:38+00:00 - Creating govc.sh file...
2022-12-07 13:11:38+00:00 - Creating vsphere_context.sh file...
2022-12-07 13:11:38+00:00 - Find virtual machines attached to ci-segment-85 and destroy
govc: The object 'vim.VirtualMachine:vm-1005857' has already been deleted or has not been completely created
{"component":"entrypoint","error":"wrapped process failed: exit status 123","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-12-07T13:11:38Z"}
error: failed to execute wrapped command: exit status 123 
[36mINFO[0m[2022-12-07T13:11:42Z] Step e2e-vsphere-windows-ipi-conf-vsphere-check failed after 10s. 
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows

vsphere setup problems again

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

deprovision timed out due to AWS slowness; test was fine

**Comment by dcbw** [comment]
/retest

https://coreos.slack.com/archives/CBN38N3MW/p1670605525701599

**Comment by dcbw** [comment]
/retest

https://coreos.slack.com/archives/CBN38N3MW/p1670605525701599

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn
/override ci/prow/e2e-aws-ovn-local-gateway
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/e2e-metal-ipi-ovn-dualstack

https://coreos.slack.com/archives/CBN38N3MW/p1670605525701599

**Pull request merged**
