### PR TITLE
OCPBUGS-9825: LoadBalancer Templates Merge Downstream: 25th May 2023

### PR DESCRIPTION
**Pull request by tssurya**
Requirements for Merge:

- [x] CI should be fully green
- [x] LGTM needed from @dceara for the main changes
- [x] LGTM needed from @npinaeva to ensure I did justice to the conflicts around https://github.com/openshift/ovn-kubernetes/pull/1652
- [x] LGTM needed from @ricky-rav to ensure I did justice to the conflicts from https://github.com/openshift/ovn-kubernetes/pull/1622

@trozet or @jcaamano or @dcbw  for approve.

We also needed an OVN fix for LB templates with V6 family:
```
* Tue Mar 28 2023 Dumitru Ceara <dceara@redhat.com> - 23.03.0-14
- lb: Allow IPv6 template LBs to use explicit backends.
[Upstream: d01fdfdb2c97222cf326c8ab5579f670ded6e3cb]
```
I am bumping OVN rpms to `ovn23.03-23.03.0-49.el9fdp`. See https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2512984 for a CHANGE log.

```
brew list-tagged  rhaos-4.14-rhel-9-candidate | grep ovn
ovn23.03-23.03.0-49.el9fdp                rhaos-4.14-rhel-9-candidate  mmichels
ovn23.03-23.03.0-7.el9fdp                 rhaos-4.14-rhel-9-candidate  dceara
```

### CODE REVIEW

**Comment by dceara** [comment]
/lgtm

I compared this to the [WIP PR I had for testing component templates](https://github.com/openshift/ovn-kubernetes/pull/1636) and it looks good to me.  The only missing thing is https://github.com/ovn-org/ovn-kubernetes/pull/3523 but that shouldn't create issues because downstream OVN versions already support component templates (since 22.12).

Thanks!

**Comment by ricky-rav** [comment]
The build step fails because it can't find the OVN image: 
```
No match for argument: ovn23.03 = 23.03.0-49.el9fdp
No match for argument: ovn23.03-central = 23.03.0-49.el9fdp
No match for argument: ovn23.03-host = 23.03.0-49.el9fdp
Error: Unable to find a match: ovn23.03 = 23.03.0-49.el9fdp ovn23.03-central = 23.03.0-49.el9fdp ovn23.03-host = 23.03.0-49.el9fdp
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1683/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn/1662017850358894592

**Comment by tssurya** [comment]
> The build step fails because it can't find the OVN image:
> 
> ```
> No match for argument: ovn23.03 = 23.03.0-49.el9fdp
> No match for argument: ovn23.03-central = 23.03.0-49.el9fdp
> No match for argument: ovn23.03-host = 23.03.0-49.el9fdp
> Error: Unable to find a match: ovn23.03 = 23.03.0-49.el9fdp ovn23.03-central = 23.03.0-49.el9fdp ovn23.03-host = 23.03.0-49.el9fdp
> ```
> 
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1683/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn/1662017850358894592

right , its because RPMs haven't synced even after 5 hours of tagging :/

**Comment by ricky-rav** [comment]
All right, my next concern is... unit tests succeed after 2 minutes only: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1683/pull-ci-openshift-ovn-kubernetes-master-unit/1662017861620600832
`hack/test-go.sh` exits quickly:
```
RACE=1 hack/test-go.sh
stat /batching: directory not found
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1683/pull-ci-openshift-ovn-kubernetes-master-unit/1662017861620600832/artifacts/test/build-log.txt

**Comment by ricky-rav** [comment]
This **openshift-ovn-kubernetes-master-unit** CI job has actually been giving this behaviour since mid march. o_O
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-unit?buildId=1639190040091299840  
It shows it's been successful, but it hasn't run anything.

The last job I see that actually ran all unit tests as expected is from March 21st:
```
1638213514390671360 | #1596[WIP] [DNM] dummy commit to test aws upgrade (365673e) by trozet | Mar 21 17:18:38Mar 21 2023, 17:18:38 UTC+0100 | 14m37s | SUCCESS
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1596/pull-ci-openshift-ovn-kubernetes-master-unit/1638213514390671360

In particular, see the logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1596/pull-ci-openshift-ovn-kubernetes-master-unit/1638213514390671360/artifacts/test/build-log.txt

**Comment by tssurya** [comment]
> This **openshift-ovn-kubernetes-master-unit** CI job has actually been giving this behaviour since mid march. o_O https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-unit?buildId=1639190040091299840 It shows it's been successful, but it hasn't run anything.
> 
> The last job I see that actually ran all unit tests as expected is from March 21st:
> 
> ```
> 1638213514390671360 | #1596[WIP] [DNM] dummy commit to test aws upgrade (365673e) by trozet | Mar 21 17:18:38Mar 21 2023, 17:18:38 UTC+0100 | 14m37s | SUCCESS
> ```
> 
> https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1596/pull-ci-openshift-ovn-kubernetes-master-unit/1638213514390671360
> 
> In particular, see the logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1596/pull-ci-openshift-ovn-kubernetes-master-unit/1638213514390671360/artifacts/test/build-log.txt

ROFL! This is cracking me up so bad.. :) Well glad we caught this snafu and this explains why the OCPHACK tests "passed" for me on the PR and failed for you locally :D

**Comment by tssurya** [comment]
ok let's see how upgrades behaves in this run
TODO: Figure out why unit tests are not running and add https://github.com/ricky-rav/ovn-kubernetes-1/pull/1/commits/d556bde435423732f8547fc8b509986fc21af7b3 as well to the PR

**Comment by trozet** [comment]
I think we found the root cause of lgw upgrade failure: https://github.com/openshift/cluster-node-tuning-operator/pull/668

lets not block this from merging any longer

/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

**Pull request merged**
