### PR TITLE
Remove no-longer-used rhel9-specific dockerfiles

### PR DESCRIPTION
**Pull request by dcbw**
Now that the normal Dockerfiles use RHEL9, we no longer need the .rhel9 specific ones.

### CODE REVIEW

**Comment by dcbw** [comment]
/test e2e-vsphere-windows

```
error: failed to push image registry.apps.build01-us-west-2.vmc.ci.openshift.org/ci-op-3symjsbg/release:latest: unable to upload new layer (0): received unexpected HTTP status: 504 Gateway Time-out
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-04-12T16:42:35Z"} 
```

**Comment by flavio-fernandes** [comment]
/test e2e-gcp-ovn

```
level=info msg=Cluster operator insights SCAAvailable is False with Forbidden: Failed to pull SCA certs from https://api.openshift.com/api/accounts_mgmt/v1/certificates: OCM API https://api.openshift.com/api/accounts_mgmt/v1/certificates returned HTTP 403: {"code":"ACCT-MGMT-11","href":"/api/accounts_mgmt/v1/errors/11","id":"11","kind":"Error","operation_id":"17e11bbf-2d1e-4239-9b47-74293910a594","reason":"Account with ID 2DUeKzzTD9ngfsQ6YgkzdJn1jA4 denied access to perform create on Certificate with HTTP call POST /api/accounts_mgmt/v1/certificates"}
```

**Comment by dcbw** [comment]
/override ci/prow/4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade
/override ci/prow/4.14-upgrade-from-stable-4.13-local-gateway-e2e-aws-ovn-upgrade
/override ci/prow/e2e-vsphere-windows

Unrelated to this PR

**Pull request merged**
