### PR TITLE
SDN-3589: downstream merge 11-02-2022

### PR DESCRIPTION
**Pull request by msherif1234**
Merge conflicts:
go-controller/pkg/node/gateway_shared_intf.go
go-controller/pkg/node/node.go 
go-controller/pkg/ovn/acl.go 
go-controller/pkg/ovn/egressgw.go 
go-controller/pkg/ovn/egressgw_test.go 
go-controller/pkg/ovn/egressip.go 
go-controller/pkg/ovn/egressip_test.go 
go-controller/pkg/ovn/hybrid_test.go 
go-controller/pkg/ovn/master.go 
go-controller/pkg/ovn/master_test.go 
go-controller/pkg/ovn/namespace.go 
go-controller/pkg/ovn/ovn.go 
go-controller/pkg/ovn/pods.go 
go-controller/pkg/ovn/pods_test.go 
go-controller/pkg/ovn/policy.go 
go-controller/pkg/ovn/policy_test.go 
go-controller/pkg/util/pod_annotation.go 

delete
go-controller/pkg/ovn/obj_retry.go

### CODE REVIEW

**Comment by dcbw** [comment]
@msherif1234 this bit is mis-merged:

```
diff --git a/go-controller/pkg/ovn/policy.go b/go-controller/pkg/ovn/policy.go
index 89b5104beba70..7d66f1a785ef7 100644
--- a/go-controller/pkg/ovn/policy.go
+++ b/go-controller/pkg/ovn/policy.go
@@ -267,6 +267,11 @@ func (oc *Controller) updateStaleDefaultDenyACLNames(npType knet.PolicyType, gre
                                return err
                        }
                }
+               if aclList[0].Direction == nbdb.ACLDirectionToLport {
+                       aclT = lportIngress
+               } else {
+                       aclT = lportEgressAfterLB
+               }
                newACL := BuildACL(
                        newName, // this is the only thing we need to change, keep the rest same
                        aclList[0].Priority,
```

And doesn't actually need to be there downstream. Upstream moved the same code a couple lines above, so this bit is now redundant.

**Comment by dcbw** [comment]
Also this bit has extra whitespace that is not upstream:

```
diff --git a/go-controller/cmd/ovnkube-trace/ovnkube-trace.go b/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
index 6cda17ae8f5bd..efaefbdba41f7 100644
--- a/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
+++ b/go-controller/cmd/ovnkube-trace/ovnkube-trace.go
@@ -464,6 +464,7 @@ func getPodInfo(coreclient *corev1client.CoreV1Client, restconfig *rest.Config,
        // Find rtos MAC (this is the pod's first hop router).
        lspCmd := "ovn-sbctl " + cmd + " --bare --no-heading --column=mac list Port_Binding " + types.RouterToSwitchPrefix + podInfo.NodeName
        ipOutput, ipError, err := execInPod(coreclient, restconfig, ovnNamespace, podInfo.OvnKubePodName, "ovnkube-node", lspCmd, "")
+
        if err != nil {
                return nil, fmt.Errorf("execInPod() failed. err: %s, stderr: %s, stdout: %s, podInfo: %v", err, ipError, ipOutput, podInfo)
        }
```

**Comment by dcbw** [comment]
Also, I wonder should these tests go upstream?

```
diff --git a/go-controller/pkg/ovn/egressip_test.go b/go-controller/pkg/ovn/egressip_test.go
index 96c3ce0e198cf..6f720127b879d 100644
--- a/go-controller/pkg/ovn/egressip_test.go
+++ b/go-controller/pkg/ovn/egressip_test.go
@@ -1413,6 +1413,351 @@ var _ = ginkgo.Describe("OVN master EgressIP Operations", func() {
                })
        })
 
+       ginkgo.Context("On node DELETE", func() {
+
+               ginkgo.It("should re-assign EgressIPs and perform proper OVN transactions when node's gateway objects are already deleted", func() {
+                       app.Action = func(ctx *cli.Context) error {

...

```

**Comment by dcbw** [comment]
FTR I added upstream as a new git remote called "ovnorg", added your git fork as a remote, fetched both, and did this:

`git diff ovnorg/master..mohamed/merge_11-3-22 go-controller`

**Comment by msherif1234** [comment]
> ginkgo.Context("On node DELETE", func()

created https://github.com/openshift/ovn-kubernetes/pull/1358 to remove dup delete test

**Pull request merged**
