### PR TITLE
Bug 2111534: Downstream Merge: 27-07-2022

### PR DESCRIPTION
**Pull request by tssurya**
commit owners: /cc @andreaskaris @dceara @maiqueb @npinaeva @dcbw 
@trozet for approve

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Looks good on my end .... (only looked at the commits I've added).

**Comment by jrvaldes** [comment]
LGTM for https://github.com/openshift/ovn-kubernetes/pull/1214/commits/3d098924fca5020805c08546f78cfd7d29304129

**Comment by dcbw** [comment]
Unit tests failing due to retry deadlock that Nadia is addressing in https://github.com/ovn-org/ovn-kubernetes/pull/3097

**Comment by tssurya** [comment]
> Unit tests failing due to retry deadlock that Nadia is addressing in [ovn-org/ovn-kubernetes#3097](https://github.com/ovn-org/ovn-kubernetes/pull/3097)

yah its interesting how we never saw this happening and now its so common :D

**Comment by dcbw** [comment]
/override e2e-metal-ipi-ovn-dualstack
/override e2e-metal-ipi-ovn-ipv6

https://coreos.slack.com/archives/CFP6ST0A3/p1659541669816749?thread_ts=1659533751.469359&cid=CFP6ST0A3

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
/override ci/prow/e2e-metal-ipi-ovn-ipv6

https://coreos.slack.com/archives/CFP6ST0A3/p1659541669816749?thread_ts=1659533751.469359&cid=CFP6ST0A3

**Pull request merged**
