### PR TITLE
[release-4.12] OCPBUGS-22091: Bump OVN to 23.06.1-39.el8fdp

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
yikes we need to tag the rpm

**Comment by dcbw** [comment]
@tssurya can you bump instead to `ovn23.06-23.06.1-39.el8fdp` ?

**Comment by tssurya** [comment]
Oh ack! Yes let me do that... is that already tagged dcbw?

**Comment by trozet** [comment]
/hold

This PR would bump OVN version to one that is higher than whats in 4.13. We need to make sure 4.13 and newer branches are at least even with older branches. older branches should not use newer versions than newer branches.

**Comment by trozet** [comment]
#1966 has merged

/hold cancel

/lgtm
/label backport-risk-assessed

**Comment by dcbw** [comment]
dual-stack appears to be permafail right now; multiple PRs show image-registry pods to come up during cluster install
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-release-4.12-e2e-metal-ipi-ovn-dualstack

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
