### PR TITLE
[release-4.15] OCPBUGS-18895,OCPBUGS-14549,OCPBUGS-18402 [DownstreamMerge] 9-11-23

### PR DESCRIPTION
**Pull request by flavio-fernandes**
Clean merge!

@trozet @tssurya @jcaamano @JacobTanenbaum @npinaeva @jordigilh @pperiyasamy @martinkennelly @kyrtapz @zeeke @qinqon @dcbw @pliurh  FYI

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
Unit test flake?
```
 Summarizing 1 Failure:
[Fail] OVN External Gateway policy when updating a policy [It] validates that removing a duplicated static hop IP from an overlapping policy static hop will keep the static IP in the route policy 
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go:188
Ran 36 of 36 Specs in 31.005 seconds
FAIL! -- 35 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestApbroute (31.10s)
FAIL
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute	31.293s
FAIL
make: *** [test] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-09-11T16:16:34Z"} 
INFO[2023-09-11T16:16:38Z] Ran for 21m39s                               
ERRO[2023-09-11T16:16:38Z] Some steps failed:                           
ERRO[2023-09-11T16:16:38Z] 
  * could not run steps: step unit failed: test "unit" failed: could not watch pod: the pod ci-op-4qypcx67/unit failed after 18m57s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 2, reason Error
---
tric_reply":"true"},"OutputPort":"rtoe-GR_node","Policy":"src-ip","RouteTable":""}
2023/09/11 16:16:34 cache: "caller"={"file":"cache.go","line":1196} "level"=5 "msg"="updating model" "table"="Logical_Router" "uuid"="7d7be933-4a89-4b54-aa37-0443249988dc" "old"={"UUID":"7d7be933-4a89-4b54-aa37-0443249988dc","Copp":null,"Enabled":null,"ExternalIDs":{},"LoadBalancer":[],"LoadBalancerGroup":[],"Name":"GR_node","Nat":[],"Options":{},"Policies":[],"Ports":[],"StaticRoutes":[]} "new"={"UUID":"7d7be933-4a89-4b54-aa37-0443249988dc","Copp":null,"Enabled":null,"ExternalIDs":{},"LoadBalancer":[],"LoadBalancerGroup":[],"Name":"GR_node","Nat":[],"Options":{},"Policies":[],"Ports":[],"StaticRoutes":["120ac3ae-f776-4840-8ffe-e701d2193326"]}
•
JUnit path was configured: /go/src/github.com/openshift/ovn-kubernetes/go-controller/_artifacts/junit-pkg_ovn_controller_apbroute.xml
JUnit report was created: /go/src/github.com/openshift/ovn-kubernetes/go-controller/_artifacts/junit-pkg_ovn_controller_apbroute.xml
Summarizing 1 Failure:
[Fail] OVN External Gateway policy when updating a policy [It] validates that removing a duplicated static hop IP from an overlapping policy static hop will keep the static IP in the route policy 
/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute/external_controller_policy_test.go:188
Ran 36 of 36 Specs in 31.005 seconds
FAIL! -- 35 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestApbroute (31.10s)
FAIL
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/controller/apbroute	31.293s
FAIL
make: *** [test] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-09-11T16:16:34Z"}
--- 
INFO[2023-09-11T16:16:38Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:running_pod' 
```

**Comment by SalDaniele** [comment]
Hello,

Our team has an internal CI that is building images from ovn-org and patching an OCP cluster to test smartNIC / hwol connectivity. We are seeing some errors introduced within the last couple days of commits (sometime between 57c4c06fa01deca95155f0b062627d34dd9a48fe and c60963123d28075288a8c23d2796c2df89f54601).

A number of the ovn-kube nodes are getting stuck in a crash loop backoff when applying the upstream ovn-kubernetes image. Is it possible to hold the Downstream Merge while we look into these failures?

Error from ovnkube pod:

`I0911 20:07:29.553359  441911 kube.go:121] Setting annotations map[k8s.ovn.org/gateway-mtu-support:false k8s.ovn.org/l3-gateway-config:{"default":{"mode":"shared","interface-id":"br-ex_worker-225","mac-address":"b8:3f:d2:a4:56:e2","ip-addresses":["192.168.122.246/16"],"ip-address":"192.168.122.246/16","next-hops":["192.168.122.1"],"next-hop":"192.168.122.1","node-port-enable":"true","vlan-id":"0"}} k8s.ovn.org/node-chassis-id:166f2ee9-f275-4786-89dd-48b49d424c26 k8s.ovn.org/node-mgmt-port-mac-address:62:09:fc:c5:b7:a1 k8s.ovn.org/node-primary-ifaddr:{"ipv4":"192.168.122.246/16"} k8s.ovn.org/zone-name:global] on node worker-225
E0911 20:07:29.554339  441911 kube.go:130] Error in setting annotation on node worker-225: nodes "worker-225" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot patch resource "nodes/status" in API group "" at the cluster scope
I0911 20:07:29.554406  441911 reflector.go:293] Stopping reflector *v1.EgressIP (0s) from github.com/openshift/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/informers/externalversions/factory.go:131
I0911 20:07:29.554452  441911 metrics.go:506] Stopping metrics server 127.0.0.1:29103
I0911 20:07:29.554476  441911 metrics.go:502] Metrics server has stopped serving at address "127.0.0.1:29103"
I0911 20:07:29.554479  441911 reflector.go:293] Stopping reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:150
F0911 20:07:29.554499  441911 ovnkube.go:136] failed to start node network manager: failed to start default node network controller: failed to set node worker-225 annotations: nodes "worker-225" is forbidden: User "system:serviceaccount:openshift-ovn-kubernetes:ovn-kubernetes-node" cannot patch resource "nodes/status"
in API group "" at the cluster scope
`

**Comment by flavio-fernandes** [comment]
> Hello,
> 
> Our team has an internal CI that is building images from ovn-org and patching an OCP cluster to test smartNIC / hwol connectivity. We are seeing some errors introduced upstream within the last couple days of commits (sometime between [57c4c06](https://github.com/openshift/ovn-kubernetes/commit/57c4c06fa01deca95155f0b062627d34dd9a48fe) and [c609631](https://github.com/openshift/ovn-kubernetes/commit/c60963123d28075288a8c23d2796c2df89f54601)).
> 
> A number of the ovn-kube nodes are getting stuck in a crash loop backoff when applying the upstream ovn-kubernetes image. Is it possible to hold the Downstream Merge while we look into these failures?
> 

Yes, Sal. 
Do you have a Jira to track the issue you described? It will be good to mention it here, so we monitor that and potentially pull in the fixes into this pr.

**Comment by SalDaniele** [comment]
> 

Updating to a more recent OCP nightly / updating the CNO seems to fix this error, merge is passing all our tests now.

**Comment by pperiyasamy** [comment]
/retitle [release-4.15] OCPBUGS-18895,OCPBUGS-14549,OCPBUGS-18402 [DownstreamMerge] 9-11-23

**Comment by trozet** [comment]
failures were not aggregator jobs, and they already passed on pre-submit CI

/lgtm

**Pull request merged**
