### PR TITLE
Upstream merge 2019-11-08 + hybrid overlay update + gateway/SDN-410 update

### PR DESCRIPTION
**Pull request by dcbw**
Verified our downstream only contains know deviations by doing a test-merge of upstream master + my hybrid overlay + mcambria's SDN-410 branches, then diffing that against this PR.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1769962

@squeed @danwinship

### CODE REVIEW

**Comment by danwinship** [comment]
This is not *just* a merge from upstream; diff it against our own master. You're pulling in an updated version of the hybrid overlay code as well.

**Comment by dcbw** [comment]
> This is not _just_ a merge from upstream; diff it against our own master. You're pulling in an updated version of the hybrid overlay code as well.

@danwinship yeah, it's pulling in updated hybrid overlay (to get Jocelyns fixes) and gateway code (for https://bugzilla.redhat.com/show_bug.cgi?id=1769962). All I was looking at was to make sure that our downstream had only expected differences (the AWS metadata service thing, dockerfile, iptables redirection) from upstream + those two PRs.

**Comment by dcbw** [comment]
```
E1109 05:52:57.673238       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/map_faststr.go:204
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:257
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:368
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:387
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:202
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:236
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:153
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:54
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:151
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:202
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:552
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 65 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14024c0, 0x17bb760)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*HAMasterController).updateOvnDbEndpoints(0xc000446cd0, 0xc000b6e780, 0x0, 0x135fa01, 0x256af20)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:257 +0x24e
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*HAMasterController).WatchOvnDbEndpoints.func1(0xc000b6e780)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:368 +0xe2
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*HAMasterController).WatchOvnDbEndpoints.func3(0x1586060, 0xc00003af00, 0x1586060, 0xc000b6e780)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:387 +0x40
github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:202
github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate(0xc00043e980, 0x1804020, 0xc000997a00, 0x1586060, 0xc00003af00, 0x1586060, 0xc000b6e780)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:236 +0x120
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).newFederatedHandler.func2.1(0xc0003544b0)
	/go-controller/_output/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:153 +0x15a
```

**Comment by danwinship** [comment]
> All I was looking at was to make sure that our downstream had only expected differences (the AWS metadata service thing, dockerfile, iptables redirection) from upstream + those two PRs.

OK, but (1) the PR title suggests this is *just* a merge from upstream, which it isn't, and (2) it's harder for anyone else to verify that it's correct when there are changes coming from multiple directions at once.

**Comment by dcbw** [comment]
Fix for test failure: https://github.com/ovn-org/ovn-kubernetes/pull/916 (and pulled downstream)

**Comment by dcbw** [comment]
@danwinship @squeed seems good now

**Comment by danwinship** [comment]
ok...
/lgtm

**Pull request merged**
