### PR TITLE
Bug 2044303: Fix update of CloudPrivateIPConfig

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
/cc

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/retitle Bug 2044303: Fix update of CloudPrivateIPConfig
/assign @trozet

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
permafail

**Pull request merged**
