### PR TITLE
Bug 1903408: Merge externalTrafficPolicy ONLY

### PR DESCRIPTION
**Pull request by astoycos**
This PR pulls in the code needed to land the externalTrafficPolicy feature. It adds a commit to deal with the fact that the smartnicv2 code has not made it downstream yet. That commit should be dropped before the next large merge of Upstream OVN-K into downstream.

### CODE REVIEW

**Comment by astoycos** [comment]
CI is foobar

**Comment by astoycos** [comment]
GCP upgrade is unstable (I ran `ci/prow/4.9-upgrade-from-stable-4.8-e2e-aws-ovn-upgrade`) just to ensure things were working 

`ci/prow/e2e-metal-ipi-ovn-dualstack` and `ci/prow/okd-e2e-gcp-ovn` are permafailing so oherwise I'd say this is ready to be merged ASAP in 4.10

**Review by flavio-fernandes — COMMENTED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
```
[It] should not have pod creation failures during install [Suite:openshift/conformance/parallel]
  github.com/openshift/origin/test/extended/authorization/scc.go:21
[AfterEach] [sig-auth][Feature:SCC][Early]
  github.com/openshift/origin/test/extended/util/client.go:140
[AfterEach] [sig-auth][Feature:SCC][Early]
  github.com/openshift/origin/test/extended/util/client.go:141
fail [github.com/openshift/origin/test/extended/authorization/scc.go:73]: 10 pods failed before test on SCC errors
Error creating: pods "console-operator-5d5d8b4f8f-" is forbidden: unable to validate against any security context constraint: [provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount] for ReplicaSet.apps/v1/console-operator-5d5d8b4f8f -n openshift-console-operator happened 13 times
Error creating: pods "console-operator-5d5d8b4f8f-" is forbidden: unable to validate against any security context constraint: [provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount] for ReplicaSet.apps/v1/console-operator-5d5d8b4f8f -n openshift-console-operator happened 12 times
Error creating: pods "console-operator-5d5d8b4f8f-" is forbidden: unable to validate against any security context constraint: [provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount] for ReplicaSet.apps/v1/console-operator-5d5d8b4f8f -n openshift-console-operator happened 14 times
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn
failed in completing the transaction because go-ovn doesn't follow the leader DB
```
I0909 23:21:54.431180       1 pods.go:251] [openshift-network-diagnostics/network-check-target-grm28] addLogicalPort took 218.12861ms
E0909 23:21:54.431233       1 ovn.go:556] error while creating logical port openshift-network-diagnostics_network-check-target-grm28 error: Reconnecting...Transaction Failed due to an error: constraint violation details: Transaction causes multiple rows in "Logical_Switch_Port" table to have identical values (openshift-network-diagnostics_network-check-target-grm28) for index on column "name".  First row, with UUID f79abac9-cb40-48b6-a0f8-0690d1174bcc, existed in the database before this transaction, which modified some of the row's columns but not any columns in this index.  Second row, with UUID 900e25ab-4989-4cc1-8e98-4b9121ff5e2e, was inserted by this transaction. in committing transaction
I0909 23:21:54.431284       1 ovn.go:465] [842ce327-c938-40c6-a8e5-7f392f694439/openshift-network-diagnostics/network-check-target-grm28] setup retry failed; will try again later
I0909 23:21:54.431944       1 event.go:282] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-network-diagnostics", Name:"network-check-target-grm28", UID:"842ce327-c938-40c6-a8e5-7f392f694439", APIVersion:"v1", ResourceVersion:"18560", FieldPath:""}): type: 'Warning' reason: 'ErrorAddingLogicalPort' error while creating logical port openshift-network-diagnostics_network-check-target-grm28 error: Reconnecting...Transaction Failed due to an error: constraint violation details: Transaction causes multiple rows in "Logical_Switch_Port" table to have identical values (openshift-network-diagnostics_network-check-target-grm28) for index on column "name".  First row, with UUID f79abac9-cb40-48b6-a0f8-0690d1174bcc, existed in the database before this transaction, which modified some of the row's columns but not any columns in this index.  Second row, with UUID 900e25ab-4989-4cc1-8e98-4b9121ff5e2e, was inserted by this transaction. in committing transaction
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-local-gateway
```
fail [github.com/openshift/origin/test/extended/authorization/scc.go:73]: 8 pods failed before test on SCC errors
Error creating: pods "cloud-credential-operator-b4df84f5f-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/cloud-credential-operator-b4df84f5f -n openshift-cloud-credential-operator happened 13 times
Error creating: pods "cluster-image-registry-operator-557ccdff74-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/cluster-image-registry-operator-557ccdff74 -n openshift-image-registry happened 14 times
Error creating: pods "ingress-operator-b884bd6fb-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/ingress-operator-b884bd6fb -n openshift-ingress-operator happened 13 times
Error creating: pods "insights-operator-79dddf8948-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/insights-operator-79dddf8948 -n openshift-insights happened 14 times
Error creating: pods "cluster-autoscaler-operator-7b779d647f-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/cluster-autoscaler-operator-7b779d647f -n openshift-machine-api happened 14 times
Error creating: pods "machine-api-operator-6ddb978445-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/machine-api-operator-6ddb978445 -n openshift-machine-api happened 14 times
Error creating: pods "marketplace-operator-65c8c5c6f4-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/marketplace-operator-65c8c5c6f4 -n openshift-marketplace happened 13 times
Error creating: pods "cluster-monitoring-operator-7969c4bbfc-" is forbidden: unable to validate against any security context constraint: provider "privileged": Forbidden: not usable by user or serviceaccount for ReplicaSet.apps/v1/cluster-monitoring-operator-7969c4bbfc -n openshift-monitoring happened 14 times
```

**Pull request merged**
