### PR TITLE
OCPBUGS-10796: [release-4.13] Egress firewall fix retry

### PR DESCRIPTION
**Pull request by npinaeva**
backport of https://github.com/ovn-org/ovn-kubernetes/pull/3449 (clean!)
downstream merge https://github.com/openshift/ovn-kubernetes/pull/1574

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-dualstack 

image mirror issue, not networking

**Pull request merged**
