### PR TITLE
OCPBUGS-17910: Emit node events only when retry failure

### PR DESCRIPTION
**Pull request by martinkennelly**
/cc
/hold

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest
Known issue with gateway migration jobs. Investigating if its getting fixed by someone on slack.

**Comment by martinkennelly** [comment]
@trozet

**Comment by jcaamano** [comment]
These are failing because of a timing issue we are already investigating

/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Comment by jcaamano** [comment]
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration

**Pull request merged**
