### PR TITLE
Bug 1806666: merge master to release-4.4

### PR DESCRIPTION
**Pull request by danwinship**
I literally just did "`git merge master`"

/cc @dcbw @pecameron @trozet

### CODE REVIEW

**Comment by danwinship** [comment]
Pay no attention to the "666" in the bug number

**Comment by danwinship** [comment]
I'm not sure why the CI bot is failing to run the normal tests here (it's not broken in general, I just tried pushing another PR). But anyway, you can verify with "git diff" that this makes release-4.4 identical to master, so the tree has already been CI'ed there.

**Comment by trozet** [comment]
I think you are missing some fixes from upstream. 

Summarizing 6 Failures:

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should enforce multiple ingress policies with ingress allow-all policy taking precedence [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should enforce policies to check ingress and egress policies can be controlled independently based on PodSelector [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should enforce policy based on NamespaceSelector with MatchExpressions[Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should stop enforcing policies after they are deleted [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should support allow-all policy [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1421

**Pull request merged**
