### PR TITLE
BZ 1927845: Bump OVS version to 2.13.0-79.5.el8fdp

### PR DESCRIPTION
**Pull request by astoycos**
Bump OVS version for OVN-Kubernetes

### CODE REVIEW

**Review by vpickard — COMMENTED** [review]
Can you summarize/highlight what changes are included with this OVS version bump that are meaningful to OVN-kubernetes?

**Comment by alexanderConstantinescu** [comment]
> @astoycos: you cannot LGTM your own PR.

Nice try!

/lgtm

**Pull request merged**
