### PR TITLE
OCPBUGS-34331: [DownstreamMerge] 23 May 2024

### PR DESCRIPTION
**Pull request by npinaeva**

### CODE REVIEW

**Comment by abhat** [comment]
/override ci/prow/e2e-gcp-ovn
https://issues.redhat.com/browse/TRT-1680

**Comment by npinaeva** [comment]
azure job summary: 2 bootstrap failures, 3 " In-tree Volumes [Driver: azure-disk] " related failures, 1 "[sig-node] [Feature:PodLifecycleSleepAction] when create a pod with lifecycle hook using sleep action valid prestop hook using sleep action"
potentially related issue: https://issues.redhat.com/browse/TRT-1679

**Comment by npinaeva** [comment]
Seems like PodLifecycleSleepAction is also struggling based on https://github.com/openshift/origin/pull/28832/files#diff-12a74ce9e0db717194cbb786d90ccf0abbe8e22828afda104f70f22e5cabf112R622

**Comment by abhat** [comment]
/override e2e-azure-ovn-upgrade
https://issues.redhat.com/browse/TRT-1679

**Comment by abhat** [comment]
/override ci/prow/e2e-azure-ovn-upgrade 
https://issues.redhat.com/browse/TRT-1679

**Pull request merged**
