### PR TITLE
OCPBUGS-2175:  Allocate Hybrid Overlay IP on node updates too

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by aravindhp** [comment]
Upstream PR: https://github.com/ovn-org/ovn-kubernetes/pull/3229

**Comment by JacobTanenbaum** [comment]
failures don't look like they have to do with my changes 

/retest

**Pull request merged**
