### PR TITLE
Bug 1960757: CARRY: block MCS for shared-gateway mode.

### PR DESCRIPTION
**Pull request by squeed**
This activates the same MCS-blocking rules as for local gateway.

### CODE REVIEW

**Comment by squeed** [comment]
CI is green.
/cc @alexanderConstantinescu can I get a review on this?

**Comment by alexanderConstantinescu** [comment]
> CI is green.
> /cc @alexanderConstantinescu can I get a review on this?

I had a look at this last week but forgot to:

/lgtm

Did you by any chance confirm that no node/hostNetworked' pod could access the MCS ports? Or do we have a dedicated test for that in CI?

**Comment by squeed** [comment]
> Did you by any chance confirm that no node/hostNetworked' pod could access the MCS ports? Or do we have a dedicated test for that in CI?

Hah, I thought I did, but it turns out I never logged in to the cluster-bot cluster and checked, oops. So,
/hold
until I do some manual testing. 

And no, we don't have a CI test for this.

**Comment by squeed** [comment]
Spun up a test a cluster and ensured this still works
/hold cancel

**Comment by squeed** [comment]
The windows test seems like an infrastructure issue:

```error obtaining aws interface object: unable to get latest Windows AMI: found zero images matching given filter```

**Comment by squeed** [comment]
dual-stack is never going to pass...
```
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: May 31 07:26:58.375: Some cluster operators are not ready: kube-apiserver (Upgradeable=False FeatureGates_RestrictedFeatureGates_IPv6DualStackNoUpgrade: FeatureGatesUpgradeable: "IPv6DualStackNoUpgrade" does not allow updates)
```

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
