### PR TITLE
[WIP Do not merge] Extra logging for testing CI job

### PR DESCRIPTION
**Pull request by tedyu**
**- What this PR does and why is it needed**
In order to find cause for kubelet livelock issue (which was observed in ovn CI jobs), I create this PR so that I can have more clue in CI job artifacts.

**- Special notes for reviewers**
This patch is used to trigger ovn tests.
From my interaction with cluster-bot, with openshift/origin PR alone, ovn tests are not run.
ovn tests were where Casey reported livelock scenario.

**- Description for the changelog**
One line change in go-controller/pkg/node/gateway_localnet.go is introduced for debugging livelock problem in ovn tests.

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
@danwinship

**Comment by tedyu** [comment]
It seems some test job is not affected by the docker build issue:
e2e-windows-hybrid-network

**Comment by danwinship** [comment]
> In order to find cause for kubelet livelock issue (which was observed in ovn CI jobs),

where?

**Comment by tedyu** [comment]
Original issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1839813

I checked a few failed ovn related test runs but haven't found reproduction of the livelock.

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?job=*master-e2e*ovn*&state=failure

**Comment by rphillips** [comment]
There is a log line [here](https://github.com/openshift/ovn-kubernetes/blob/abba14f4bdcf6d9de97f83ccd6accf8838ec4dd6/go-controller/pkg/node/gateway_localnet.go#L321) at level (5) to help in debugging the `delIptRules` function.

Additionally, the klog.Infof() should have parameters which it does not. Generally, I do not think this patch is needed.

**Comment by tedyu** [comment]
This patch is used to trigger ovn tests.
From my interaction with cluster-bot, with openshift/origin PR, ovn tests are not run.
ovn tests were where Casey reported livelock scenario.

Once livelock scenario is root caused, this PR would be closed.

**Pull request closed without merging**
