### PR TITLE
SDN-4919,OCPBUGS-39406: Downstream Merge 28th August

### PR DESCRIPTION
**Pull request by tssurya**
backport of https://github.com/openshift/ovn-kubernetes/pull/2276

### CODE REVIEW

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-techpreview 

infra

**Comment by martinkennelly** [comment]
/retitle SDN-4919,OCPBUGS-39406: Downstream Merge 28th August

**Comment by martinkennelly** [comment]
/test e2e-azure-ovn-upgrade 

Doesnt look related

**Comment by martinkennelly** [comment]
CI looks ok, just waiting on upgrade.

**Comment by tssurya** [comment]
/hold cancel
here things look ok: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2283/pull-ci-openshift-ovn-kubernetes-release-4.17-4.17-upgrade-from-stable-4.16-e2e-gcp-ovn-rt-upgrade/1830625843420860416

**Pull request merged**
