### PR TITLE
Bug 1968569: UPSTREAM: NetworkPolicy: bulk-add pods to new policies (or on restart)

### PR DESCRIPTION
**Pull request by squeed**
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2249

### CODE REVIEW

**Comment by squeed** [comment]
CI is looking pretty good, though it, uh, doesn't test this feature.

**Comment by squeed** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
it's broken

/test e2e-metal-ipi-ovn-ipv6
flake

/test e2e-aws-ovn-windows
not sure what happened, no test results

**Comment by dcbw** [comment]
@squeed is this supposed to be for 4.8?

**Comment by squeed** [comment]
@dcbw good catch, yeah, I'll re-file.

**Pull request closed without merging**
