### PR TITLE
Dockerfile: bump OVN to 20.09.0-21

### PR DESCRIPTION
**Pull request by dcbw**
Only change is a fix to LB VIP selection in ovn-northd that was
broken in -14 and later.

@trozet

### CODE REVIEW

**Comment by dcbw** [comment]
/hold
need to wait a bit for the mirrors to update with -21

**Comment by alexanderConstantinescu** [comment]
Well, now that 20.09.0-21.el8fdn has been tagged with `rhaos-4.7-rhel-8-candidate` our builds are broken, because we still reference 20.09.0-20.el8fdn.

so, 

either we un-tag  20.09.0-21.el8fdn

or

/lgtm 

and get this in

**Comment by dcbw** [comment]
/retest
openstack 
```
level=error
level=error msg=Error: Error waiting for instance (e360aa3e-2fe5-4a0a-8fff-8b9d5250e9ed) to become ready: The server timed out waiting for the request
level=error
level=error msg=  on ../tmp/openshift-install-195106665/masters/main.tf line 43, in resource "openstack_compute_instance_v2" "master_conf":
level=error msg=  43: resource "openstack_compute_instance_v2" "master_conf" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-dualstack
packet.net was performing maintenance

**Comment by trozet** [comment]
as @alexanderConstantinescu  mentioned CI is broken until this gets in and almost seems to be passing so...

/hold cancel

/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
packet.net is still having problems and this PR is blocking other CI

**Pull request merged**
