### PR TITLE
Bug 2040540: Fix String formatting error

### PR DESCRIPTION
**Pull request by zshi-redhat**
Corrects formatting error in ovsargs.

Fixes: #2726

Signed-off-by: Hareesh Puthalath <hareeshp@nvidia.com>
(cherry picked from commit 2dada25771c6b235651933494449e33abe6ea8d8)

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Looks fine; good catch.

**Comment by andreaskaris** [comment]
FYI, I think that ci/prow/e2e-metal-ipi-ovn-dualstack test  is perma failing: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack
Check the latest convo in team-sdn, you might just request an override there.

**Comment by jluhrsen** [comment]
> FYI, I think that ci/prow/e2e-metal-ipi-ovn-dualstack test is perma failing: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack Check the latest convo in team-sdn, you might just request an override there.

yes it is permafailing. it's easier to see with the periodic job in testgrid:
 https://testgrid.k8s.io/redhat-openshift-ocp-release-4.10-informing#periodic-ci-openshift-release-master-nightly-4.10-e2e-metal-ipi-ovn-dualstack
 
 maybe we should make it an optional job?

**Comment by zshi-redhat** [comment]
@trozet @jluhrsen Do we need another override for `ci/prow/e2e-metal-ipi-ovn-dualstack` ? Looks like it is consistently failing.

**Comment by jluhrsen** [comment]
> @trozet @jluhrsen Do we need another override for `ci/prow/e2e-metal-ipi-ovn-dualstack` ? Looks like it is consistently failing.

yeah, and I don't see it passing any time soon. I see that @trozet did the override once. maybe he needs to do it again?

**Comment by zshi-redhat** [comment]
> > @trozet @jluhrsen Do we need another override for `ci/prow/e2e-metal-ipi-ovn-dualstack` ? Looks like it is consistently failing.
> 
> yeah, and I don't see it passing any time soon. I see that @trozet did the override once. maybe he needs to do it again?

@trozet Could you override the `ci/prow/e2e-metal-ipi-ovn-dualstack` again?

**Comment by abhat** [comment]
Dualstack job is perma-failing. Overriding it.

**Pull request merged**
