### PR TITLE
[release-4.13] OCPBUGS-17120: Bump OVN to 23.06-23.06.0-51

### PR DESCRIPTION
**Pull request by jcaamano**
Includes fix for
https://issues.redhat.com/browse/OCPBUGS-16866
https://bugzilla.redhat.com/show_bug.cgi?id=2177197

### CODE REVIEW

**Comment by dcbw** [comment]
/retest-required

 {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2023-07-31T22:26:23Z"}

**Comment by jcaamano** [comment]
Re-enacting @dcbw LGTM

/lgtm

**Review by tssurya — APPROVED** [review]
/lgtm

**Pull request merged**
