### PR TITLE
EIP: remove downstream's duplicate node delete test

### PR DESCRIPTION
**Pull request by msherif1234**
during review #1355 dcbw caught duplicate test downstream
removing this test to keep upstream and downsteam in sync
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

**Comment by tssurya** [comment]
/lgtm 
but for every new commit we are adding here and in the other downstream merge - the last few commits that weren't squashed into the conflict commits.. we are actually deviating from upstream ovnk right? Usually when looking at previous merges the pattern has been to keep the same history and outline the conflicts in each commit...? Is this ok?

**Comment by tssurya** [comment]
seems like 4.12 has this duplicate test issue, but 4.11 doesn't.. so this might need back port? not sure if that needs a bugzilla :D

**Comment by msherif1234** [comment]
> /lgtm thanks Mohamed! not related to this PR: but for every new commit we are adding here and in the other downstream merge - the last few commits that weren't squashed into the conflict commits.. we are actually deviating from upstream ovnk right? Usually when looking at previous merges the pattern has been to keep the same history and outline the conflicts in each commit...? Is this ok? - on the other hand the bridge has already been crossed so I guess we need to do this one anyways since the problem is only in downstream? I wonder for how long this duplicate test has existed?

this is downstream and it was introduced by this commit 
https://github.com/openshift/ovn-kubernetes//commit/2100d49a169b0df503b4052da36b8aab72b53ec9

**Review by trozet — APPROVED** [review]

**Pull request merged**
