### PR TITLE
OCPBUGS-3369: Fix mac address not set in SRIOV container interface

### PR DESCRIPTION
**Pull request by wizhaoredhat**
containernetworking bump accidentally removed setting the MAC address of the container interface for SRIOV.

Increase coverage of TestSetupSriovInterface to help preventing similar issues in the future.

Fixes: https://github.com/ovn-org/ovn-kubernetes/pull/3137

Upstream: https://github.com/ovn-org/ovn-kubernetes/pull/3186

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
(cherry picked from commit 37c6c1d7039fd4c8f3cca560691a254e720172de)

### CODE REVIEW

**Comment by zshi-redhat** [comment]
This is a required for 4.12 OVS HWOL.

**Comment by wizhaoredhat** [comment]
Commit already in master:
https://github.com/openshift/ovn-kubernetes/pull/1355/commits/37c6c1d7039fd4c8f3cca560691a254e720172de

**Pull request merged**
