### PR TITLE
Bug OCPBUGS-3077: [release-4.11] Fix netpol races

### PR DESCRIPTION
**Pull request by npinaeva**
cherry-pick of https://github.com/openshift/ovn-kubernetes/pull/1347
Also includes required commits that were not present in 4.11:
- [bump go version to 1.18](https://github.com/openshift/ovn-kubernetes/pull/1353/commits/127615726755bc295a0f72e1a1becfcd543a12e7) to enable generics
- [Remove default ACL severity (was used before as a workaround for](https://github.com/openshift/ovn-kubernetes/pull/1353/commits/a3114eb51dbd0002d3d2f7589f450ae1eea8bff7) to add ovn/acl.go file and common acl functions
- [remove networkPolicy.created field](https://github.com/openshift/ovn-kubernetes/pull/1353/commits/e6caa8f5854e5b20becda16574dd0f8ea19359c3) is a part of netpol refactoring
- [Add retry logic to Namespace resources](https://github.com/openshift/ovn-kubernetes/pull/1353/commits/065161ab62189ba6e612500dec1ae7e67b129b36) to make sure events that namespace handles (acl loglevel update) will be retried

Main differences between 4.12 and 4.11:
- obj_retry doesn't have per-object lock
- egress firewall logging is not backported, most changes for egressfirewall are ignored

### CODE REVIEW

**Review by trozet — COMMENTED** [review]
A couple commits were hard to review cause of so many conflicts, but they look OK.

Should we also pull in https://github.com/ovn-org/ovn-kubernetes/pull/3219 ?
and a follow up test fix: https://github.com/ovn-org/ovn-kubernetes/pull/3243

**Comment by trozet** [comment]
> A couple commits were hard to review cause of so many conflicts, but they look OK.
> 
> Should we also pull in [ovn-org/ovn-kubernetes#3219](https://github.com/ovn-org/ovn-kubernetes/pull/3219) ? and a follow up test fix: [ovn-org/ovn-kubernetes#3243](https://github.com/ovn-org/ovn-kubernetes/pull/3243)

Nvm I see it was already pulled into 4.11 here: https://github.com/openshift/ovn-kubernetes/pull/1334

**Comment by trozet** [comment]
Some odd behavior in the aws-ovn job where we couldn't retry delete cause of some annotation missing on the node. I don't think it is related to this PR but something to look into:

```
I1103 13:29:01.810856       1 obj_retry.go:645] Node retry delete failed for ip-10-0-165-49.us-west-2.compute.internal, will try again later: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-165-49.us-west-2.compute.internal, macAddress annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal"]
E1103 13:29:01.810893       1 obj_retry.go:1279] Failed to create *v1.Node object ip-10-0-165-49.us-west-2.compute.internal, error: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-165-49.us-west-2.compute.internal, macAddress annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal"]
```

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1353/pull-ci-openshift-ovn-kubernetes-release-4.11-e2e-aws-ovn/1588153522359111680/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-pwzmv_ovnkube-master_previous.log

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by npinaeva** [comment]
> Some odd behavior in the aws-ovn job where we couldn't retry delete cause of some annotation missing on the node. I don't think it is related to this PR but something to look into:
> 
> ```
> I1103 13:29:01.810856       1 obj_retry.go:645] Node retry delete failed for ip-10-0-165-49.us-west-2.compute.internal, will try again later: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-165-49.us-west-2.compute.internal, macAddress annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal"]
> E1103 13:29:01.810893       1 obj_retry.go:1279] Failed to create *v1.Node object ip-10-0-165-49.us-west-2.compute.internal, error: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-165-49.us-west-2.compute.internal, macAddress annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-165-49.us-west-2.compute.internal"]
> ```


How did you find that error message?
I chose random run for the same job https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1366/pull-ci-openshift-ovn-kubernetes-release-4.11-e2e-aws-ovn/1590344880415051776, and found the same errors in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1366/pull-ci-openshift-ovn-kubernetes-release-4.11-e2e-aws-ovn/1590344880415051776/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-khs2v_ovnkube-master.log: 
```
I1109 14:37:41.246276       1 obj_retry.go:639] Node retry delete failed for ip-10-0-233-167.us-west-1.compute.internal, will try again later: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-233-167.us-west-1.compute.internal, macAddress annotation not found for node "ip-10-0-233-167.us-west-1.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-233-167.us-west-1.compute.internal"]
E1109 14:37:41.246301       1 obj_retry.go:1358] Failed to create *v1.Node object ip-10-0-233-167.us-west-1.compute.internal, error: [k8s.ovn.org/node-chassis-id annotation not found for node ip-10-0-233-167.us-west-1.compute.internal, macAddress annotation not found for node "ip-10-0-233-167.us-west-1.compute.internal" , k8s.ovn.org/l3-gateway-config annotation not found for node "ip-10-0-233-167.us-west-1.compute.internal"]
```
so it probably happens all the time

**Pull request merged**
