### PR TITLE
Bug 2032998: perf/scale backports

### PR DESCRIPTION
**Pull request by dcbw**

### CODE REVIEW

**Comment by dcbw** [comment]
/hold
There will be a few more commits in this PR before we want to land it.

**Comment by dcbw** [comment]
/test e2e-aws-ovn-windows
/e2e-ovn-hybrid-step-registry
Windows/hybrid should work now that https://github.com/openshift/ovn-kubernetes/pull/913 merged

/override ci/prow/e2e-metal-ipi-ovn-dualstack
Dual-stack is still busted because of version skew between kube-apiserver and the e2e tests
https://bugzilla.redhat.com/show_bug.cgi?id=2040671

/test e2e-openstack-ovn
platform setup failures

**Comment by vpickard** [comment]
cc @vpickard

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
https://bugzilla.redhat.com/show_bug.cgi?id=2040671

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
dual-stack detection is broken in metal platform right now
https://bugzilla.redhat.com/show_bug.cgi?id=2040671

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade
seems high number of etcd leader changes has recently been an issue as well
https://coreos.slack.com/archives/C02NZBANL3G/p1641240185494000?thread_ts=1641202612.493300&cid=C02NZBANL3G

**Pull request merged**
