### PR TITLE
Revert "SDN-4930,OCPBUGS-39009: Downstream Merge Sept 18th"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/ovn-kubernetes#2302

Test revert at this point

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by martinkennelly** [comment]
Hoping this https://github.com/openshift/origin/pull/29179 fixes it.

**Comment by martinkennelly** [comment]
Hopefully fixed now and we can close this - waiting 24 hours..

**Comment by neisw** [comment]
/close
Neither individual revert fixed the issue but https://github.com/openshift/origin/pull/29179 did

**Pull request closed without merging**
