### PR TITLE
[release-4.12] OCPBUGS-2896: Refactor retry into its own pkg

### PR DESCRIPTION
**Pull request by ricky-rav**
cherry-pick of commits from https://github.com/ovn-org/ovn-kubernetes/pull/3171

With respect to https://github.com/ovn-org/ovn-kubernetes/pull/3171, the recent rework of network policy code hasn't been applied in this cherry pick, since it's not merged in downstream/master yet.

**UPDATE: we should probably wait for https://github.com/openshift/ovn-kubernetes/pull/1347 to merge, after which I'll rebase against it and we can merge this PR.**

Fixes #OCPBUGS-2896

### CODE REVIEW

**Comment by dcbw** [comment]
/retest-required

CI pod "got deleted unexpectedly"

**Comment by ricky-rav** [comment]
Closing in favor of https://github.com/openshift/ovn-kubernetes/pull/1376

**Pull request closed without merging**
