### PR TITLE
[release-4.12] OCPBUGS-34273,OCPBUGS-34414: Improves service iptables efficiency on start up + ICMP error messages to pass through

### PR DESCRIPTION
**Pull request by trozet**
Conflicts and modifications done in the first patch: [CARRY: manual cherry pick of iptables refactor](https://github.com/openshift/ovn-kubernetes/commit/5b6b6e9e038ff06c0e3c3d8bf6cf463753b37bfb)

The rest was pretty clean. I also brought in [Make PMTUD works in shared gateway mode](https://github.com/openshift/ovn-kubernetes/commit/84895aea4cdc980202c54969d01da2a70c219ac3)

in order to make the rest of the cherry-picking clean.

@pperiyasamy fyi ^

### CODE REVIEW

**Comment by trozet** [comment]
/retitle [release-4.12] OCPBUGS-34273,OCPBUGS-34414: Improves service iptables efficiency on start up + ICMP error messages to pass through

**Comment by pperiyasamy** [comment]
/lgtm

The backport of a relevant commit  0171f86bf63f46903fe0e6be9c0047da80e2b339 for PMTUD fix is skipped. Hope that's intentional as that just contains e2e for fix.

**Pull request merged**
