### PR TITLE
Bug 1830416: build: require OVN >= 2.13.0-30 for rhbz#1819785, rhbz#1827403, rhbz#1828637, rhbz#1823755

### PR DESCRIPTION
**Pull request by dcbw**
HAProxy Router performance is off with OVNKubernetes as SDN on OCP 4.3.9 deployed on AWS
https://bugzilla.redhat.com/show_bug.cgi?id=1819785 [ovn]
https://bugzilla.redhat.com/show_bug.cgi?id=1830370 [ocp]

ovn-northd: Optimize flows for LB Hairpin traffic.
https://bugzilla.redhat.com/show_bug.cgi?id=1827403

ovn-northd: Clear SB records depending on stale datapaths.
https://bugzilla.redhat.com/show_bug.cgi?id=1828637

Fix ACL reject action for UDP packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1823755

Also lock openvswitch2.13 to 2.13.0-10 to ensure signed RPMs are picked up rather than stuff from the FDN repos.

### CODE REVIEW

**Comment by sdodson** [comment]
/hold to prevent CI hotlooping
Feel free to clear this tomorrow after reviewing why these are failing.

**Comment by sdodson** [comment]
Oh, nevermind, package installation is failing. Need to sort out repos with ART I assume.

**Comment by dcbw** [comment]
@sdodson just pushed another attempt to lock to a signed version of openvswitch2.13

**Comment by sdodson** [comment]
/lgtm
Image build installation matches the defined rpm versions

**Comment by dcbw** [comment]
> @dcbw can you open a PR to bring master branch back in sync with this then I'll `cherry-pick-approve` ?

https://github.com/openshift/ovn-kubernetes/pull/164

**Pull request merged**
