### PR TITLE
Bug 1806667: merge master to release-4.3

### PR DESCRIPTION
**Pull request by danwinship**
4.3 version of #99. Again, literally just `git merge master`

/cc @dcbw @pecameron @trozet

### CODE REVIEW

**Comment by russellb** [comment]
@danwinship Can you get this updated to include https://github.com/ovn-org/ovn-kubernetes/pull/1091 ?

**Comment by danwinship** [comment]
I'm not sure why the CI bot is failing to run the normal tests here (it's not broken in general, I just tried pushing another PR). But anyway, you can verify with "git diff" that this makes release-4.4 identical to master, so the tree has already been CI'ed there.

**Pull request merged**
