### PR TITLE
OCPBUGSM-45393: Bug 2078691: [Downstream Merge] 22-07-2022

### PR DESCRIPTION
**Pull request by tssurya**
/cc @zshi-redhat @dceara @msherif1234 @numansiddique tagging because each one has a commit in the merge
/assign @trozet for approve
/assign @dcbw for approve

Fixes bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=2095852 (@anuragthehatter)
https://bugzilla.redhat.com/show_bug.cgi?id=2078691 (@huiran0826)
https://bugzilla.redhat.com/show_bug.cgi?id=2106444

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
```
level=error msg=Error: error creating EC2 NAT Gateway: InvalidElasticIpID.NotFound: The elasticIp ID 'eipalloc-0858731243416eb5f' does not exist
level=error msg=	status code: 400, request id: c71beae7-b49f-4a90-9335-e10d873e89ee
level=error
level=error msg=  with module.vpc.aws_nat_gateway.nat_gw[0],
level=error msg=  on vpc/vpc-public.tf line 85, in resource "aws_nat_gateway" "nat_gw":
level=error msg=  85: resource "aws_nat_gateway" "nat_gw" { 
```

**Comment by anuragthehatter** [comment]
/label qe-approved
QE regression passed on associated cases https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/524494/console

**Comment by anuragthehatter** [comment]
Ahh there are couple of more bugs as I noted in description. Sorry for that

/label qe-approved cancel

**Comment by anuragthehatter** [comment]
> Ahh there are couple of more bugs as I noted in description. Sorry for that
> 
> /label qe-approved cancel

@dcbw @abhat I need your help to take off ```qe-approved``1 label from it :)

**Comment by tssurya** [comment]
again the metal dualstack job doesn't look promosing: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack

**Pull request merged**
