### PR TITLE
[release-4.7] Bug 1997574: Fix: sync egress IP for missed events on start-up

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
4.7 backport of #665 

/assign @abhat 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jupierce** [comment]
Patch did not merge within window. Please check failing tests.

**Comment by alexanderConstantinescu** [comment]
/hold 

Stop re-running the failing job, I will need to check it.

**Pull request merged**
