### PR TITLE
[DownstreamMerge] 03-12-2021

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**

This is the downstream merge PR for this week.

**- Special notes for reviewers**

Conflicts:
There was one tiny conflict in the tests https://github.com/openshift/ovn-kubernetes/blob/92e3fa272e298f3caa5148992576ffbd201a66f1/go-controller/pkg/node/gateway_init_linux_test.go#L727 around `expectedIPTablesRules` function which was removed since the new tests don't use that function.

Two downstream only commits are present at the end:
- https://github.com/openshift/ovn-kubernetes/pull/863/commits/822fd5aefd9834401e6fa867629a4d6e25e04e7d to fix the tests for the MCS specific iptable rules.
- https://github.com/openshift/ovn-kubernetes/pull/863/commits/744c49a8447c0436252f08697cd64594827f20e1 to fix the test harness for downstream specific hybrid overlay tests.

/assign @trozet @dcbw

### CODE REVIEW

**Comment by tssurya** [comment]
/hold
I might have to fix the iptable rules in the tests to accommodate the OCP_HACKS.go special rules

**Comment by tssurya** [comment]
```
--- PASS: TestNodeSuite (2.34s)
PASS
coverage: 51.7% of statements
go test -mod=vendor -test.v  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn -ginkgo.v  -ginkgo.reportFile ./_artifacts/junit-pkg_ovn.xml
# github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn [github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.test]
pkg/ovn/pods_test.go:718:29: cannot use ctx (type *cli.Context) as type libovsdb.TestSetup in argument to fakeOvn.startWithDBSetup
pkg/ovn/pods_test.go:718:29: cannot use initialDB (type libovsdb.TestSetup) as type "k8s.io/apimachinery/pkg/runtime".Object in argument to fakeOvn.startWithDBSetup:
	libovsdb.TestSetup does not implement "k8s.io/apimachinery/pkg/runtime".Object (missing DeepCopyObject method)
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn [build failed]
FAIL
```
wait I see unit tests passing against upstream, but something is not working downstream. Investigating....

**Comment by tssurya** [comment]
> ```
> --- PASS: TestNodeSuite (2.34s)
> PASS
> coverage: 51.7% of statements
> go test -mod=vendor -test.v  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn -ginkgo.v  -ginkgo.reportFile ./_artifacts/junit-pkg_ovn.xml
> # github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn [github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.test]
> pkg/ovn/pods_test.go:718:29: cannot use ctx (type *cli.Context) as type libovsdb.TestSetup in argument to fakeOvn.startWithDBSetup
> pkg/ovn/pods_test.go:718:29: cannot use initialDB (type libovsdb.TestSetup) as type "k8s.io/apimachinery/pkg/runtime".Object in argument to fakeOvn.startWithDBSetup:
> 	libovsdb.TestSetup does not implement "k8s.io/apimachinery/pkg/runtime".Object (missing DeepCopyObject method)
> FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn [build failed]
> FAIL
> ```
> 
> wait I see unit tests passing against upstream, but something is not working downstream. Investigating....

ok I need to update downstream specific unit tests since we have https://github.com/openshift/ovn-kubernetes/pull/863/commits/b99bcc1b74d752c050359b40849b3cef3b10ef80

**Comment by tssurya** [comment]
All unit tests have passed:
```
JUnit path was configured: ./_artifacts/junit-hybrid-overlay_pkg_controller.xml

JUnit report was created: /home/surya/go/src/github.com/openshift/ovn-kubernetes/go-controller/_artifacts/junit-hybrid-overlay_pkg_controller.xml

Ran 14 of 14 Specs in 3.022 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestHybridOverlayControllerSuite (3.03s)
PASS
coverage: 58.9% of statements
```

**Review by trozet — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
