### PR TITLE
Bug 1837953: 9-24-2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Fixes Include:

1. Prefer routing external gateways over hybrid overlay gateways
2. Handling OVN DB corruption and ensuring raft membership

### CODE REVIEW

**Comment by aojea** [comment]
/retest
the gcp job only shows 1 failure and 5 flakes 

the azure job looks bad, but it seems the usual
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-azure-ovn

**Comment by trozet** [comment]
@aojea these 3 tests seem to consistently fail now on GCP only:

```
[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (default fs)] volume-expand should not allow expansion of pvcs without AllowVolumeExpansion property [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (ntfs)][sig-windows] subPath should support file as subpath [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]
```

**Comment by trozet** [comment]
> @aojea these 3 tests seem to consistently fail now on GCP only:
> 
> ```
> [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
> [sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (default fs)] volume-expand should not allow expansion of pvcs without AllowVolumeExpansion property [Suite:openshift/conformance/parallel] [Suite:k8s]
> [sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (ntfs)][sig-windows] subPath should support file as subpath [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]
> ```

Actually I take that back. It seems like 3 random sig-storage volume tests seem to fail consistently between runs. That makes me think there is either some temporary network outage or some resource contention.

**Comment by aojea** [comment]
not much a storage guy but should `[sig-storage] In-tree Volumes [Driver: vsphere]` run in gcp?

**Pull request merged**
