### PR TITLE
[DownstreamMerge] Bug 2026461: 4-4-22 merge

### PR DESCRIPTION
**Pull request by trozet**
Includes retry pod deletion
Removing completed pods

@tssurya PTAL

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
@trozet @jcaamano we may need to `/override ci/prow/e2e-metal-ipi-ovn-ipv6`
if we want to merge this in before bug 2070703 is fixed.
ipv6 is broken due to: https://bugzilla.redhat.com/show_bug.cgi?id=2070703

**Comment by trozet** [comment]
dualstack passed once previously on this PR, seems to be perma failing now

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Comment by trozet** [comment]
@JacobTanenbaum FYI

**Comment by trozet** [comment]
metal jobs are failing due to metal platform problems as well as this testcase:
https://github.com/openshift/origin/pull/26975

/override ci/prow/e2e-metal-ipi-ovn-dualstack
/override ci/prow/e2e-metal-ipi-ovn-ipv6

**Pull request merged**
