### PR TITLE
Bug 2052398: [DownstreamMerge] 2-25-22

### PR DESCRIPTION
**Pull request by trozet**
Relevant BZ 2052398 changes include:

1. sbdb model schema update
2. libovsdb CARRY fixes to resolve potential hang in libovsdb during disconnect/reconnect handling

### CODE REVIEW

**Comment by trozet** [comment]
@kyrtapz @zshi-redhat @andreaskaris FYI

**Comment by anuragthehatter** [comment]
QE testing multiple upgrades to verify this fix. Thanks

**Pull request merged**
