### PR TITLE
Bump OVN to ovn2.13-20.12.0-24.el8fdp

### PR DESCRIPTION
**Pull request by dcbw**
@trozet @abhat

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
Maybe the repos have synced now?

**Comment by dcbw** [comment]
/retest
` curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
{"component":"entrypoint","error":"wrapped process failed: exit status 56","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-26T21:57:23Z"}
error: failed to execute wrapped command: exit status 56 `

**Comment by trozet** [comment]
Upgrade job is using openshift sdn again...

**Comment by aojea** [comment]
This has the feature in ovn to reject on load balancer without endpoints, right? @dcbw

**Comment by vrutkovs** [comment]
Is there a plan to backport this to 4.7? This change should supposedly fix https://github.com/openshift/okd/issues/405

**Pull request merged**
