### PR TITLE
[WIP] Add IPsec package with IPv6 fix

### PR DESCRIPTION
**Pull request by markdgray**
DO NOT REVIEW - This PR is for testing

Signed-off-by: Mark Gray <mark.d.gray@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by yselkowitz** [comment]
This cannot be merged in its current state, as it is not mulit-arch conformant.  A mechanism already exists for pinning the version installed, so why is this necessary?

**Comment by markdgray** [comment]
> This cannot be merged in its current state, as it is not mulit-arch conformant. A mechanism already exists for pinning the version installed, so why is this necessary?

Hi @yselkowitz 

Thanks for reviewing but this PR is only for testing. This is a scratch build RPM as the changes are not available in upstream OVS yet. I marked this PR as "draft" and "wip" to indicate that it was not ready for review. I will add some text to the PR to explain this to avoid further confusion.

**Comment by markdgray** [comment]
Failures look unrelated

/retest

**Comment by markdgray** [comment]
Look unrelated

/retest

**Comment by dcbw** [comment]
/retest
metal problems are container pull issues

**Comment by dcbw** [comment]
/test e2e-aws-ovn
Failure waiting for pod annotations is unrelated to IPsec

**Comment by markdgray** [comment]
/test e2e-metal-ipi-ovn-dualstack

Looks unrelated: dev-scripts does not finish deploying

**Comment by markdgray** [comment]
/test e2e-gcp-ovn

Failures connecting to API server from, what looks to me to be, test runners. Seems unrelated.

**Comment by markdgray** [comment]
/test e2e-aws-ovn-windows

Looks unrelated - waiting for node annotation

**Comment by markdgray** [comment]
/test e2e-gcp-ovn

Cannot create service account - GCP IAM error

**Comment by markdgray** [comment]
/test all

Rebased to latest master, as it looks like some changes have been introduced in the last couple of days.

**Comment by markdgray** [comment]
/test e2e-vsphere-ovn

Looks like some kind of privilege issue - unrelated.

**Comment by markdgray** [comment]
Dualstack test failure is unrelated (Failing invariant -  Only known images used by tests)
/test e2e-metal-ipi-ovn-dualstack

IPv6 failure is unrelated (Couldn't subscribe to Deployments: the server has received too many requests)
/test e2e-metal-ipi-ovn-ipv6

Azure failure is unrelated (KubePersistentVolumeErrors)
/test e2e-azure-ovn

vsphere windows is unrelated (TestWMCO/create/Node_Metadata failure)
/test e2e-vsphere-windows

AWS ovn windows is unrelated (TestWMCO/create/Node_Metadata failure)
/test e2e-aws-ovn-windows

vsphere is unrelated (KubePersistentVolumeErrors)
/test e2e-vsphere-ovn

openstack might be unrelated (lots of volumes errors)
/test e2e-openstack-ovn

gcp ovn upgrade (sandbox error)
/test e2e-gcp-ovn-upgrade

okd gcp ovn is suspicious (lots of tcp timeouts)
/test okd-e2e-gcp-ovn

**Comment by markdgray** [comment]
Dualstack test failure is unrelated (Failing invariant - Only known images used by tests) +1
/test e2e-metal-ipi-ovn-dualstack

~~IPv6 failure is unrelated (Couldn't subscribe to Deployments: the server has received too many requests)~~

~~Azure failure is unrelated (KubePersistentVolumeErrors)~~

vsphere windows is unrelated (TestWMCO/create/Node_Metadata failure) +1
/test e2e-vsphere-windows

AWS ovn windows is unrelated (TestWMCO/create/Node_Metadata failure) +1
/test e2e-aws-ovn-windows

vsphere is unrelated (Pod openshift-vsphere-infra/mdns-publisher crashlooping and Pod  openshift-marketplace/community-operators not healthy)
/test e2e-vsphere-ovn

openstack might be unrelated (lots of volumes errors)

gcp ovn upgrade is unrelated (sandbox error +1 and some pods (e.g. Prometheus) aren't getting created.)
/test e2e-gcp-ovn-upgrade

okd gcp ovn is unrelated(alert KubeAPIErrorBudgetBurn alerts, lifecycle manager panic, and Prometheus error)
/test okd-e2e-gcp-ovn

**Comment by markdgray** [comment]
Dualstack test failure is unrelated (Failing invariant - Only known images used by tests +1 +1 and some "connection refused"s for oauth tests)
/test e2e-metal-ipi-ovn-dualstack

vsphere windows is unrelated (TestWMCO/create/Node_Metadata failure +1 and and failed to acquire lease: resources not found)
/test e2e-vsphere-windows

AWS ovn windows is unrelated (TestWMCO/create/Node_Metadata failure) +1 +1
/test e2e-aws-ovn-windows

vsphere is unrelated (Pod openshift-vsphere-infra/mdns-publisher crashlooping and Pod openshift-marketplace/community-operators not healthy and failed to acquire lease: resources not found)
/test e2e-vsphere-ovn

openstack might be unrelated (lots of volumes errors, test timeouts and readiness probe failures)
/test e2e-openstack-ovn

gcp ovn upgrade is unrelated (sandbox error +1 and some pods (e.g. Prometheus) aren't getting created and failed to acquire lease: resources not found)
/test e2e-gcp-ovn-upgrade

okd gcp ovn is unrelated(alert KubeAPIErrorBudgetBurn alerts, lifecycle manager panic, and Prometheus error)
(also seeing network policy errors which may be related but I think this is a known issue)
/test okd-e2e-gcp-ovn

**Comment by markdgray** [comment]
Dualstack test failure is unrelated (Failing invariant - Only known images used by tests +1 +1  +1 and some "connection refused"s for oauth tests)
/test e2e-metal-ipi-ovn-dualstack

vsphere windows is unrelated (TestWMCO/create/Node_Metadata failure +1 and and failed to acquire lease: resources not found +1)
/test e2e-vsphere-windows

AWS ovn windows is unrelated (TestWMCO/create/Node_Metadata failure) +1 +1 +1 
/test e2e-aws-ovn-windows

vsphere is unrelated (Pod openshift-vsphere-infra/mdns-publisher crashlooping and Pod openshift-marketplace/community-operators not healthy and failed to acquire lease: resources not found and marketplace pod crashlooping)
/test e2e-vsphere-ovn

openstack might be unrelated (lots of volumes errors, test timeouts and readiness probe failures, cluster does not deploy)
/test e2e-openstack-ovn

gcp ovn upgrade is unrelated (sandbox error +1 and some pods (e.g. Prometheus) aren't getting created and failed to acquire lease: resources not found +1)
/test e2e-gcp-ovn-upgrade

okd gcp ovn is unrelated(alert KubeAPIErrorBudgetBurn alerts, lifecycle manager panic, and Prometheus error)
(also seeing network policy errors which may be related but I think this is a known issue)
/test okd-e2e-gcp-ovn

**Comment by dcbw** [comment]
https://github.com/celebdor/zeroconf/pull/4 fixes the mdns-publisher crash

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-windows
known issue with kubelet verison mismatch

**Comment by markdgray** [comment]
Full PR at https://github.com/openshift/ovn-kubernetes/pull/492

**Pull request closed without merging**
