### PR TITLE
Merge 2021-07-21 2nd

### PR DESCRIPTION
**Pull request by trozet**
pulls in extra fix for https://github.com/ovn-org/ovn-kubernetes/pull/2355 (not yet merged)

### CODE REVIEW

**Comment by dcbw** [comment]
https://github.com/ovn-org/ovn-kubernetes/pull/2355 is now merged upstream

**Comment by dcbw** [comment]
/test e2e-gcp-ovn
capacity issues are failing GCP cluster bringups

**Comment by dcbw** [comment]
Consistent GCP cluster capacity failures like:
```
level=fatal msg=failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": error(MissingQuota): compute.googleapis.com/backend_services is not available in global because the required number of resources (1) is more than remaining quota of -1, compute.googleapis.com/cpus is not available in us-central1 because the required number of resources (24) is more than remaining quota of -136, compute.googleapis.com/regional_static_addresses is not available in us-central1 because the required number of resources (2) is more than remaining quota of 0
```
/retest

**Comment by trozet** [comment]
@dcbw 
aws-ovn only failed with:

```


[sig-network] pods should successfully create sandboxes by other expand_less | 0s
-- | --
1 failures to create the sandbox  ns/e2e-statefulset-5983 pod/ss-0 node/ip-10-0-185-125.ec2.internal - 5.77 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ss-0_e2e-statefulset-5983_af38aad0-6630-41a9-b97e-d58912700df1_0(4f5906775782a76ce5e21b09201c48082399bca88d4cabe97d348d1125980a1e): error adding pod e2e-statefulset-5983_ss-0 to CNI network "multus-cni-network": [e2e-statefulset-5983/ss-0:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-statefulset-5983/ss-0 4f5906775782a76ce5e21b09201c48082399bca88d4cabe97d348d1125980a1e] [e2e-statefulset-5983/ss-0 4f5906775782a76ce5e21b09201c48082399bca88d4cabe97d348d1125980a1e] failed to configure pod interface: pod OVN annotations changed waiting for OVS port binding for 0a:58:0a:80:02:ae [10.128.2.174/23]


```
I think it is safe to override this and the gcp job

**Comment by trozet** [comment]
aws ovn only failed due to sandbox synthetic issue

/override ci/prow/e2e-aws-ovn

**Pull request merged**
