### PR TITLE
Bug 2004269: Sync ECMP routes on startup and fixes stale ECMP routes

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@tssurya @fedepaol there was a merge conflict on the sync commit. I had to remove the outport stuff that was added for secondary bridge, since we dont have that in 4.8. Also in 4.8 it doesnt look like we configure routes with output_port. Can you please double check what I did to make sure I did it right?

**Comment by hardys** [comment]
[patch-manager] @trozet looks like both windows jobs are perma-failing, is investigation in progress to figure out why?

**Comment by trozet** [comment]
@hardys @JacobTanenbaum is going to look into this

**Comment by hardys** [comment]
> @hardys @JacobTanenbaum is going to look into this

Thanks @trozet - are there any bz's I can reference?

**Comment by hardys** [comment]
[patch-manager] Approving for cherry-pick with a score of 2.0

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
failed test is `should check if kubectl can dry-run update Pods` and the failure is deleting a 15m timeout deleting e2e-kubectl-7491/e2e-test-httpd-pod, yet the delete event for the pod doesn't show up anywhere that I can find. Other flakes are for the lb-ext kubeconfig thing that isn't network related.

**Pull request merged**
