### PR TITLE
Bug 2034668: Fix pod handlers and pod IP parsing for egress IP

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Cherry-pick of https://github.com/ovn-org/ovn-kubernetes/pull/2572 for 4.9

/assign @dcbw @trozet 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/retitle Bug 2034668: Fix pod handlers and pod IP parsing for egress IP

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Comment by trozet** [comment]
@anuragthehatter PTAL

**Pull request merged**
