### PR TITLE
NHE-805,OCPBUGS-19050,OCPBUGS-22691,OCPBUGS-22767,SDN-4173: [DownstreamMerge] 11 November 2023

### PR DESCRIPTION
**Pull request by qinqon**
/cc @npinaeva @jcaamano @trozet @wizhaoredhat @flavio-fernandes @lmilleri

### CODE REVIEW

**Comment by jcaamano** [comment]
@qinqon 

FYI we are now required to have jira references describing all the changes. Not all the changes are bugs and probably not all are tied to a story right now. I think it is ok for us to not fully comply with this while we have a discussion on how to handle it but it might be worth it to give a chance for everyone to attach their references as available. This might be slow as many of us are away this week.

**Comment by qinqon** [comment]
> @qinqon
> 
> FYI we are now required to have jira references describing all the changes. Not all the changes are bugs and probably not all are tied to a story right now. I think it is ok for us to not fully comply with this while we have a discussion on how to handle it but it might be worth it to give a chance for everyone to attach their references as available. This might be slow as many of us are away this week.

Ok, I will send a message at the channel so people can attach their info here, if this  is what you mean.

**Comment by wizhaoredhat** [comment]
[Prevent multiple encap-ips per single chassis](https://github.com/openshift/ovn-kubernetes/pull/1952/commits/fbd29249541a74dd945ff9a5024f425579690cd3) NHE-805

**Comment by lmilleri** [comment]
[Fix pod creation with SRIOV interfaces](https://github.com/openshift/ovn-kubernetes/pull/1952/commits/5a08eb28c1618ce9748073b42bd9ef6c795e7a98) is related to PR https://github.com/ovn-org/ovn-kubernetes/pull/3987

**Comment by jcaamano** [comment]
/title NHE-805,OCPBUGS-19050,OCPBUGS-22691,OCPBUGS-22767,SDN-4173: [DownstreamMerge] 11 November 2023

**Comment by jcaamano** [comment]
/retitle NHE-805,OCPBUGS-19050,OCPBUGS-22691,OCPBUGS-22767,SDN-4173: [DownstreamMerge] 11 November 2023

**Pull request merged**
