### PR TITLE
Bug 1908789: Dockerfile: bump OVS to 2.13.0-79

### PR DESCRIPTION
**Pull request by markdgray**
This version of 'ovs-monitor-ipsec' contains a number of bugfixes
that are required to fix IPsec support.

### CODE REVIEW

**Comment by markdgray** [comment]
Still need to tag openvswitch package.

**Comment by alexanderConstantinescu** [comment]
Same deal as always, our master builds have been broken for a couple of days because -79 now has been tagged. @dcbw could you approve the PR so that the bot starts hammering it?

**Comment by markdgray** [comment]
> Same deal as always, our master builds have been broken for a couple of days because -79 now has been tagged. @dcbw could you approve the PR so that the bot starts hammering it?

FYI: It has only been tagged since yesterday. I don't understand why two packages with different versions cant be in the repo?

**Comment by markdgray** [comment]
These look like flakes

/retest

**Comment by alexanderConstantinescu** [comment]
> > Same deal as always, our master builds have been broken for a couple of days because -79 now has been tagged. @dcbw could you approve the PR so that the bot starts hammering it?
> 
> FYI: It has only been tagged since yesterday. I don't understand why two packages with different versions cant be in the repo?

This is a limitation on ART. Well, truth be told we are to only ones pinning version like this in our images. ART presupposes that by tagging your brew build with the `rhaos` tag, _is_ pinning the version. Doing it twice like we are, "is wrong". Anyhow, @trozet  has a Jira opened to them for implementing this, https://issues.redhat.com/browse/ART-2525

**Comment by dcbw** [comment]
gcp-ovn is `[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Dynamic PV (default fs)] volumes should allow exec of files on the volume [Suite:openshift/conformance/parallel] [Suite:k8s]`

**Comment by alexanderConstantinescu** [comment]
`e2e-gcp-ovn` 5 / 2727 tests failed....can we just override that job given the urgency to unblock everyone? @dcbw 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/402/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn/1349696468453167104

**Comment by markdgray** [comment]
@dcbw Can this be pushed now? I think we need an approval?

**Comment by aojea** [comment]
this failures is recurrent
```

: Undiagnosed panic detected in pod expand_less | 0s
-- | --
pods/openshift-operator-lifecycle-manager_packageserver-cc5c77886-7n829_packageserver.log.gz:E0114 13:21:04.808864       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference

```

**Pull request merged**
