### PR TITLE
[release-4.14] OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

### PR DESCRIPTION
**Pull request by flavio-fernandes**
This is a back-logged PR to catch release-4.14 up with all the fixes that were held while
branching of release 4.14 took place.

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
Note: with this PR, the only difference between master and release-4.14 branch is:

```
❯ git diff kyrtapz-merge-9-18-23
diff --git a/Dockerfile.microshift b/Dockerfile.microshift
index 4e0dbb0a8..9145baa6b 100644
--- a/Dockerfile.microshift
+++ b/Dockerfile.microshift
@@ -12,7 +12,7 @@
 # openvswitch-devel, openvswitch-ipsec, libpcap, iproute etc
 # ovn-kube-util, hybrid-overlay-node.exe, ovndbchecker and ovnkube-trace

-FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.19-openshift-4.14 AS builder
+FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.14 AS builder

 WORKDIR /go/src/github.com/openshift/ovn-kubernetes
 COPY . .
```

**Comment by trozet** [comment]
/hold

this contains commits not yet in master, https://github.com/openshift/ovn-kubernetes/pull/1885

**Comment by trozet** [comment]
/hold cancel

@flavio-fernandes can you update the title to include all of the other 4.14 jira bugs as well? You may have to make them.

**Comment by martinkennelly** [comment]
QE (JC) is running their regression suite against this PR on all platforms (AWS,GCP,Azure,BM,vsphere, etc)

**Comment by martinkennelly** [comment]
/retest-required

`e2e-aws-ovn-upgrade` and `e2e-aws-ovn-upgrade-local-gateway ` failed:
```
pod pending for more than 30m0s: containers have not started in 1h40m29.087151306s: test: 
* Container test is not ready with reason ImagePullBackOff and message Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-2ztsmm6r/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a"
Found 17 events for Pod e2e-aws-ovn-upgrade-ipi-conf:
```
I noticed yesterday there were (dnf) pkg pulling failures - maybe its related.

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-kubevirt 
```
 unable to pull image: ImagePullBackOff: Back-off pulling image "registry.build05.ci.openshift.org/ci-op-4i9xyflh/stable@sha256:9d4dcf33eebdeb01573a70cc4aa0f7f9e492a5f2d5cfdfd410d5bd00766302f8"
```

**Comment by martinkennelly** [comment]
I picked a specific job to focus on  `e2e-ovn-hybrid-step-registry`:
I looked at ovnkube pods - and i see a number of containers are pending:
```
$omg  -n openshift-ovn-kubernetes get pod 
NAME                                    READY  STATUS   RESTARTS  AGE
ovnkube-control-plane-7fbc954bcd-d5zgj  2/2    Running  1         33m
ovnkube-control-plane-7fbc954bcd-jggn5  2/2    Running  0         33m
ovnkube-control-plane-7fbc954bcd-pmzs8  2/2    Running  0         33m
ovnkube-node-48b7d                      0/8    Pending  0         25m
ovnkube-node-6lzg9                      8/8    Running  0         32m
ovnkube-node-9kvxz                      8/8    Running  0         32m
ovnkube-node-glj5p                      8/8    Running  0         32m
ovnkube-node-hrkzq                      2/8    Pending  0         25m
ovnkube-node-w9f2n                      5/8    Pending  0         25m
```

```
$omg  -n openshift-ovn-kubernetes get pod ovnkube-node-48b7d -o yaml
....
status:
  conditions:
...
  - image: registry.build05.ci.openshift.org/ci-op-4i9xyflh/stable@sha256:b5e574c5b2fdd0a90d899793e2ce97792dc2d3e3fbf934a107139b1b4f2732a7
    imageID: ''
    lastState: {}
    name: kube-rbac-proxy-ovn-metrics
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "registry.build05.ci.openshift.org/ci-op-4i9xyflh/stable@sha256:b5e574c5b2fdd0a90d899793e2ce97792dc2d3e3fbf934a107139b1b4f2732a7"
        reason: ImagePullBackOff
```
Looks like CI issues yesterday..

**Comment by martinkennelly** [comment]
Update from QE is that they were unable to build pre-merge images - it failed 5 times for them. This maybe related to what we see here. QE will continue today.

**Comment by flavio-fernandes** [comment]
/retitle [release-4.14] OCPBUGS-18584OCP-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

**Comment by flavio-fernandes** [comment]
/retitle [release-4.14] OCPBUGS-18584,OCP-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

**Comment by flavio-fernandes** [comment]
/retitle [release-4.14] OCPBUGS-18584,OCPBUGS-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

**Comment by martinkennelly** [comment]
Upgrade is failing because of CI issues:
```
INFO[2023-09-21T15:52:22Z] pod pending for more than 30m0s: containers have not started in 30m0.000217111s: test: 
* Container test is not ready with reason ImagePullBackOff and message Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-bcdpt9mq/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a" 
```

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-upgrade

Reason for retest is there are still image pull issues and this is explained by CI stability:
- Within build log for `network-check-target`
```
processed event: {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:network-check-target-6w4xb.178704fb513aea28 GenerateName: Namespace:openshift-network-diagnostics SelfLink: UID:714aa823-19df-4fe8-9a0a-be5b43916fbc ResourceVersion:58138 Generation:0 CreationTimestamp:2023-09-21 20:47:42 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[monitor.openshift.io/observed-recreation-count: monitor.openshift.io/observed-update-count:1] OwnerReferences:[] Finalizers:[] ManagedFields:[{Manager:kubelet Operation:Update APIVersion:v1 Time:2023-09-21 20:49:33 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:source":{"f:component":{},"f:host":{}},"f:type":{}} Subresource:}]} InvolvedObject:{Kind:Pod Namespace:openshift-network-diagnostics Name:network-check-target-6w4xb UID:66c8417c-3739-4d46-bb31-e2f95a9b955c APIVersion:v1 ResourceVersion:57185 FieldPath:spec.containers{network-check-target-container}} Reason:Failed Message:Error: ImagePullBackOff Source:{Component:kubelet Host:ip-10-0-58-42.us-east-2.compute.internal} FirstTimestamp:2023-09-21 20:47:42 +0000 UTC LastTimestamp:2023-09-21 20:49:33 +0000 UTC Count:3 Type:Warning EventTime:0001-01-01 00:00:00 +0000 UTC Series:nil Action: Related:nil ReportingController: ReportingInstance:}
```
- `multus-additional-cni-plugins`:
```
event happened 109 times, something is wrong: ns/openshift-multus pod/multus-additional-cni-plugins-nrbx8 node/ip-10-0-58-42.us-east-2.compute.internal hmsg/7dcc43892b - pathological/true reason/BackOff Back-off pulling image "registry.build05.ci.openshift.org/ci-op-rl10b5jl/stable@sha256:5ae9edd9e2d6ee455c6a4fdff123cd44982138adaef45edaf
```

**Comment by martinkennelly** [comment]
Launched the following upgrade jobs (using `test upgrade 4.13.13 openshift/ovn-kubernetes#1889` on CB and they all passed:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1704942954910584832
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1704942855643992064
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1704942969708089344
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1704942929191112704

E2Es on GCP and AWS also passed.

QE attempted to run regression tests but encountered known CI registry issues while attempting to pull images.

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-upgrade 
It failed because of gateway 5XX http code - known CI issue.

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-upgrade-local-gateway

```
unable to pull image: ImagePullBackOff: Back-off pulling image "registry.build05.ci.openshift.org/ci-op-mslwxz86/stable-
``

**Comment by martinkennelly** [comment]
/test e2e-aws-ovn-kubevirt 
```
a032b38a8b49795d3801e7ea224c3546eccfdd9adcc389ad: pinging container registry image-registry.openshift-image-registry.svc:5000: Get \"https://image-registry.openshift-image-registry.svc:5000/v2/\": dial tcp 172.30.62.55:5000: connect: connection refused"
```

**Comment by flavio-fernandes** [comment]
@martinkennelly @trozet @kyrtapz PTAL!

**Comment by martinkennelly** [comment]
/test e2e-vsphere-ovn
Unknown why this job failed with:
```
{  etcdHighCommitDurations was at or above info for at least 10m54s on platformidentification.JobType{Release:"4.14", FromRelease:"", Platform:"vsphere", Architecture:"amd64", Network:"ovn", Topology:"ha"} (maxAllowed=0s): pending for 8m54s, firing for 10m54s:
```

**Comment by tssurya** [comment]
and we finally have our stable upgrades back lol

**Comment by jcaamano** [comment]
/retitle [release-4.14] OCPBUGS-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

**Comment by flavio-fernandes** [comment]
retitle [release-4.14] OCPBUGS-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

**Comment by flavio-fernandes** [comment]
> /retitle [release-4.14] OCPBUGS-18977,OCPBUGS-18427,OCPBUGS-19538,OCPBUGS-19568,OCPBUGS-19507: merging from master to release-4.14

sorry for the mid-air collision, Jaime

**Comment by flavio-fernandes** [comment]
/hold 
we have picked up changes that do not belong in 4.15. I will review these and correct it

**Comment by flavio-fernandes** [comment]
/remove-hold

located the art commits that do not belong on this pr and took them out. TY @jcaamano !

**Comment by trozet** [comment]
vsphere failures were all volume related with test panic

payload/ci blocking tests seem mostly good. There are a few failures but they look more infra/cloud related and not something to do with this PR.

/approve
/label backport-risk-assessed

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
