### PR TITLE
CARRY: honor openshift-sdn legacy annotations for idling and multicast

### PR DESCRIPTION
**Pull request by dcbw**
@squeed @danwinship @rcarrillocruz @alexanderConstantinescu @JacobTanenbaum @pecameron @abhat

### CODE REVIEW

**Comment by danwinship** [comment]
Did this requirement come from somewhere? We have separate openshift-sdn and ovn-kubernetes docs anyway, so it doesn't simplify the documentation (much), and we don't support migration (and if we did we could easily migrate the annotations), so... ?

**Comment by dcbw** [comment]
> Did this requirement come from somewhere? We have separate openshift-sdn and ovn-kubernetes docs anyway, so it doesn't simplify the documentation (much), and we don't support migration (and if we did we could easily migrate the annotations), so... ?

@danwinship just though it would be nice-to-have. But if we don't need it, I'm happy to drop it.

**Comment by danwinship** [comment]
fewer carry patches seems better to me... but we can remember this PR is here if we decide we need it later

**Pull request closed without merging**
