### PR TITLE
Bug 1874928: Pinning the OVN version for 4.5.8 release

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Pin the version for 4.5.8 as to avoid problems during the upgrade from 4.5.7 -> 4.5.8

/assign @knobunc @joepvd 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
As long as there's a Jira card and commitment to revert this PR after 4.5.7 ships, ok with me.

**Comment by alexanderConstantinescu** [comment]
> As long as there's a Jira card and commitment to revert this PR after 4.5.7 ships, ok with me.

There is. Once https://github.com/openshift/cluster-network-operator/pull/755 merges and has been back-ported, we'll be able to revert this.

**Comment by knobunc** [comment]
@dcbw we are tracking it with the urgent bug https://bugzilla.redhat.com/show_bug.cgi?id=1874737 for a 4.5 revert.

**Comment by joepvd** [comment]
From [build](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/248/pull-ci-openshift-ovn-kubernetes-release-4.5-e2e-aws-ovn/1301164550929780736/artifacts/build-logs/ovn-kubernetes.log
):
```
Installing:
 ovn2.13            x86_64    2.13.0-39.el7fdp      rhel-fast-datapath    4.2 M
 ovn2.13-central    x86_64    20.06.1-6.el7fdp      rhel-fast-datapath  1.8M
 ovn2.13-host       x86_64    20.06.1-6.el7fdp      rhel-fast-datapath   980k
 ovn2.13-vtep       x86_64    20.06.1-6.el7fdp      rhel-fast-datapath   862k
```
Version pin worked, but might need to be supplied to all packages.

**Comment by knobunc** [comment]
**Why I overrode:** There is no 4.6 change for this since we do not want to change the ovn version there.  The override was needed so that we could pin the ovn version in 4.5 so that we don't have a schema upgrade yet.  We have a 4.6 PR to support schema upgrades properly (https://github.com/openshift/cluster-network-operator/pull/755) with 4.6 and 4.5 tracking bugs.  Once that PR lands and is backported to 4.5 we will revert this change.

**Comment by alexanderConstantinescu** [comment]
Seems to be properly pinned now:

```
Installed:
  ovn2.13.x86_64 0:2.13.0-39.el7fdp                                             
  ovn2.13-central.x86_64 0:2.13.0-39.el7fdp                                     
  ovn2.13-host.x86_64 0:2.13.0-39.el7fdp                                        
  ovn2.13-vtep.x86_64 0:2.13.0-39.el7fdp    
```
From: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/248/pull-ci-openshift-ovn-kubernetes-release-4.5-images/1301177262988595200/artifacts/build-logs/ovn-kubernetes.log

**Comment by knobunc** [comment]
/override

We have test runs of gcp-ovn that passed on clusterbot, and the failures we had have been flakes in the past.

**Pull request merged**
