### PR TITLE
Bug 1933752: [wip] [4.6] soak-test ovn2.13-20.09.0-7.el8fdn

### PR DESCRIPTION
**Pull request by dcbw**
Soak-test updated OVN version to solve conjunction issues with ovn-20.06.2-11 for https://bugzilla.redhat.com/show_bug.cgi?id=1933752

### CODE REVIEW

**Comment by dcbw** [comment]
We had good signal in 4.6 last fall with this OVN via https://github.com/openshift/ovn-kubernetes/pull/324, FWIW

**Comment by dcbw** [comment]
4.7 upgraded through this OVN build as well via https://github.com/openshift/ovn-kubernetes/pull/327

**Comment by trozet** [comment]
tagging and moving to #455 for official PR (I tried to use this same PR, but did not have rights to push)

**Pull request closed without merging**
