### PR TITLE
Bug 1877561:  [release-4.5]Fix orphaned ACLs backport to 4.5

### PR DESCRIPTION
**Pull request by astoycos**
This PR backports the fixes found in https://github.com/ovn-org/ovn-kubernetes/pull/1665

I also had to solve some merge conflicts: 

in `policy.go` With with how we loop though the `gressPolicies`, it now uses a `namespacePolicy` now rather than a *knet.NetworkPolicy to get the policy's name and namespace 

in `namespace.go` remove `oc.deleteGWRoutesForNamespace(nsInfo)` and keep `deleteAddressSet(hashedAddressSet(ns.Name))`

### CODE REVIEW

**Comment by astoycos** [comment]
@dcbw i'm seeing a bunch of test flakes here...

**Comment by astoycos** [comment]
@knobunc let me know what you think :)

**Comment by astoycos** [comment]
@JacobTanenbaum If I could get a quick review on this backport I'd really appreciate it!

**Comment by astoycos** [comment]
@trozet  You could review this as well :)

**Comment by astoycos** [comment]
Not sure why `ci/prow/e2e-metal-ipi-ovn-ipv6 ` is failing here.. Seems like a must-gather issue?

**Comment by abhat** [comment]
Can you please include a link to the downstream 4.6/master PR here or are we directly putting the fix in 4.5.z?

**Comment by astoycos** [comment]
So it merged upstream and then got pulled downstream with one of Tim's Rebases for 4.6

Upstream PR => https://github.com/ovn-org/ovn-kubernetes/pull/1665

Downstream merge PR => https://github.com/openshift/ovn-kubernetes/pull/286

**Comment by trozet** [comment]
@hardys @stbenjam do we expect/want metal-ipi-ovn-ipv6 to be required on 4.5? Also should the metal-ipi job be removed? That is probably openshift-sdn right?

**Comment by danwinship** [comment]
"e2e-metal-ipi" is the same job as "e2e-metal-ipi-ovn-ipv6", it's just that the PR was created before the job was renamed and so now it has references to both versions... I think maybe
/refresh
will clear it up? Or maybe it's
/skip

**Comment by danwinship** [comment]
/override ci/prow/e2e-aws-ovn
e2e-gcp-ovn passed, and e2e-aws-ovn seems very flaky in 4.5 for some reason (which we should figure out...)

**Pull request merged**
