### PR TITLE
OCPBUGS-4860, OCPBUGS-4838: [release-4.11] Avoid duplicate transactions and minimize handlers with empty namespace selectors

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of https://github.com/openshift/ovn-kubernetes/pull/1439

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
https://coreos.slack.com/archives/CFP6ST0A3/p1670860628776879

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn
failure is unrelated to this PR and has nothing to do with network policy

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade
infra install problems

```
level=error msg=Error: Error launching source instance: InvalidParameterValue: Value (ci-op-bz7gc8ih-3ae76-w4vlr-bootstrap-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
level=error msg=	status code: 400, request id: ff04efd5-051c-4c19-9183-cc5675ff111a
level=error
level=error msg=  with aws_instance.bootstrap,
level=error msg=  on main.tf line 152, in resource "aws_instance" "bootstrap": 
```

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
https://issues.redhat.com/browse/OCPBUGS-4977

**Pull request merged**
