### PR TITLE
Bug 1959352: phase 2 scale improvements

### PR DESCRIPTION
**Pull request by trozet**
Changes Include:

1. batch pod operations into a single operation
2. remove unnecessary locking around address sets to avoid lock contention during pod operations
3. combine address set operations for add/remove IP into logical port OVN transactions
4. use uuids for OVSDB operations involving conditions like "where x == y"
5. update 2/3 json rpc methods for ovsdb
6. leader only connections for go-ovn
7. temporarily revert libovsdb clients until they have support for 5 and 6
8. fix an issue where reconnect in go-ovn client can hang forever if ovsdb server does not respond with a reply

### CODE REVIEW

**Comment by trozet** [comment]
/assign @dcbw 
/assign @tssurya 

@dceara FYI

**Comment by trozet** [comment]
/hold
[20 node-density-light](http://grafana.rdu2.scalelab.redhat.com:3000/d/hIBqKNvMz/kube-burner-report?orgId=1&from=1631737345933&to=1631740945933&var-Datasource=Keith-ES-kube-burner&var-sdn=All&var-job=All&var-uuid=d14b2167-b23a-4c4e-89fb-4906769156c1&var-master=All&var-worker=ip-10-0-133-175.us-west-2.compute.internal&var-infra=ip-10-0-142-66.us-west-2.compute.internal&var-namespace=All&var-verb=All&var-resource=All&var-flowschema=All&var-priority_level=All)

P99: 38.9s, avg 9.2s

**Comment by trozet** [comment]
I believe the perf degradation is due to the fact we are still using go-ovn with regular update json rpc methods. Causes more workload on nbdb to produce the monitor updates. Seems like too much effort to try to rip out go-ovn across the code. I think we need to add the update2/3 support and leader only.

**Comment by trozet** [comment]
Latest results:
**20 node density light**: http://grafana.rdu2.scalelab.redhat.com:3000/d/hIBqKNvMz/kube-burner-report?orgId=1&from=16318[…]urce=All&var-flowschema=All&var-priority_level=All
p99: 5.558s, avg: 3.819

**20 node-density-heavy:** p99: 7.50m, avg: 1.93m, http://grafana.rdu2.scalelab.redhat.com:3000/d/hIBqKNvMz/kube-burner-report?orgId=1&from=16318[…]urce=All&var-flowschema=All&var-priority_level=All

**node-density-light 120 node**: p99: 59m, avg: 16m http://grafana.rdu2.scalelab.redhat.com:3000/d/hIBqKNvMz/kube-burner-report?orgId=1&from=16319[…]urce=All&var-flowschema=All&var-priority_level=All

**node-density-light 120 node, 25 test pods per node (39 total per node)-** p99: 3.87s, avg: 2.94s, http://grafana.rdu2.scalelab.redhat.com:3000/d/hIBqKNvMz/kube-burner-report?orgId=1&from=16318[…]urce=All&var-flowschema=All&var-priority_level=All

**Comment by trozet** [comment]
lol aws failure:
Prometheus when installed on the cluster when using openshift-sdn should be able to get the sdn ovs flows

**Comment by dcbw** [comment]
There's something wrong if we're settling for node-density-light 120 node: p99: 59m, avg: 16m, given our test patches can bring that down to at least 14m p99/3.4m avg even without Ilya's ovsdb fixes. What are the things we're not bringing in here that get us down that far?

**Comment by trozet** [comment]
@dcbw OK I will submit a PR upstream and cherry pick it back here

**Comment by trozet** [comment]
/hold

going to rework this PR to use go-ovn instead as we think we can get better performance without much added risk

**Comment by dcbw** [comment]
/retest
A couple jobs (vsphere, gcp) failed terraform setup, a couple others (aws, local gateway) failed due to the security context constraints thing.

**Comment by trozet** [comment]
passed all CI previously, tagged in local quay: quay.io/trozet/ovn-kubernetes:phase2_scale27_pr750

**Comment by trozet** [comment]
/hold

we are going to need to address bottlenecks with multiple exgws as well...

**Comment by trozet** [comment]
/hold cancel

bottlenecks with multiple external gateways have been addressed

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn
`StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset` is flaky and already considered a flake if it fails once

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn
failed on network must-gather, not the actual e2e tests

**Comment by dcbw** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6
`StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset` is flaky and already considered a flake if it fails once

**Pull request merged**
