### PR TITLE
Bug 1823557: Upstream merge 2020-04-20

### PR DESCRIPTION
**Pull request by dcbw**
4.4 version of #123 and https://github.com/openshift/ovn-kubernetes/pull/141

@openshift/networking

### CODE REVIEW

**Comment by dcbw** [comment]
@trozet @knobunc note this PR won't work until the corresponding CNO bits land first.

**Comment by trozet** [comment]
@dcbw the ssl args just got merged:
https://github.com/openshift/cluster-network-operator/pull/578

**Comment by trozet** [comment]
@dcbw as you mentioned the failure is with ingress router:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/135/pull-ci-openshift-ovn-kubernetes-release-4.4-e2e-aws-ovn/135/artifacts/e2e-aws-ovn/pods/openshift-ingress_router-default-6c744dfc98-b5c4r_router.log

I don't see anything obvious in the logs, and I just created a KIND CNO setup with your PR and it works OK. I can create a pod and curl API server from it.

/retest

**Comment by trozet** [comment]
Looks like from the logs there was a leader change:

I0414 14:28:43.546098       1 leaderelection.go:288] failed to renew lease openshift-ovn-kubernetes/ovn-kubernetes-master: timed out waiting for the condition
I0414 14:28:43.546136       1 master.go:76] no longer leader; exiting

I wonder if this is what caused the problem.

**Comment by knobunc** [comment]
/retest
Bootstrapping failed

**Comment by dcbw** [comment]
This PR probably won't merge unitl https://github.com/openshift/machine-config-operator/pull/1615 does

**Comment by knobunc** [comment]
This won't work until https://github.com/openshift/machine-config-operator/pull/1615 lands.

**Comment by trozet** [comment]
MCO change was merged

**Comment by trozet** [comment]
We hit https://bugzilla.redhat.com/show_bug.cgi?id=1823460 on aws-ovn

I'll try to get that downstream in 4.5 and then we can update this PR to pull it in.

**Comment by trozet** [comment]
@dcbw merge went into master with fixes for network policy bug. Can you please update this PR to include them?

**Pull request merged**
