### PR TITLE
exit 0 instead of 1

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jluhrsen** [comment]
@trozet, is this something I should be putting in upstream as well, or just leave it here in d/s since it's really just addressing some mess we see in CI?

**Comment by dcbw** [comment]
@jluhrsen can you repost to upstream?

**Comment by jluhrsen** [comment]
> @jluhrsen can you repost to upstream?

here it is:
  https://github.com/ovn-org/ovn-kubernetes/pull/2689
  
what's the proper flow here? should we close this one and let it come in with some future periodic merge?

**Pull request closed without merging**
