### PR TITLE
12-03-2020 merge

### PR DESCRIPTION
**Pull request by trozet**
Includes DNS egress firewall implementation and shared gw/services fixes.

### CODE REVIEW

**Comment by trozet** [comment]
@JacobTanenbaum @dcbw

**Comment by dcbw** [comment]
/retest
capacity issues on GCP, plus this odd error on azure and openstack:
`Storing signatures
error: error copying source path /app/prow/cmd/clonerefs/app.binary.runfiles/io_k8s_test_infra/prow/cmd/clonerefs/linux_amd64_pure_stripped/app.binary to .: exit status 1
2020/12/04 18:04:33 No custom metadata found and prow metadata already exists. Not updating the metadata.`

**Comment by dcbw** [comment]
/retest e2e-gcp-ovn
```
level=error msg=Error: Request "Create IAM Members roles/iam.serviceAccountUser serviceAccount:ci-op-gryd16xi-99b10-cfkg9-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" returned error: Batch request and retried single request "Create IAM Members roles/iam.serviceAccountUser serviceAccount:ci-op-gryd16xi-99b10-cfkg9-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" both failed. Final error: Error applying IAM policy for project "openshift-gce-devel-ci": Error setting IAM policy for project "openshift-gce-devel-ci": googleapi: Error 400: Service account ci-op-24x8d1fz-3caf3-wq5zq-m@openshift-gce-devel-ci.iam.gserviceaccount.com does not exist., badRequest
```

**Comment by dcbw** [comment]
/test e2e-gcp-ovn
```
level=error msg=Error: Request "Create IAM Members roles/iam.serviceAccountUser serviceAccount:ci-op-gryd16xi-99b10-cfkg9-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" returned error: Batch request and retried single request "Create IAM Members roles/iam.serviceAccountUser serviceAccount:ci-op-gryd16xi-99b10-cfkg9-m@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" both failed. Final error: Error applying IAM policy for project "openshift-gce-devel-ci": Error setting IAM policy for project "openshift-gce-devel-ci": googleapi: Error 400: Service account ci-op-24x8d1fz-3caf3-wq5zq-m@openshift-gce-devel-ci.iam.gserviceaccount.com does not exist., badRequest
```

**Comment by dcbw** [comment]
Some continuing capacity issues, and docker pull ratelimiting in some jobs.

```
 level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error creating/updating Private DNS Zone Virtual network link "ci-op-kf3hi9yv-e6384-8q9h6-network-link" (Resource Group "ci-op-kf3hi9yv-e6384-8q9h6-rg"): pollingTrackerBase#updateRawBody: failed to read response body: StatusCode=0 -- Original Error: read tcp 10.128.39.60:41012->13.71.173.192:443: read: connection reset by peer
level=error
level=error msg=  on ../tmp/openshift-install-868459663/dns/dns.tf line 13, in resource "azureprivatedns_zone_virtual_network_link" "network":
level=error msg=  13: resource "azureprivatedns_zone_virtual_network_link" "network" { 
```

**Comment by trozet** [comment]
https://github.com/openshift/ovn-kubernetes/pull/370 already passed and got merged

**Pull request closed without merging**
