### PR TITLE
Bug 2073378: Add node name into egress ip status for the removal

### PR DESCRIPTION
**Pull request by pperiyasamy**
This commit ensures node name is added into EgressIPStatusItem so that
executeCloudPrivateIPConfigOps removes the egress ip from cloud config
store even though assignment didn't actually happen on the node.

Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit https://github.com/openshift/ovn-kubernetes/commit/1af0a7bee7ab2b9295450736866c91c001d4965a)

### CODE REVIEW

**Comment by andreaskaris** [comment]
That's a cherry-pick from upstream, right? Can you add the -x option when cherry-picking so that we can preserve the original SHA?

https://docs.google.com/document/d/11Ax17QT0FB_OMV9_ifwWX3ppoLlc3OujjAikZP3J1v4/edit#heading=h.wqpod1ric6e

`During feature freeze, be sure to only cherry-pick commits upstream into downstream that are fixes. Always use the git cherry-pick -x option. This will include the original upstream commit SHA in the downstream commit message in the form of a line such as “(cherry picked from commit xyz)”. `

**Review by andreaskaris — CHANGES_REQUESTED** [review]
That's a cherry-pick from upstream, right? Can you add the -x option when cherry-picking so that we can preserve the original SHA?

https://docs.google.com/document/d/11Ax17QT0FB_OMV9_ifwWX3ppoLlc3OujjAikZP3J1v4/edit#heading=h.wqpod1ric6e

`During feature freeze, be sure to only cherry-pick commits upstream into downstream that are fixes. Always use the git cherry-pick -x option. This will include the original upstream commit SHA in the downstream commit message in the form of a line such as “(cherry picked from commit xyz)”. `

**Review by andreaskaris — APPROVED** [review]
/lgtm

**Comment by jechen0648** [comment]
bugzilla cc-qa

**Pull request merged**
