### PR TITLE
[WIP] HACK: Use VXLAN instead of Geneve by default.

### PR DESCRIPTION
**Pull request by dceara**
Just testing things out..

### CODE REVIEW

**Comment by dceara** [comment]
I didn't dig too much into this but it's possible that the issue is due to https://bugzilla.redhat.com/show_bug.cgi?id=2054549

**Comment by tssurya** [comment]
This PR is skewing up our pre-submit CI dashboard which measures "are presubmit jobs healthy OR not". :/
closing this PR to ensure CI dashboard is catching real failures, else is hard to chase down a "real redness in the dashboard" with all the WIP PRs staying open for long.

**Comment by tssurya** [comment]
also always feel free to reopen if you need to..

**Pull request closed without merging**
