### PR TITLE
OCPBUGS-6823: [release-4.12] Fix Egress FW ACL rules in dualstack mode

### PR DESCRIPTION
**Pull request by martinkennelly**
Clean cherry-pick.

Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest

Nearly all the jobs failed to build image with error: "unable to convert the image to a compatible schema version"

**Comment by martinkennelly** [comment]
/retest
Unrelated to this PR failures including infra and a known hypershift issue that I am reporting.

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows
https://redhat-internal.slack.com/archives/CBN38N3MW/p1675695577499609

**Pull request merged**
