### PR TITLE
Bug 1888352: Fix IPv6 neighbor discovery hack

### PR DESCRIPTION
**Pull request by danwinship**
Fixes an IPv6 regression introduced by #238

### CODE REVIEW

**Comment by stbenjam** [comment]
@danwinship Is the aws-ovn failure legit? It looks like the last periodics on 4.5 have passed aws-ovn, but it's consistently failing here.

**Comment by danwinship** [comment]
/override ci/prow/e2e-aws-ovn

Each run is failing different tests. I think it's just really flaky. :frowning_face: 
And the PR only affects IPv6 anyway, so it's definitely not the cause of the e2e-aws-ovn failure

**Comment by stbenjam** [comment]
Tide isn't reporting status to GitHub, but I guess it's still doing it's thing. We need a cherry-pick-approved label. Not sure if anyone wants to try to bug the patch manager about it, but I would guess they should get to it soon.

**Pull request merged**
