### PR TITLE
OCPBUGS-17641,OCPBUGS-18352,OCPBUGS-18549,OCPBUGS-19456,OCPBUGS-17455: [DownstreamMerge] 9-26-23

### PR DESCRIPTION
**Pull request by trozet**
@martinkennelly @s1061123 @JacobTanenbaum @tssurya FYI

### CODE REVIEW

**Comment by trozet** [comment]
/retitle OCPBUGS-18352, OCPBUGS-18549, OCPBUGS-19456, OCPBUGS-17455: [DownstreamMerge] 9-26-23

**Comment by tssurya** [comment]
/retitle OCPBUGS-18352,OCPBUGS-18549,OCPBUGS-19456,OCPBUGS-17455: [DownstreamMerge] 9-26-23

**Comment by tssurya** [comment]
LGTM from my side, waiting for full CI run,

**Comment by martinkennelly** [comment]
LGTM for my commits

**Comment by jluhrsen** [comment]
https://issues.redhat.com/browse/OCPBUGS-19456

**Comment by martinkennelly** [comment]
/retitle OCPBUGS-17641,OCPBUGS-18352,OCPBUGS-18549,OCPBUGS-19456,OCPBUGS-17455: [DownstreamMerge] 9-26-23

Added issue erroneously - that needs https://github.com/ovn-org/ovn-kubernetes/pull/3913

**Comment by martinkennelly** [comment]
/test e2e-vsphere-ovn

CSI driver issues - unrelated issue - panic in the test code.

**Comment by martinkennelly** [comment]
/test e2e-vsphere-windows
"Windows node creation failed" - This job has been relatively stable. Retesting to see if its a flake.

**Comment by tssurya** [comment]
https://github.com/openshift/release/pull/43612 has merged, stable upgrades should have 0 disruption, if someone could verify that is indeed the case... cc @JacobTanenbaum

**Comment by tssurya** [comment]
/lgtm
We need payloads for 4.14, we should be good here in master with some room/flexibility

**Pull request merged**
