### PR TITLE
Bug 2052966: [release-4.8] bump ovn to 20.12.0-193

### PR DESCRIPTION
**Pull request by squeed**
Pick up the fix for https://bugzilla.redhat.com/show_bug.cgi?id=2049011

### CODE REVIEW

**Comment by tssurya** [comment]
> /cherry-pick release-4.8

you meant 4.7 right? :)

**Comment by tssurya** [comment]
/lgtm
per https://bugzilla.redhat.com/show_bug.cgi?id=2049011#c1
seems like 4.9 and higher already have this fix.

**Comment by squeed** [comment]
/cherry-pick release-4.7

thanks @tssurya :bow:

**Comment by dcbw** [comment]
@squeed I've tagged -193 into 4.7 and 4.8; that's what's missing here

**Comment by squeed** [comment]
@knobunc when you get in, can you add the magic labels for this?

**Comment by weliang1** [comment]
cherry-pick-approved

**Pull request merged**
