### PR TITLE
OCPBUGS-1705: [Downstream Merge] - 06-10-2022

### PR DESCRIPTION
**Pull request by tssurya**
Conflicts:
    1) go-controller/pkg/ovn/hybrid_test.go
    Conflict in the import library since we need k8stypes, fmt and runtime
    for the downstream only unit tests.
Screenshot from 2022-10-06 15-09-19

    2) go-controller/pkg/ovn/ovn.go
    Conflict in type namespaceInfo struct positioning - had to keep the hybridoverlay variables in nsInfo

Screenshot from 2022-10-06 15-02-37

    3) go-controller/pkg/ovn/pods.go
    Confict in addLogicalPort around
    https://github.com/ovn-org/ovn-kubernetes/pull/3048/commits/6f6d134f04ac2a9ff9b44ccebcbb0bceb579c2c5#diff-9446f38c60c510407e435ea73659254783cc86dcffd3b05debf078144d430f13L577
    because we seem to have different positions where we call
    oc.addPodToNamespace(pod.Namespace, podIfAddrs) upstream versus
    downstream. This is not related to this PR; seems the difference
    has existed for a long time.

Screenshot from 2022-10-06 14-46-18

### CODE REVIEW

**Comment by tssurya** [comment]
Tagging commit owners: @zshi-redhat @maiqueb (can you also check Cathy's fixes for multihoming that are in this set?) @npinaeva @ricky-rav @flavio-fernandes 
/cc @jcaamano and @trozet

**Comment by tssurya** [comment]
/hold
Let's wait for CI to be fully green...

**Comment by npinaeva** [comment]
/lgtm
conflict resolution looks good

**Comment by tssurya** [comment]
/hold cancel
CI seems to be passing, just that the merge pool got churned since ovn bump went in.

**Comment by tssurya** [comment]
/hold
this didn't get into 4.12.
Opened https://github.com/openshift/ovn-kubernetes/pull/1300

**Pull request closed without merging**
