### PR TITLE
rhel9: bump to ovn23.03-23.03.0-preview.4

### PR DESCRIPTION
**Pull request by dcbw**
Brings performance improvements and some new features, most notable are:

- controller: Flush CT for removed LB backends https://bugzilla.redhat.com/1839103

- northd: 30%+ performance and memory improvement in LB heavy scenarios https://patchwork.ozlabs.org/project/ovn/list/?series=341076&archive=both&state=*

- northd: automatically trim memory when idle

### CODE REVIEW

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

Only error is `fail [k8s.io/kubernetes@v1.26.1/test/e2e/storage/mounted_volume_resize.go:138]: Mar  2 17:20:07.802: While waiting for pvc resize to finish: error while waiting for controller resize to finish: timed out waiting for the condition`

**Comment by dcbw** [comment]
/override ci/prow/4.13-upgrade-from-stable-4.12-e2e-aws-ovn-upgrade

`fail [k8s.io/kubernetes@v1.26.1/test/e2e/storage/mounted_volume_resize.go:138]: Mar  2 17:15:09.761: While waiting for pvc resize to finish: error while waiting for controller resize to finish: timed out waiting for the condition`

**Review by tssurya — APPROVED** [review]
/lgtm

**Comment by dcbw** [comment]
/retest
Infra issues

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows
`FAIL: TestWMCO/create/Services_ConfigMap_validation/Invalid_services_ConfigMap_deletion` is unrelated to this PR

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-windows
FAIL: TestWMCO/create/Services_ConfigMap_validation/Invalid_services_ConfigMap_deletion is unrelated to this PR

/tide refresh

**Pull request merged**
