### PR TITLE
[DownstreamMerge] 11 jul 23

### PR DESCRIPTION
**Pull request by jcaamano**
Conflict on `base_network_controller_pods.go` as `joinSubnetToRoute` and `AddRoutesGatewayIP` where moved to `util/pod_annotation.go`

/cc @dcbw @maiqueb @npinaeva @trozet

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]

**Comment by dcbw** [comment]
V4SubnetAllocationThresholdExceeded alerts introduced by this PR should be fixed by https://github.com/ovn-org/ovn-kubernetes/pull/3760 upstream

**Comment by jcaamano** [comment]
> V4SubnetAllocationThresholdExceeded alerts introduced by this PR should be fixed by [ovn-org/ovn-kubernetes#3760](https://github.com/ovn-org/ovn-kubernetes/pull/3760) upstream

Thanks for the fix @dcbw . Copy paste snafu on my side there.

**Pull request merged**
