### PR TITLE
12-9-20 merge

### PR DESCRIPTION
**Pull request by trozet**
Includes:

1. endpoint slices
2. configurable join subnets
3. subnet metrics
4. fixes gateway init race and gateway ready check

### CODE REVIEW

**Comment by trozet** [comment]
@aojea @abhat @dcbw

**Comment by abhat** [comment]
LGTM.

**Comment by aojea** [comment]
/retest
9 test failed in aws 1 flake 1115 ok

**Comment by aojea** [comment]
failed job has this error
```
versions. Use '=' operator instead.
Error: Unable to find a match: ovn2.13 == 20.09.0-20.el8fd...host == 20.09.0-20.el8fdn ovn2.13-vtep == 20.09.0-20.el8fdn
```

/test e2e-aws-ovn-windows-custom-vxlan

**Pull request merged**
