### PR TITLE
SDN-5297: DownStream Merge Sync from 4.18 [10-31-2024]

### PR DESCRIPTION
**Pull request by jluhrsen**
This is based off of the currently unmerged [[release-4.17] SDN-4919,OCPBUGS-39200: 4.18 merge - 5th Sept](https://github.com/openshift/ovn-kubernetes/pull/2291) PR

### CODE REVIEW

**Comment by jluhrsen** [comment]
> This is based off of the currently unmerged [[release-4.17] SDN-4919,OCPBUGS-39200: 4.18 merge - 5th Sept](https://github.com/openshift/ovn-kubernetes/pull/2291) PR

/hold

**Comment by tssurya** [comment]
This one needs

1. https://github.com/openshift/origin/pull/29259 
2. https://github.com/openshift/origin/pull/29241
3. https://github.com/openshift/origin/pull/29244
4. https://github.com/openshift/origin/pull/29250
5. https://github.com/openshift/cluster-network-operator/pull/2551
6. https://github.com/openshift/cluster-network-operator/pull/2540

Am I missing anything else @trozet and @kyrtapz ?

**Comment by tssurya** [comment]
/retitle SDN-5297: DownStream Merge Sync from 4.18 [10-31-2024]

**Comment by jluhrsen** [comment]
closing in favor of https://github.com/openshift/ovn-kubernetes/pull/2349

**Pull request closed without merging**
