### PR TITLE
Dockerfile: bump to OVS 2.17

### PR DESCRIPTION
**Pull request by dcbw**
Has some DB performance improvements and will be the newest "stable"
FDP release in a week or two.

@jcaamano @tssurya @trozet

### CODE REVIEW

**Comment by tssurya** [comment]
LGTM,
as soon as the currently ART issues are solved

**Comment by dcbw** [comment]
dualstack failed with:
```
 level=debug msg=[INFO] running Terraform command: ocp/ostest/terraform/bin/terraform init -no-color -force-copy -input=false -backend=true -get=true -upgrade=false -plugin-dir=ocp/ostest/terraform/plugins
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed doing terraform init: fork/exec ocp/ostest/terraform/bin/terraform: no such file or directory 
```
/retest

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-ipv6

`level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed doing terraform init: fork/exec ocp/ostest/terraform/bin/terraform: no such file or directory`

**Comment by dcbw** [comment]
/test e2e-metal-ipi-ovn-dualstack 

level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed doing terraform init: fork/exec ocp/ostest/terraform/bin/terraform: no such file or directory

**Pull request merged**
