### PR TITLE
OCPBUGS-29599: Update HostNetworkNamespace address_set for remote zone nodes

### PR DESCRIPTION
**Pull request by tssurya**
CLEAN PICK from https://github.com/openshift/ovn-kubernetes/pull/2073
===
While Interconnect is enabled, it becomes essential to keep address_set specific to HostNetworkNamespace updated when a	remote zone node gets added to the cluster.

This PR is to add/remove management-port IP & node-gateway-router-lrp-ifaddr of both remote and local zone nodes to/from address_set created for HostNetworkNamespace.

Changelog:
- Added a syncMap syncHostNetAddrSetFailed to be used by node event handler. This is required as AddResource event for remote zone nodes are received a lot before than required annotations are set on the node being added.
- addIPToHostNetworkNamespaceAddrsSet is to add management-port IP & node-gateway-router-lrp-ifaddr to address_set while adding both local and remote zone node.
- delIPFromHostNetworkNamespaceAddrsSet is to delete management-port IP & node-gateway-router-lrp-ifaddr from address_set during node deletion for both local and remote zone nodes.
- Above mentioned functions gets called from either AddResource or UpdateResource for NodeType objects.

Jira: https://issues.redhat.com/browse/OCPBUGS-28724
Upstream Issue: https://github.com/ovn-org/ovn-kubernetes/issues/4098

Signed-off-by: Arnab Ghosh <arnabghosh89@gmail.com>
(cherry picked from commit 8cba7dde86c8e1c15320d1327947f27257e0d6ab)

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by jechen0648** [comment]
@arghosh93   I did pre-merge test on the PR, test failed, it is still in bug state, I can not approve the PR.  Please see my comment in OCPBUGS-29599

**Pull request merged**
