### PR TITLE
[release-4.9] Bug 2088630: EgressIP NATs are not being cleared correctly from the logical router

### PR DESCRIPTION
**Pull request by flavio-fernandes**
When handling NAT table updates for EgressIPs, the previous implementation
relied on node from egress ip status field to locate logical router.

Additionally, update of NAT rows did not check logical_port field and
ended up with a SNAT row using the wrong logical router.

Signed-off-by: Flavio Fernandes <flaviof@redhat.com>

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
@kyrtapz @trozet PTAL

**Review by tssurya — APPROVED** [review]
/lgtm

**Pull request merged**
