### PR TITLE
[DownstreamMerge] Downstream merge 2-1-22

### PR DESCRIPTION
**Pull request by trozet**
Passes unit tests

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
AWS jobs all failed with terraform setup issues for Security Groups.

**Comment by dcbw** [comment]
/retest
continued AWS terraform problems

**Comment by trozet** [comment]
aws-ovn-upgrade has some random AWS failures, but 2 jobs failed because:



disruption_tests: [sig-network-edge] Console remains available via cluster ingress using new connections expand_less | 1h9m50s
-- | --
Feb  2 03:15:22.969: ns/openshift-console route/console disruption/ingress-to-console connection/new was unreachable during disruption for at least 1h9m28s of 1h9m49s (maxAllowed=3s):  Feb 02 02:05:33.470 - 3562s E ns/openshift-console route/console disruption/ingress-to-console connection/new ns/openshift-console route/console disruption/ingress-to-console connection/new stopped responding to GET requests over new connections: response did not contain the correct body contents: "<!DOCTYPE html>\n<html lang=\"en\" class=\"no-js\">\n\n  <head>\n    <base href=\"/\">\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n    \n      \n      \n      \n      <title>Red Hat OpenShift</title>\n      <meta name=\"application-name\" content=\"Red Hat OpenShift\">\n      \n      \n      \n      \n\n      \n      <link rel=\"shortcut icon\" href=\"static/assets/openshift-favicon.png\">\n      <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"static/assets/openshift-apple-touch-icon-precomposed.png\">\n      <link rel=\"mask-icon\" href=\"static/assets/openshift-mask-icon.svg\" color=\"#DB242F\">\n      <meta name=\"msapplication-TileColor\" content=\"#000000\">\n      <meta name=\"msapplication-TileImage\" content=\"static/assets/openshift-mstile-144x144.png\">\n      \n    \n\n    <meta name=\"description\" content=\"\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <script type=\"text/javascript\">\n      window.SERVER_FLAGS = {\"consoleVersion\":\"v6.0.6-19278-ge0947a9811\",\"authDisabled\":false,\"kubectlClientID\":\"\",\"basePath\":\"/\",\"loginURL\":\"https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/auth/login\",\"loginSuccessURL\":\"https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/\",\"loginErrorURL\":\"https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/error\",\"logoutURL\":\"https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/auth/logout\",\"logoutRedirect\":\"\",\"multiclusterLogoutRedirect\":\"https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/api/logout/multicluster\",\"requestTokenURL\":\"https://oauth-openshift.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/oauth/token/request\",\"kubeAdminLogoutURL\":\"https://oauth-openshift.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/logout\",\"kubeAPIServerURL\":\"https://api.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com:6443\",\"prometheusBaseURL\":\"/api/prometheus\",\"prometheusTenancyBaseURL\":\"/api/prometheus-tenancy\",\"alertManagerBaseURL\":\"/api/alertmanager\",\"meteringBaseURL\":\"/api/metering\",\"branding\":\"ocp\",\"customProductName\":\"\",\"customLogoURL\":\"\",\"statuspageID\":\"\",\"documentationBaseURL\":\"https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/\",\"alertManagerPublicURL\":\"\",\"grafanaPublicURL\":\"\",\"prometheusPublicURL\":\"\",\"thanosPublicURL\":\"\",\"loadTestFactor\":0,\"inactivityTimeout\":0,\"GOARCH\":\"amd64\",\"GOOS\":\"linux\",\"graphqlBaseURL\":\"/api/graphql\",\"developerCatalogCategories\":\"\",\"userSettingsLocation\":\"configmap\",\"addPage\":\"{}\",\"consolePlugins\":[],\"quickStarts\":\"\",\"projectAccessClusterRoles\":\"\",\"clusters\":[\"local-cluster\"]};\n    </script>\n  <link href=\"static/app-bundle.542f26283d0f8f465dea.css\" rel=\"stylesheet\"><link href=\"static/app-bundle.112daa10103ed8d25261.css\" rel=\"stylesheet\"></head>\n\n  <body class=\"pf-m-redhat-font\">\n    <noscript>JavaScript must be enabled.</noscript>\n    <div id=\"popper-container\"></div>\n    <div id=\"app\"></div>\n  <script type=\"text/javascript\" src=\"static/vendor-patternfly-core-chunk-55986bb23a43cd9578d9.min.js\"></script><script type=\"text/javascript\" src=\"static/main-chunk-3669ca2180551a381ae1.min.js\"></script><script type=\"text/javascript\" src=\"static/runtime~main-bundle-1021971dcafdf1c7cde8.min.js\"></script><script type=\"text/javascript\" src=\"static/vendors~main-chunk-e2eca951b9c7693e7d39.min.js\"></script></body>\n</html>\n" Feb 02 03:04:55.470 - 1s    E ns/openshift-console route/console disruption/ingress-to-console connection/new ns/openshift-console route/console disruption/ingress-to-console connection/new stopped responding to GET requests over new connections: Get "https://console-openshift-console.apps.ci-op-9bz4s5j5-e1d2a.origin-ci-int-aws.dev.rhcloud.com/healthz": read tcp 10.129.125.39:60652->35.165.128.12:443: read: connection reset by peer

**Comment by trozet** [comment]
Same problems are happening for this job in on #902

**Comment by trozet** [comment]
problem is due to a regression in openshift console: https://github.com/openshift/console/pull/10940/files

/override ci/prow/e2e-aws-ovn-upgrade

**Pull request merged**
