### PR TITLE
12-01-2020 merge

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
**- What this PR does and why is it needed**

Master pull from upstream -> downstream

/assign @dcbw @trozet 

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
@trozet / @dcbw : I've rebased as to get the OVN 20 version in this patch...things are looking good! Could you `lgtm` this so that the bot does the retrying?

**Comment by trozet** [comment]
> @trozet / @dcbw : I've rebased as to get the OVN 20 version in this patch...things are looking good! Could you `lgtm` this so that the bot does the retrying?

@alexanderConstantinescu I don't think you needed to rebase. It should automatically merge with the latest HEAD on the next job run.

**Comment by alexanderConstantinescu** [comment]
> > @trozet / @dcbw : I've rebased as to get the OVN 20 version in this patch...things are looking good! Could you `lgtm` this so that the bot does the retrying?
> 
> @alexanderConstantinescu I don't think you needed to rebase. It should automatically merge with the latest HEAD on the next job run.

Hmm, it didn't though. Maybe I should have done a `/retest`. Oh well...

**Pull request merged**
