### PR TITLE
[WIP] DNM: Soak test for 4.7 ovn2.13-20.12.0-24.el8fdp.x86_64

### PR DESCRIPTION
**Pull request by trozet**
Signed-off-by: Tim Rozet <trozet@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
Seems to be working...are we actually intending on bumping this on 4.7?

**Comment by trozet** [comment]
yup @alexanderConstantinescu , closing this and moving to https://github.com/openshift/ovn-kubernetes/pull/451

**Pull request closed without merging**
