### PR TITLE
OCPBUGS-24014: Downstream merge 28th November 2023

### PR DESCRIPTION
**Pull request by dcbw**
Really just pulls in https://github.com/ovn-org/ovn-kubernetes/pull/4012 and an improvement related to https://github.com/openshift/machine-config-operator/pull/4040

### CODE REVIEW

**Comment by dcbw** [comment]
/test e2e-azure-ovn

```
"errorMessage": "Query was throttled with reason: ServerBusy. Requested Metric:AzComputeShoeboxCUS|Shoebox|OS Disk Queue Depth. Output Dimensions: . Dimension Filters: microsoft.resourceGroupName,microsoft.resourceId,microsoft.resourceType,microsoft.subscriptionId. RequestedSamplingType: Count,Sum,NullableAverage. Start time: 11/28/2023 3:45:27 PM End time: 11/28/2023 4:44:27 PM. Resolution: 00:01:00, Last Value Mode: False. Context:MetricsMP, CustomerId:Unknown. TraceID:{a7cbaa9e-d881-48b5-a8c6-8b2eaf369723};AzSubId=d38f1e38-4bed-438e-b227-833f997adf6a;AzResType=Microsoft.Compute/virtualMachines;AzRegion=centralus;, IsUserQuery:1, ClientTimeout:00:01:40, ClientName:GatewayService-API->QueryServiceCoordinator, ElapsedTime(ms):0, Exception:Microsoft.Online.QueryService.Contracts.QueryThrottledException: Query service is overloaded and is not accepting new queries at this time: too many queries in flight.\r\n   at Microsoft.Online.Metrics.QueryServiceCoordinator.Throttling.QueryCapacityThrottlingManager.CheckCapacity(String clientName, Boolean throttlingBypassMode, Boolean isPercentileGroupByQuery, Boolean isDistinctCountGroupByQuery) in D:\\dbs\\sh\\acem\\1019_131421_0\\cmd\\l\\src\\QueryService\\QueryServiceCoordinator\\Throttling\\QueryCapacityThrottlingManager.cs:line 106\r\n   at Microsoft.Online.Metrics.QueryServiceCoordinator.QueryCoordinator.<ExecuteAsync>d__51.MoveNext() in D:\\dbs\\sh\\acem\\1019_131421_0\\cmd\\l\\src\\QueryService\\QueryServiceCoordinator\\QueryCoordinator.cs:line 420.",
```

**Comment by flavio-fernandes** [comment]
/lgtm

```
compared against upstream
git checkout 0384de6421c729b34f5c5a7544c5847d48a9cd2d
```

**Pull request merged**
