### PR TITLE
SDN-5297,SDN-5508: DownStream Merge Sync from 4.18 [11-12-2024]

### PR DESCRIPTION
**Pull request by jluhrsen**
#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold

@surya [mentioned this](https://github.com/openshift/ovn-kubernetes/pull/2335#issuecomment-2451539790) in the previously failed 4.18->4.17 sync:


> This one needs
> 
> https://github.com/openshift/origin/pull/29259
> https://github.com/openshift/origin/pull/29241
> https://github.com/openshift/origin/pull/29244
> https://github.com/openshift/origin/pull/29250
> https://github.com/openshift/cluster-network-operator/pull/2551
> https://github.com/openshift/cluster-network-operator/pull/2540
> https://github.com/openshift/cluster-network-operator/pull/2526 -> also need to backport that
> 
> Am I missing anything else @trozet and @kyrtapz ?

**Comment by maiqueb** [comment]
I'm torn, since this PR to me is already huge, but, shouldn't we also backport https://github.com/openshift/ovn-kubernetes/pull/2345 in it ?...

**Comment by jluhrsen** [comment]
> I'm torn, since this PR is already huge, but, shouldn't we also backport #2345 in it ?...
>  
> Without that, we won't fix https://issues.redhat.com/browse/OCPBUGS-43454, which means localnet virt users will still be unable to upgrade to 4.17.
> 
> @trozet / @jluhrsen

I mean, we can keep adding to this making it bigger and bigger, but it was noted that we can't get the 4.18->4.17 sync in until we have a bunch of other origin and CNO PR backports merged. (see above comment for that list), and I guess the origin PRs have to go in a certain order and I can't get movement on the first one yet...

but, yes, this PR is now 272 commits. I have no idea which of those commits requires the origin/CNO back ports but wondering if there is some set of the first X commits that don't need them and we could make a smaller sync PR to get that in so that we have a smaller PR for this waiting for the other work?

**Comment by jluhrsen** [comment]
> > [openshift/cluster-network-operator#2526](https://github.com/openshift/cluster-network-operator/pull/2526) -> also need to backport that

https://github.com/openshift/cluster-network-operator/pull/2568

**Comment by maiqueb** [comment]
> > > [openshift/cluster-network-operator#2526](https://github.com/openshift/cluster-network-operator/pull/2526) -> also need to backport that
> 
> [openshift/cluster-network-operator#2568](https://github.com/openshift/cluster-network-operator/pull/2568)

Can this 1 commit PR be merged on its own ? If so, let's have it in ! It's CI look very good (.. not used to that ...)

**Comment by maiqueb** [comment]
> > I'm torn, since this PR is already huge, but, shouldn't we also backport #2345 in it ?...
> > Without that, we won't fix https://issues.redhat.com/browse/OCPBUGS-43454, which means localnet virt users will still be unable to upgrade to 4.17.
> > @trozet / @jluhrsen
> 
> I mean, we can keep adding to this making it bigger and bigger, but it was noted that we can't get the 4.18->4.17 sync in until we have a bunch of other origin and CNO PR backports merged. (see above comment for that list), and I guess the origin PRs have to go in a certain order and I can't get movement on the first one yet...
> 
> but, yes, this PR is now 272 commits. I have no idea which of those commits requires the origin/CNO back ports but wondering if there is some set of the first X commits that don't need them and we could make a smaller sync PR to get that in so that we have a smaller PR for this waiting for the other work?

I do understand. The thing is we have 2 weeks to finalize 4.17.2. If we don't get #2345 merged by then, our virt customers won't be able to upgrade to 4.17 ...

**Comment by jluhrsen** [comment]
> > > > [openshift/cluster-network-operator#2526](https://github.com/openshift/cluster-network-operator/pull/2526) -> also need to backport that
> > 
> > 
> > [openshift/cluster-network-operator#2568](https://github.com/openshift/cluster-network-operator/pull/2568)
> 
> Can this 1 commit PR be merged on its own ? If so, let's have it in ! It's CI look very good (.. not used to that ...)

I don't know 🤷🏻‍♂️ 

there is a comment in [[release-4.17] SDN-4930: Adds UDN list/watch to ovnknode rbac](https://github.com/openshift/cluster-network-operator/pull/2540#issuecomment-2464697406) that indicates that 2568 needs to go in right after 2540

So I guess I will try to keep track of both of those and see about getting them to land one after the other.

**Comment by jluhrsen** [comment]
> /lgtm

@maiqueb had to fix some merge conflicts. looks like some extra commits came in to 4.17 since this was first posted so I brought those in to this.

**Comment by jluhrsen** [comment]
we are hitting job timeouts a lot and it makes analyzing our CI a big PITA. I am working on a few things to make this less of a headache. [longer job timeout](https://github.com/openshift/release/pull/59262) and [dnf configs](https://github.com/openshift/ovn-kubernetes/pull/2367) to stop choking on unreachable repos.

as for the 6 failed required jobs:

1. [4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade/1861437699169193984) passed all e2e and upgrade was successful. the job timedout in the gather extra step.
2. [4.17-upgrade-from-stable-4.16-local-gateway-e2e-aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-4.17-upgrade-from-stable-4.16-local-gateway-e2e-aws-ovn-upgrade/1861437699227914240) looks to have cleared all e2e and the upgrade was fine, but the timeout did happen during the e2e/upgrade stage I think.
3. [e2e-aws-ovn-serial](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-aws-ovn-serial/1861437699353743360) was fine with e2e and job timeout happened during a gather post step
4. [e2e-aws-ovn-upgrade-local-gateway](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-aws-ovn-upgrade-local-gateway/1861437699395686400) is the same as #2
5. [e2e-metal-ipi-ovn-dualstack](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-metal-ipi-ovn-dualstack/1861437699475378176)  completely failed the build. something about authentication had trouble. will rerun it below
6. [e2e-metal-ipi-ovn-ipv6](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-metal-ipi-ovn-ipv6/1861437702549803008) failed to install. failure in devscripts-setup. will rerun that below, but that job really only has a [28% pass rate](https://jluhrsen.github.io/PRStats/PreSubmitAnalysisD3.html) right now, so may need to do that a few more times.


/test e2e-metal-ipi-ovn-dualstack
/test e2e-metal-ipi-ovn-ipv6

**Comment by jluhrsen** [comment]
the one failing TP job [e2e-aws-ovn-hypershift-conformance-techpreview](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2349/pull-ci-openshift-ovn-kubernetes-release-4.17-e2e-aws-ovn-hypershift-conformance-techpreview/1861437699269857280) only has failures related to [this storage bug](https://issues.redhat.com/browse/OCPBUGS-44293)

**Comment by npinaeva** [comment]
/retitle SDN-5297,SDN-5508: DownStream Merge Sync from 4.18 [11-12-2024]

**Comment by jluhrsen** [comment]
/hold cancel

this is hopefully ready for review now that we should get a better CI signal

**Comment by jluhrsen** [comment]
new PR for this work is here:
  https://github.com/openshift/ovn-kubernetes/pull/2400

**Pull request closed without merging**
