### PR TITLE
Bug 1868082: 8 14 2020 merge

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@abhat @danwinship

**Comment by aojea** [comment]
This is odd, the aws job 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/234/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1294608621207818240
fails on these tests  
Failing tests:

[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Pre-provisioned PV (ext3)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: vsphere] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount [Suite:openshift/conformance/parallel] [Suite:k8s]

**Comment by danwinship** [comment]
It appears that they failed due to cluster flakiness before even reaching the point where the test code could call `SkipUnlessProviderIs`:

```
Aug 15 13:10:19.825: FAIL: Failed to get kubernetes service ClusterIP: rpc error: code = Unavailable desc = transport is closing

Full Stack Trace
k8s.io/kubernetes/test/e2e.getDefaultClusterIPFamily(0x6b5ec40, 0xc001bc2840, 0x0, 0xc001bc2840)
	@/k8s.io/kubernetes/test/e2e/e2e.go:175 +0x14f
k8s.io/kubernetes/test/e2e.setupSuitePerGinkgoNode()
	@/k8s.io/kubernetes/test/e2e/e2e.go:431 +0xf7
```

There are a ton of flakes in the last run too; I guess these two are just the two tests that failed both times

**Comment by aojea** [comment]
I'm in mobile but seems that start failing before

Aug 15 13:00:00.056 W ns/e2e-deployment-914 pod/webserver-86766955d6-mgngf node/ip-10-0-143-8.ec2.internal reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_webserver-86766955d6-mgngf_e2e-deployment-914_28d55b9f-47ed-472a-b6c9-9af2e21713db_0(3613879d4cab3f9d810ced1e74faeb703b51eef429b3cb63197192d99587c9c4): [e2e-deployment-914/webserver-86766955d6-mgngf:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-deployment-914/webserver-86766955d6-mgngf] failed to configure pod interface: timed out waiting for pod flows for pod: webserver-86766955d6-mgngf, error: timed out waiting for the condition\n'

**Comment by trozet** [comment]
> I'm in mobile but seems that start failing before
> 
> Aug 15 13:00:00.056 W ns/e2e-deployment-914 pod/webserver-86766955d6-mgngf node/ip-10-0-143-8.ec2.internal reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_webserver-86766955d6-mgngf_e2e-deployment-914_28d55b9f-47ed-472a-b6c9-9af2e21713db_0(3613879d4cab3f9d810ced1e74faeb703b51eef429b3cb63197192d99587c9c4): [e2e-deployment-914/webserver-86766955d6-mgngf:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-deployment-914/webserver-86766955d6-mgngf] failed to configure pod interface: timed out waiting for pod flows for pod: webserver-86766955d6-mgngf, error: timed out waiting for the condition\n'

@aojea can you please link the artifacts where you saw this?

**Comment by trozet** [comment]
The only things that I've noticed that look flaky on the networking side are some of the policy tests flake and then I've seen this fail a few times now on AWS:
[sig-network] Networking Granular Checks: Services should update endpoints: http 
[sig-network] Networking Granular Checks: Services should update endpoints: udp

Example here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/234/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1294506192638316544

Took a brief look at that one, and initial glance looks like KAPI access failure.

**Comment by aojea** [comment]
again this errors that Dan mentioned
```
rpc error: code = Unavailable desc = transport is closing
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/234/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1294731604001820672

I think that error is related to apiserver- etcd communications, but I could not verified it

**Comment by aojea** [comment]
something happens with the apiserver, it has lot of logs switching what it seems the etcd endpoints and raise the transport error connection errors later

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/234/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1294731604001820672/artifacts/e2e-aws-ovn/pods/openshift-kube-apiserver_kube-apiserver-ip-10-0-237-5.ec2.internal_kube-apiserver.log

> 0815 21:28:40.444482      17 client.go:360] parsed scheme: "passthrough"
> I0815 21:28:40.444583      17 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.0.237.5:2379  <nil> 0 <nil>}] <nil> <nil>}
> I0815 21:28:40.444612      17 clientconn.go:948] ClientConn switching balancer to "pick_first"
> I0815 21:28:40.444892      17 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc032fa55c0, {CONNECTING <nil>}
> I0815 21:28:40.460900      17 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc032fa55c0, {READY <nil>}
> I0815 21:28:40.481391      17 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> I0815 21:28:41.360682      17 node_authorizer.go:209] "NODE DENY" err="node 'ip-10-0-231-205.ec2.internal' cannot get unknown secret e2e-volumemode-5652/default-dockercfg-pncn7"

**Comment by trozet** [comment]
Looks like gcp job had the same error in the first couple failures then it paseed.

**Comment by trozet** [comment]
Last run only 2 sig storage tests failed

**Comment by aojea** [comment]
/retest
How can we discard if it is ovn or another.component problem?
It's a high number of test failures to have confidence in the quality and stability

**Comment by trozet** [comment]
https://github.com/openshift/ovn-kubernetes/pull/235 proved the transport closing error in AWS was not due to this PR

@danwinship should we override since gcp ovn worked?

**Comment by danwinship** [comment]
yeah, as noted in #forum-sdn, e2e-aws-ovn seems almost 100% broken
/override ci/prow/e2e-aws-ovn
/lgtm

**Pull request merged**
