### PR TITLE
Downstream Merge 2023-8-10

### PR DESCRIPTION
**Pull request by jcaamano**
PTAL @tssurya @bpickard22 @flavio-fernandes 

Got a weird conflict in pkg/ovn/controller/services/lb_config.go on something not delimited with OCP HACK label. Resolved to the best of my ability. Interested parties are @bpickard22 and @tssurya:

```
<<<<<<< HEAD
					routerV4targetips, changed, _ := config.makeNodeRouterTargetIPs(service, &node, config.eps.V4IPs, types.V4HostMasqueradeIP)
					if !routerV4TargetNeedsTemplate && changed {
						routerV4TargetNeedsTemplate = true
					}
					routerV6targetips, changed, _ := config.makeNodeRouterTargetIPs(service, &node, config.eps.V6IPs, types.V6HostMasqueradeIP)
=======
					routerV4targetips, changed := config.makeNodeRouterTargetIPs(&node, config.eps.V4IPs, conf.Gateway.MasqueradeIPs.V4HostMasqueradeIP.String())
					if !routerV4TargetNeedsTemplate && changed {
						routerV4TargetNeedsTemplate = true
					}
					routerV6targetips, changed := config.makeNodeRouterTargetIPs(&node, config.eps.V6IPs, conf.Gateway.MasqueradeIPs.V6HostMasqueradeIP.String())
>>>>>>> upstream/master
```

### CODE REVIEW

**Comment by bpickard22** [comment]
thats a downstream hack that we use to minimize disruption for services

**Comment by tssurya** [comment]
Migration jobs will most likely timeout on ic unless the release pr i have merges... cc @jluhrsen can help with that

**Comment by trozet** [comment]
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration
/override ci/prow/e2e-aws-ovn-shared-to-local-gateway-mode-migration

**Pull request merged**
