### PR TITLE
Revert "[DownstreamMerge] Fix previous downstream merge"

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts openshift/ovn-kubernetes#812.  Upgrade jobs are failing again after this was merged yesterday :-\

### CODE REVIEW

**Comment by deads2k** [comment]
This inadvertently blocked payload promotion because two previously reliable tests 98-99% on aws-ovn-upgrade stopped passing.  To keep payload promotion running we attempt to quickly detect regressions and revert them [Improving CI Signal](https://docs.google.com/document/d/16E0dLFLbLBTe0J4fUd_55I-8bJc9t22BwsdWqFuutaQ/edit).

This one was more complicated because some fixes need to be backported and we update master first to ensure we don't accidentally regress on an upgrade, but for this particular backport we've found an alternative solution.

For the unrevert PR, @petr-muller can create multiple job runs that match the periodic jobs used by payload promotion with upgrade-conformance to run both the upgrade and the e2e-parallel on the upgraded job.

Reference to slack thread: https://coreos.slack.com/archives/C01CQA76KMX/p1636646822105600?thread_ts=1636642773.088500&cid=C01CQA76KMX

/lgtm

**Comment by deads2k** [comment]
the failed update appears to be failing on known OVN failures: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/831/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade/1458851150836011008

the metal ipv6 is also failing on known failures: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/831/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6/1458812860309180416

**Comment by bparees** [comment]
The remaining failing CI jobs match failures that were seen prior to the original PR being introduced (i.e. are not a result of this PR), manually merging to get us back to healthy payloads, in accordance w/ our current process on handling payload-acceptance-blocking regressions(https://docs.google.com/document/d/16E0dLFLbLBTe0J4fUd_55I-8bJc9t22BwsdWqFuutaQ/edit).

Given that the primary concern around reverting this change is/was that it prevents backporting a fix, and we have an accepted path to getting that fix backported independent of this, there seems to be little downside to reverting this change "proactively"

**Pull request merged**
