### PR TITLE
OCPBUGS-5040: [release-4.10] Fix hybrid overlay unit tests

### PR DESCRIPTION
**Pull request by trozet**
Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
Hitting race fixed in  https://github.com/openshift/ovn-kubernetes/pull/1461/

Need to wait for that to propagate down. Also hitting a race in pods completed test.

**Comment by dcbw** [comment]
Unit test failed because only 4.13 has the upstream fix https://github.com/ovn-org/ovn-kubernetes/pull/3250 for a testcase data race.

/test unit

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade
unrelated to this pr

**Pull request merged**
