### PR TITLE
Merge 2021-07-18

### PR DESCRIPTION
**Pull request by trozet**
@fedepaol @jcaamano @astoycos @abhat @alexanderConstantinescu @dcbw FYI

### CODE REVIEW

**Comment by trozet** [comment]
No synthetic failures

/retest

**Comment by trozet** [comment]
@dcbw aws-ovn showed one instance of: 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/609/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1416887054985334784

: [sig-network] pods should successfully create sandboxes by other expand_less | 0s
-- | --
2 failures to create the sandbox  ns/e2e-statefulset-5668 pod/ss-0 node/ip-10-0-177-63.us-west-2.compute.internal - 5.86 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ss-0_e2e-statefulset-5668_2da4f8db-d5aa-4c3f-8c28-101be3f3b2fc_0(1f421d4e535e5a910460de2db32ed2607316320c6a8c1b9991e7661f25fded39): error adding pod e2e-statefulset-5668_ss-0 to CNI network "multus-cni-network": [e2e-statefulset-5668/ss-0:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-statefulset-5668/ss-0 1f421d4e535e5a910460de2db32ed2607316320c6a8c1b9991e7661f25fded39] [e2e-statefulset-5668/ss-0 1f421d4e535e5a910460de2db32ed2607316320c6a8c1b9991e7661f25fded39] failed to configure pod interface: pod OVN annotations changed waiting for OVS port binding for 0a:58:0a:80:03:a0 [10.128.3.160/23] ' ns/e2e-statefulset-5668 pod/ss-0 node/ip-10-0-177-63.us-west-2.compute.internal - 9.86 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ss-0_e2e-statefulset-5668_2da4f8db-d5aa-4c3f-8c28-101be3f3b2fc_0(954add4cb169d1ce25d77b6eb8fc408d5e8c517ed145137945095c93a549767d): error adding pod e2e-statefulset-5668_ss-0 to CNI network "multus-cni-network": [e2e-statefulset-5668/ss-0:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-statefulset-5668/ss-0 954add4cb169d1ce25d77b6eb8fc408d5e8c517ed145137945095c93a549767d] [e2e-statefulset-5668/ss-0 954add4cb169d1ce25d77b6eb8fc408d5e8c517ed145137945095c93a549767d] failed to configure pod interface: pod OVN annotations changed waiting for OVS port binding for 0a:58:0a:80:03:a3 [10.128.3.163/23]

**Comment by trozet** [comment]
another instance on vsphere-ovn:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/609/pull-ci-openshift-ovn-kubernetes-master-e2e-vsphere-ovn/1417112356160278528

```
ns/e2e-statefulset-2737 pod/ss-0 node/ci-op-54fj8rgh-fb62e-5sxj5-worker-rzsq9 - 10.65 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ss-0_e2e-statefulset-2737_9e952dcd-e239-4fe4-8590-075859dcadc2_0(03255bf81d9e3dd58ce4953f00f0361ded0bdd9d85771dfed687e5cc289ae3bd): error adding pod e2e-statefulset-2737_ss-0 to CNI network "multus-cni-network": [e2e-statefulset-2737/ss-0:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[e2e-statefulset-2737/ss-0 03255bf81d9e3dd58ce4953f00f0361ded0bdd9d85771dfed687e5cc289ae3bd] [e2e-statefulset-2737/ss-0 03255bf81d9e3dd58ce4953f00f0361ded0bdd9d85771dfed687e5cc289ae3bd] failed to configure pod interface: pod OVN annotations changed waiting for OVS port binding for 0a:58:0a:80:03:58 [10.128.3.88/23]
```

They are definitely less frequent now @dcbw

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn
/lgtm
failures are known issues and being worked on

**Pull request merged**
