### PR TITLE
Bug 2003245: [4.9] Revert "Add libovsdb clients to controllers & test harness"

### PR DESCRIPTION
**Pull request by dcbw**
This reverts commit 59cb3ee5aac5c6f068c7e518d00a30cb8d797ea1.

The client isn't used for anything yet, but it still registers
update handlers using old inefficient update mechanisms which
significantly increase load on ovsdbserver.

@trozet @alexanderConstantinescu

### CODE REVIEW

**Comment by dcbw** [comment]
/retest e2e-aws-ovn
```
Error: error updating LB Target Group (arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/ci-op-qjgi523l-834bf-8qrp8-aint/3810c9f93f17a86e) tags: error tagging resource (arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/ci-op-qjgi523l-834bf-8qrp8-aint/3810c9f93f17a86e): TargetGroupNotFound: Target groups 'arn:aws:elasticloadbalancing:us-east-1:460538899914:targetgroup/ci-op-qjgi523l-834bf-8qrp8-aint/3810c9f93f17a86e' not found
```

**Comment by trozet** [comment]
/hold 

I think we want this just in 4.9, not 4.10

**Comment by dcbw** [comment]
/hold cancel
I chagned the base branch

**Pull request merged**
