### PR TITLE
SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180,OCPBUGS-4370,OCPBUGS-1715,OCPBUGS-10592,OCPBUGS-12747,OCPBUGS-4485,OCPBUGS-10841: Downstream Merge 6th June 2023

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**
This PR brings in OVN-Interconnect feature, multiple bug fixes and commits, Egress Service CRD feature, CPU Pinning feature.
Not clean,
Conflicts in merge PR:

Conflicts:
	go-controller/pkg/config/config_test.go
because we already brought down
https://github.com/openshift/ovn-kubernetes/commit/d7e5bb9fc45eed2d01bdb9e9dcd4ea862a921b56
	go-controller/pkg/ovn/gateway_init.go
because we already brought down
https://github.com/openshift/ovn-kubernetes/commit/fe63418d89e376a74b11013c37552decc9a3ffc5

in the previous merge

**- Special notes for reviewers**

1. There is one downstream specific commit: https://github.com/openshift/ovn-kubernetes/pull/1697/commits/dcd500354c3ed7a11a5ef36dbc014eead7a06291 that is required to fix tests with the new changes coming in from egress svc CRD feature
2. I had to cherry-pick https://github.com/openshift/ovn-kubernetes/pull/1697/commits/5d2d4730f3e5c0b7960b6cb4ae340f9bd4bf9d46 out of order to ensure unit tests don't panic
3. I had to cherry-pick https://github.com/openshift/ovn-kubernetes/pull/1697/commits/a416d67fcc059d1657579736a6a78dfda220a0c2 an unmerged PR: https://github.com/ovn-org/ovn-kubernetes/pull/3653 from upstream -> as discussed with @trozet we can remove the conflict next time during the merge
4. NEW EDIT AFTER PREVIOUS REVIEW: Had to cherry-pick https://github.com/ovn-org/ovn-kubernetes/pull/3671 to ensure we don't have 2 LE's running at the same time during upgrades.

**- How to verify it**
All tests have to be green

commit owners: @numansiddique @oribon @zeeke @MikeZappa87 @bpickard22 @dceara @trozet @wizhaoredhat @cathy-zhou @ricky-rav @maiqueb @pperiyasamy @martinkennelly @jcaamano @bn222 @JacobTanenbaum @dcbw @tssurya @kyrtapz @DmytroLinkin

### CODE REVIEW

**Comment by tssurya** [comment]
upgrade failed because of: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1697/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade/1666525642855813120 
```
ster-network-liveness connection/new should be available throughout the test expand_less | 1h11m38s
{  ci-cluster-network-liveness-new-connections was unreachable during disruption testing for at least 7s of 1h11m38s (maxAllowed=5s):  }
```
but I think this is known because it was happening long before the previous d/s merge went in

**Comment by jcaamano** [comment]
/title SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180: Downstream Merge 6th June 2023

**Comment by ricky-rav** [comment]
/title SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180,OCPBUGS-4370: Downstream Merge 6th June 2023

**Comment by tssurya** [comment]
/retitle SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180,OCPBUGS-4370: Downstream Merge 6th June 2023

**Comment by martinkennelly** [comment]
/retitle SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180,OCPBUGS-4370,OCPBUGS-1715: Downstream Merge 6th June 2023

**Comment by tssurya** [comment]
I am re-running the stable upgrades because the failure seems suspicious:
```
{Failed: Passed 5 times, failed 5 times.  (P95=23.90s requiredPasses=6 successes=[1667853903502249984=12s 1667853904861204480=9s 1667853907126128640=6s 1667853904408219648=14s 1667853905318383616=0s] failures=[1667853906681532416=72s 1667853903951040512=578s 1667853906224353280=267s 1667853905767174144=111s 1667853903049265152=75s])  name: service-load-balancer-with-pdb-new-connections disruption P95 should not be
  worse
testsuitename: aggregated-disruption
summary: 'Failed: Passed 5 times, failed 5 times.  (P95=23.90s requiredPasses=6 successes=[1667853903502249984=12s
  1667853904861204480=9s 1667853907126128640=6s 1667853904408219648=14s 1667853905318383616=0s]
  failures=[1667853906681532416=72s 1667853903951040512=578s 1667853906224353280=267s
  1667853905767174144=111s 1667853903049265152=75s])'
```
how can we be fast on 5 runs but sooo slow on the other 5 runs? Re-running to ensure its not AWS infra at fault here.

**Comment by tssurya** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade 10

**Comment by tssurya** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by trozet** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade 10

**Comment by trozet** [comment]
@dgoodwin aggregator is now passing. We figured out the issue and fixed it in an extra commit. This is ready to go in. Will wait for you to remove hold when ready on your side.

**Comment by tssurya** [comment]
> @dgoodwin aggregator is now passing. We figured out the issue and fixed it in an extra commit. This is ready to go in. Will wait for you to remove hold when ready on your side.

haha yea its so green now :) +1 this one is ready for merge!

**Comment by martinkennelly** [comment]
/retitle SDN-3733,SDN-3838,SDN-3840,OCPBUGS-11180,OCPBUGS-4370,OCPBUGS-1715,OCPBUGS-10592,OCPBUGS-12747,OCPBUGS-4485,OCPBUGS-10841: Downstream Merge 6th June 2023

**Pull request merged**
