### PR TITLE
OCPBUGS-45343: Dockerfile: Update OVN to the 24.03.2-32.el9fdp minor release.

### PR DESCRIPTION
**Pull request by igsilya**
It is the most recent release of 24.03 with all the latest bug fixes. See the jira for more details.

### CODE REVIEW

**Comment by anuragthehatter** [comment]
Not worried looking at e2e-aws-ovn-fdp-qe results, skipped one's are ok as usual and couple fo failures appears to be env or flake issues. Re-ran locally looks good. @igsilya Feel free to override those from QE behalf

**Comment by asood-rh** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2377/pull-ci-openshift-ovn-kubernetes-release-4.16-e2e-aws-ovn-fdp-qe/1864320142947651584/artifacts/e2e-aws-ovn-fdp-qe/

<pre>
openshift-extended-test:
  total: 52
  failures: 0
  errors: 0
  skipped: 2
cucushift-e2e:
  total: 25
  failures: 0
  errors: 0
  skipped: 2
</pre>

/label qe-approved

**Comment by igsilya** [comment]
Just for completeness.
/test e2e-aws-ovn-fdp-qe

**Pull request merged**
