### PR TITLE
Bug 1954773: adding cli flag for egressfirewall and removing CRD watcher

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
cherry-picked three commits from upstream ovn-kube to apply cleanly and solve the problem 

[c37c866f78765dfe15fb06943ead64d0723fedba](https://github.com/ovn-org/ovn-kubernetes/commit/c37c866f78765dfe15fb06943ead64d0723fedba) -  change the egressFirewall to use a cli flag instead of dynamically turn
    on from watching CRDs

[2e870eb23259c71216bb56895d63394d84166527](https://github.com/ovn-org/ovn-kubernetes/commit/2e870eb23259c71216bb56895d63394d84166527) - Remove node-side egress IP clients to help everything apply cleanly

[f9af29bbd67dda81d7091c9651cef0cb3b1ff895](https://github.com/ovn-org/ovn-kubernetes/commit/f9af29bbd67dda81d7091c9651cef0cb3b1ff895) - remove the CRD watch and related bits as they are no longer needed

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by alexanderConstantinescu — COMMENTED** [review]
This is more of a question, but why do we need commit: `Remove node-side egress IP clients` for this patch?

**Review by alexanderConstantinescu — APPROVED** [review]
> This is more of a question, but why do we need commit: `Remove node-side egress IP clients` for this patch?

Actually, never mind I can answer my own question: "because `remove the CRD watch and related bits as they are no longer needed ` also touched `pkg/node/ovn_test.go` which means we need that commit to cleanly cherry-pick"

/lgtm

**Comment by knobunc** [comment]
@JacobTanenbaum can you see if you can work out what is wrong with the Windows test?  It seems to fail for everyone.  Perhaps Jamo has some insight.

**Comment by knobunc** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

This is being tracked separately.

**Comment by dcbw** [comment]
ovn-windows is known AMI issue in AWS

/override ci/prow/e2e-aws-ovn-windows
/override ci/prow/4.8-upgrade-from-stable-4.7-e2e-aws-ovn-upgrade
/retest

**Comment by dcbw** [comment]
dual-stack failure is https://github.com/openshift/machine-config-operator/pull/2580

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-ovn-windows
/override ci/prow/e2e-metal-ipi-ovn-dualstack

There is another PR open to fix the test failures.

**Pull request merged**
