### PR TITLE
[4.4] 5-15-2020 merge - Includes hybrid overlay external gateway

### PR DESCRIPTION
**Pull request by dcbw**
@rcarrillocruz @trozet @danwinship

### CODE REVIEW

**Comment by dcbw** [comment]
`The HAProxy router should set Forwarded headers appropriately ` is a known flake in 4.4 that has been disabled in 4.5 because the test is not correct.  https://bugzilla.redhat.com/show_bug.cgi?id=1812960#c17

**Comment by sdodson** [comment]
#167 is being used instead based on slack.
/retitle [4.4] 5-15-2020 merge - Includes hybrid overlay external gateway

**Comment by knobunc** [comment]
Closing because we chose the smaller cherry-pick rather than the full rebase.   https://github.com/openshift/ovn-kubernetes/pull/167

**Pull request closed without merging**
