### PR TITLE
[release-4.13] OCPBUGS-27257: Ensure session affinity cleanup on backend removal

### PR DESCRIPTION
**Pull request by npinaeva**
Backport of https://github.com/openshift/ovn-kubernetes/pull/2021
Use ovn version 23.06.1-82.el9fdp

### CODE REVIEW

**Comment by mffiedler** [comment]
Successfully tested pre-merge with this PR and the procedure at Tested pre-merge using the linked PR.    Test procedure is found in the original bug at https://issues.redhat.com/browse/OCPBUGS-26023?focusedId=23752131&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23752131

With the PR, session affinity is maintained after deleting the pod which was backend for the svc.

**Review by trozet — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
