### PR TITLE
Bug 1956318: Revert "removing the hybrid overlay externalGW code"

### PR DESCRIPTION
**Pull request by trozet**
Adds back external gw code via hybrid overlay. Also includes various missing unit test fixes downstream that were causing lint and formatting issues.

### CODE REVIEW

**Comment by dcbw** [comment]
Compared 4.7 before exGW revert to this PR:

```
git checkout release-4.7
git reset --hard 05894787208a828410c27302e24f57e012a2a44c
git diff ..trozet/bz1956318 go-controller/hybrid-overlay/ go-controller/pkg/ovn/ovn.go go-controller/pkg/ovn/pods.go
```

and only differences are in pkg/ovn/ovn.go and pods.go. hybrid-overlay code is exactly the same.

/lgtm

**Comment by trozet** [comment]
thanks @dcbw

**Pull request merged**
