### PR TITLE
Bug 1841828: Upstream merge 2020-06-17

### PR DESCRIPTION
**Pull request by dcbw**
Sync downstream master with upstream.

@openshift/networking

### CODE REVIEW

**Comment by squeed** [comment]
Tests are probably going to fail until the MCO pr that reverts openvswitch merges.

**Comment by trozet** [comment]
@dcbw why the revert for conntrack entries removal?

**Comment by dcbw** [comment]
@trozet Jacob and I identified some issues with that PR upstream that were causing the downstream CI failures. @JacobTanenbaum is preparing an upstream PR to fix those.

**Pull request merged**
