### PR TITLE
OCPBUGS-36865,SDN-4919,OCPBUGS-36614: [DownstreamMerge] 29 July 2024

### PR DESCRIPTION
**Pull request by npinaeva**
Revert https://github.com/openshift/ovn-kubernetes/pull/2243, aka re-apply https://github.com/openshift/ovn-kubernetes/pull/2233
clean merge

### CODE REVIEW

**Comment by tssurya** [comment]
/retitle SDN-4919,OCPBUGS-36614: [DownstreamMerge] 29 July 2024

**Comment by tssurya** [comment]
tech preview has passed: https://pr-payload-tests.ci.openshift.org/runs/ci/47e23e80-502b-11ef-8d22-147fe03cc8c9-0
waiting for other payloads to finish

**Comment by neisw** [comment]
FYI Though there are failures in your blocking jobs I think they are all seen outside of this pr as well.

[azure ci failures](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-azure-ovn-upgrade/1819205618557259776)
[azure nightly failures](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade/1819205703332532224)
[hypershift ci failures](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-ovn-kubernetes-2241-periodics-e2e-aws-ovn/1819205648840134656)
[metal nightly](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-ovn-kubernetes-2241-nightly-4.17-e2e-metal-ipi-ovn-bm/1819205781313032192) [InsufficientResources](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/openshift-ovn-kubernetes-2241-nightly-4.17-e2e-metal-ipi-ovn-bm/1819205781313032192/artifacts/e2e-metal-ipi-ovn-bm/gather-extra/artifacts/machines.json)
Are all things we see in our release controller payloads so not suspect

[fips nightly failure](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-ovn-kubernetes-2241-nightly-4.17-fips-payload-scan/1819205778804838400) looks to be CI related 
[e2e-gcp-ovn-rt-upgrade nightly failure](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-gcp-ovn-rt-upgrade/1819205731799273472) appears frequently in your [presubmits](https://sippy.dptools.openshift.org/sippy-ng/jobs/Presubmits/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22job%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22pull-ci-openshift-ovn-kubernetes-master-4.17-upgrade-from-stable-4.16-e2e-gcp-ovn-rt-upgrade%22%7D%5D%7D) outside of this PR as well.

**Comment by tssurya** [comment]
thanks so much @neisw !! that's good to know yeah and definitely helps us understand if its us or not.
Once the rt-upgrade on gcp passes we'll get this PR in

**Comment by tssurya** [comment]
/retitle OCPBUGS-36865,SDN-4919,OCPBUGS-36614: [DownstreamMerge] 29 July 2024

**Comment by tssurya** [comment]
/override ci/prow/4.17-upgrade-from-stable-4.16-e2e-gcp-ovn-rt-upgrade

**Pull request merged**
