### PR TITLE
[release-4.12] OCPBUGS-3399: Drop in-cluster traffic towards svcCIDR at wrong port

### PR DESCRIPTION
**Pull request by tssurya**
This PR fixes two traffic flows:

1) podCIDR to svcCIDR:unexposedPort. This flow currently sends the packets towards br-ex in both gateway modes since OVN LB's won't DNAT and OVN doesn't know what to do then other than to send these packets out. However the argument here is svcCIDR is a private range, these packets shouldn't be sent outside. Hence like SDN let's drop them.

2) nodeCIDR to svcCIDR:unexposedPort. Same as above.

Fix: Add a new flow at 105 priority right above the default 100 priority flow (that sends the pkt out to primary interface if coming from OVN) which will drop it instead of sending it out the primary interface.

 cookie=0xdeff105, duration=7804.947s, table=0, n_packets=18, n_bytes=1332, idle_age=6984, priority=105,ip,in_port=2,nw_dst=10.96.0.0/16 actions=drop
 cookie=0xdeff105, duration=7804.947s, table=0, n_packets=0, n_bytes=0, idle_age=7804, priority=100,ip,in_port=2 actions=ct(commit,zone=64000,exec(load:0x1->NXM_NX_CT_MARK[])),output:1

This has been tested for both traffic flows on both SGW and LGW modes.

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit e5d3e3f3f992bca605a6c194b9209656fe063a40)

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by flavio-fernandes — COMMENTED** [review]
/lgtm

TY for staying on top of the backports, @tssurya !

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by tssurya** [comment]
Failure in dualstack job is unrelated:
```
: [sig-network][Feature:EgressFirewall] when using openshift ovn-kubernetes should ensure egressfirewall is created [Suite:openshift/conformance/parallel]
```
This is I think: https://issues.redhat.com/browse/OCPBUGS-4425 bug so we can skip this job.

**Comment by jcaamano** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

Due to https://issues.redhat.com//browse/OCPBUGS-4425

**Comment by tssurya** [comment]
err the gcp-ovn had passed in the first go of this PR, very strange its not passing now.

**Comment by dcbw** [comment]
/retest-required
All issues are unrelated to this PR (RPM mirror problems, known dual-stack EgressFW issue that's being backported, etc)

**Comment by dcbw** [comment]
/override  ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade
due to the image caching errors with loki-promtail

**Comment by dcbw** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade
Failures are unrelated to this PR

**Pull request merged**
