### PR TITLE
[DNM] EIP on non-OVN managed networks (pre)merge testing

### PR DESCRIPTION
**Pull request by martinkennelly**
/cc

### CODE REVIEW

**Comment by martinkennelly** [comment]
Tests passed - resync with changes u/s

**Comment by trozet** [comment]
/retitle [DNM] EIP on non-OVN managed networks (pre)merge testing

**Comment by martinkennelly** [comment]
Refreshed with latest Upstream changes.

**Comment by martinkennelly** [comment]
/test e2e-metal-ipi-ovn-dualstack 
Init cluster failure

**Pull request closed without merging**
