### PR TITLE
OCPBUGS-44379: Revert "Pin libreswan to the known working version 4.5"

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by huiran0826** [comment]
Tested this PR on a fresh install cluster, libreswan version got reverted to 4.9
```
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-0.ci.test-2024-11-11-033317-ci-ln-54c8m2b-latest   True        False         48m     Cluster version is 4.14.0-0.ci.test-2024-11-11-033317-ci-ln-54c8m2b-latest
% oc rsh -n openshift-ovn-kubernetes ovn-ipsec-containerized-58dwp  
Defaulted container "ovn-ipsec" out of: ovn-ipsec, ovn-keys (init)
sh-5.1# ipsec --version
Libreswan 4.9
```
IPSec regression passed https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1065777/console

**Comment by zshi-redhat** [comment]
cc @jcaamano @yuvalk @trozet could you take a quick look at this one. Pinning libreswan to 4.5 regresses CVEs, need to revert the change.

**Comment by yuvalk** [comment]
/lgtm

though
pinning regresses CVEs,
but using latest is not usable

**Comment by wking** [comment]
I changed the `blocks` link to `relates to`.

/jira refresh

**Pull request merged**
