### PR TITLE
Bug 2097243: Fix egressips for pods recreated with same name

### PR DESCRIPTION
**Pull request by tssurya**
EIP handler uses logicalPortCache for getting pod's
portInfo. Since cache removes entries only 60 seconds
after deletion, its possible that when pod is recreated
with the same name within the 60seconds timer, stale
info gets used to create SNATs and reroutes for the eip pods

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit 13f3f3f9f11ba9e28b9c824e0d34f40c064a6638)

Clean Cherry Pick

### CODE REVIEW

**Comment by tssurya** [comment]
ipi-ovn-dualstack job failing because of:
```
: node count should match or exceed machine count expand_less	0s
{  
          Timed out waiting for node count (5) to equal or exceed machine count (6).
          NAMESPACE               NAME                          PHASE         TYPE   REGION   ZONE   AGE
openshift-machine-api   ostest-9gzzc-master-0         Running                              60m
openshift-machine-api   ostest-9gzzc-master-1         Running                              60m
openshift-machine-api   ostest-9gzzc-master-2         Running                              60m
openshift-machine-api   ostest-9gzzc-worker-0-njmjc   Running                              43m
openshift-machine-api   ostest-9gzzc-worker-0-rvwqm   Provisioned                          43m
openshift-machine-api   ostest-9gzzc-worker-0-v5b47   Running                              43m
          NAME                                 STATUS   ROLES    AGE   VERSION
master-0.ostest.test.metalkube.org   Ready    master   47m   v1.24.0+bd7662a
master-1.ostest.test.metalkube.org   Ready    master   47m   v1.24.0+bd7662a
master-2.ostest.test.metalkube.org   Ready    master   47m   v1.24.0+bd7662a
worker-0.ostest.test.metalkube.org   Ready    worker   30m   v1.24.0+bd7662a
worker-1.ostest.test.metalkube.org   Ready    worker   29m   v1.24.0+bd7662a
        }

```
F1: [https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kuberne[…]tes-master-e2e-metal-ipi-ovn-dualstack/1544741112055336960](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1169/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1544741112055336960)
F2: [https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kuberne[…]tes-master-e2e-metal-ipi-ovn-dualstack/1545031688029999104](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1169/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1545031688029999104)
Opened https://bugzilla.redhat.com/show_bug.cgi?id=2105003 to track this.

**Comment by jcaamano** [comment]
Does not seem related at all.

/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
