### PR TITLE
OCPBUGS-2303: [4.11] Stale chassis are not removed

### PR DESCRIPTION
**Pull request by bn222**
Missing backport

### CODE REVIEW

**Comment by bn222** [comment]
@pliurh

**Comment by bn222** [comment]
@zshi-redhat

**Comment by trozet** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-e2e-aws-ovn-upgrade
/override ci/prow/4.12-upgrade-from-stable-4.11-images
/override ci/prow/4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade

**Comment by trozet** [comment]
/override ci/prow/4.12-upgrade-from-stable-4.11-local-gateway-images

**Pull request merged**
