### PR TITLE
Bug 1798613: OVN: Bump image to include ovn2.12

### PR DESCRIPTION
**Pull request by pecameron**
SDN-643
https://issues.redhat.com/browse/SDN-643

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@knobunc PTAL

**Comment by pecameron** [comment]
@dcbw PTAL
Tests fail on unmodified version. Not sure how to test this in CI getting cno to pick up this image.

**Comment by pecameron** [comment]
@danwinship @rcarrillocruz PTAL

**Comment by danwinship** [comment]
from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/72/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/164/artifacts/e2e-aws-ovn/pods/openshift-ovn-kubernetes_ovnkube-node-vd9rj_ovnkube-node.log:
    time="2020-01-17T12:34:07Z" level=fatal msg="unknown pid for ovn-controller process: open /var/run/ovn/ovn-controller.pid: no such file or directory"

**Comment by danwinship** [comment]
@pecameron see my comment above; not all of the failures are flakes. Some of them are failing because of the new pid file paths

**Comment by pecameron** [comment]
@danwinship Thanks for spotting that, I am looking into it.

**Comment by dcbw** [comment]
@pecameron any update on this? would be good to get this in sooner as the IPv6 stuff depends on it.

**Comment by pecameron** [comment]
@dcbw cno pr 445 needs to get in then we can see if this works. PR445 works in ci at present (using ovn2.11) so it s safe to merge. I have been trying to test ovn2.12 using a cobbled together built based on fedora whith ovn2.12. There have been numerous infrastructure problems with aws last week (often times nodes don't get created). Maybe we should just merge 445 and re-test this.

**Pull request merged**
