### PR TITLE
SDN-3732,SDN-3733,OCPBUGS-12747,OCPBUGS-16413,OCPBUGS-10650: [DownstreamMerge] 7-19-23

### PR DESCRIPTION
**Pull request by pperiyasamy**
/assign @npinaeva

### CODE REVIEW

**Comment by pperiyasamy** [comment]
/hold
/assign @jechen0648 
This [change](https://github.com/openshift/ovn-kubernetes/pull/1750/commits/8dd5d2e3b109bfe328e6d5cecf3050860c70fbba#diff-f706ecf5fbc17ede0f5a27577b1d4b3c08c00fe2837f6c1be461503de71ce21bR1073) seems to be introducing new bug [OCPBUGS-16413](https://issues.redhat.com/browse/OCPBUGS-16413) on egressip failover. must need to relax this on node name check.

**Comment by qinqon** [comment]
e2e-aws-ovn failing on capacity 
```
We currently do not have sufficient m6a.xlarge capacity in the Availability Zone y
```

**Comment by qinqon** [comment]
The part delated to live-migration is working as expected
- The kubevirt provider job "ci/prow/e2e-aws-ovn-kubevirt" is green 
- The normal jobs are parsing dns-service-namespace and dns-service-name as expected without warnings.

**Comment by qinqon** [comment]
This is closing SDN-3732 too, can we modify the description ?

**Comment by qinqon** [comment]
/retitle SDN-3732,SDN-3733,OCPBUGS-12747,OCPBUGS-16413,OCPBUGS-10650: [DownstreamMerge] 7-19-23

**Comment by qinqon** [comment]
CI failing at openshift/tools imagebackoff 

https://prow.ci.openshift.org/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fbaremetalds-e2e-test%2Fartifacts%2Fjunit%2Fjunit_e2e__20230724-152631.xml%22%2C%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fbaremetalds-e2e-test%2Fartifacts%2Fjunit_nodes.xml%22%2C%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fbaremetalds-packet-setup%2Fartifacts%2Fjunit_metal_setup.xml%22%2C%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_install_status.xml%22%2C%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_symptoms.xml%22%2C%22artifacts%2Fe2e-metal-ipi-ovn-ipv6%2Fgather-must-gather%2Fartifacts%2Fjunit_install.xml%22%2C%22artifacts%2Fjunit_operator.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Forigin-ci-test%2Fpr-logs%2Fpull%2Fopenshift_ovn-kubernetes%2F1750%2Fpull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6%2F1683468923749535744%22%7D&topURL=https%3A//prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1750/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-ipv6/1683468923749535744&lensIndex=2#

**Comment by jcaamano** [comment]
nightly job is also failing due to the same reason

[https://sippy.dptools.openshift.org/sippy-ng/jobs/4.14/runs?filters=%7B%22items%22%3A%5B%7[…]-ipi-ovn-ipv6%22%7D%5D%7D&sortField=timestamp&sort=desc](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.14/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6%22%7D%5D%7D&sortField=timestamp&sort=desc)

**Comment by tssurya** [comment]
should we override this if we know exactly what's failing? we know `e2e-metal-ipi-ovn-dualstack` passes this PR...

**Comment by qinqon** [comment]
> should we override this if we know exactly what's failing? we know `e2e-metal-ipi-ovn-dualstack` passes this PR...

Fine by me, @jcaamano are you ok overriding it ?

**Comment by jcaamano** [comment]
The jobs has passed for CNO here
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1893/pull-ci-openshift-cluster-network-operator-master-e2e-metal-ipi-ovn-ipv6/1683753524493553664

**Pull request merged**
