### PR TITLE
OCPBUGS-19501: Add additonal certificate acceptance condition feature in ovnkube-ide…

### PR DESCRIPTION
**Pull request by s1061123**

### CODE REVIEW

**Comment by kyrtapz** [comment]
Most of the CI failures seem to be related to image registry issues:
```
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-fpzz18dq/pipeline@sha256:ff5716ed9d36549cd92b49c05fd93e7bae0b1dc7c0b148a031c04fd7b19995a5...
error: error creating buildah builder: initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-fpzz18dq/pipeline@sha256:ff5716ed9d36549cd92b49c05fd93e7bae0b1dc7c0b148a031c04fd7b19995a5: reading manifest sha256:ff5716ed9d36549cd92b49c05fd93e7bae0b1dc7c0b148a031c04fd7b19995a5 in image-registry.openshift-image-registry.svc:5000/ci-op-fpzz18dq/pipeline: received unexpected HTTP status: 500 Internal Server Error
...
...
* 2023-09-21T14:47:44Z 3x kubelet: Pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-ldqxz36v/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a"
* 2023-09-21T14:47:45Z 3x kubelet: Failed to pull image "image-registry.openshift-image-registry.svc:5000/ci-op-ldqxz36v/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a": rpc error: code = Unknown desc = fetching target platform image selected from manifest list: reading manifest sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc in image-registry.openshift-image-registry.svc:5000/ci-op-ldqxz36v/pipeline: manifest unknown: manifest unknown
* 2023-09-21T14:47:45Z 3x kubelet: Error: ErrImagePull
* 2023-09-21T14:46:39Z 1x kubelet: Container image "gcr.io/k8s-prow/sidecar:v20230920-7b72c6f3a0" already present on machine
* 2023-09-21T14:46:40Z 1x kubelet: Created container sidecar
* 2023-09-21T14:46:40Z 1x kubelet: Started container sidecar
* 2023-09-21T15:11:42Z 106x kubelet: Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-ldqxz36v/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a"
* 2023-09-21T14:47:06Z 3x kubelet: Error: ImagePullBackOff 
[36mINFO[0m[2023-09-21T15:16:38Z] Step e2e-aws-ovn-windows-ipi-conf failed after 30m1s. 
[36mINFO[0m[2023-09-21T15:16:38Z] Step phase pre failed after 30m1s.  
```

/retest-required

**Comment by jcaamano** [comment]
/override ci/prow/e2e-vsphere-windows 

This job passed before on the same set of changes. The last attempt failed due to infra related issue, not related to these changes.

**Comment by jcaamano** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack
/override ci/prow/e2e-metal-ipi-ovn-ipv6

Overriding jobs that passed before on the same changeset.

**Pull request merged**
