### PR TITLE
OCPBUGS-18572,OCPBUGS-19331,OCPBUGS-16641: [DownstreamMerge] 9-18-23

### PR DESCRIPTION
**Pull request by kyrtapz**

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
/retitle OCPBUGS-19331,OCPBUGS-16641: [DownstreamMerge] 9-18-23

**Comment by flavio-fernandes** [comment]
/lgtm

```
❯ git diff kyrtapz-merge-9-18-23 | wc -l
0

❯ git rev-parse HEAD
c6e197ccc3a9fe2032b001603193b8598fee706f
```

**Comment by trozet** [comment]
/retitle OCPBUGS-18572,OCPBUGS-19331,OCPBUGS-16641: [DownstreamMerge] 9-18-23

**Pull request merged**
