### PR TITLE
OCPBUGS-8741: [release-4.13] Handle Completed pods deletion

### PR DESCRIPTION
**Pull request by zeeke**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

Backport of:
- https://github.com/ovn-org/ovn-kubernetes/pull/3433

### CODE REVIEW

**Comment by zeeke** [comment]
@zhaozhanqi @anuragthehatter 
can you review this and add `cherry-pick-approved` ?

**Comment by dcbw** [comment]
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

https://redhat-internal.slack.com/archives/C01CQA76KMX/p1678449206350089

**Pull request merged**
