### PR TITLE
[release-4.10] Bug 2070392: Fix egress IP reassignment on cloud

### PR DESCRIPTION
**Pull request by kyrtapz**
Clean backport of two commits from: https://github.com/ovn-org/ovn-kubernetes/pull/2897 which got into 4.11 here: https://github.com/openshift/ovn-kubernetes/pull/1040

The last commit was already backported here: https://github.com/openshift/ovn-kubernetes/pull/1098

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/approve

**Comment by anuragthehatter** [comment]
@huiran0826 can you PTAL? thanks

**Comment by huiran0826** [comment]
> @huiran0826 Are you ok with adding cherry-pick-approved for this one?

Sorry, I missed this PR, added cherry-pick-approved

**Pull request merged**
