### PR TITLE
Bug 2111733: Bump OVN to 22.06.0-27

### PR DESCRIPTION
**Pull request by tssurya**
Bump OVN to 22.06.0-27 to get https://patchwork.ozlabs.org/project/ovn/patch/20220727221505.1673659-1-hzhou@ovn.org/ in.

### CODE REVIEW

**Comment by dcbw** [comment]
(have to wait for RPM mirrors to sync after the cross-tag, image builds will fail for a couple hours)

**Comment by tssurya** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1222/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1554054347992600576 is failing because of https://bugzilla.redhat.com/show_bug.cgi?id=2105003

**Pull request merged**
