### PR TITLE
[release-4.6] Bug 1953088: master: Delay deleting Namespace's address set for 20 seconds

### PR DESCRIPTION
**Pull request by squeed**
Manual cherry-pick of  #507. Needed a bit of massaging,

### CODE REVIEW

**Comment by squeed** [comment]
Not good - `NoRunningOvnMaster` is firing in a bunch of clusters. Weird.

**Comment by squeed** [comment]
Aha, https://github.com/openshift/cluster-network-operator/pull/1096/ needs to merge.

**Comment by squeed** [comment]
test failures are all uninteresting or infrastructure issues...
/retest

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 2.30

approved

**Pull request merged**
