### PR TITLE
[release-4.14] OCPBUGS-24326: APB External Route: Add IPv4 and IPv6 validation in CRD schema for static hop IP field

### PR DESCRIPTION
**Pull request by jordigilh**
Backport cherry picked from 4.15. Upstream https://github.com/ovn-org/ovn-kubernetes/pull/3994

@npinaeva @jcaamano PTAL.

### CODE REVIEW

**Comment by npinaeva** [comment]
/retitle [release-4.14] OCPBUGS-24326: APB External Route: Add IPv4 and IPv6 validation in CRD schema for static hop IP field

**Comment by jordigilh** [comment]
@jcaamano @trozet can any of you approve this back port fix for APB for 4.14? Thanks 😄

**Pull request merged**
