### PR TITLE
Bug 1888827: 11-13-2020 merge

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by trozet** [comment]
@juanluisvaladas @tssurya another prom alert issue:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/317/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1319395856822046720

**Comment by juanluisvaladas** [comment]
@trozet This is a legit failure that won't happen once we get this merged: https://github.com/openshift/cluster-network-operator/pull/841

**Comment by dcbw** [comment]
https://github.com/openshift/cluster-network-operator/pull/841 has now merged

**Comment by trozet** [comment]
@abhat @dcbw @vishnoianil I think there is something wrong with the commits for reject ACL. Removing those 2 commits and everything is passing here:
https://github.com/openshift/ovn-kubernetes/pull/328

**Comment by trozet** [comment]
now that https://github.com/openshift/cluster-network-operator/pull/772 is merged, lets try again and see if it reveals anything why the console and authentication pods are cannot use routes:

```

E1102 22:33:50.648360       1 auth.go:235] error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.ci-op-vsv115gs-834bf.origin-ci-int-aws.dev.rhcloud.com/oauth/token failed: Head https://oauth-openshift.apps.ci-op-vsv115gs-834bf.origin-ci-int-aws.dev.rhcloud.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by trozet** [comment]
Still a problem on GCP with reject ACL. Looks like it happens because of ovnkube-master restarting:

```172.30.1.143:443 service ip
35.185.81.234 external IP

I1109 20:58:05.831454       1 service.go:385] Service Reject ACL created for ClusterIP service: router-default, namespace: openshift-ingress, via: TCP:172.30.1.143:443, ACL UUID: 1811f9c0-1c05-4030-b425-11c44c1dc3e9

I1109 21:01:59.014637       1 kube.go:63] Setting annotations map[k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.128.6.5/23"],"mac_address":"0a:58:0a:80:06:05","gateway_ips":["10.128.6.1"],"ip_address":"10.128.6.5/23","gateway_ip":"10.128.6.1"}}] on pod openshift-ingress/router-default-84f94bcf49-7525c
I1109 21:01:59.297283       1 pods.go:272] [openshift-ingress/router-default-84f94bcf49-7525c] addLogicalPort took 282.797247ms

I1109 21:02:14.254335       1 endpoints.go:47] Adding endpoints: router-default for namespace: openshift-ingress

###ovnkube master restarts

I1109 21:03:28.530176       1 service.go:172] Service Sync: Removing OVN stale reject ACL: 70e72625-7284-4b8d-a589-bb6c2b91ed76-172.30.1.143:443
2020-11-09T21:03:28.534Z|00207|nbctl|INFO|Running command run -- --if-exists remove port_group d21f1b63-ee41-4e5f-95f1-23e09a953e7b acls 1811f9c0-1c05-4030-b425-11c44c1dc3e9
I1109 21:03:28.545711       1 loadbalancer.go:365] ACL: 1811f9c0-1c05-4030-b425-11c44c1dc3e9, removed from the port group : d21f1b63-ee41-4e5f-95f1-23e09a953e7b
2020-11-09T21:03:28.566Z|00208|nbctl|INFO|Running command run -- --if-exists remove logical_switch caf32519-ab94-4e29-a6c9-d0ac2f4051ac acl 1811f9c0-1c05-4030-b425-11c44c1dc3e9 -- --if-exists remove logical_switch 890edac2-913e-4cf9-a20b-c4d1302b5676 acl 1811f9c0-1c05-4030-b425-11c44c1dc3e9 -- --if-exists remove logical_switch 81891b7f-c56c-4ed0-9628-d6f824f58e1f acl 1811f9c0-1c05-4030-b425-11c44c1dc3e9 -- --if-exists remove logical_switch 7cf284bf-54ab-4307-b029-96cca341ae7f acl 1811f9c0-1c05-4030-b425-11c44c1dc3e9

I1109 21:05:15.302740       1 endpoints.go:47] Adding endpoints: router-default for namespace: openshift-ingress
2020-11-09T21:05:15.883Z|00515|nbctl|INFO|Running command run -- set load_balancer 70e72625-7284-4b8d-a589-bb6c2b91ed76 "vips:\"172.30.1.143:443\"=\"10.128.6.5:443\""

2020-11-09T21:06:00.460Z|00588|nbctl|INFO|Running command run -- set load_balancer 70e72625-7284-4b8d-a589-bb6c2b91ed76 "vips:\"172.30.1.143:443\"=\"10.128.10.5:443,10.128.6.5:443\""


####oauth operator still complains:
E1109 21:44:37.126018       1 base_controller.go:250] "OAuthRouteCheckEndpointAccessibleController" controller failed to sync "key", err: Get "https://oauth-openshift.apps.ci-op-83q7lzl8-99b10.origin-ci-int-gce.dev.openshift.com/healthz": dial tcp 35.185.81.234:443: connect: connection refused
```
Need to see whats still in ovn nbdb and unfortunately we do not get network must gather on the e2e-gcp-ovn job... @astoycos can you help out here with a PR?

**Comment by trozet** [comment]
@dcbw migrated the gcp job to step registry so we can get the necessary output:
https://github.com/openshift/release/pull/13530

**Comment by trozet** [comment]
gcp passed install, just failed the sandbox check which we are currently coming up with a fix for

**Comment by trozet** [comment]
override ci/prow/e2e-metal-ipi-ovn-dualstack

**Comment by trozet** [comment]
@dcbw i think we are good to go

**Comment by aojea** [comment]
these tests are still failing
```
: [sig-network] pods should successfully create sandboxes by getting pod expand_more | 0s
: [sig-network] pods should successfully create sandboxes by other expand_more
```

the former with multus errors

> Multus: [e2e-test-cli-deployment-89tz9/deployment-test-3-7w5tv]: error getting pod: pods "deployment-test-3-7w5tv" not found

the later with the 
> [e2e-statefulset-3573/ss-0 3fa182a6391b6e4a80e4fe9c3b6c2246e364fef25f6816a6088e95a9edd5fdc3] failed to configure pod interface: error while waiting on flows for pod: timed out waiting for OVS flows
'
but only 2 times

**Comment by aojea** [comment]
hmmm is curious that all seem to fail on the tests with statefulsets

> [e2e-statefulset-822/ss-0

why are those tests stressing so much the CNI?

**Comment by trozet** [comment]
Yes there are still more things to debug, but just clarifying here that should not stop this from being merged.

The read failures are a crio/multus problem. We still have some flow timeouts over 5 sec but they are less now. Need to look into them Monday.

**Comment by aojea** [comment]
> Yes there are still more things to debug, but just clarifying here that should not stop this from being merged.
> 
> The read failures are a crio/multus problem. We still have some flow timeouts over 5 sec but they are less now. Need to look into them Monday.

I was just commenting, I 'm totally in favor in merging and iterate, just that there are 2 interesting things here to analyze:
- the statefulset test that causes the errors
- the usage of client-go for some queries, client-go is rate limited by default, we should check if that is affecting us

**Pull request merged**
