### PR TITLE
SDN-3555,SDN-3790,OCPBUGS-4485,OCPBUGS-14449,OCPBUGS-13863,OCPBUGS-14286,OCPBUGS-12800: Downstream Merge 1st June

### PR DESCRIPTION
**Pull request by tssurya**
This PR is bringing down

- [x] ACL Indexes: https://issues.redhat.com/browse/SDN-3555
- [x] Multi Network Policies: https://issues.redhat.com/browse/SDN-3790
- [x] and a bunch of smaller commits that are mostly bug fixes...

Not Clean:
Had two small easy conflicts:
 Conflicts:
	go-controller/pkg/libovsdb/libovsdb.go
because https://github.com/openshift/ovn-kubernetes/pull/1652 went in
	go-controller/pkg/node/healthcheck_service.go
because https://github.com/openshift/ovn-kubernetes/pull/1671 went in

This is a merge PR upto Multi-Network Policy Support upstream + had to cherry-pick 3 bug fixes that are required for CI stability:

1. https://github.com/ovn-org/ovn-kubernetes/pull/3625
2. https://github.com/ovn-org/ovn-kubernetes/pull/3623
3. https://github.com/ovn-org/ovn-kubernetes/pull/3555 (without the merge commit -> we'll get that in the next round of merges along with IC)

Commit owners: @npinaeva @tssurya @zeeke @dceara @JacobTanenbaum @pliurh @dcbw @jcaamano @trozet @ricky-rav  @aserdean @bpickard22 @josecastillolema @maiqueb @martinkennelly

### CODE REVIEW

**Comment by tssurya** [comment]
the errors are happening because of:
```
3/3672 Tests Failed. | expand_less
-- | --
: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_lessRun #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_newRun #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | : [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less | Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_newRun #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less | 5m45s | {  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less | 5m43s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less
Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_newRun #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less | 5m45s | {  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less | 5m43s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #0: Failed expand_less5m45s{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #0: Failed expand_less | 5m45s | {  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #0: Failed expand_less | 5m45s
{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Error: exit with code 1 Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #1: Failed expand_less5m43s{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new | Run #1: Failed expand_less | 5m43s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new
Run #1: Failed expand_less | 5m43s
{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition Ginkgo exit error 1: exit with code 1}open stdoutopen_in_new

: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) CustomResourceDefinition Should scale with a CRD targetRef [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less
Run #0: Failed expand_less	5m45s
{  fail [test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition
Error: exit with code 1
Ginkgo exit error 1: exit with code 1}
open stdoutopen_in_new
Run #1: Failed expand_less	5m43s
{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/autoscaling/autoscaling_utils.go:378]: timed out waiting for the condition
Ginkgo exit error 1: exit with code 1}
[open stdoutopen_in_new](https://prow.ci.openshift.org/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_install_status.xml%22%2C%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fgather-extra%2Fartifacts%2Fjunit%2Fjunit_symptoms.xml%22%2C%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fgather-must-gather%2Fartifacts%2Fjunit_install.xml%22%2C%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fopenshift-e2e-test%2Fartifacts%2Fjunit%2Fjunit_e2e__20230601-082246.xml%22%2C%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fopenshift-e2e-test%2Fartifacts%2Fjunit_node_ready.xml%22%2C%22artifacts%2Fe2e-ovn-hybrid-step-registry%2Fopenshift-e2e-test%2Fartifacts%2Fjunit_nodes.xml%22%2C%22artifacts%2Fjunit_operator.xml%22%5D%2C%22index%22%3A2%2C%22src%22%3A%22gs%2Forigin-ci-test%2Fpr-logs%2Fpull%2Fopenshift_ovn-kubernetes%2F1692%2Fpull-ci-openshift-ovn-kubernetes-master-e2e-ovn-hybrid-step-registry%2F1664174774856716288%22%7D&topURL=https%3A//prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1692/pull-ci-openshift-ovn-kubernetes-master-e2e-ovn-hybrid-step-registry/1664174774856716288&lensIndex=2#)
```
an unrelated failure, but I don't see any bugs for this.. I don't see how this can be related to OVNK changes, other tests are all passing..

**Comment by tssurya** [comment]
again hypershift is failing for unrelated reasons, no wonder we can't make it a required job, seems unstable:
```
: [sig-instrumentation][Late] OpenShift alerting rules [apigroup:image.openshift.io] should have description and summary annotations [Skipped:Disconnected] [Suite:openshift/conformance/parallel] expand_less
--
Run #0: Failed expand_more4sRun #1: Failed expand_less3s{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_more4s | Run #0: Failed expand_more | 4s | Run #1: Failed expand_less3s{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1} | Run #1: Failed expand_less | 3s | {  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_more4s | Run #0: Failed expand_more | 4s
Run #0: Failed expand_more | 4s
Run #1: Failed expand_less3s{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1} | Run #1: Failed expand_less | 3s | {  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1}
Run #1: Failed expand_less | 3s
{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:148]: Incompliant rules detected:  Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalFailedOver2Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'description' annotation, but has a 'message' annotation. OpenShift alerts must use 'description' -- consider renaming the annotation Alerting rule "CsvAbnormalOver30Min" (group: olm.csv_abnormal.rules) has no 'summary' annotation Ginkgo exit error 1: exit with code 1}

**Comment by tssurya** [comment]
e2e-aws-ovn-upgrade this time failed because of:
```
{  ci-cluster-network-liveness-new-connections was unreachable during disruption testing for at least 6s of 51m28s (maxAllowed=5s):
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1692/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade/1664230528171118592

**Comment by trozet** [comment]
/override ci/prow/unit

unit tests have been broken for months and the next downstream PR will fix it

/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

already have  a JIRA for this and fix posted in tuned

**Comment by trozet** [comment]
/skip

hypershift bug reported: https://github.com/openshift/ovn-kubernetes/pull/1692#issuecomment-1572121712

**Comment by tssurya** [comment]
> @deads2k @dgoodwin we think this is good to go (pending pass on aws-ovn-upgrade). @tssurya will fill out the form and update the title of the PR with relevant bug fixes. Feel free to remove the hold when you want to signal approval.

form filled!

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade 10

**Comment by zeeke** [comment]
/retitle SDN-3555,SDN-3790,OCPBUGS-14449,OCPBUGS-13863,OCPBUGS-14286,OCPBUGS-12800: Downstream Merge 1st June

Removing OCPBUGS-4485 from the title as it also needs 
- https://github.com/ovn-org/ovn-kubernetes/pull/3557

to be marked as fixed

**Comment by zeeke** [comment]
/retitle SDN-3555,SDN-3790,OCPBUGS-4485,OCPBUGS-14449,OCPBUGS-13863,OCPBUGS-14286,OCPBUGS-12800: Downstream Merge 1st June

Re-adding OCPBUGS-4485 as discussed with @tssurya . This will ensure the full change history is linked to the issue.

**Comment by dgoodwin** [comment]
/hold cancel

Bringing into next payloads.

**Pull request merged**
