### PR TITLE
Bug 1845664: release-4.5 Cleanup Conntrack when endpoints and pods are deleted 

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
**- What this PR does and why is it needed**

When pods and endpoints are deleted if there are ongoing networking connections there will be a stale conntrack entry. This PR ensures that those conntrack entries are cleaned up 

**- Special notes for reviewers**

**- How to verify it**

See the [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1845664) for reproduction information

**- Description for the changelog**

Add cleanup of pods and endpoints conntrack entries

### CODE REVIEW

**Comment by dcbw** [comment]
@JacobTanenbaum does this backport need to be redone to match the new upstream implementation?

**Comment by dcbw** [comment]
/bugzilla refresh
/hold
(until it matches newer upstream implementation)

**Comment by JacobTanenbaum** [comment]
@dcbw please take a look, manual edits where necessary on two of the commits (4f8232c40db9a3a620b7b1aaf228304f3bc397e7 and https://github.com/openshift/ovn-kubernetes/pull/180/commits/e25f547dffc0d6351f01aa6a2c1b2b9a90ac19a1) the first because the revendor wasn't clean and the second because a large PR that edited the formating of log messages went in that has not been backported (and doesn't backport cleanly). Let me know what you think?

**Comment by JacobTanenbaum** [comment]
aws had some sig-storage issues 


/retest

**Pull request merged**
