### PR TITLE
Bug 1883660: Fix IPv6 on 4.4

### PR DESCRIPTION
**Pull request by danwinship**
Fixes an IPv6 regression introduced by #238 
...and anything else keeping e2e-metal-ipi-ovn-ipv6 from passing

### CODE REVIEW

**Comment by danwinship** [comment]
/retest
weird flakes, but it at least successfully installed

**Comment by danwinship** [comment]
/hold
there's some additional failure here...

**Comment by sdodson** [comment]
(patch manager) Please remove the hold if you'd like to see this cherry-pick-approved.

**Comment by danwinship** [comment]
We don't need IPv6 to work in 4.4
/close

**Pull request closed without merging**
