### PR TITLE
OCPBUGS-8080,OCPBUGS-8280,OCPBUGS-8278,OCPBUGS-7988,OCPBUGS-7932,OCPBUGS-9990: Downstream Merge [10-mar-2023]

### PR DESCRIPTION
**Pull request by zshi-redhat**
clean merge.
- NAD controller fix
- Multi-homing doc
- Egressfirewall changes
- Duplicate metric fix for MicroShift
- Bump K8s to 1.26
- single leader election

### CODE REVIEW

**Comment by npinaeva** [comment]
/lgtm
thanks @zshi-redhat !

**Review by maiqueb — COMMENTED** [review]
multi homing doc looks good.

**Comment by npinaeva** [comment]
/retitle OCPBUGS-8278,OCPBUGS-7988,OCPBUGS-7932: Downstream Merge [10-mar-2023]

**Comment by trozet** [comment]
/retitle OCPBUGS-8280,OCPBUGS-8278,OCPBUGS-7988,OCPBUGS-7932: Downstream Merge [10-mar-2023]

**Comment by dcbw** [comment]
Hmm, that's a couple runs of the aws-upgrade and aws-upgrade-local-gateway with a bunch of disruption... do we have a problem with the PR?

**Comment by dcbw** [comment]
@trozet @npinaeva looks like the retest Tim did also failed the same way. The aws-ovn-upgrade tests have never succeeded here and they both seem to fail the disruption tests every time.

**Comment by npinaeva** [comment]
I filed a bug for `Cluster operator control-plane-machine-set is not available` problem, but that doesn't always happen and doesn't really explain disruption https://issues.redhat.com/browse/OCPBUGS-10032
There is another job that failed the same way https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1574/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade/1634410710559625216 for https://github.com/openshift/ovn-kubernetes/pull/1573, so there is a chance it is not this-pr-related

**Comment by jcaamano** [comment]
/retitle OCPBUGS-8080,OCPBUGS-8280,OCPBUGS-8278,OCPBUGS-7988,OCPBUGS-7932: Downstream Merge [10-mar-2023]

**Comment by trozet** [comment]
/override ci/prow/4.13-upgrade-from-stable-4.12-e2e-aws-ovn-upgrade

**Comment by martinkennelly** [comment]
https://github.com/ovn-org/ovn-kubernetes/pull/3494 should fix `e2e-metal-ipi-ovn-dualstack` job. Testing in https://github.com/openshift/ovn-kubernetes/pull/1597

**Comment by jcaamano** [comment]
@trozet @jluhrsen Attempting a fix for the upgrade jobs: https://github.com/openshift/release/pull/37558

**Pull request merged**
