### PR TITLE
Bug 2079439: [DownstreamMerge] 4-29-22

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by deads2k** [comment]
/payload 4.11 ci blocking

looking at aws 4.10 to 4.11 upgrades to confirm the fix.  if for some reason infra fails, I'd take this as a equivalent to https://github.com/openshift/ovn-kubernetes/pull/1062 to get a good signal over the weekend.

**Comment by deads2k** [comment]
failed on known `[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the h2spec conformance tests [Suite:openshift/conformance/parallel/minimal] ` that has been reverted.

/override ci/prow/e2e-gcp-ovn

/retest-required

**Comment by trozet** [comment]
@dcbw @tssurya looks like there may be some new/existing issue exposed during upgrade. Some of the pods with static names seem to fail to bind port:

```
 '[openshift-monitoring/alertmanager-main-0 b62bda5ec1c8bafdb307c265d762d05179d9d33c07a24dfd916b7167d8d4ced2] [openshift-monitoring/alertmanager-main-0 b62bda5ec1c8bafdb307c265d762d05179d9d33c07a24dfd916b7167d8d4ced2] failed to configure pod interface: timed out waiting for OVS port binding (ovn-installed) for 0a:58:0a:80:02:14 [10.128.2.20/23]
```

Looking closer this pod alertmanager-main-0 was killed/brought back up several times. In ovn-controller I see:
```
2022-04-29T21:53:31.405Z|00030|binding|INFO|Mismatch iface-id-ver for lport openshift-monitoring_alertmanager-main-0, expected ee673f9c-0c20-40ea-adf4-e64d1eaafc18, found 73c6123b-e5a2-4033-abfe-6ec4210f38c2
2022-04-29T21:53:49.774Z|00031|lflow_cache|INFO|Detected cache inactivity (last active 30006 ms ago): trimming cache
2022-04-29T21:59:19.773Z|00032|reconnect|ERR|ssl:10.0.211.118:9642: no response to inactivity probe after 180 seconds, disconnecting
2022-04-29T21:59:19.773Z|00033|reconnect|INFO|ssl:10.0.211.118:9642: connection dropped
2022-04-29T21:59:19.774Z|00034|reconnect|INFO|ssl:10.0.182.207:9642: connecting...
2022-04-29T21:59:19.777Z|00035|reconnect|INFO|ssl:10.0.182.207:9642: connected
2022-04-29T21:59:19.909Z|00036|binding|INFO|Claiming lport openshift-image-registry_image-registry-7cb6d5db6c-fcv4m for this chassis.
2022-04-29T21:59:19.909Z|00037|binding|INFO|openshift-image-registry_image-registry-7cb6d5db6c-fcv4m: Claiming 0a:58:0a:80:02:0b 10.128.2.11
2022-04-29T21:59:19.909Z|00038|binding|INFO|Claiming lport openshift-dns_dns-default-jhg9v for this chassis.
2022-04-29T21:59:19.909Z|00039|binding|INFO|openshift-dns_dns-default-jhg9v: Claiming 0a:58:0a:80:02:03 10.128.2.3
2022-04-29T21:59:19.909Z|00040|binding|INFO|Claiming lport openshift-monitoring_alertmanager-main-0 for this chassis.
2022-04-29T21:59:19.909Z|00041|binding|INFO|openshift-monitoring_alertmanager-main-0: Claiming 0a:58:0a:80:02:14 10.128.2.20
```

So because the pod uid didn't match it failed to bind. Then ovn-controller doesn't do anything for 6 minutes (may be hung?), until it reconnects and binds the port correctly. The new sbdb didnt come up until 
```
2022-04-29T22:26:57.191Z|00013|raft|INFO|ssl:10.0.182.207:56898: learned server ID da73
```

Which is long after these ovn-controller timings.  We are also missing the ovnkube-master log from the 4.10, which would have handled port events during this time.

Job run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1064/pull-ci-openshift-ovn-kubernetes-master-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1520130656028332032

**Comment by trozet** [comment]
alertmanager-main-0 is indeed a statefulset pod, and it was scheduled at:

```
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2022-04-29T21:53:23Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
```

Right about when CNI tries to add it. I really wish we could get the logs of the older ovnkube-master pods. Is that possible with some loki magic @deads2k ?

**Comment by trozet** [comment]
this port binding issue was not seen in @zshi-redhat downstream merge:
https://github.com/openshift/ovn-kubernetes/pull/1058

and it was not seen in the WIP PR to test completed fixes:
https://github.com/openshift/ovn-kubernetes/pull/1062

This means that either:
1. some other commit pulled into the downstream merge is causing the problem
2. the other fixups i did based on the reviews for the completed pods PR caused some issue
3. some combination of commits is triggering this issue

Going to open PRs with @zshi-redhat downstream merge + only the completed pods fixes as well as another PR with only the completed pod fixes.

**Comment by dcbw** [comment]
@trozet here's the ovnkube master that had the lease at the time the must-gather logs start:

`{invoker="openshift-internal-ci/pull-ci-openshift-ovn-kubernetes-master-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1520130656028332032"} | unpack | namespace="openshift-ovn-kubernetes" | host="ip-10-0-157-135.us-west-2.compute.internal" | app="ovnkube-master" | container_name="ovnkube-master"`

**Comment by trozet** [comment]
Thanks @dcbw Looking at the older loki logs for the ovnkube-master container:

```

I0429 21:53:23.511798       1 transact.go:41] Configuring OVN: [{Op:mutate Table:Address_Set Row:map[] Rows:[] Columns:[] Mutations:[{Column:addresses Mutator:insert Value:{GoSet:[10.128.2.20]}}] Timeout:<nil> Where:[where column _uuid == {e0878e8f-3105-4dd2-a919-4f34e361389f}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:} {Op:insert Table:Logical_Switch_Port Row:map[addresses:{GoSet:[0a:58:0a:80:02:14 10.128.2.20]} external_ids:{GoMap:map[namespace:openshift-monitoring pod:true]} name:openshift-monitoring_alertmanager-main-0 options:{GoMap:map[iface-id-ver:73c6123b-e5a2-4033-abfe-6ec4210f38c2 requested-chassis:ip-10-0-186-128.us-west-2.compute.internal]} port_security:{GoSet:[0a:58:0a:80:02:14 10.128.2.20]}] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:u2596996316} {Op:mutate Table:Logical_Switch Row:map[] Rows:[] Columns:[] Mutations:[{Column:ports Mutator:insert Value:{GoSet:[{GoUUID:u2596996316}]}}] Timeout:<nil> Where:[where column _uuid == {39e0f438-c34a-40e7-9095-0584afd53863}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUIDName:}]
```

We set the right iface-id-ver. The message

```
2022-04-29T21:53:31.405Z|00030|binding|INFO|Mismatch iface-id-ver for lport openshift-monitoring_alertmanager-main-0, expected ee673f9c-0c20-40ea-adf4-e64d1eaafc18, found 73c6123b-e5a2-4033-abfe-6ec4210f38c2
```

indicates that the expected value is the value from the DB, and found is whats in OVS. So even though ovnk-master configured the NBDB 8 seconds earlier, ovn-controller somehow got the older value of a previuos port that was deleted.

**Comment by trozet** [comment]
Have another downstream merge with just the changes from @zshi-redhat and the completed pods fixes: https://github.com/openshift/ovn-kubernetes/pull/1065

**Comment by tssurya** [comment]
> this port binding issue was not seen in @zshi-redhat downstream merge: #1058

not true, seems like it was happening in that PR as well!
see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1058/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade-local-gateway/1520066348162486272/artifacts/e2e-aws-ovn-upgrade-local-gateway/gather-extra/
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1058/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn-upgrade-local-gateway/1520066348162486272/artifacts/e2e-aws-ovn-upgrade-local-gateway/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-node-nz7ml_ovn-controller.log

```
2022-04-29T18:47:42.079Z|01258|binding|INFO|Mismatch iface-id-ver for lport e2e-statefulset-3241_ss2-0, expected 9d5336a7-5fc3-4c6f-83cc-b2262fbd4e28, found 4d93a4ae-b533-4db1-80c4-e83d92ea9722
2022-04-29T18:48:03.378Z|01359|binding|INFO|Mismatch iface-id-ver for lport e2e-statefulset-3241_ss2-0, expected ae81bd45-46ed-45ba-b778-12d6c9863b5c, found 9d5336a7-5fc3-4c6f-83cc-b2262fbd4e28
2022-04-29T18:50:54.202Z|01963|binding|INFO|Mismatch iface-id-ver for lport e2e-statefulset-3307_ss2-0, expected 57867a90-1511-4c38-be88-699153991be6, found aeb3f380-8a06-447c-8d09-becd045aeab7
```

so either its been there before that itself or we introduced it in 1058. at least its not from completed pods PR.

**Comment by tssurya** [comment]
It's been happening for quiet some time now it seems?
I tracked the same errors in ovn-controller from PR 1050 (previous downstream merge): https://prow.ci.openshift.org/pr-history/?org=openshift&repo=ovn-kubernetes&pr=1050 which was full green on upgrade jobs. When I open the controller logs I can see:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1050/pull-ci-openshift-ovn-kubernetes-master-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1518917490397155328/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-node-bjn5l_ovn-controller.log
```
2022-04-26T14:00:14.737Z|00976|binding|INFO|Mismatch iface-id-ver for lport e2e-statefulset-9214_ss2-0, expected 9fa5700e-374d-471a-a552-6706d0e5930c, found f613cfca-18b9-4fd4-b84f-208b53f8a82a
```
However its not blocking upgrades right? I don't see how they passed on that run? IMHO this seems to be a new bug which we need to fix but we probably shouldn't hold your PR of duplicate IPs...

**Comment by tssurya** [comment]
oh spoke too soon, seems like we were lucky on those runs since the alertmanager-main and prometheus-k8s statefulsets came up fine,, in the current PR they aren't so this is blocking I guess.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1050/pull-ci-openshift-ovn-kubernetes-master-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1518917490397155328/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/oc_cmds/statefulsets

**Comment by trozet** [comment]
@tssurya right it does eventually come up after some time. I dont know if its because it disconnects and reconnects to a new sbdb, but you are right this bug already exists. I see it happening in 4.11 periodic jobs. I'm going to attempt 2 reverts to ovs and OVN and see if that fixes it.

**Comment by trozet** [comment]
since this issue already exists in periodic jobs, we know it isnt introduced by this PR. Going to merge this PR to get rid of some of the noise caused by the duplicate IPs bug and then debug further from there

**Comment by trozet** [comment]
/override ci/prow/4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade
/override ci/prow/e2e-aws-ovn-local-to-shared-gateway-mode-migration
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/e2e-aws-ovn-upgrade-local-gateway

**Comment by trozet** [comment]
/override ci/prow/4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade

**Comment by deads2k** [comment]
discussed with trozet and bbennett.  No conflict with the level we tested on.  this is likely than the current state.

**Pull request merged**
