### PR TITLE
Bug 2072134: [DownstreamMerge] 4-18-22

### PR DESCRIPTION
**Pull request by trozet**

### CODE REVIEW

**Comment by tssurya** [comment]
@trozet : can you please pull again? I have two high prio bug fixes that merged upstream end of last week..

**Comment by tssurya** [comment]
/hold
till we get https://github.com/ovn-org/ovn-kubernetes/pull/2937

**Comment by tssurya** [comment]
/hold cancel
upstream fix merged!

**Comment by squeed** [comment]
ci/prow/e2e-metal-ipi-ovn-dualstack will fail until https://github.com/openshift/origin/pull/27035 merges.

**Comment by squeed** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack 
https://github.com/openshift/origin/pull/27035 fixes a bug with the test

**Pull request merged**
