### PR TITLE
Bug 1973672: Fix compatibility of multiple ipBlock NetworkPolicies

### PR DESCRIPTION
**Pull request by danwinship**
The previous change to support NetworkPolicies with multiple ipBlocks
was not backward-compatible with existing clusters. Fix it to still
use the old-style external-ids for policies with 0 or 1 ipBlock(s).

(backport from upstream master, included in #579 for downstream master.)

/assign @trozet

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by trozet** [comment]
upgrade failures are not related to this PR:

/override ci/prow/e2e-gcp-ovn-upgrade

**Comment by danwinship** [comment]
/skip
to make prow notice that 4.8-upgrade-from-stable-4.7-e2e-aws-ovn-upgrade is no longer required
(hopefully)

**Pull request merged**
