### PR TITLE
Dockerfile: bump OVS to openvswitch2.15-2.15.0-2

### PR DESCRIPTION
**Pull request by dcbw**
@trozet @abhat @danwinship

### CODE REVIEW

**Comment by dcbw** [comment]
prometheus alert failures:
```
            s: "query failed: \nsort_desc((\ncount_over_time(ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured\",alertstate=\"firing\",severity!=\"info\"}[30m21s:1s]) unless\ncount_over_time(ALERTS{alertname=\"AggregatedAPIDown\",name=\"v1alpha1.wardle.example.com\",alertstate=\"firing\"}[30m21s:1s])\n) > 0): promQL query: \nsort_desc((\ncount_over_time(ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured\",alertstate=\"firing\",severity!=\"info\"}[30m21s:1s]) unless\ncount_over_time(ALERTS{alertname=\"AggregatedAPIDown\",name=\"v1alpha1.wardle.example.com\",alertstate=\"firing\"}[30m21s:1s])\n) > 0) had reported incorrect results:\n[{\"metric\":{\"alertname\":\"KubePersistentVolumeErrors\",\"alertstate\":\"firing\",\"container\":\"kube-rbac-proxy-main\",\"endpoint\":\"https-main\",\"job\":\"kube-state-metrics\",\"namespace\":\"openshift-monitoring\",\"persistentvolume\":\"pvc-80d6de38-b8d5-4b5c-8897-96c45647c459\",\"phase\":\"Failed\",\"service\":\"kube-state-metrics\",\"severity\":\"critical\"},\"value\":[1615566291.419,\"240\"]}]",
```

/retest

**Comment by dcbw** [comment]
vsphere fails cluster install very early
openstack has no leases available

**Comment by vpickard** [comment]
gcp-ovn job failed here:

failed to configure pod interface: error while waiting on flows for pod: timed out waiting for OVS flows

I think I saw a PR to address this, let me see if I can find it

**Comment by vpickard** [comment]
https://github.com/openshift/ovn-kubernetes/pull/475 has this commit, which I believe should address the OVS flows error above:

https://github.com/openshift/ovn-kubernetes/pull/475/commits/09020087ce9f6080f8e056ab62933d9b4d324500

**Comment by vpickard** [comment]
PR to address the iptables failures in CNI add for okd-e2e-gcp-ovn job:

https://github.com/openshift/ovn-kubernetes/pull/476

**Comment by vpickard** [comment]
e2e-gcp-ovn job failed with resource issue:

`failed to acquire lease: resources not found`

**Comment by vpickard** [comment]
The gcp-ovn-upgrade job has some troubling failures, such as this one:

`ns/openshift-network-diagnostics pod/network-check-target-kwsds node/**************-a52b2-vwj45-master-1 - never deleted - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_network-check-target-kwsds_openshift-network-diagnostics_e10db8f6-fb6a-4c83-b0f6-0bac65bd567b_0(72abca977b3afa2c26181254ef0dfa1eb785ebc44014f24053afa34fd8f5c329): [openshift-network-diagnostics/network-check-target-kwsds:ovn-kubernetes]: error adding container to network "ovn-kubernetes": CNI request failed with status 400: '[openshift-network-diagnostics/network-check-target-kwsds 72abca977b3afa2c26181254ef0dfa1eb785ebc44014f24053afa34fd8f5c329] [openshift-network-diagnostics/network-check-target-kwsds 72abca977b3afa2c26181254ef0dfa1eb785ebc44014f24053afa34fd8f5c329] timed out waiting for annotations`

**Comment by dcbw** [comment]
> The gcp-ovn-upgrade job has some troubling failures, such as these:

@vpickard at least some of those, anything between:

```
2021-03-25T05:41:24.493Z|00003|fatal_signal|WARN|terminating with signal 15 (Terminated)
...
I0325 05:42:20.894505153 - ovnkube-master - start ovnkube --init-master ci-op-dmr06nd5-a52b2-vwj45-master-0
...
I0325 05:42:33.083844       1 ovn.go:365] Completing all the Watchers took 11.183565699s
```

is because ovnkube-master was restarted due to the upgrade. There is a 56s gap between when the old ovnkube master is killed, and when the new pod starts, then ovnkube-master initializes for 12 seconds before it's ready to take requests.

That's all expected; this is what I don't think is valid from the test point of view. While ovnkube-master is down, of *course* pods aren't going to be able to start, and nothing prevents scheduling pods during this window.

**Comment by trozet** [comment]
regardless of what we do to fix upgrade or fix the tests, this PR isn't causing the problem. i see these same upgrade problems in other jobs:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn-upgrade

/lgtm

**Pull request merged**
