### PR TITLE
OCPBUGS-44195: DownstreamMerge 11-04-2024

### PR DESCRIPTION
**Pull request by maiqueb**
#### What this PR does and why is it needed

This PR brings the fix of OCP-BUGS-43454 downstream.

#### Which issue(s) this PR fixes

Fixes #

#### Special notes for reviewers

Clean merge. 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by maiqueb** [comment]
OK, so [all payloads are green](https://pr-payload-tests.ci.openshift.org/runs/ci/ae9b4f80-9e24-11ef-929d-04053b0865ff-1) in CI builds.

Not so good on the nighlies, but it doesn't look extremely bad:
https://pr-payload-tests.ci.openshift.org/runs/ci/de344a30-9df2-11ef-8708-741efc6bc4c5-0

These are the payload jobs I haven't seen passing yet:
- periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial
- periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview-serial
- periodic-ci-openshift-release-master-nightly-4.18-fips-payload-scan
- periodic-ci-openshift-microshift-release-4.18-periodics-e2e-aws-ovn-ocp-conformance
- periodic-ci-openshift-microshift-release-4.18-periodics-e2e-aws-ovn-ocp-conformance-serial

@jluhrsen could you spare any guidance here ? FWIW, most of the failures on the failing lanes seem to be related to `MetricsCollectionProfiles` feature gate.

**Comment by abhat** [comment]
@tssurya @trozet should we be pulling in: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4827 as well in this downstream merge to turn the component readiness green on mainline?

**Comment by tssurya** [comment]
@abhat : @maiqueb tells me this is an escalation ? Though I don't see any prio tickets on his bug.. Not sure if we should repull or just get this merged..

@jluhrsen @maiqueb : what's blocking this? How is the signal looking ?

**Comment by abhat** [comment]
@tssurya this and the component readiness failures need to get fixed asap this week. since this PR hasn't merged, I imagine TRT expects our our next downstream merge to have a fix for the component readiness regression.

**Comment by maiqueb** [comment]
> @tssurya this and the component readiness failures need to get fixed asap this week. since this PR hasn't merged, I imagine TRT expects our our next downstream merge to have a fix for the component readiness regression.

Opened https://github.com/openshift/ovn-kubernetes/pull/2345 to address the component readiness backport.

**Comment by maiqueb** [comment]
> @abhat : @maiqueb tells me this is an escalation ? Though I don't see any prio tickets on his bug.. Not sure if we should repull or just get this merged..

You'll find them on the bug https://issues.redhat.com/browse/OCPBUGS-43454 which I have opened to track the 4.17 issue. @tssurya 

> 
> @jluhrsen @maiqueb : what's blocking this? How is the signal looking ? Can we prioritize getting this in so that we can get the next batch in ?

**Comment by maiqueb** [comment]
/payload 4.18 nightly blocking

/payload 4.18 ci blocking

Rebased on top of latest, and added the merge commit. Really unsure why it was missing in the first place ...

**Comment by maiqueb** [comment]
Superseded by #2345

**Pull request closed without merging**
