### PR TITLE
Bug 1915981: Dockerfile: add ethtool & conntrack, and change maintainer email to Tim

### PR DESCRIPTION
**Pull request by dcbw**
@trozet @abhat

### CODE REVIEW

**Comment by abhat** [comment]
/lgtm

although, going forward shouldn't these already be in the network-tools container?

**Comment by dcbw** [comment]
/override ci/prow/e2e-vsphere-ovn

```
 Pulling image image-registry.openshift-image-registry.svc:...bdea3217a42bcfa57ef9c9d6bc0fc92736ac9e9bd9405a8cc41f081 ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: failed to pull image: After retrying 2...id username/password: unauthorized: authentication required
time="2021-01-08T21:21:07Z" level=info msg="Reporting job state 'failed' with reason 'executing_graph:step_failed:cloning_source'" 
```

**Comment by dcbw** [comment]
/retest
now that https://github.com/openshift/ovn-kubernetes/pull/402 merged this should be unblocked

**Pull request merged**
