### PR TITLE
Fix setting of other-config:exclude_ips

### PR DESCRIPTION
**Pull request by danwinship**
Fixes a bug in the merging of the hybrid overlay code with upstream ipv6 changes: We can't just pass `""` to `RunOVNNbctl()` because it actually gets passed as a 0-length argument, resulting in

    ovn-nbctl: : missing column name

/assign @dcbw

### CODE REVIEW

**Comment by dcbw** [comment]
Obsoleted by https://github.com/openshift/ovn-kubernetes/pull/93

**Comment by danwinship** [comment]
This was not obsoleted by #93; the code is still there. (This is not an upstream fix, it's a fix to the hybrid overlay integration.)

**Comment by danwinship** [comment]
oops, no, I was looking at release-4.4, not master

**Pull request closed without merging**
