### PR TITLE
OCPBUGS-7012: [release-4.10] Fix Egress FW ACL rules in dualstack mode

### PR DESCRIPTION
**Pull request by martinkennelly**
Clean cherry-pick.

Downstream merge: https://github.com/openshift/ovn-kubernetes/pull/1496
Upstream merge: https://github.com/ovn-org/ovn-kubernetes/pull/3384

### CODE REVIEW

**Comment by martinkennelly** [comment]
/retest-required
Infra setup failure

**Comment by martinkennelly** [comment]
/test e2e-gcp-ovn 
Looks like API did not come or route to API broken.
/test e2e-azure-ovn
Unrelated CSI driver issue
/test e2e-vsphere-ovn
"static pod lifecycle failure - static pod: "etcd" in namespace: "openshift-etcd" for revision: 6 on node: "ci-op-5ky67c4m-ef07c-vjwjq-master-0" didn't show up, waited: 2m30s}"

**Review by trozet — APPROVED** [review]
/label backport-risk-assessed

**Comment by martinkennelly** [comment]
@zhaozhanqi Can you add cherry-pick approved?

**Comment by dcbw** [comment]
/retest ci/prow/e2e-aws-ovn-local-gateway

AWS setup issue

**Comment by dcbw** [comment]
/test e2e-aws-ovn-local-gateway
/test 4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade

AWS infra install issues

**Pull request merged**
