### PR TITLE
OCPBUGS-16120: Dockerfile: bump to ovn 23.06

### PR DESCRIPTION
**Pull request by dcbw**
New features and improvements:
    - ARP proxy support (needed for CNV)
    - Per-Load Balancer ct_flush
    - Tiered ACLs
    - northd: Update obsolete datapath groups instead of re-creating (perf/scale)
    
    Relevant bug fixes:
    - controller: Handle OpenFlow errors (rhbz#2134880)
    - ovn-controller: fixed port not always set down when unbinding interface (rhbz#2150905)
    - ovn-controller.c: Fix assertion failure during address set update

### CODE REVIEW

**Comment by dcbw** [comment]
/retest
now that the OVNKube retry alert is fixed, and also for various AWS/EC2 install issues

**Comment by dcbw** [comment]
/retest

```
level=error msg=Error: creating EC2 Instance: InsufficientInstanceCapacity: We currently do not have sufficient m6a.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get m6a.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d, us-east-1f.
```

**Comment by dcbw** [comment]
/retest-required
now that https://issues.redhat.com/browse/OCPBUGS-15992 is really fixed for metal-dualstack

**Comment by dcbw** [comment]
There were some payload failures:

periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade - some upgrade distruption it seems

periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade - ran into failures with OVNKubernetesResourceRetryFailure because it's an upgrade, which should be fixed by https://github.com/openshift/ovn-kubernetes/pull/1747 already

periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-serial -- etcd and kube-apiservers were upgrading and rejected connections from cluster-network-operator, which then reported an error and didn't retry reconciliation.

**Comment by trozet** [comment]
I see:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-ovn-kubernetes-1719-ci-4.14-e2e-gcp-ovn-upgrade/1679519043616247808

{  OVNKubernetesResourceRetryFailure was at or above info for at least 10m58s on platformidentification.JobType{Release:"4.14", FromRelease:"4.14", Platform:"gcp", Architecture:"amd64", Network:"ovn", Topology:"ha"} (maxAllowed=0s): pending for 0s, firing for 10m58s:

```
W0713 18:07:06.065326       1 obj_retry.go:232] Dropping retry entry for *factory.egressIPPod e2e-replicaset-2344/my-hostname-private-3dbb4afd-3bad-46dc-a380-5d394f154b52-xmdjq: exceeded number of failed attempts
W0713 18:07:06.065518       1 obj_retry.go:232] Dropping retry entry for *factory.egressIPPod e2e-endpointslice-4342/pod-handle-http-request: exceeded number of failed attempts
```

```
I0713 18:06:36.065986       1 obj_retry.go:269] Retry object setup: *factory.egressIPPod e2e-replicaset-2344/my-hostname-private-3dbb4afd-3bad-46dc-a380-5d394f154b52-xmdjq
I0713 18:06:36.066176       1 obj_retry.go:302] Removing old object: *factory.egressIPPod e2e-replicaset-2344/my-hostname-private-3dbb4afd-3bad-46dc-a380-5d394f154b52-xmdjq (failed: 14)
I0713 18:06:36.066286       1 obj_retry.go:310] Retry delete failed for *factory.egressIPPod e2e-replicaset-2344/my-hostname-private-3dbb4afd-3bad-46dc-a380-5d394f154b52-xmdjq, will try again later: namespace "e2e-replicaset-2344" not found
```

looks like delete is failing if it cant find the namespace. we need to fix this. @tssurya @dcbw

**Comment by trozet** [comment]
oh looks like @kyrtapz already fixed this, it just wasnt in this PR and I guess somehow the aggregator jobs didnt merge this PR into master before running? Anyway I've pulled the OVN bump into https://github.com/openshift/ovn-kubernetes/pull/1757 which also has patryk's fix. Lets see how that goes.

**Comment by tssurya** [comment]
yeah pat already fixed that last week..

**Pull request closed without merging**
